#
# File: bootver.s
#
# Abstract:
#    This file defines the bootcode version number.
#
# Copyright 2002 The MathWorks, Inc.
# THIS FILE IS AUTOMATICALLY GENERATED: DO NOT MAKE CHANGES
# DIRECTLY TO THIS FILE

#
# Use the first 2-bytes of internal flash to store the version 
# number of the MathWorks bootcode.
#
# Current version of Embedded Target for Motorola MPC555: 2.0 (r14)
# Current major bootcode version number: 1
# Current minor bootcode version number: 3
#
   .org 0x0
# Write the major boot version
   .byte 1
# Write the minor boot version
   .byte 3 
