function [out,out2]=propertypage(obj,action,varargin)
%PROPERTYPAGE   Generate an editing page for this constraint
%
%  LYT=PROPERTYPAGE(OBJ,'CREATE',FIG,PTR,MDL,FACTORS)
%  [OK,MSG]= PROPERTYPAGE(OBJ,'FINALISE',LYT)
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.5.2.2 $  $Date: 2004/02/09 06:58:10 $

switch lower(action)
case 'create'
   out=i_createlyt(varargin{:});
   out2=[];
case 'finalise'
   [out,out2]=i_finalise(varargin{:});
end
return



function lyt=i_createlyt(fig,ptr,mdl,fact)

txt=xreguicontrol('parent',fig,...
   'hittest','off',...
   'enable','inactive',...
   'visible','off',...
   'style','text',...
   'string','Values are in coded units',...
   'horizontalalignment','left');
P=getparams(ptr.info);
tbl=xregtable(fig,...
   'visible','off',...
   'position',[0 0 150 100],...
   'cols.size',53,...
   'rows.size',20,...
   'frame.hborder',[0 0],...
   'frame.vborder',[0 0],...
   'frame.box','off',...
   'cells.defaultbackgroundcolor',[1 1 1],...
   'defaultcelltype','edit',...
   'defaultcellformat','%.4g',...
   'rows.number',size(P.W,2)+1,...
   'cols.number',size(P.W,2)+2,...
   'rows.fixed',1,...
   'cols.fixed',2,...
   'zeroindex',[2 3],...
   'frame.visible','off'); 

set(tbl,...
   'cells.rowselection',[1 size(P.W,2)+1],...
   'cells.colselection',[1 1],...
   'cells.type','uitogglebutton',...
   'cells.enable','inactive',...
   'cells.backgroundcolor',get(0,'defaultuicontrolbackgroundcolor'),...
   'cells.colselection',[1 size(P.W,2)+2],...
   'cells.rowselection',[1 1],...
   'cells.backgroundcolor',get(0,'defaultuicontrolbackgroundcolor'),...
   'cells.type','uitogglebutton',...
   'cells.enable','inactive',...
   'cells.rowselection',[1 size(P.W,2)+1],...
   'cells.colselection',[2 2],...
   'cells.backgroundcolor',[0.9 0.9 0.9]);

tbl(:,:)=P.W;
tbl(0,0:end).string= [{'Xc'} fact];
tbl(:,0)= P.xc;
tbl(:,-1).string= fact(:);

msk= (triu(ones(size(P.W)),1)~=0);
tbl(msk).visible= 'off';

ud.tbl= tbl;
ud.ptr=ptr;

lyt=xregpanellayout(fig,...
   'innerborder',[0 0 0 0],...
   'center',tbl,...
   'packstatus','off',...
   'userdata',ud);
lyt=xreggridbaglayout(fig,...
   'dimension',[2 1],...
   'rowsizes',[15 -1],...
   'border',[0 0 0 5],...
   'gapy',5,...
   'elements',{txt,lyt},...
   'userdata',ud);
return




function [ok,msg]=i_finalise(lyt)
ud=get(lyt,'userdata');

W= tril( ud.tbl(:,:) );
W= W + tril(W,-1)';
Xc= ud.tbl(:,0);

[c,msg]=setparams(ud.ptr.info,'W',W,'xc',Xc);
ud.ptr.info=c;
ok= isempty(msg);
return