%GuiDm_16  GUI to show 3D plots
% Copyright S. Nakamura, 1995
clf, clear
h6=figure(1);
set(h6,'Position',[60, 300,380,380],...
       'Color',[ 0. 0.0 0.],...
       'NumberTitle','off',...
       'Name','GuiDm_16    3D plots')
[x,y,z]=sphere(10);
axes( 'Position', [0.4 0.2, 0.55 0.55],...
      'Box', 'on', 'Color','k')
surf(x,y,z,-z);
%=============================Slider control
txt_sl1 = uicontrol(gcf,...
        'Style','text', ...
        'String','Mesh size',...
        'Position',[10,50,110,20]);
txt_sl2 = uicontrol(gcf,...
        'Style','text',...
        'String','10............50',...
        'Position',[10,30,110,20]);
txt_sli = uicontrol(gcf,...
        'Style','slider',...
        'Min' ,10,'Max', 50, ...
        'Position',[10,10,110,20], ...
        'Value', -30,...
        'CallBack',...
  ['clear x y z; ',...
   ' [x,y,z]=sphere(ceil(get(txt_sli,''Value'')));',...
   ' surf(x,y,z,-z)'...
  ]);
%============================= Shading selection
push0=uicontrol(gcf, ...
        'Style','text',...
        'Position', [10,140, 110,20],...
        'String','Shading Selct:   ',...
        'Value',0);
sym(1)=uicontrol(gcf,...
        'Style','push',...
        'Position', [10,80,110,20], ...
        'String','interp', ...
        'CallBack','shading interp ');
sym(2)=uicontrol(gcf, 'Style','push',...
        'Position', [10,100,110,20],...
        'String','flat',...
        'CallBack','shading flat ');
sym(3)=uicontrol(gcf, 'Style','push',...
        'Position', [10,120, 110,20], ...
        'String','Faceted',...
        'CallBack','shading faceted ');
%============================== Color Map Selection
push3=uicontrol(gcf, 'Style','push',...
        'Position', [10,170, 110,20], ...
        'String','jet',...
        'CallBack','colormap(jet)');
push2=uicontrol(gcf, 'Style','push',...
        'Position', [10,190, 110,20],...
        'String','flag',...
        'CallBack','colormap(flag)');
push1=uicontrol(gcf, 'Style','push',...
        'Position', [10,210, 110,20], ...
        'String','hsv',...
        'CallBack','colormap(hsv)');
push0=uicontrol(gcf, 'Style','text',...
        'Position', [10,230, 110,20], ...
        'String','Color Map Select:',...
        'CallBack','dummy=0');
%============================== View Angle Input
edtx0=uicontrol(gcf, 'Style','text',...
        'Position', [10,280, 110,20], ...
        'String', 'View Angles [ , ]');
edtx1=uicontrol(gcf, 'Style','edit', ...
        'Position', [10,260, 110,20],...
        'String','[-20,30]',...
        'CallBack',...
        ['v_ang=str2num(get(edtx1,''String''));',...
         'view(v_ang) ']);
%============================== Axis on/off
ckbox=uicontrol(gcf, 'Style','checkbox',...
        'Position', [10,310, 110,20], ...
        'String','Axis on/off', ...
        'CallBack',...
         ['ckv= get(ckbox,''Value'');if ckv==1,',...
          'axis on,elseif ckv==0, axis off, end ']);
%============================== Top title
title=uicontrol(gcf, 'Style','text',...
        'Position', [60,345, 310,20], 'String',...
        'User Interface Demo: GuiDm_16');

