%GuiDemo_17   
% Copyright S. Nakamura, 1995
% GuiDemo_17:  Electric Circuit Analysis
clf, clear 
h6=figure(1);
clf
R=0;G=0.4;B=0;
set(h6,'Position',[60, 300,680,380],...
   'Name','GuiDm_17  Electric circuit response',...
   'NumberTitle','off',...
   'Color',[ 0. 0.0 0.]);
[x,y,z]=sphere(10);
ah=axes( 'Position', [0.05 0.25, 0.4 0.50],...
   'Box', 'on', ...
   'Color',[R,G,B],...
   'XColor',[0,0,0],'YColor',[0,0,0]);
ah2=axes( 'Position', [0.55 0.3, 0.42 0.50],...
   'Box', 'on', ...
   'Color',[R,G,B],...
   'XColor',[0,0,0],'YColor',[0,0,0]);
subplot(ah); APE_circ     
                    %calling APE_circ (diagram)
La=0.01; Lb=0.5;Ra=200;Rb=20;C=0.002;
subplot(ah2); APE_rk(La, Lb, Ra, Rb ,C); 
                          %calling 2nd RK
%============================= 
t1 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['La=',num2str(La)],...
   'HorizontalAlignment','Left',...
   'Position',[30,360,100,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t1B= uicontrol(gcf,'Style','text', ...
   'String',...
      ['Lb=',num2str(Lb)],...
   'HorizontalAlignment','Left',...
   'Position',[130,360,100,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['Ra=',num2str(Ra)],...                        
   'HorizontalAlignment','Left',...
   'Position',[30,340,100,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t2B = uicontrol(gcf,'Style','text', ...
   'String',...
      ['Rb=',num2str(Rb)],...
   'HorizontalAlignment','Left',...
   'Position',[130,340,100,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t3 = uicontrol(gcf,'Style','text', ...
   'String',...
      ['C=',num2str(C)],...
   'HorizontalAlignment','Left',...
   'Position',[30,320,100,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
%=============================Popup Menu
p1 = uicontrol('Style','Popup', ...
   'String',...
      'Rb=20|Rb=100|Rb=1000',...
   'Position',[330,360,100,20],...
   'Value',1,...
   'CallBack',...
   [...
    ' cla;cv=get(p1,''Value'');'...
    ' if cv==1, Rb=20; end;'...
    ' if cv==2, Rb=100; end;'...
    ' if cv==3, Rb=1000; end;'...
    ' set(t2B,''String'',[''Rb='',num2str(Rb)])'...
   ]);
p2 = uicontrol('Style','Popup', ...
   'String',...
      'Lb=0.05|Lb=0.5|Lb=5',...
   'Position',[430,360,100,20],...
   'Value',2,...
   'CallBack',...
   [...
    ' cla;cv=get(p2,''Value'');'...
    ' if cv==1, Lb=0.05; end;'...
    ' if cv==2, Lb=0.5; end;'...
    ' if cv==3, Lb=5; end;'...
    ' set(t1B,''String'',[''Lb='',num2str(Lb)])'...
   ]);

%=============================Slider La 
b1 = uicontrol(gcf,'Style','text', ...
   'String','La',...
   'Position',[10,50,110,20],...
   'BackgroundColor',[0.8,0.8,1]);
b2 = uicontrol(gcf,'Style','text',...
   'String','0.01............0.1',...
   'Position',[10,30,110,20]);
b3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,0.01,'Max', 0.1, ...
   'Position',[10,10,110,20], ...
   'Value', La,...
   'CallBack', ...
     [ 'cla;La=get(b3,''Value'');',...
       'set(t1,''String'',[''La='',num2str(La)]);',...
     ]);
%=============================Slider for Lb 
g1 = uicontrol(gcf,'Style','text', ...
   'String','Lb',...
   'Position',[130,50,110,20],...
   'BackgroundColor',[0.8,1,0.8]);
g2 = uicontrol(gcf,'Style','text',...
   'String','0.1............0.5',...
   'Position',[130,30,110,20]);
g3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,0.1,'Max', 0.5, ...
   'Position',[130,10,110,20], ...
   'Value', Lb,...
   'CallBack', ...
     [ 'cla;Lb=get(g3,''Value'');',...
       'set(t1B,''String'',[''Lb='',num2str(Lb)]);',...
     ]);
%=============================Slider for Ra 
r1 = uicontrol(gcf,'Style','text', ...
   'String','Ra',...
   'Position',[250,50,110,20],...
   'BackgroundColor',[1,0.8,0.8]);
r2 = uicontrol(gcf,'Style','text',...
   'String','20............200',...
   'Position',[250,30,110,20]);
r3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,20,'Max',200, ...
   'Position',[250,10,110,20], ...
   'Value', Ra,...
   'CallBack', ...
     [ 'cla;Ra=get(r3,''Value'');',...
       'set(t2,''String'',[''Ra='',num2str(Ra)]);',...
     ]);
%================================ Push button
r1 = uicontrol(gcf,'Style','Push', ...
   'String','Push to  start RK',...
   'Position',[380,10,110,60],...
   'CallBack',...
   'disp([La,Lb,Ra,Rb,C]);APE_rk(La, Lb, Ra, Rb ,C)');



