%GuiDm_5 Demonstration of popup menu.
% Copyright S. Nakamura, 1995
close;clg
h1=figure(1);
set(h1,'Position',[100,100,300,200],...
       'NumberTitle','off', ...
       'Name','GuiDm_5  Demo of Popup Menu')
k1=uicontrol('Style','Popup',...
             'String','A|B|C|D|Close',...
             'Value',  1,...
             'Position',[ 20,150,140,30], ...
             'Callback','task_1(h1,k1)');

