function moebius(figNumber,GalleryGUIFlag)
% MOEBIUS  Construct a moebius strip.
%   Moebius strip generated by revolving the 
%   figure-8 curve defined by moebius1.

%   Barbara Kuhn , University of Stuttgart. 19/02/03.
%
% Gallery initialization =================
if ~exist('GalleryGUIFlag'), figNumber=0; end;
% Create help.
infoStr= ...                                            
        ['                                               '  
         ' Moebius strip                                 '  
         ' by Barbara Kuhn                               '  
         '                                               '  
         '                                               '  
         ' File name: moebius1.m                         '];
gallinit(figNumber,infoStr);

ab = [0 2*pi];
rtr = [2 0.5 1];
pq = [40 40];
box = [-3 3 -3 3 -2 2];
vue = [55 60];

set(gcf,'color',[.7 .8 .9]);
tube('moebius1',ab,rtr,pq,box,vue);
shading interp
%map = [1 0 0];
colormap(autumn);
