%GuiDm_10  RGB color demonstration   
% Copyright S. Nakamura, 1995
clear,close 
h6=figure(1);
clf
R=0.7;G=0.6;B=0.9;
set(h6,'Position',[60, 300,380,380],...
   'Name','GuiDm_10 RGB Demo',...
   'NumberTitle','off',...
   'Color',[ 0. 0.0 0.]);
[x,y,z]=sphere(10);
ah=axes( 'Position', [0.4 0.1, 0.55 0.50],...
   'Box', 'on', ...
   'Color',[R,G,B],...
   'XColor',[0,0,0],'YColor',[0,0,0]);
%============================= 
t1 = uicontrol(gcf,'Style','text', ...
   'String',...
      'RGB color consists of red, green and blue. ',...
   'HorizontalAlignment','Left',...
   'Position',[30,360,320,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t2 = uicontrol(gcf,'Style','text', ...
   'String',...
      'By moving the sliders, intensity of each ',...
   'HorizontalAlignment','Left',...
   'Position',[30,340,320,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t3 = uicontrol(gcf,'Style','text', ...
   'String',...
      'color can be changed, and the resultant  ',...
   'HorizontalAlignment','Left',...
   'Position',[30,320,320,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
t4 = uicontrol(gcf,'Style','text', ...
   'String',...
      'RGB color is seen in the square.  ',...
   'HorizontalAlignment','Left',...
   'Position',[30,300,320,20],...
   'BackgroundColor',[0.8 0.8 0.8]);
%=============================Slider control
b1 = uicontrol(gcf,'Style','text', ...
   'String','Blue intensity',...
   'Position',[10,50,110,20],...
   'BackgroundColor',[0.8,0.8,1]);
b2 = uicontrol(gcf,'Style','text',...
   'String','0............1',...
   'Position',[10,30,110,20]);
b3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,0,'Max', 1, ...
   'Position',[10,10,110,20], ...
   'Value', B,...
   'CallBack', ...
      'B=get(b3,''Value'');set(ah,''Color'',[R,G,B])');
%=============================Slider for Green 
g1 = uicontrol(gcf,'Style','text', ...
   'String','Green intensity',...
   'Position',[10,150,110,20],...
   'BackgroundColor',[0.8,1,0.8]);
g2 = uicontrol(gcf,'Style','text',...
   'String','0............1',...
   'Position',[10,130,110,20]);
g3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,0,'Max', 1, ...
   'Position',[10,110,110,20], ...
   'Value', G,...
   'CallBack', ...
      'G=get(g3,''Value'');set(ah,''Color'',[R,G,B])');
%=============================Slider for RED 
r1 = uicontrol(gcf,'Style','text', ...
   'String','Red intensity',...
   'Position',[10,250,110,20],'BackgroundColor',[1,0.8,0.8]);
r2 = uicontrol(gcf,'Style','text',...
   'String','0............1',...
   'Position',[10,230,110,20]);
r3 = uicontrol(gcf,...
   'Style','slider',...
   'Min' ,0,'Max',1, ...
   'Position',[10,210,110,20], ...
   'Value', R,...
   'CallBack', ...
      'R=get(r3,''Value'');set(ah,''Color'',[R,G,B])');

