% GuiDm_6                           MAC test OK        
% Copyright S. Nakamura, 1995
        clg
h1=figure(2);
set(h1,'Position',[30,50,280,100], ...
    'Color',[0,0.5, 0.5],'Name','GuiDm_6',...
    'NumberTitle','off');
j=uicontrol('Position',[ 0,60,250,30], ...
    'Style','text',...
    'String','Select from A, B, C, D or Close');
k=uicontrol('Style','Popup',...
            'String','A|B|C|D|Close',...
            'Position',[ 0,30,100,30], ...
            'Callback','task_1(h1,k)');

fprintf('This m-file is incomplete.\n')
fprintf('Do not click at the menu:  You can click at GuiDm_7.\n')
