function hInfo = propPageModel(obj, hPropDialog)
%PROPPAGEMODEL Create the Model property tab
%
%  INFO = PROPPAGEMODEL(OBJ, HPROPDIALOG) creates the info object that
%  represents the model-specific tab in a property dialog.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.1.6.2 $    $Date: 2004/04/12 23:34:40 $

hInfo = xregGui.propertyPageInfo('Model');
hInfo.HelpHandler = 'cghelptool';
hInfo.HelpCode = 'CGMODELPROPPAGEMODEL';

mdl = get(obj, 'model');
if isa(mdl, 'cgfuncmodel')
    % Just display function string
    hFunc = i_maketextcontrol(hPropDialog, 'Function:', char(mdl), 50);
    hGrid = xreggridbaglayout(hPropDialog.Figure, ...
        'dimension', [1 1], ...
        'rowsizes', 15, ...
        'border', [10 10 10 10], ...
        'elements', {hFunc});

elseif isa(mdl, 'cgexprmodel')
    % Display name of original expression
    hDesc = uicontrol('Parent', hPropDialog.Figure, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Enable', 'inactive', ...
        'HorizontalAlignment', 'left', ...
        'String', description(mdl));
    hGrid = xreggridbaglayout(hPropDialog.Figure, ...
        'dimension', [1 1], ...
        'rowsizes', 15, ...
        'border', [10 10 10 10], ...
        'elements', {hDesc});

elseif isa(mdl, 'xregstatsmodel')
    % Display model origination info, plus model description
    INFO = getinfo(mdl);
    projfile = 'Unknown';
    mdlpath = 'Unknown';
    loadEn = 'off';
    if ~isempty(INFO);
        if isfield(INFO, 'Parent') && exist(INFO.Parent, 'file')
            [p,f,e]= fileparts(INFO.Parent);
            projfile = f;
            loadEn = 'on';
        end
        if isfield(INFO, 'path')
            mdlpath = INFO.path;
        end
    end
    hFile = i_maketextcontrol(hPropDialog, 'Model project file:', projfile, 90);
    hModelPath = i_maketextcontrol(hPropDialog, 'Model path:', mdlpath, 90);    
    hModelLoad = uicontrol('Parent', hPropDialog.Figure, ...
        'Style', 'pushbutton', ...
        'Visible','off', ...
        'Enable', loadEn, ...
        'String', 'Load Model', ...
        'Callback', {@i_loadmodel, hPropDialog});


    hModelDispLabel = uicontrol('Parent', hPropDialog.Figure, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Enable', 'inactive', ...
        'HorizontalAlignment', 'left', ...
        'String', 'Model definition:');
    SC = xregGui.SystemColorsDbl;
    hModelDisp = xregMdlGui.modelpane('parent', hPropDialog.Figure, ...
        'visible', 'off', ...
        'backgroundcolor', SC.CTRL_BACK, ...
        'model', model(mdl));

    hPanel = xregpanellayout(hPropDialog.Figure, ...
        'Visible', 'off', ...
        'innerborder', [0 0 0 0], ...
        'center', hModelDisp);
    hGrid = xreggridbaglayout(hPropDialog.Figure, ...
        'dimension', [7 2], ...
        'rowsizes', [15 10 15 10 15 2 -1], ...
        'colsizes', [-1 75], ...
        'mergeblock', {[1 2], [2 2]}, ...
        'mergeblock', {[3 3], [1 2]}, ...
        'mergeblock', {[5 5], [1 2]}, ...
        'mergeblock', {[7 7], [1 2]}, ...
        'border', [10 10 10 10], ...
        'elements', {hFile, [], hModelPath, [], hModelDispLabel, [], hPanel, hModelLoad});

else
    % Pick up output from description method
    hDesc = i_maketextcontrol(hPropDialog, 'Description:', description(mdl), 60);
    hGrid = xreggridbaglayout(hPropDialog.Figure, ...
        'dimension', [1 1], ...
        'rowsizes', 15, ...
        'border', [10 10 10 10], ...
        'elements', {hDesc});
end
hInfo.TabComponent = hGrid;


function h = i_maketextcontrol(hPropDialog, Label, Text, LabelSize)
h = xregGui.labelcontrol('parent', hPropDialog.Figure, ...
    'Visible', 'off', ...
    'LabelSizeMode', 'absolute', ...
    'LabelSize', LabelSize, ...
    'ControlSizeMode', 'relative', ...
    'ControlSize', 1, ...
    'String', Label, ...
    'Control', xregGui.truncateduicontrol('parent', hPropDialog.Figure, ...
    'Style', 'text', ...
    'HorizontalAlignment', 'left', ...
    'Enable', 'inactive', ...
    'Visible', 'off', ...
    'String', Text));


function i_loadmodel(src, evt, hPropDialog)
loadmodel(get(hPropDialog.Object, 'model'));
