function fig = phgui()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

% 03-Aug-02, Rajbabu, updated this file for new layout of the 'phrace' GUI
  
  load phgui

h0 = figure('CloseRequestFcn','phrace CloseRequestFcn', ...
	    'Color',[0.659 0.761 0.847], ...
	    'Colormap',mat0, ...
	    'CreateFcn','phrace SetFigureSize', ...
	    'DoubleBuffer','on',...
	    'PaperPosition',[18 180 576 432], ...
	    'PaperUnits','points', ...
	    'Units','Characters',...
	    'Position',[50.2 21.577 134.2 34.462], ...
	    'ResizeFcn','phrace ResizeFcn', ...
	    'Tag','PHRACE',...
	    'MenuBar','none', ...  
	    'NumberTitle','off');
% ----Frame and Pushbuttons, that lie on the 'right' side of the GUI ---------
h1 = uicontrol('Parent',h0,...
	       'Units','Characters', ...
	       'Position',[103 3.0 26 29.14], ...
	       'BackGroundColor',[0.5 0.5 0.5],...
	       'Style','Frame',...
	       'Tag','frame1');
h1 = uicontrol('Parent',h0,...
	       'Units','Characters', ...
	       'Position',[104 24.2 24 7.2], ...
	       'BackGroundColor',[0.69 0.69 0.69],...
	       'Style','Frame',...
	       'Tag','centerframe1');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'BackgroundColor',...
	       [0.752941176470588 0.752941176470588 0.752941176470588], ...
	       'Callback','phrace(''NewQuestion'')', ...
	       'ListboxTop',0, ...
	       'Position',[106 28.615 20.2 1.8], ...
	       'String','New Question', ...
	       'Tag','NewQuestion');
h1 = uicontrol('Parent',h0,...
	       'Units','Characters',...
	       'BackGroundColor',[0.69 0.69 0.69],...
	       'Position',[106 27 20.2 1.2],...
	       'Style','Text',...
	       'HorizontalAlignment','left',...
	       'Tag', 'TypeofTestlabel',...
	       'String','Type of Test:');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'BackgroundColor',...
	       [0.6 0.6 0.6],...
	       'ListboxTop',0, ...
	       'Position',[106 25.1 20.2 1.8], ...
	       'String','Complex|Sinusoid|RealPart|Spectrum|Sampling|ZTransform|All', ...
	       'Style','popupmenu', ...
	       'Tag','TypeOfTest', ...
	       'Callback','phrace(''NewQuestion'')', ...
	       'Value',1);
h1 = uicontrol('Parent',h0,...
	       'Units','Characters', ...
	       'Position',[104 15.23 24 6.6], ...
	       'BackGroundColor',[0.69 0.69 0.69],...
	       'Style','Frame',...
	       'Tag','centerframe2');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'ForeGroundColor',...
	       [0 0.5 0], ...
	       'Callback','phrace(''StartTimer'')', ...
	       'ListboxTop',0, ...
	       'Position',[106 19.154 20.2 1.8], ...
	       'String','Start Timer', ...
	       'Tag','StartTimer');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'ForeGroundColor',...
	       [0.9 0 0], ...
	       'Callback','phrace(''StopTimer'')', ...
	       'ListboxTop',0, ...
	       'Position',[106 16.231 20.2 1.8], ...
	       'String','Stop Timer', ...
	       'Tag','StopTimer');
h1 = uicontrol('Parent',h0,...
	       'Units','Characters', ...
	       'Position',[104 4 24 8.6], ...
	       'BackGroundColor',[0.69 0.69 0.69],...
	       'Style','Frame',...
	       'Tag','centerframe3');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'BackgroundColor',...
	       [0.752941176470588 0.752941176470588 0.752941176470588], ...
	       'ForeGroundColor',[0.5 0 0.5],...
	       'Callback','phrace(''ShowAnswer'')', ...
	       'ListboxTop',0, ...
	       'Position',[106 10.1 20.2 1.8], ...
	       'String','Show Answer', ...
	       'Tag','ShowAnswer');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'BackgroundColor',...
	       [0.752941176470588 0.752941176470588 0.752941176470588], ...
	       'Callback','phrace(''AlternateAnswers'')', ...
	       'Visible','off',...
	       'ListboxTop',0, ...
	       'Position',[106 7.231 20.2 1.8], ...
	       'String','Alternate Answers', ...
	       'ToolTipString','View alternate form of Answer',...
	       'Tag','AlternateAnswers');
h1 = uicontrol('Parent',h0, ...
	       'Units','Characters', ...
	       'BackGroundColor',[0.69 0.69 0.69],...
	       'CallBack','phrace(''ShowRectForm'')' ,...
	       'ListboxTop',0, ...
	       'Position',[105.4 5 21.2 1.8], ...
	       'String','Rectangular Form', ...
	       'TooltipString','Rectangular form',...
	       'Style','checkbox', ...
	       'Tag','ShowRectForm');
% ---- Text and Axes that are on the 'left' side of the GUI --------------------
h1 = axes('Parent',h0, ...
	  'Units','characters', ...
	  'CameraPosition',[0.5 0.5 9.160254037844391], ...
	  'CameraPositionMode','manual', ...
	  'CameraTarget',[0.5 0.5 0.5], ...
	  'CameraTargetMode','manual', ...
	  'CameraUpVector',[0 1 0], ...
	  'CameraUpVectorMode','manual', ...
	  'CameraViewAngle',6.60861036031192, ...
	  'CameraViewAngleMode','auto', ...
	  'CLimMode','manual', ...
	  'Color',[1 1 1], ...
	  'ColorOrder',mat1, ...
	  'DataAspectRatioMode','auto', ...
	  'PlotBoxAspectRatioMode','auto', ...
	  'Position',[-20.2 -0.077 134 35.385], ...
	  'Tag','TextArea', ...
	  'TickDirMode','manual', ...
	  'Visible','off',...
	  'WarpToFill','off', ...
	  'XColor',[0 0 0], ...
	  'YColor',[0 0 0], ...
	  'ZColor',[0 0 0]);
h2 = text('Parent',h1,...
	  'color','m',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'Position',[0.5 0.95],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','top',...
	  'Tag','TextTitle',...
	  'String','Complex: Adding Complex Amplitudes');
h2 = text('Parent',h1,...
	  'color','k',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'Position',[0.5 0.75],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','middle',...
	  'Tag','TextQuestion',...
	  'String','');
h2 = text('Parent',h1,...
	  'color','k',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'Position',[0.5 0.70],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','middle',...
	  'Tag','TextQuestionline',...
	  'String','');
h2 = text('Parent',h1,...
 	  'color','k',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'Position',[0.5 0.65],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','middle',...
	  'Tag','TextQuestionden',...
	  'String','');
h2 = text('Parent',h1,...
	  'color','r',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'FontSize',0.05,...
	  'Position',[0.5 0.53],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','middle',...
	  'Tag','TextTimer',...
	  'String','TIMER: 0 secs',...
	  'Visible','on');
h2 = text('Parent',h1,...
 	  'color','b',...
	  'Units','normalized',...
	  'FontUnits','normalized',...
	  'Position',[0.5 0.3],...
	  'HorizontalAlignment','center',...
	  'VerticalAlignment','middle',...
	  'Tag','TextAnswer',...
	  'String','The Answer');
% ---- ZPlane plot -------------------------------------------------------------
h1 = axes('Parent',h0, ...
	  'Box','on',...
	  'Units','Characters', ...
	  'CameraPositionMode','manual', ...
	  'CameraPosition',[0.5 0.5 9.160254037844391], ...
	  'CameraTargetMode','manual',...
	  'CameraUpVector',[0 1 0], ...
	  'CameraUpVectorMode','auto', ...
	  'CameraViewAngle',6.60861036031192, ...
	  'CameraViewAngleMode','auto', ...
	  'CLimMode','manual', ...
	  'Color',[1 1 1], ...
	  'ColorOrder',mat1, ...
	  'DataAspectRatio', [1 1 1], ...
	  'PlotBoxAspectRatio',[100 100 100], ...
	  'Position',[36.8 4.538 32 12.308], ...
	  'Tag','zplaneArea', ...
	  'TickDirMode','manual', ...
	  'Visible','off',...
	  'XColor',[0 0 0], ...
	  'YColor',[0 0 0], ...
	  'ZColor',[0 0 0],...
	  'FontSize',0.1);
h2 = text('Parent',h1, ...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.1181434599156118, ...
	'HandleVisibility','on', ...
	'HorizontalAlignment','center', ...
	'Position',[0.4936708860759493 -0.1772151898734177 0], ...
	'String','Real Part', ...
	'Tag','Axes1Xlabel', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);

h2 = text('Parent',h1, ...
	  'Color','r',...
	'Units','normalized', ...
	'FontUnits','normalized', ...
	'FontSize',0.1181434599156118, ...
	'HandleVisibility','on', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.2784810126582278 0.4936708860759493 0], ...
	'Rotation',90, ...
	'String','Imaginary Part', ...
	'Tag','Axes1Ylabel', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);

%% This is needed here for the Zplane to 
%% show up correctly in all versions of Matlab
MATLABVER = versioncheck(5.1);
if MATLABVER >= 6.0
  set(h1, 'CameraTarget',[0.5 0.5 0.5]);
else
  set(h1, 'CameraTarget',[0.0 0.0 0.0]); 
  set(h1, 'CameraPosition',[0.0 0.0 18.16]);
end

% ---- Menus in the GUI --------------------------------------------------------
h1 = uimenu('Parent',h0, ...
	    'Label','&Options', ...
	    'Tag','Options');
h2 = uimenu('Parent',h1, ...
	    'Label','&Level', ...
	    'Tag','Level');
h3 = uimenu('Parent',h2, ...
	    'Callback','phrace SelectLevel', ...
	    'Checked','on', ...
	    'Label','&Novice', ...
	    'Tag','Novice');
h3 = uimenu('Parent',h2, ...
	    'Callback','phrace SelectLevel', ...
	    'Label','&Pro', ...
	    'Tag','Pro');
h1 = uimenu('Parent',h0, ...
	    'Label','&Help', ...
	    'Tag','Help');
h2 = uimenu('Parent',h1, ...
	    'Callback','phrace Help', ...
	    'Label','&Contents', ...
	    'Tag','Contents');

if nargout > 0, fig = h0; end
