function initialize_Primary_state(menu_items)

global Primary_state init_distributions_parm

std_menu_items = { {'Binomial' 'Erlang' 'Exponential' 'Geometric' ...
                    'Negative Binomial' 'Normal' 'Poisson' } ...
                   {'Machine Reliability' 'Weather' 'Inventory System' ...
                    'Manufacturing' 'Manpower Planning' 'Stock Market' ...
                    'Telecommunication'} ...
                   {'General Machine Shop' 'Finite Capacity Single Server Queue' ...
                    'Inventory System' 'Finite Birth and Death Process' ...
                    'Telephone Switch' 'Call Center' 'Manufacturing' ...
                    'Airplane Reliability' 'Leaky Bucket'} ...
                   {'Series System'} ...
                   {'M/M/1/K' 'M/M/s/K' 'M/M/1' 'M/M/s' 'M/M/infinity' 'M/G/1' ...
                    'G/M/1' 'Jackson Network'} ...
                   {'Optimal Leasing of Phone Lines' 'Optimal Number of Tellers' ...
                    'Optimal Replacement' 'Optimal Server Allocation'} ...
                   {'Optimal Group Maintenance' 'Optimal Inventory Control' ...
                    'Optimal Processor Scheduling' 'Optimal Machine Operation'} } ;
scalar_parm_labels = { { {'n' 'p'} {'k' 'lambda'} {'lambda'} {'p'} ...
                         {'r' 'p'} {'mu' 'sigma'} {'lambda'} } ...
                       { {'No. of Repairpersons' 'No. of Machines' ...
                          'P(down|down)' 'P(up|up)'} ...
                         {'No scalar input required'} ...
                         { 'Restocking Level' 'Basestock Level'} ...
                         {'Size of Bin 1' 'Size of Bin 2' ...
                          'P(no defect) Mach. 1' 'P(no defect) Mach. 2'} ...
                         {'No. of Grades'} ...
                         {'Upper Limit' 'Lower Limit'} ...
                         { 'Buffer Capacity'} } ...
                       { {'No. of Repairpersons' 'No. of Machines' 'Failure Rate' ...
                          'Repair Rate'} ...
                         {'Capacity' 'Service Rate' 'Arrival Rate'} ...
                         {'Order Size' 'Base Stock' 'Demand Rate' 'Delivery Rate'} ...
                         {'No. of States'} ...
                         {'Switch Capacity' 'Call Completion Rate' 'Call Arrival Rate'} ...
                         {'Max Calls on Hold' 'No. of Agents' 'Call Service Rate' ...
                          'Call Arrival Rate'} ...
                         {'Storage Capacity' 'Lower Control Limit' 'Demand Rate' ...
                          'Production Rate'} ...
                         {'Engine Failure Rate'} ...
                         {'Token Pool Capacity' 'Data Buffer Capacity' ...
                          'Token Generation Rate' 'Packet Arrival Rate'} } ...
                       { {'No. of Components'} } ...
                       { {'Capacity' 'Service Rate' 'Arrival Rate'} ...
                         {'Capacity' 'No. of Servers' 'Service Rate' 'Arrival Rate'} ...
                         {'Service Rate' 'Arrival Rate'} ...
                         {'No. of Servers' 'Service Rate' 'Arrival Rate'} ...
                         {'Service Rate' 'Arrival Rate'} ...
                         {'Service Time Variance' 'Mean Service Time' 'Arrival Rate'} ...
                         {'Mean Service Rate'} ...
                         {'No. of Nodes'} } ...
                       { {'Max. No. of Lines' 'Lease Rate per Line' 'Call Charge Rate' ...
                          'Call Completion Rate' 'Call Arrival Rate'} ...
                         {'Waiting Cost Rate' 'Teller Salary' 'Capacity' ...
                          'Service Rate' 'Arrival Rate'} ...
                         {'Unplanned Rep. Cost' 'Planned Rep. Cost'} ...
                         {'Total No. of Servers' 'Service Rate 1' 'Service Rate 2' ...
                          'Arrival Rate'} } ...
                       { {'Revenue Rate' 'Cost of Visit' 'Cost of New Machine' ...
                          'No. of Machines' 'P(up|up)'} ...
                         {'Poisson Demand Rate' 'Storage Capacity' 'Delivery Charge' ...
                          'Purchase Price' 'Selling Price' 'Storage Cost Rate'} ...
                         {'Cost of Losing a Job' 'Job Completion Rate' ...
                          'Arrival Rate' 'Capacity' 'Max No. of Processors' ...
                          'Proc. Oper. Cost Rate' 'Holding Cost Rate'} ...
                         {'Oper. Cost Rate' 'Revenue Per Item' 'Demand Rate' ...
                          'Production Rate' 'Capacity' 'Turn-on Cost' ...
                          'Holding Cost Rate'} } } ;
init_scalars = { { {0 0} {0 0} {0} {0} {0 0} {0 0} {0} } ...
                 { {0 0 0 0} { } {0 0} {0 0 0 0} {0} {0 0} {0} } ...
                 { {0 0 0 0} {0 0 0} {0 0 0 0} {0} {0 0 0} {0 0 0 0} ...
                   {0 0 0 0} {0} {0 0 0 0} } ...
                 { {0} } ...
                 { {0 0 0} {0 0 0 0} {0 0} {0 0 0} {0 0} {0 0 0} {0} {0} } ...
                 { {0 0 0 0 0} {0 0 0 0 0} {0 0} {0 0 0 0} } ...
                 { {0 0 0 0 0} {0 0 0 0 0 0} {0 0 0 0 0 0 0} {0 0 0 0 0 0 0} } } ; 
vector_parm_labels = {{} ...
                      { {} {} {'P(Demand in a period = i)'} {} ...
                        {'P(Promotion from Grade i)' 'P(Departure from Grade i)' ...
                         'P(New worker joins Grade i)'} {} {'P(i Packets arrive in a slot)'} } ...
                      { {} {} {} {'Birth Rate in State i:' 'Death Rate in State i:'} ...
                        {} {} {} {} {} } ...
                      { {'Mean Lifetime of Component i:' 'Mean Rep. Time of Component i:'} } ...
                      {{} {} {} {} {} {} {'P(Int. Arr. Time = i):'} {'Number of Servers at Node i:' ...
                         'Service Rates at Node i:' 'External Arrival Rate at Node i:'}} ...
                      {{} {} {'P(Life-time = i):'} {}} ...
                      {} };
init_vectors = {{} {} {} {} {} {} {}} ;
matrix_parm_labels = {  {}...
      						{}...
      						{}...
      						{}...
                        {{} {} {} {} {} {} {} {'Routing Matrix:'}}...
                        {} ...
                        {}};
init_matrices = {{} {} {} {} {} {} {}};
distribution_parm_labels = {  {}...
                              {{} {} {'Demand Distribution'} {} {} ...
                               {} {'Packet Arrival Distribution'}}...
      						      {}...
      						      {}...
                              {{} {} {} {} {} {} {'Interarrival Distribution'} {}}...
                              {{} {} {'Lifetime Distribution'} {}} ...
                              {}};
distribution_menu_items = {  {}...
                              {{} {} {'Binomial' 'Geometric' 'Poisson' 'Discrete'} {} {} ...
                               {} {'Binomial' 'Geometric' 'Poisson' 'Discrete'}}...
      						      {}...
      						      {}...
                              {{} {} {} {} {} {} {'Exponential' 'Erlang'  'Geometric' 'Discrete'} {}}...
                              {{} {} {'Erlang' 'Discrete'} {}} ...
                              {}};
                        
                        distribution_item_num = {{}...
                              {{} {} {4} {} {} {} {4}}...
                              {}...
                              {}...
                              {{} {} {} {} {} {} {4} {}}...
                              {{} {} {2} {}}...
                              {}};
                              
                              
                        init_distributions_parm = {{}...
                              {{} {} {{0 0} {0 0} {0} {0} ...
      {0 0} {0 0} {0} {-1}} {} {} {} {{0 0} {0 0} {0} {0} ...
      {0 0} {0 0} {0} {-1}}}...
                              {}...
                              {}...
                              {{} {} {} {} {} {} {{0 0} {0 0} {0} {0} ...
      {0 0} {0 0} {0} {-1}}{}}...
                              {{} {} {{0 0} {0 0} {0} {0} ...
      {0 0} {0 0} {0} {-1}} {}}...
                              {}};
                        
% specify how many std menu items will be present for the next
% submenu for each of the primary models (1-1 and ordered)
stdmenu_num = {7 7 9 1 8 4 4} ;       
% create primary model state structure
Primary_state = struct('state', 0, ...
                       'model', menu_items, ... 
                       'std_menu_num', stdmenu_num, ...
                       'std_model_array', std_menu_items, ...
                       'std_state', 0, ...
                       'scalar_label', scalar_parm_labels, ...
                       'scalar_parm', init_scalars, ...
                       'vector_label', vector_parm_labels, ...
                       'vector_matrix', init_vectors, ...
                       'matrix_label', matrix_parm_labels, ...
                       'matrix_matrix', init_matrices,...
                       'distribution_label', distribution_parm_labels,...
                       'distribution_parm', init_distributions_parm,...
                       'distribution_menu', distribution_menu_items,...
                       'distribution_num',distribution_item_num) ;     
 
