function maxim_main()

% This is the main driver - called by start_maxim (which only sets the path)

global Scale Primary_state Next_process Last_process Printer_name
% initialize local variables
menu_items = {'Probability Models' 'Discrete Time Markov Models'...
              'Continuous Time Markov Models' 'Generalized Markov Models'...
              'Queueing Models' 'Design Models' 'Control Models' } ;
m = size(menu_items, 2) ;

% initialize global variables
Scale = .8 ;
initialize_Primary_state(menu_items) ;
Next_process = 'select_mode' ;
Last_process = 'maxim_main' ;

% temporarily hardcoding printer until this can be gotten another way
Printer_name = '\\server1\printer1' ;

% display main menu
mainfig = figure('Name','MAXIM', ...
                 'NumberTitle','off', ...
                 'Units','Normalized', ...
                 'Color',[0.76 0.76 0.76], ...
                 'Position',[0 .02 1 .92], ...
                 'Menubar','none', ...
                 'Tag','main_figure') ;

% add exit menu item and titles
exit = end_maxim (mainfig);
exit = help_msg(mainfig,1);
uicontrol('Parent',mainfig, ...
          'Units','normalized', ...
        	 'Position',[.25 .92 .50 .07], ...
          'BackgroundColor', [0.76 0.76 0.76], ...
          'Style','text', ...
          'Fontname','time roman', ...
          'Fontsize',Scale*30, ...
          'String', 'Welcome to MAXIM') ;
uicontrol('Parent',mainfig, ...
          'Units','normalized', ...
        	 'Position',[.25 .78 .50 .07], ...
          'BackgroundColor', [0.76 0.76 0.76], ...
          'Style','text', ...
          'Fontname','time roman', ...
          'Fontsize',Scale*30, ...
          'String', 'Main Menu') ;

% display main menu items, use callback to set the primary state matrix
for k=1:m
      uicontrol('Parent',mainfig, ...
                'Units','normalized', ...
                'Fontname','time roman', ...
                'Fontsize',Scale*18, ...
                'String',menu_items{k}, ...
                'Callback', [sprintf('set_primary_model_state(%i, 1);', k), ...
                             'uiresume(gcbf)'], ...
                'Position',[.33 .2+.07*(m-k) .33 .07]) ;
end

% wait for user to click on a menu item before resuming          
uiwait(mainfig)

% create a loop that will allow Previous Screen to function
quit = 0 ;
while (quit == 0)
  % display menu for selection of Std Model, Load Model, Create Model
  select_mode ;

  % Execute selection and pass control to module standard_load_create
  standard_load_create ;

  if (strcmp(lower(Next_process), 'maxim_main') ...
     | strcmp(lower(Next_process), 'quit'))
     quit = 1 ;                       
  end 
end  %while quit

% If we came here from Previous Screen, restart main module
if strcmp(lower(Next_process), 'maxim_main')
  close all ;
  maxim_main ;
end
