function select_mode()

global Scale Primary_state Next_process Last_process Current_process

% If this is not the correct procedure to be executing, return to caller
if strcmp(lower(Next_process), 'select_mode') ~= 1
  return
else
   Current_process = 'select_mode';
  Last_process = 'maxim_main' ;
  Next_process = 'standard_load_create' ;
end

% make the background figure blank
set(findobj('Parent',findobj('Tag','main_figure')),'Visible','off')

% retrieve the row number of the currently selected Primary model
% in the Primary_state structure - also retrieve its label
module = get_primary_model ; 
model = Primary_state(module).model ;
%module_name = sprintf('Standard %s', model) ;
module_name = model;
% display the mode selection menu 
modefig = figure('Name',module_name, ...
                 'NumberTitle','off', ...
                 'Color',[0.76 0.76 0.76], ...
	              'Units','normalized', ...
                 'Position', [.33 .25 .4 .4], ...
                 'Menubar','none', ...
                 'Tag','Fig1');

% add exit, return to main, previous screen, and title
exit = exit_menu(modefig) ;
exit = return_to_main(modefig) ;
exit = previous_screen(modefig) ;
% initialize help_message_ids
help_msg_id = [2 3 4 5 6 7 8];
exit = help_msg(modefig,help_msg_id(module));

uicontrol('Parent',modefig, ...
          'Units','normalized', ...
        	 'Position',[.15 .75 .7 .2], ...
          'Style','text', ...
          'Fontname','time roman', ...
          'Fontsize',Scale*20, ...
          'String', module_name) ;

% Standard Model - callback updates the global Primary_state structure
% with a state value of 2
uicontrol('Parent',modefig, ...
          'Units','normalized', ...
          'BackgroundColor',[0.752941 0.752941 0.752941], ...
          'Callback', [sprintf('set_primary_model_state(%i, 2);', module), ...
                       'uiresume(gcbf)'],...
          'FontName','time roman', ...
	       'Fontsize',Scale*18, ...
	       'Position',[.1 .45 .8 .2], ...
          'String','Use a Standard Model', ...
	       'Tag','ModeSelect');

% Create a New Model - callback updates the global Primary_state structure
% with a state value of 4
uicontrol('Parent',modefig, ...
          'Units','normalized', ...
          'BackgroundColor',[0.752941 0.752941 0.752941], ...
          'Callback', [sprintf('set_primary_model_state(%i, 4);', module), ...
                       'uiresume(gcbf)'],...
          'FontName','time roman', ...
	       'Fontsize',Scale*18, ...
	       'Position',[.1 .25 .8 .2], ...
          'String','Create a New Model', ...
	       'Tag','ModeSelect');

% Load a Model - callback updates the global Primary_state structure
% with a state value of 3
uicontrol('Parent',modefig, ...
          'Units','normalized', ...
          'BackgroundColor',[0.752941 0.752941 0.752941], ...
          'Callback', [sprintf('set_primary_model_state(%i, 3);', module), ...
                       'uiresume(gcbf)'],...
          'FontName','time roman', ...
	       'Fontsize',Scale*18, ...
	       'Position',[.1 .05 .8 .2], ...
          'String','Get Model From a File', ...
          'Tag','ModeSelect');

% wait for user to select a mode before closing and returning to main module
uiwait(modefig)

% Execute this code only if the figure still exists
if ishandle(modefig)
  close(modefig)
end
