num = [1 .98];
den = conv([1 -1],[1 -.93]);
[kbreak,sbreak] = rlpoba(num,den);
[kmax,smax] = rootmag(num,den,1);
[kk,ss] = rootangl(num,den,90);
r = rlocus(num,den,sort([kbreak' kmax' kk' linspace(0,15)]));
axis([-5 2 -2.5 2.5]); plot(r,'-'); grid; axis([-5 2 -2.5 2.5]);
xlabel('Real'); ylabel('Imaginary');
hold on;
z = roots(num); plot(z+sqrt(-1)*eps,'ow');
p = roots(den); plot(p+sqrt(-1)*eps,'xw');
plot(0,imag(ss),'*g',0,-imag(ss),'*b');
text(0,imag(ss),[' K = ' num2str(kk)]);
text(0,-imag(ss),[' S = ' num2str(-imag(ss)) 'j']);
plot(real(smax),imag(smax),'*y');
text(real(smax(1)),imag(smax(1)),[' Kmax = ' num2str(kmax(1))]);
text(real(smax(2)),imag(smax(2)),[' Kmax = ' num2str(kmax(2))]);
text(real(smax(4)),imag(smax(4)),[' Kmin = ' num2str(kmax(4))]);
w = linspace(0,2*pi); plot(cos(w),sin(w),'--');
hold off;
