num = [1 .98];
den = conv([1 -0.2],[1 -1]);
[kbreak,sbreak] = rlpoba(num,den);
[kmax,smax] = rootmag(num,den,1);
r = rlocus(num,den,sort([kbreak' kmax' linspace(0,15) 100]));
axis([-5 2 -2.5 2.5]); plot(r,'-'); grid; axis([-5 2 -2.5 2.5]);
hold on;
z = roots(num); plot(real(z),imag(z),'o');
p = roots(den); plot(real(p),imag(p),'x');
w = linspace(0,2*pi); plot(cos(w),sin(w),'--');
plot(real(smax),imag(smax),'*b');
xlabel('Real Z'); ylabel('Imaginary Z');
text(real(smax(1)),imag(smax(1)),[' Kmax = ' num2str(kmax(1))]);
text(real(smax(2)),imag(smax(2)),[' Kmax = ' num2str(kmax(2))]);
text(real(smax(4)),imag(smax(4)),[' Kmin = ' num2str(kmax(4))]);
zeta = 0.45; w = linspace(0,12); z = exp(-zeta*w+sqrt(zeta^2-1)*w);
plot(z,':b');
kk=0.2565; rr = rlocus(num,den,kk);
text(real(rr(1)),imag(rr(1)),' K = 0.2565');
hold off;
