function cons=getconstrainttypes(obj)
%GECONSTRAINTTYPES
%
%  CONS=GETCONSTRAINTTYPES(OBJ)  returns a cell array
%  containing the constructor names for all of the supported
%  constraint types.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.4.6.1 $    $Date: 2004/02/09 06:53:19 $

if allowsums(obj)
    cons={ ...
            'conlinear'; ...
            'conellipsoid'; ...
            'contable1'; ...
            'contable2'; ...
            'concgmodel'; ...
            'consumcgmodel'; ...
        };
else
    cons={ ...
            'conlinear'; ...
            'conellipsoid'; ...
            'contable1'; ...
            'contable2'; ...
            'concgmodel'; ...
        };
end
