function mpc555setupinfo
%MPC555SETUPINFO

% Copyright 2001-2002 The MathWorks, Inc.
% $Revision: 1.5.4.1 $
% $Date: 2004/04/19 01:27:09 $

home

msg = sprintf(['\n',...
  '  To configure the Embedded Target for Motorola MPC555,\n',...
  '  at the MATLAB command window, type:\n\n',...
  '    >> tpObj = gettargetprefs(''mpc555dk'')\n',...
  '    >> edit(tpObj)\n\n',...
  '  When you have finished configuring your target preferences,\n',...
  '  you must activate your changes using SETTARGETPREFS. To\n',...
  '  activate your settings, type:\n\n',...
  '    >> settargetprefs(''mpc555dk'', tpObj)\n\n',...
  '  For more information on setting up your environment \n',...
  '  for the Embedded Target for Motorola MPC555, type:\n \n',...
  '    >>help gettargetprefs \n',...
  '    >>help settargetprefs \n\n']);

disp(msg);
