function [out,out2]=propertypage(obj,action,varargin)
%PROPERTYPAGE   Generate an editing page for this constraint
%
%  LYT=PROPERTYPAGE(OBJ,'CREATE',FIG,PTR,MDL,FACTORS)
%  [OK,MSG]= PROPERTYPAGE(OBJ,'FINALISE',LYT)
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.4.2.2 $  $Date: 2004/02/09 06:58:25 $

switch lower(action)
case 'create'
   out=i_createlyt(varargin{:});
   out2=[];
case 'finalise'
   [out,out2]=i_finalise(varargin{:});
end
return



function lyt=i_createlyt(fig,ptr,mdl,fact)

txt=xreguicontrol('parent',fig,...
   'hittest','off',...
   'enable','inactive',...
   'visible','off',...
   'style','text',...
   'string','Values are in coded units',...
   'horizontalalignment','left');
P=getparams(ptr.info);
tbl=xregtable(fig,...
   'visible','off',...
   'position',[0 0 100 100],...
   'cols.size',53,...
   'rows.size',20,...
   'frame.hborder',[0 0],...
   'frame.vborder',[0 0],...
   'frame.box','off',...
   'frame.visible','off',...
   'cells.defaultbackgroundcolor',[1 1 1],...
   'defaultcelltype','edit',...
   'defaultcellformat','%.4g',...
   'rows.number',2,...
   'cols.number',size(P.A,2)+1,...
   'zeroindex',[2 1]);

set(tbl,...
   'cells.colselection',[1 size(P.A,2)+1],...
   'cells.rowselection',[1 1],...
   'cells.type','uitogglebutton',...
   'cells.enable','inactive',...
   'cells.backgroundcolor',get(0,'defaultuicontrolbackgroundcolor'),...
   'cells.colselection',[size(P.A,2)+1 size(P.A,2)+1],...
   'cells.rowselection',[1 2],...
   'cells.backgroundcolor',[0.9 0.9 0.9]);

tbl(1,1:size(P.A,2))=P.A;
tbl(1,end)=P.b;
tbl(0,:).string= [fact {'b'}];

ud.tbl= tbl;
ud.ptr=ptr;

lyt=xregpanellayout(fig,...
   'innerborder',[0 0 0 0],...
   'center',tbl,...
   'packstatus','off');
lyt=xreggridbaglayout(fig,...
   'dimension',[2 1],...
   'rowsizes',[15 65],...
   'border',[0 0 0 5],...
   'gapy',5,...
   'elements',{txt,lyt},...
   'userdata',ud);
return


function [ok,msg]=i_finalise(lyt)
ud=get(lyt,'userdata');
A= ud.tbl(1,1:end-1);
b= ud.tbl(1,end);

[c,msg]=setparams(ud.ptr.info,'A',A,'b',b);
ud.ptr.info=c;
ok= isempty(msg);
return