Shear=-10; %Newtons
AYValue=0.035; %meters
BYValue=0.02; %meters
CYValue=0.01; %meters
CSW=0.05; %meters
CSH=0.04; %meters
CSBase=0.01; %meters
CSWeb=0.01; %meters
I=ibeam(CSW,CSH,CSBase,CSWeb,'I','Ix');
AThickness=CSW;
BThickness=CSWeb;
CThickness=CSWeb;
OldCentroid=ibeam(CSW,CSH,CSBase,CSWeb,'I','centY');
AQArea=rectangl(CSW,CSH-AYValue,'area');
AQNewCen=rectangl(CSW,CSH-AYValue,'centY')+AYValue;
AQYBar=abs(OldCentroid-AQNewCen);
AQ=AQYBar*AQArea;
BQArea=tbeam(CSW,CSH-BYValue,CSBase,CSWeb,'n','area');
BQNewCen=tbeam(CSW,CSH-BYValue,CSBase,CSWeb,'n','area')+BYValue;
BQYBar=abs(OldCentroid-BQNewCen);
BQ=BQYBar*BQArea;
CQArea=rectangl(CSW,CSH-CYValue,'area');
CQNewCen=rectangl(CSW,CSH-CYValue,'centY');
CQYBar=abs(OldCentroid-CQNewCen);
CQ=CQYBar*CQArea;
AStress=Shear*AQ/(I*AThickness);
BStress=Shear*BQ/(I*BThickness);
CStress=Shear*CQ/(I*CThickness);
