Base=0.07; %meters
Height=0.1; %meters
BaseHeight=0.02; %meters
WebT=0.01; %meters
PointX=0.01; %placement of point A
PointY=0.1; %placement of point A
%PointX=0.035; %placement of point B
%PointY=0; %placement of point B
Moment=50; %Newton meters
Angle=DR(30);
XAxisMoment=cos(Angle)*Moment;
YAxisMoment=sin(Angle)*Moment;
Ix=tbeam(Base,Height,BaseHeight,WebT,'n','Ix');
Iy=tbeam(Base,Height,BaseHeight,WebT,'n','Iy');
CentX=tbeam(Base,Height,BaseHeight,WebT,'n','centX');
CentY=tbeam(Base,Height,BaseHeight,WebT,'n','centY');
Xoffset=PointX-CentX;
Yoffset=CentY-PointY;
SigmaFromX=XAxisMoment*Yoffset/Ix
SigmaFromY=YAxisMoment*Xoffset/Iy
TotalStress=SigmaFromX+SigmaFromY
