function hInfo = propPageGeneral(obj, hPropDialog)
%PROPPAGEGENERAL Create the General property tab
%
%  INFO = PROPPAGEGENERAL(OBJ, HPROPDIALOG) creates the info object that
%  represents the General tab in a property dialog.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.1.6.2 $    $Date: 2004/04/12 23:34:34 $

hInfo = xregGui.propertyPageInfo('General');
hInfo.HelpHandler = 'cghelptool';
hInfo.HelpCode = 'CGEXPRPROPPAGEGENERAL';

imdata = cgresload(iconfile(obj),'bmp');
sc = xregGui.SystemColors;
imdata = replacecolor(imdata, [255 0 255], sc.CTRL_BACK);
im = xregGui.axesimage('parent',hPropDialog.Figure,...
    'visible', 'off', ...
    'image',imdata);
nmtxt = uicontrol('style','text',...
    'parent', hPropDialog.Figure,...
    'enable', 'inactive', ...
    'visible', 'off', ...
    'string', getname(obj),...
    'horizontalalignment','left');

divl = xregGui.dividerline('parent', hPropDialog.Figure, ...
    'visible', 'off');

tpCtrl = i_maketextcontrol(hPropDialog, 'Type:', get(obj, 'type'), 130);
inpCtrl = i_maketextcontrol(hPropDialog, 'Number of inputs:', ...
    sprintf('%d', length(getinputs(obj))), 130);

if concheck(obj)
    constr = 'Available';
else
    constr = 'Not available';
end
conCtrl = i_maketextcontrol(hPropDialog, 'Constraints:', constr, 130);

if pevcheck(obj)
    pevstr = 'Available';
else
    pevstr = 'Not available';
end
pevCtrl = i_maketextcontrol(hPropDialog, 'Prediction error variance:', pevstr, 130);

hGrid = xreggridbaglayout(hPropDialog.Figure, ...
    'dimension', [9, 2], ...
    'rowsizes', [1 15 10 2 5 25 25 25 25], ...
    'colsizes', [16 -1], ...
    'gapx', 10, ...
    'border', [10 10 10 10], ...
    'mergeblock', {[1 2], [1 1]}, ...
    'mergeblock', {[4 4], [1 2]}, ...
    'mergeblock', {[6 6], [1 2]}, ...
    'mergeblock', {[7 7], [1 2]}, ...
    'mergeblock', {[8 8], [1 2]}, ...
    'mergeblock', {[9 9], [1 2]}, ...
    'elements', {im, [], [], divl, [], tpCtrl, inpCtrl, conCtrl, pevCtrl, ...
    [], nmtxt});

hInfo.TabComponent = hGrid;


function h = i_maketextcontrol(hPropDialog, Label, Text, LabelSize)
h = xregGui.labelcontrol('parent', hPropDialog.Figure, ...
        'Visible', 'off', ...
        'LabelSizeMode', 'absolute', ...
        'LabelSize', LabelSize, ...
        'ControlSizeMode', 'relative', ...
        'ControlSize', 1, ...
        'String', Label, ...
        'Border', [0 5 0 5], ...
        'Control', xregGui.truncateduicontrol('parent', hPropDialog.Figure, ...
        'Style', 'text', ...
        'HorizontalAlignment', 'left', ...
        'Enable', 'inactive', ...
        'Visible', 'off', ...
        'String', Text));
