function cgoptionsgui
%CGOPTIONSGUI  GUI for setting user options in cage
%
%  CGOPTIONSGUI

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.5.2.4 $  $Date: 2004/04/04 03:36:53 $


AP= mbcprefs('mbc');

ud.options.files = getpref(AP,'PathDefaults');
ud.options.user = initfromprefs(mbcuser);
ud.options.optim = initfromprefs(cgoptimfuncs);

fs = [400,240];
screensize = get(0,'screensize');
fh= xregdialog('position',[50,screensize(4)-fs(2)-50,fs],...
    'resize','off',...
    'visible','off',...
    'Tag','CAGEOptions',...
    'name','CAGE Preferences');
xregpersistfigpos(fh,'key','CAGEOptions');
xregmoveonscreen(fh);

% File location tab
ud.Hand.File.cagfiles = xregGui.labelcontrol('parent',fh,...
    'visible','off',...
    'string','Projects:',...
    'labelsizemode','absolute',...
    'controlsizemode','relative',...
    'labelsize',70,...
    'controlsize',1,...
    'border',[0 1 0 1],...
    'Control',xregGui.uicontrol('parent',fh,...
    'style','edit',...
    'string',ud.options.files.cagfiles,...
    'horizontalalign','left',...
    'backgroundcolor',[1 1 1]));

ud.Hand.File.cagedatafiles = xregGui.labelcontrol('parent',fh,...
    'visible','off',...
    'string', 'Data files:',...
    'labelsizemode','absolute',...
    'controlsizemode','relative',...
    'labelsize',70,...
    'controlsize',1,...
    'border',[0 1 0 1],...
    'Control',xregGui.uicontrol('parent',fh,...
    'style','edit',...
    'string',ud.options.files.cagedatafiles,...
    'horizontalalign','left',...
    'backgroundcolor',[1 1 1]));

ud.Hand.File.Push(1)= xregGui.iconuicontrol('parent',fh,...
    'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
    'transparentColor', [0 255 0],...
    'callback',{@i_GetFile,'cagfiles'});
ud.Hand.File.Push(2)= xregGui.iconuicontrol('parent',fh,...
    'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
    'transparentColor', [0 255 0],...
    'callback',{@i_GetFile,'cagedatafiles'});

okbtn = uicontrol('parent',fh,...
    'style','pushbutton',...
    'callback','set(gcbf,''visible'',''off'',''tag'',''ok'');',...
    'string','OK');
cancbtn = uicontrol('parent',fh,...
    'style','pushbutton',...
    'callback','set(gcbf,''visible'',''off'');',...
    'string','Cancel');

filegrd = xreggridbaglayout(fh,...
    'packstatus','off',...
    'dimension',[2 2],...
    'gapx',5,...
    'gapy',7,...
    'border',[10 10 10 15],....
    'rowsizes',[22 22],...
    'colsizes',[-1 22],...
    'elements',{ud.Hand.File.cagfiles, ud.Hand.File.Push(1); ...
        ud.Hand.File.cagedatafiles, ud.Hand.File.Push(2)});

userobj = createguiobject(ud.options.user,'edit',fh);
optimobj = createguiobject(ud.options.optim, fh);
userlyt = xreglayerlayout(fh,'border',[10 10 10 15],...
    'elements',{userobj});
optimlyt = xreglayerlayout(fh,'border',[10 10 10 15],...
    'elements',{optimobj});

tabs = xregtablayout2(fh,'numcards',3,...
    'tablabels',{'File Locations','User Information', 'Optimization'});
attach(tabs,filegrd,1);
attach(tabs,userlyt,2);
attach(tabs,optimlyt,3);

lyt = xreggridbaglayout(fh,...
    'dimension',[2 3],...
    'rowsizes',[-1 25],...
    'colsizes',[-1 65 65],...
    'gapy',10,...
    'gapx',7,...
    'border',[7 7 7 7],...
    'mergeblock',{[1 1],[1 3]},...
    'elements',{tabs,[],[],okbtn,[],cancbtn});


fh.LayoutManager = lyt;
set(lyt,'packstatus','on');
fh.Userdata = ud;
fh.showDialog(okbtn);

status = get(fh,'tag');
if strcmp(status,'ok')
    ud.options.files.cagfiles = get(ud.Hand.File.cagfiles.Control,'string');
    ud.options.files.cagedatafiles = get(ud.Hand.File.cagedatafiles.Control,'string');
    ud.options.user = initfromguiobject(ud.options.user,userobj);
    ud.options.optim = initfromguiobject(ud.options.optim, optimobj);
    
    AP= mbcprefs('mbc');
    setpref(AP,'PathDefaults',ud.options.files);
    sendtoprefs(ud.options.user);
    sendtoprefs(ud.options.optim);
end
delete(fh);


function i_GetFile(h,evt,prefname)
fh = get(h,'parent');
ud = get(fh,'userdata');

edt = get(ud.Hand.File.(prefname),'Control');
oldpath = get(edt,'string');
newpath = uigetdir(oldpath,'Select path:');
if newpath~=0
    set(edt,'string',newpath);
end