function chap02
% List of plots in chapter 2 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 2.1: mf_univ', ...
    '#Figure 2.2: lingmf', ...
    '#Figure 2.4: convexmf', ...
    '#Figure 2.5: subset', ...
    '#Figure 2.6: fuzsetop', ...
    '#Figure 2.7: disp_mf', ...
    '#Figure 2.8: allbells', ...
    '#Figure 2.10: disp_sig', ...
    '#Figure 2.11: difflr', ...
    '#Figure 2.12: cyl_ext', ...
    '#Figure 2.13: project', ...
    '#Figure 2.14: mf2d', ...
    '#Figure 2.15: negation', ...
    '#Figure 2.16 & 2.17: tnorm', ...
    '#Figure 2.18: sstnorm', ...
    '#Figure 2.19: resolut'];

[labels, callbacks] = list2cb(list);
choices('Chapter 2', 'Plots for Chapter 2', labels, callbacks, 1);
