function chap03
% List of plots in chapter 3 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 2', 'Plots for Chapter 2', labels, callbacks);

list = [...
    '#Figure 3.2: extensio', ...
    '#Figure 3.4: lv', ...
    '#Figure 3.5: complv', ...
    '#Figure 3.6: intensif', ...
    '#Figure 3.8 & 3.9: fuzimp', ...
    '#Figure 3.11: cri'];

[labels, callbacks] = list2cb(list);
choices('Chapter 3', 'Plots for Chapter 3', labels, callbacks, 1);
