function chap04
% List of plots in chapter 4 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 2', 'Plots for Chapter 2', labels, callbacks);

list = [...
    '#Figure 4.5: mam1', ...
    '#Figure 4.6: mam2', ...
    '#Figure 4.7: ruleview mam21', ...
    '#Figure 4.9: sug1', ...
    '#Figure 4.10: sug2', ...
    '#Figure 4.12: tsu1'];

[labels, callbacks] = list2cb(list);
choices('Chapter 4', 'Plots for Chapter 4', labels, callbacks, 1);
