function chap06
% List of plots in chapter 6 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 6.6: descent', ...
    '#Figure 6.13: gdss1', ...
    '#Figure 6.14: cg', ...
    '#Figure 6.15: gdss1', ...
    '#Figure 6.17: gdss2', ...
    '#Figure 6.20: gdconv'];

[labels, callbacks] = list2cb(list);
choices('Chapter 6', 'Plots for Chapter 6', labels, callbacks, 1);
