function chap09
% List of plots in chapter 9 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 9.3: xordata', ...
    '#Figure 9.5: xorsurf1', ...
    '#Figure 9.7: activati'];

[labels, callbacks] = list2cb(list);
choices('Chapter 9', 'Plots for Chapter 9', labels, callbacks, 1);
