function chap11
% List of plots in chapter 11 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 11.2: compball', ...
    '#Figure 11.4: kfm(1)', ...
    '#Figure 11.5: kfm(2)', ...
    '#Figure 11.6: kfm(5)', ...
    '#Figure 11.7: lvqdata'];

[labels, callbacks] = list2cb(list);
choices('Chapter 11', 'Plots for Chapter 11', labels, callbacks, 1);
