function chap12
% List of plots in chapter 12 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 12.6: init_mf', ...
    '#Figure 12.8 & 9: trn_2in', ...
    '#Figure 12.11 & 12: trn_3in', ...
    '#Figure 12.14: trn_1in(5)', ...
    '#Figure 12.15: trn_1in(4)', ...
    '#Figure 12.16: trn_1in(3)', ...
    '#Figure 12.17 & 18 & 19: trn_4in'];

[labels, callbacks] = list2cb(list);
choices('Chapter 12', 'Plots for Chapter 12', labels, callbacks, 1);
