function chap14
% List of plots in chapter 14 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 14.2: tsurf1', ...
    '#Figure 14.2: tsurf2', ...
    '#Figure 14.4: impurity', ...
    '#Figure 14.5: splits', ...
    '#Figure 14.6 & 7: go_cart', ...
    '#Figure 14.8: carterr', ...
    '#Figure 14.9: cartmf', ...
    '#Figure 14.10: ftsurf1', ...
    '#Figure 14.10: ftsurf2'];

[labels, callbacks] = list2cb(list);
choices('Chapter 14', 'Plots for Chapter 14', labels, callbacks, 1);
