function chap17
% List of plots in chapter 17 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 17.6 & 7: inv_sig', ...
    '#Figure 17.7 & 8: inv_fc'];

[labels, callbacks] = list2cb(list);
choices('Chapter 17', 'Plots for Chapter 17', labels, callbacks, 1);
