function chap19
% List of plots in chapter 19 of "Neuro-Fuzzy and Soft Computing".

%labels = str2mat(...
%    'Figure 2.1: mf_univ', ...
%    'Figure 2.2: lingmf', ...
%    'Figure 2.19: resolut');
%
%% Callbacks
%callbacks = str2mat(...
%    'genfig(''Figure 2.1''); mf_univ', ...
%    'genfig(''Figure 2.2''); lingmf', ...
%    'genfig(''Figure 2.19''); resolut');
%
%choices('Chapter 1', 'Plots for Chapter 1', labels, callbacks);

list = [...
    '#Figure 19.1: xordata', ...
    '#Figure 19.1: xormf', ...
    '#Figure 19.2: xor2dmf', ...
    '#Figure 19.3: xorsurf',...
    '#Figure 19.4: pchar',...
    '#Figure 19.5: fuzpcr',...
    '#Figure 19.7: invsurf',...
    '#Figure 19.8: invkine',...
    '#Figure 19.9: mpgpick2',...
    '#Figure 19.10 & 11(a): mpgtrain',...
    '#Figure 19.11(b): mpgdata',...
    '#Figure 19.12: bjpick2',...
    '#Figure 19.13: bjtrain',...
    '#Figure 19.15: nonoise',...
    '#Figure 19.16: optideci',...
    '#Figure 19.17: equdata',...
    '#Figure 19.18: equdensi',...
    '#Figure 19.19: eqtrain(2)',...
    '#Figure 19.20: eqtrain(3)',...
    '#Figure 19.21: equdec',...
    '#Figure 19.23, 24, 25, 26, 27: noise1',...
    '#Figure 19.28, 29, 30, 31: noise2'];

[labels, callbacks] = list2cb(list);
choices('Chapter 19', 'Plots for Chapter 19', labels, callbacks, 1);
