list = [...
    '#Cool Demos: cooldemo', ...
    '#Figures in Chapter 2: ch02', ...
    '#Figures in Chapter 3: ch03', ...
    '#Figures in Chapter 4: ch04', ...
    '#Figures in Chapter 5: ch05', ...
    '#Figures in Chapter 6: ch06', ...
    '#Figures in Chapter 7: ch07', ...
    '#Figures in Chapter 9: ch09', ...
    '#Figures in Chapter 11: ch11', ...
    '#Figures in Chapter 12: ch12', ...
    '#Figures in Chapter 14: ch14', ...
    '#Figures in Chapter 15: ch15', ...
    '#Figures in Chapter 17: ch17', ...
    '#Figures in Chapter 19: ch19'];

[labels, callbacks] = list2cb(list);
choices('Demos and Figures', ...
	'Demos and Figures for "Neuro-Fuzzy and Soft Computing"', ...
	labels, callbacks, 1);
