function [T,ok]=gui_setupinputs(T,action,varargin)
%GUI_SETUPINPUTS  Select variables as inputs to table
%
%  [T,OK]=GUI_SETUPINPUTS(T,'figure','DD',P_DD)

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.8.2.5 $  $Date: 2004/04/04 03:27:34 $

switch lower(action)
case 'figure'
   [T,ok] = i_createfig(T,varargin{:});
end



function [Tout,ok] = i_createfig(T,varargin)
scrpos=get(0,'screensize');
figh=xregdialog('name','Table Setup',...
   'resize','off',...
   'tag','tableinputs');
xregcenterfigure(figh,[300 190]);

p=xregpointer(T);
lyt=i_createlyt(figh,p,varargin{:});
set(lyt,'visible','on');
okbtn=uicontrol('parent',figh,...
   'style','pushbutton',...
   'string','OK',...
   'callback','set(gcbf,''tag'',''ok'',''visible'',''off'');',...
   'interruptible','off');
cancbtn=uicontrol('parent',figh,...
   'style','pushbutton',...
   'string','Cancel',...
   'callback','set(gcbf,''visible'',''off'');',...
   'interruptible','off');

grd=xreggridbaglayout(figh,...
   'dimension',[2 3],...
   'rowsizes',[-1 25],...
   'colsizes',[-1 65 65],...
   'gapy',10,'gapx',7,...
   'border',[7 7 7 7],...
   'mergeblock',{[1 1],[1 3]},...
   'elements',{lyt,[],[],okbtn,[],cancbtn});
figh.LayoutManager=grd;
set(grd,'packstatus','on');

figh.showDialog(okbtn);

%dialog blocks here

tg=get(figh,'tag');
if strcmp(tg,'ok')
   i_finalise(lyt);
   Tout=p.info;
   ok=1;
else
   Tout=T;
   ok=0;
end
delete(figh);
freeptr(p);


function lyt=i_createlyt(figh,p,varargin)
p_ud=xregGui.RunTimePointer;

ud.Tpointer=p;
ud.DDpointer=[];

for n=1:2:length(varargin)
   switch lower(varargin{n})
   case 'dd'
      % pick up data dictionary
      ud.DDpointer=varargin{n+1};
   end
end

ud.Name=xregGui.labelcontrol('parent',figh,...
   'labelsize',50,...
   'labelsizemode','absolute',...
   'string','Name:',...
   'controlsize',1,...
   'controlsizemode','relative',...
   'gap',5,...
   'Control',uicontrol('parent',figh,...
   'style','edit',...
   'backgroundcolor','w',...
   'horizontalalignment','left',...
   'callback',@i_disallowempty));
   
ud.Xvar=xregGui.labelcontrol('parent',figh,...
   'labelsize',50,...
   'labelsizemode','absolute',...
   'string','X input:',...
   'controlsize',1,...
   'controlsizemode','relative',...
   'gap',5,...
   'Control',uicontrol('parent',figh,...
   'style','edit',...
   'backgroundcolor','w',...
   'horizontalalignment','left',...
   'callback',@i_disallowempty));

ud.Yvar=xregGui.labelcontrol('parent',figh,...
   'labelsize',50,...
   'labelsizemode','absolute',...
   'string','Y input:',...
   'controlsize',1,...
   'controlsizemode','relative',...
   'gap',5,...
   'Control',uicontrol('parent',figh,...
   'style','edit',...
   'backgroundcolor','w',...
   'horizontalalignment','left',...
   'callback',@i_disallowempty));

ud.EditXSize = xregGui.clickedit('parent', figh, ...
    'horizontalalign','right',...
    'min', 2, ...
    'rule', 'int', ...
    'dragging', 'off', ...
    'enable','off');
ud.ManTextX = xregGui.labelcontrol('parent',figh, ...
    'string','Rows: ',...
    'LabelAlignment','left', ...
    'LabelSizeMode', 'Absolute', ...
    'LabelSize', 50, ...
    'gap',5,...
    'ControlSize',50, ...
    'control', ud.EditXSize);

ud.EditYSize = xregGui.clickedit('parent', figh, ...
    'horizontalalign','right',...
    'min', 2, ...
    'rule', 'int', ...
    'dragging', 'off', ...
    'enable','off');
ud.ManTextY = xregGui.labelcontrol('parent',figh, ...
    'string','Columns: ',...
    'LabelAlignment','left', ...
    'LabelSizeMode', 'Absolute', ...
    'LabelSize', 50, ...
    'gap',5,...
    'ControlSize',50, ...
    'control', ud.EditYSize);

ud.EditValue = xregGui.clickedit('parent', figh, ...
    'enable','off');
ud.ValueLabel = xregGui.labelcontrol('parent',figh, ...
    'string', 'Initial value:',...
    'LabelAlignment','left', ...
    'LabelSizeMode', 'Absolute', ...
    'LabelSize', 60, ...
    'gap',5,...
    'ControlSize',70, ...
    'control', ud.EditValue);

lyt = xreggridbaglayout(figh, ...
    'packstatus', 'off', ...
    'dimension', [5 3], ...
    'rowsizes', [20 20 20 20 20], ...
    'colsizes', [130 150 -1], ...
    'gapy', 10, ...
    'mergeblock', {[1 1], [1 3]}, ...
    'mergeblock', {[2 2], [1 3]}, ...
    'mergeblock', {[3 3], [1 3]}, ...
    'elements', {ud.Name, ud.Xvar, ud.Yvar, ud.ManTextX, ud.ManTextY , ...
    [], [], [], ud.ValueLabel}, ...
    'userdata', p_ud);

ud=i_setvalues(ud);
p_ud.info=ud;
return


function i_disallowempty(src,evt)
str=get(src,'string');
if isempty(str)
   set(src,'string',get(src,'userdata'));
else
   set(src,'userdata',str);
end



function ud=i_setvalues(ud);
T=ud.Tpointer.info;
Nx=get(T,'x');
Ny=get(T,'y');

% get default strings from normaliser settings if possible
Vx=Nx.get('x');
Vy=Ny.get('x');
strX='';
strY='';
if ~isempty(Vx) & Vx~=0
   strX=Vx.getname;
end
if ~isempty(Vy) & Vy~=0
   strY=Vy.getname;
end
if isempty(strX) | isempty(strY)
   % get list of names from DD
   DD=ud.DDpointer;
   if ~isempty(DD)
      nms= DD.listnames;
      k=1;
      N_nms=length(nms);
      if isempty(strX)
         if k<=N_nms
            strX=nms{k};
            k=k+1;
         else
            strX='X';
         end
      end
      if isempty(strY)
         if k<=N_nms
            strY=nms{k};
         else
            strY='Y';
         end
      end
   else
      % make up some default names
      if isempty(strX)
         strX='X';
      end
      if isempty(strX)
         strX='Y';
      end
   end
end

name = getname(T);
set(ud.Xvar.Control,'string',strX,'userdata',strX);
set(ud.Yvar.Control,'string',strY,'userdata',strY);
set(ud.Name.Control,'string', name, 'userdata', name);

%------------------------------
function i_finalise(lyt)
%

p_ud = get(lyt,'userdata');
ud = p_ud.info;

name  = get(ud.Name.Control, 'string');
strX  = get(ud.Xvar.Control,'string');
strY  = get(ud.Yvar.Control,'string');
ysize = get(ud.EditYSize, 'value');
xsize = get(ud.EditXSize, 'value');
val   = get(ud.EditValue, 'value');
val   = repmat(val, xsize, ysize);

T = ud.Tpointer.info;

Nx = get(T,'x');
Ny = get(T,'y');

if ~isempty(ud.DDpointer);
   DD=ud.DDpointer.info;
   [DD,Vx]= add(DD,strX);
   [DD,Vy]= add(DD,strY);
else
   % make standalone value objects if needed
   Vx=Nx.get('x');
   if isempty(Vx) | Vx==0
      Vx = cgvalue(strX);
      Vx.info = Vx.set('range', [-1 1]);
      Vx.info = Vx.setpoint(0);
   else
      Vx.info=Vx.setname(strX);
   end
   Vy=Ny.get('x');
   if isempty(Vy) | Vy==0
      Vy = cgvalue(strY);
      Vy.info = Vy.set('range', [-1 1]);
      Vy.info = Vy.setpoint(0);
   else
      Vy.info=Vy.setname(strY);
   end
end

% set value pointers
Nx.info= Nx.setX(Vx);
Ny.info= Ny.setX(Vy);

% set names
Nx.info = setname(Nx.info, sprintf('%sNormalizer', Vx.getname));
Ny.info = setname(Ny.info, sprintf('%sNormalizer', Vy.getname));

ud.Tpointer.info = setname(ud.Tpointer.info, name);


% set the tables values, and linspace the BP's
if xsize>0 & ysize>0
    xRange = Vx.get('range');
    Nx.info = set(Nx.info, 'matrix', [linspace(xRange(1), xRange(2), ysize)', (0:ysize-1)']);
    yRange = Vy.get('range');
    Ny.info = set(Ny.info, 'matrix', [linspace(yRange(1), yRange(2), xsize)', (0:xsize-1)']);
    ud.Tpointer.info = set(ud.Tpointer.info, 'matrix', val);
end


