function [m,OK]= gui_SummaryStats(m)
%GUI_SUMMARYSTATS

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.4.6.4 $  $Date: 2004/04/04 03:30:19 $

[s,list,SummStatsType,Description]= summary(m);



h= cell(sum(SummStatsType>0)+1,3);
hFig= xregdialog('Name','Summary Statistics',...
    'position',[10 10 600 size(h,1)*25+60]);
xregcenterfigure(hFig)
i=1;

h{1,1}= uicontrol('parent',hFig,...
    'style','text',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','Statistic');

h{1,2}= uicontrol('parent',hFig,...
    'style','text',...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','Description');
h{1,3}= uicontrol('parent',hFig,...
    'style','text',...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','Formula');

colsizes = zeros(1, 3);
for j= find(SummStatsType>0);
    i=i+1;
    h{i,1}= uicontrol('parent',hFig,...
        'style','checkbox',...
        'value',ismember(j,m.Stats.Summary),...
        'string',list{j},...
        'callback',{@i_Change,hFig,j});
    % need to add some space for the checkbox
    ex = get(h{i,1}, 'Extent')+20;
    if ex(3)>colsizes(1)
        colsizes(1) = ex(3);
    end
    h{i,2}= uicontrol('parent',hFig,...
        'style','text',...
        'HorizontalAlignment','left',...
        'string',Description{j,1});
    ex = get(h{i,2}, 'Extent');
    if ex(3)>colsizes(2)
        colsizes(2) = ex(3);
    end
    h{i,3}= uicontrol('parent',hFig,...
        'style','text',...
        'HorizontalAlignment','left',...
        'string',Description{j,2});
    ex = get(h{i,3}, 'Extent');
    if ex(3)>colsizes(3)
        colsizes(3) = ex(3);
    end
end

hGrid= xreggridlayout(hFig,...
    'dimension',size(h),...
    'elements',h(:)',...
    'rowsizes',20*ones(size(h,1)),...
    'colsizes',colsizes,...
    'correctalg','on',...
    'border',[10 10 10 15],...
    'gapy',5,...
    'gapx',10);

okbtn=uicontrol('style','pushbutton',...
   'parent',hFig,...
   'string','OK',...
   'position',[0 0 65 25],...
   'callback','set(gcbf,''tag'',''ok'', ''visible'', ''off'');');
cancbtn=uicontrol('style','pushbutton',...
   'parent',hFig,...
   'string','Cancel',...
   'position',[0 0 65 25],...
   'callback','set(gcbf, ''visible'', ''off'');');

helpbtn = mv_helpbutton( hFig, 'xreg_summarystats' );

flw=xregflowlayout(hFig,'orientation','right/center',...
   'gap',7,'elements',{helpbtn, cancbtn,okbtn},'border',[0 0 0 0]);
brd=xregborderlayout(hFig,'center',hGrid,'south',flw,'container',double(hFig),...
   'innerborder',[10 45 10 10],'packstatus','on');

hFig.LayoutManager= brd;
set(hFig, 'userdata', {m} );
hFig.showDialog(okbtn);

if strcmp(get(hFig,'tag'),'ok')
    ud= get(hFig,'userdata');
    m= ud{1};
    
    OK= 1;
else
    OK= 0;
end
delete(hFig)


function i_Change(h,evt,hFig,ind);

ud= get(hFig,'userdata');
m= ud{1};

% toggle 
if ismember(ind,m.Stats.Summary)
    m.Stats.Summary = setdiff(m.Stats.Summary,ind);
else
    m.Stats.Summary = sort([m.Stats.Summary(:);ind]);
end
set(hFig,'userdata',{m});





    
        