function out=designtree(T,tree)
% DESIGNTREE Get/Set the design tree in the testplan
%
%   DESIGNTREE(T,TREE) sets the design tree in T to the 
%   structure TREE.  TREE is generated by the function
%   mv_designeditor and contains a list of desins, their
%   parents and the chosen design.
%
%   TREE=DESIGNTREE(T) returns the current tree structure
%   which may be used for setting up the design editor.
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.2.2.2 $  $Date: 2004/02/09 08:07:41 $

% Created 28/3/2000

if nargin>1
   T.DesignTree=tree;
   pointer(T);
   if nargout
      out=T;
   else
      nm=inputname(1);
      assignin('caller',nm,T);
   end  
else
   out=T.DesignTree;  
end


