function [T,ok]=TemplateDialog(T)
%TEMPLATEDIALOG

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.
%   $Revision: 1.6.4.2 $  $Date: 2004/02/09 08:07:28 $




figh=xregfigure('menubar','none',...
   'toolbar','none',...
   'numbertitle','off',...
   'name','Test Plan Template Setup',...
   'doublebuffer','on',...
   'renderer','zbuffer',...
   'closerequestfcn','set(gcbf,''tag'',''cancel'');',...
   'position',[1 1 250 150],...
   'visible','off',...
   'color',get(0,'defaultuicontrolbackgroundcolor'),...
   'tag','ResponseModSetup',...
   'resize','off');
figh= double(figh);

xregcenterfigure(figh)

p_md=address(T);
[lyt,ud]=i_createlyt(figh,p_md);


% ok and cancel buttons
okbtn = uicontrol('parent',figh,...
   'string','OK',...
   'style','pushbutton',...
   'callback','set(gcbf,''tag'',''ok'');',...
   'position',[0 0 65 25]);
cancbtn = uicontrol('parent',figh,...
   'string','Cancel',...
   'style','pushbutton',...
   'callback','set(gcbf,''tag'',''cancel'');',...
   'position',[0 0 65 25]);
helpbtn = mv_helpbutton(figh,'xreg_makeTestplanTemplate');
set(helpbtn,'position',[0 0 65 25]);

flw=xregflowlayout(figh,'orientation','right/bottom',...
   'elements',{helpbtn,cancbtn,okbtn},...
   'gap',7,...
   'border',[0 10 -7 10]);
brd=xregborderlayout(figh,'center',lyt,'south',flw,...
   'innerborder',[10 45 10 10],...
   'container',figh,...
   'packstatus','on');

set(figh,'visible','on');
drawnow;
set(figh,'windowstyle','modal');

waitfor(figh,'tag');

tg=get(figh,'tag');
switch lower(tg)
case 'ok'
	
	DesignDir = xregGetDefaultDir('Designs');
	Tname = get(ud.Name,'string');

	fname= fullfile(DesignDir, [Tname, '.mbt']);
	
	if isstr(fname)
		[pth,fname,ext]= fileparts(fname);
		if isempty(ext)
			ext= '.mbt';
		end
		fname= fullfile(pth,[fname,ext]);
		if exist(fname)
			resp= questdlg(sprintf('%s already exists.\n Do you want to replace it?',fname),'Template File','Yes','No','No');
			if strcmp(resp,'No')
				delete(figh);
				return
			end
			drawnow;
		end
		
		% make template
		T= MakeTemplate(T,get(ud.Designs,'value'),get(ud.Models,'value'),Tname);
		try
			save('-mat',fname,'T');
		catch
			xregerror('File Error');
		end
	end

   ok=1;
end
T= info(T);
% don't free pointer - it's a dynamic copy that's shared by everyone!
delete(figh);
return


function [lyt,ud]=i_createlyt(figh,p);

T= info(p);

mtxt=uicontrol('style','text',...
	'parent',figh,...
	'horizontalalignment','left',...
	'string','Name:',...
	'position',[0 0 80 15]);

ud.Name=uicontrol('style','edit',...
	'parent',figh,...
	'horizontalalignment','left',...
	'backGroundColor','w',...
	'string',name(T),...
	'position',[0 0 80 15]);
nlyt= xreggridlayout(figh,...
	'dimension',[1 2],...
	'elements',{mtxt,ud.Name},...
	'correctalg','on',...
	'colsizes',[50 -1]);

ud.Designs=uicontrol('style','checkbox',...
	'parent',figh,...
	'horizontalalignment','left',...
	'string','Include designs',...
	'value',1,...
	'position',[0 0 80 15]);

ud.Models=uicontrol('style','checkbox',...
	'parent',figh,...
	'horizontalalignment','left',...
	'string','Include response models',...
	'value',isempty(T.Responses) | numChildren(T),...
	'position',[0 0 80 15]);


lyt= xreggridlayout(figh,...
	'dimension',[3 1],...
	'elements',{nlyt,ud.Designs,ud.Models},...
	'correctalg','on',...
	'gapy',5,...
	'border',[20 0 20 10],...
	'rowsizes',[20 15 15]);
