function big_message(message)

% PRINTS A LARGE MESSAGE WINDOW.  'default' PRINTS message_string
% IF message IS A CELL ARRAY, TAKES ARRAY AS MULTIPLE-FRAME, SHOWS ONE FRAME AT A TIME
% MESSAGES CAN CONTAIN ESCAPE CHARACTERS TO CONTROL FORMAT 

global Scale message_string 
% if message='multiple_next' or 'multiple_start' then this is a command
% and the message is stored as UserData in the message box

if iscell(message)
   frame=message{1};
elseif strcmp(message,'default')
   frame=message_string;
else
   frame=message;
end

switch frame
   
case 'multiple_next'
   
   message_string=get(gcf,'UserData');
   i=get(findobj(gcf,'Tag','big_message'),'Userdata')+1;
   set(findobj(gcf,'Tag','big_message'), ...
      'String',sprintf(message_string{i}), ...
      'Userdata',i)
   if i==2
      set(findobj(gcf,'Tag','< button'),'Visible','on')
   end
   if i==length(message_string)
      set(findobj(gcf,'Tag','> button'),'Visible','off')
   end
   
case 'multiple_back'
   
   message_string=get(gcf,'UserData');
   i=get(findobj(gcf,'Tag','big_message'),'Userdata')-1;
   set(findobj(gcf,'Tag','big_message'), ...
      'String',sprintf(message_string{i}), ...
      'Userdata',i)
   if i==length(message_string)-1
      set(findobj(gcf,'Tag','> button'),'Visible','on')
   end
   if i==1
      set(findobj(gcf,'Tag','< button'),'Visible','off')
   end
   
otherwise
   
   % draw message figure
   
   fig=figure('Name','Help message', ...
      'NumberTitle','off', ...
      'Color',[.76 .76 .76], ...
      'Units','points', ...
      'Position',Scale*[200 100 500 350], ...
      'Tag','big_message figure', ...
      'Menubar','none')
%      'Windowstyle','modal');
   
      
   % message
   
   uicontrol('Parent',fig, ...
      'Units','points', ...
      'BackgroundColor',[.76 .76 .76], ...
      'Style','text', ...
      'FontName','time roman', ...
      'FontSize',Scale*18, ...
      'HorizontalAlignment','left', ...
      'Position',Scale*[25 50 450 280], ...
      'String',sprintf(frame), ...
      'Tag','big_message', ...
      'UserData',1);
   
   % control boxes
   
   uicontrol('Parent',fig, ...
      'Units','points', ...
      'Callback','big_message(''multiple_back'')' ,...
      'FontName','time roman', ...
      'FontSize',Scale*14, ...
      'Position',Scale*[205 20 30 30], ...
      'String','<', ...
      'Tag','< button', ...
      'Visible','off');
   uicontrol('Parent',fig, ...
      'Units','points', ...
      'Callback','close' ,...
      'FontName','time roman', ...
      'FontSize',Scale*14, ...
      'Position',Scale*[235 20 30 30], ...
      'String','OK', ...
      'Tag','OK button');
   % (UserData holds the current frame number)
   uicontrol('Parent',fig, ...
      'Units','points', ...
      'Callback','big_message(''multiple_next'')' ,...
      'FontName','time roman', ...
      'FontSize',Scale*14, ...
      'Position',Scale*[265 20 30 30], ...
      'String','>', ...
      'Tag','> button', ...
      'Visible','off');
   
   if iscell(message)
      set(findobj('Tag','> button'),'Visible','on')
      set(gcf,'UserData',message)
   end
   
end
