
% A program of type script
% Program name is Q201.m 
% To accompany the textbook:
% Applications of MATLAB: Numerical Solutions.
% By Yasin A. Shiboul
% To run this program, enter its name,'Q201' in the command window.

clear all
clc
disp(' ');
disp('This program answers questions 1&2 of chapter 2')
disp('----------------------------------------------------------------------')
disp(' ')
disp('To see the required matrix P, press Enter')
pause
disp(' ')
P=[0:pi/4:pi;1:5;5:-1:1;2:2:10]
disp(' To see the matrix P in a column form, press Enter')
pause
clc
disp(' ')
disp('The matrix P in column form is:')
P=P(:)
disp('To see the value of P(12), press Enter')
pause
clc
disp(' ')
P=P(:)
disp('The element P(12) is:')
P(12)
disp(' ')
 disp('TO CLEAR SCREEN, PRESS ENTER')
 pause
 clc
