function [m,ok]=gui_localmodopts(m,action,fig,p);
% GUI_LOCALMODOPTS  Local model options dialog
%
%   [M,OK]=GUI_LOCALMODOPTS(M) creates a modal dialog for
%   setting up options specific to the current local model
%   class.  This function is the default, creating a simple
%   'No options available dialog'.  Overload it in local 
%   models which have additional options such as spline order.
%
%   LYT=GUI_LOCALMODOPTS(M,'layout',FIG,P) creates and returns
%   a layout in figure FIG, based around altering the model in
%   the pointer P.  This interface must be supported by overloaded
%   methods.  FIG may also be an existing layout object in which
%   case the layout is updated with fresh information from the 
%   model in P.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.
%   $Revision: 1.5.4.3 $  $Date: 2004/04/04 03:29:43 $




if nargin<2
    action='figure';
end

switch lower(action)
case 'figure'
    [m,ok]=i_createfig(m);
case 'layout'
    m=i_createlyt(fig,p);
case 'hiord'
    i_ordchng('high',fig);
case 'loword'
    i_ordchng('low',fig); 
end




function [mout,ok]=i_createfig(m)

scsz=get(0,'screensize');
figh=figure('menubar','none',...
    'toolbar','none',...
    'numbertitle','off',...
    'name','Local Model Options',...
    'doublebuffer','on',...
    'renderer','zbuffer',...
    'closerequestfcn','set(gcbf,''tag'',''cancel'');',...
    'position',[scsz(3).*0.5-125 scsz(4).*0.5-45 250 85],...
    'visible','off',...
    'color',get(0,'defaultuicontrolbackgroundcolor'),...
    'tag','LocalOpts',...
    'resize','off');

p=pointer(m);
lyt=i_createlyt(figh,p);

% ok and cancel buttons
okbtn = xreguicontrol('parent',figh,...
    'string','OK',...
    'visible','off',...
    'style','pushbutton',...
    'callback','set(gcbf,''tag'',''ok'');',...
    'position',[0 0 65 25]);
cancbtn = xreguicontrol('parent',figh,...
    'string','OK',...
    'visible','off',...
    'style','pushbutton',...
    'callback','set(gcbf,''tag'',''cancel'');',...
    'position',[0 0 65 25]);
flw=xregflowlayout(figh,'orientation','right/center',...
    'elements',{cancbtn,okbtn},...
    'border',[0 10 0 10]);
brd=xregborderlayout(figh,'center',lyt,'south',flw,...
    'innerborder',[10 45 10 10],...
    'container',figh,...
    'packstatus','on');

set(figh,'visible','on');
drawnow;
set(figh,'windowstyle','modal');

waitfor(figh,'tag');
tg=get(figh,'tag');
switch lower(tg)
case 'ok'
    mout=p.info
    ok=1;
case 'cancel'
    mout=m;
    ok=0;
end
freeptr(p);
delete(figh);
return



function lyt=i_createlyt(figh,p)

if ~isa(figh,'xregcontainer')
    ud.pointer=p;
    ud.figh=figh;
    text1=xreguicontrol('parent',figh,...
        'visible','off',...
        'style','text',...
        'string','Spline order:',...
        'horizontalalignment','left',...
        'position',[0 0 70 15]);
    text2=xreguicontrol('parent',figh,...
        'style','text',...
        'visible','off',...
        'string','Below knot',...
        'position',[0 0 60 15]);
    text3=xreguicontrol('parent',figh,...
        'visible','off',...
        'style','text',...
        'string','Above knot',...
        'position',[0 0 60 15]);
    ud.loword=xreguicontrol('parent',figh,...
        'style','edit',...
        'backgroundcolor','w',...
        'visible','off',...
        'interruptible','off',...
        'position',[0 0 60 20]);
    ud.hiord=xreguicontrol('parent',figh,...
        'visible','off',...
        'style','edit',...
        'backgroundcolor','w',...
        'interruptible','off',...
        'position',[0 0 60 20]);
    
    % data
    builtin('set',text1,'userdata',localpspline);
    objh=sprintf('%20.15f',text1);
    udh=sprintf('%20.15f',text2);
    
    % callbacks
    set(ud.loword,'callback',['gui_localmodopts(get(' objh ',''userdata''),''loword'',' udh ');']);
    set(ud.hiord,'callback',['gui_localmodopts(get(' objh ',''userdata''),''hiord'',' udh ');']);
    
    flw1=xregflowlayout(figh,'packstatus','off',...
        'border',[70 0 0 0],...
        'elements',{text2,text3},...
        'orientation','left/bottom',...
        'gap',5);
    flw2=xregflowlayout(figh,...
        'gap',5,...
        'border',[-5 0 0 0],...
        'orientation','left/center',...
        'elements',{text1,ud.loword,ud.hiord});
    grd=xreggridlayout(figh,...
        'dimension',[2 1],...
        'gapy',5,...
        'elements',{flw1,flw2});
    lyt=xregborderlayout(figh,...
        'north',grd,...
        'innerborder',[0 0 0 40]);
    set(text2,'userdata',ud);
else
    el = get(get(figh,'north'),'elements');
    el = get(el{1},'elements');
    ud=get(el{1},'userdata');
    ud.pointer=p;
    set(el{1},'userdata',ud);
    lyt=figh;
end
i_setvalues(ud,p);
return



function i_setvalues(ud,p)
m=p.info;
ord=getorder(m);
set([ud.loword;ud.hiord],{'string'},{ord(2);ord(1)});
return


function i_ordchng(tp,udh)
ud=get(udh,'userdata');

switch lower(tp)
case 'low'
    obj=ud.loword;
    ind=2;
case 'high'
    obj=ud.hiord;
    ind=1;
end

val=str2num(get(obj,'string'));
m=ud.pointer.info;
ord=getorder(m);
% check val
if isempty(val) | length(val)>1 | val~=floor(val) ...
        | val<2
    set(obj,'string',ord(ind));
else
    ord(ind)=val;
    m=setorder(m,ord);
    ud.pointer.info=m;
end

return
