fun=figure(...
   'position',[200 150 400 300],...
   'color',[0 0 0.5],...
   'numbertitle','off',...
   'name','Funciones definidas por el usuario',...
   'resize','off');
texto1=...
   ['fprintf(''Numero 1 \n'');'];
texto2=...
   ['fprintf(''Numero 2 \n'');'];
      
n1=uicontrol( ...
   'style','radiobutton',...
   'position',[240 215 120 40],...
   'string','step (x)',...
   'callback',texto1);
n2=uicontrol( ...
   'style','radiobutton',...
   'position',[240 215 120 40],...
   'string','step (x)',...
   'callback',texto2);
