function ejer1
descripcion='Escriba 5 numeros y vea cuales son mayores que el promedio';
b=uicontrol(...
    'Position',[100 300 300 30],...
    'Style','text',...
    'String',descripcion...
    )