vent=figure(...
    'Units','pixels',...
    'Position',[100,100,600,400],...
    'Menubar','none',...
    'Color',[0.5 .5 .5],...
    'Name','Clase Practica 3',...
    'NumberTitle','off',...
    'Resize','off',...
    'WindowStyle','normal'...
)
barraopc(vent);
b=uicontrol(...
    'Position',[100 100 100 50],...
    'Style','popupmenu',...
    'String','Rommel|Jose|Briones|Mena'...
    )