clc;
ventana=figure(...
    'Position',[150,150,400,200],...
    'Color',[0.8 0.8 0.8],...
    'MenuBar','none',...
    'Name','Mi primer ventana grafica en Matlab',...
    'NumberTitle','off',...
    'Resize','off');
% %**********************************************************
% uicontrol(...%Etiqueta de Texto original
%     'Style','text',...
%     'Position',[30 250 140 20],...
%     'String','Escriba el texto:',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% txtcadena=uicontrol(...%Cuadro de texto original
%     'Style','edit',...
%     'Position',[160 250 300 20],...
%     'BackgroundColor','w',...
%     'ForegroundColor','b',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% %***********************************************************
% chknegrita=uicontrol(...%Cuadro check de negrita
%     'Style','checkbox',...
%     'Position',[40 200 100 20],...
%     'String','Negrita',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% chkcursiva=uicontrol(...%Cuadro check de cursiva
%     'Style','checkbox',...
%     'Position',[130 200 80 20],...
%     'String','Cursiva',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontAngle','italic',...
%     'HorizontalAlignment','left');
% cmbalinea=uicontrol(...%
%     'Style','popupmenu',...
%     'Position',[300 205 100 20],...
%     'String','Izquierda|Centro|Derecha',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% sldtamanio=uicontrol(...%
%     'Style','slider',...
%     'Position',[30 160 100 20],...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'Max',28,...
%     'Min',8,...
%     'Value',12,...
%     'SliderStep',[0.05 0.05],...
%     'Callback','set(txttamanio,''String'',get(sldtamanio,''Value''));');
% txttamanio=uicontrol(...%Cuadro de texto original
%     'Style','edit',...
%     'Position',[150 160 30 20],...
%     'String',12,...
%     'BackgroundColor','w',...
%     'ForegroundColor',[0 0.5 0],...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% opttimes=uicontrol(...%
%     'Style','radiobutton',...
%     'Position',[250 160 150 20],...
%     'String','Times New Roman',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'Value',1,...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left',...
%     'Callback','exclusion_mutua(1,mathandles)');
% optarial=uicontrol(...%
%     'Style','radiobutton',...
%     'Position',[250 140 150 20],...
%     'String','Arial',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left',...
%     'Callback','exclusion_mutua(2,mathandles)');
% optwingdings=uicontrol(...%
%     'Style','radiobutton',...
%     'Position',[250 120 150 20],...
%     'String','Wingdings',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left',...
%     'Callback','exclusion_mutua(3,mathandles)');
% %*************************************************************************
% uicontrol(...%Etiqueta de Texto formateado
%     'Style','text',...
%     'Position',[30 80 140 20],...
%     'String','Texto con formato:',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% txtformato=uicontrol(...%Cuadro de texto formateado
%     'Style','edit',...
%     'Position',[160 60 300 40],...
%     'BackgroundColor','w',...
%     'ForegroundColor','r',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman');
% cmdaplicar=uicontrol(...%Boton Aplicar Formato
%     'Style','pushbutton',...
%     'Position',[130 10 100 30],...
%     'String','Aplicar',...
%     'TooltipString','Aplicar el formato seleccionado al texto',...
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'Callback','aplicar(mathandles);');
% cmdsalir=uicontrol(...%Boton Salir del Programa
%     'Style','pushbutton',...
%     'Position',[270 10 100 30],...
%     'String','Salir',...
%     'TooltipString','Salir del Programa',...    
%     'BackgroundColor',[0.8 0.8 0.8],...
%     'ForegroundColor','k',...
%     'FontUnits','pixels',...
%     'FontName','Times New Roman',...
%     'FontSize',14,...
%     'FontWeight','bold',...
%     'Callback','close(ventana)');
% mathandles(1)=txtcadena;
% mathandles(2)=chknegrita;
% mathandles(3)=chkcursiva;
% mathandles(4)=cmbalinea;
% mathandles(5)=sldtamanio;
% mathandles(6)=opttimes;
% mathandles(7)=optarial;
% mathandles(8)=optwingdings;
% mathandles(9)=txtformato;