function obj = infoeditdlg( obj )
%INFOEDITDLG  Create modal dialog for editing user information
%
%   OBJ = INFOEDITDLG(OBJ) creates a modal dialog and does not return until
%   it is closed.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.4.4.4 $  $Date: 2004/04/04 03:25:39 $


scr=get(0,'screensize');
H = xregdialog('tag','UserInfoEditor',...
   'Name','User Information',...
   'Resize','off',...
   'position',[scr(3)/2-150 scr(4)/2-70 300 144]);
xregpersistfigpos(H);
xregmoveonscreen(H);
infolyt = createguiobject(obj,'edit',H);

okH = uicontrol('parent',H,...
   'style','pushbutton',...
   'string','OK',...
   'callback','set(gcbf,''visible'',''off'',''userdata'',''ok'');');
cancelH = uicontrol('parent',H,...
   'style','pushbutton',...
   'string','Cancel',...
   'callback','set(gcbf,''visible'',''off'');');
lyt = xreggridbaglayout(H,...
   'dimension',[2 3],...
   'gapy',10,'gapx',7,...
   'rowsizes',[-1 25],...
   'colsizes',[-1 65 65],...
   'mergeblock',{[1 1],[1 3]},...
   'elements',{infolyt,[],[],okH,[],cancelH},...
   'packstatus','off',...
   'border',[7 7 7 7]);
H.LayoutManager = lyt;
set(lyt,'packstatus','on');
H.showDialog(okH);

ud = get(H,'userdata');
if strcmp(ud,'ok')
   obj = initfromguiobject(obj,infolyt);
end
delete(H);
