function schema()
%SCHEMA  Class constructor function (for osek.ToolChain).

%   Copyright 1994-2002 The MathWorks, Inc.
%   $Revision: 1.1 $  $Date: 2002/10/23 01:49:17 $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTE:
% - This file was automatically generated by the Simulink data class designer.
% - The contents of this file are arranged so that the Simulink data class
%   designer can load the associated classes for editing.
% - Hand modification of this file is not recommended as it may prevent the
%   Simulink class designer from loading the associated classes.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% - Generated on:   13-Sep-2002 10:44:04
% - MATLAB version: 6.5.0.180913a (R13)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% Get handles of associated packages and classes
% Not derived from any other class
hCreateInPackage   = findpackage('osek');

%%%% Construct class
hThisClass = schema.class(hCreateInPackage, 'ToolChain');

%%%% Add properties to this class
hThisProp = schema.prop(hThisClass, 'Debugger', 'osek_debugger');
hThisProp.AccessFlags.Init = 'on';
hThisProp.FactoryValue = 'SingleStep';

hThisProp = schema.prop(hThisClass, 'DebuggerPath', 'string');
hThisProp.AccessFlags.Init = 'on';
%hThisProp.FactoryValue = 'd:\Applications\SingleStep\sds762';
hThisProp.FactoryValue = 'd:\Applications\WindRiver\TornadoOW_ppc_3.0\host\sds\7.7.1';

hThisProp = schema.prop(hThisClass, 'DebuggerEXE', 'string');
hThisProp.AccessFlags.Init = 'on';
%hThisProp.FactoryValue = 'bdmp58.exe';
hThisProp.FactoryValue = 'visppc.exe';

hThisProp = schema.prop(hThisClass, 'DebuggerSwitches', 'string');
hThisProp.AccessFlags.Init = 'on';
%hThisProp.FactoryValue = '-p LPT1=1';
hThisProp.FactoryValue = '-V MPC555 -p visionPROBE:LPT1';

