function h = ToolChain(varargin)
%TOOLCHAIN  Class instantiation function (for osek.ToolChain).

%   Copyright 1994-2002 The MathWorks, Inc.
%   $Revision: 1.1 $  $Date: 2002/10/23 01:49:20 $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTE:
% - This file was automatically generated by the Simulink data class designer.
% - The contents of this file are arranged so that the Simulink data class
%   designer can load the associated classes for editing.
% - Hand modification of this file is not recommended as it may prevent the
%   Simulink class designer from loading the associated classes.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% - Generated on:   13-Sep-2002 10:44:04
% - MATLAB version: 6.5.0.180913a (R13)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% Instantiate class
h = osek.ToolChain;

%%%% Initialize property values
% ENTER CLASS INITIALIZATION CODE HERE (optional) ...