clc; disp('Relays   :'); help relays;
disp('Press any key to display the Hysterysis response curve');
disp('(Same as Figures 10.18 & 10.19)'); pause;
hd = [0 .25 .5 1 2 3]; nd = []; md = [];
for ii = 1:length(hd);
  md = [md; linspace(1+hd(ii),6)];
  nd = [nd; relays((0*md(ii,:)+1)./md(ii,:),hd(ii))]; 
end;  md = md'; ndm = abs(nd)'; nda = angle(nd)'*180/pi;
clg; sbplot(211); 
plot(md,ndm,'r-',[1;1]*md(1,:),[0;1]*ndm(1,:),'g--'); grid;
title('Hysteresis'); xlabel('M / D'); ylabel('D | N / K1 |');
for ii = 1:length(hd);
  text(md(8,ii),ndm(8,ii)-.025,[' h/d = ',num2str(hd(ii))]);
end;
sbplot(212);
plot(md,nda,'r-',[1;1]*md(1,:),[0*nda(1,:)-40;nda(1,:)],'g--'); grid;
title('Hysteresis'); xlabel('M / D'); ylabel('Phase Shift of N (Degrees)');
for ii = 1:length(hd);
  text(md(8,ii),nda(8,ii),[' h/d = ',num2str(hd(ii))]);
end;
% meta demo53
pause; clear hd nd md ii ndm nda;
clc; disp('To find LIMIT Cycles (used to determine stability):');
disp('  1. Overlay the transfer function plot and the Hysterisis plot (-1/N).');
disp('  2. Determine Intersections of these two plots.');
disp(' '); disp('Example of problem 10.22');
disp(' '); disp('For the transfer function :');
disp('num = 10; den = [1 4 0]; w = logspace(0,2);');
num = 10; den = [1 4 0]; w = logspace(0,2);
disp('[mag,ph] = bode(num,den,w); magdb = 20*log10(mag);');
[mag,ph] = bode(num,den,w); magdb = 20*log10(mag);
disp(' '); disp('For the Hysterisis curve :');
disp('d = 0.01; h = 0.02; m = logspace(log10(d+h),log10(1.5));');
disp('n = relays(m,h,d); ninv = (0*n-1)./n;');
d = 0.01; h = 0.02; m = logspace(log10(d+h),log10(1.5));
n = relays((0*m+d)./m,h/d)/d; ninv = (0*n-1)./n;
disp(' '); disp('Press any key to overlay the two curves (with a few points labeled)');
pause;
clg; plot([-180 -120],[-40 0],'.'); grid;
hold on; plot(ph,magdb,'-r',angle(ninv)*180/pi,20*log10(abs(ninv)),'--g'); hold off;
xlabel('Phase (degrees)'); ylabel('Gain (dB)');
w = [3 4 5 7 10 12 20 25 30]; [mag,ph] = bode(num,den,w); magdb = 20*log10(mag);
hold on; plot(ph,magdb,'*r'); hold off;
for ii = 1:length(w); text(ph(ii),magdb(ii),[' w = ' num2str(w(ii))]); end;
m = [1 .5 .3 .2 .1 .07 .03]; 
n = relays(m,h,d); ninv = (0*n-1)./n;
hold on; plot(angle(ninv)*180/pi,20*log10(abs(ninv)),'*g'); hold off;
for ii = 1:length(m);
  text(angle(ninv(ii))*180/pi,20*log10(abs(ninv(ii))),[' M = ' num2str(m(ii))]);
end;
% meta demo53
pause;
disp(' '); disp('To find the intersection (LIMIT Cycles) of the two curves');
disp(' We know that there is one intersections, from the graph.');
nm = polysbst(num,[sqrt(-1),0]); dn = polysbst(den,[sqrt(-1),0]);
disp(' The occurs between M = .07 and M = .03');
disp(' '); disp('To find it we do :');
disp('m = crosser(''relays'',[.07 .03],[],[],h,d,nm,dn)');
m = crosser('relays',[.07 .03],[],[],h,d,nm,dn)
disp('n = relays(m,h,d); ninv = (0*n-1)./n;');
n = relays(m,h,d); ninv = (0*n-1)./n;
disp('Then we find w by either the phase or magintude of -1/n. We''ll do polymag.');
disp('w = polymag(nm,dn,abs(-1/n))');
w = polymag(nm,dn,abs(-1/n))
disp('Press any key to display the plot'); pause;
hold on; plot(angle(ninv)*180/pi,20*log10(abs(ninv)),'*'); hold off;
text(angle(ninv)*180/pi,20*log10(abs(ninv)),[' M = ' num2str(m) ', w = ' num2str(w(1))]);
% meta demo53
clear num den w mag ph magdb nm dn d h m n ninv ii;
