function initialize(this, fig, gridsize)
%  INITIALIZE(H,FIG,[M N]) creates an @axesgrid object of size MxN
%  to display response plots.

%  Copyright 1986-2002 The MathWorks, Inc.
%  $Revision: 1.1.4.1 $ $Date: 2004/04/16 22:21:00 $

% Create and configure axes
ax = axes('Parent',fig, 'Visible','off');
LocalSetPreferences(this, ax)

% Axes geometry parameters
geometry = struct('HeightRatio',[],...
   'HorizontalGap', 16, 'VerticalGap', 16, ...
   'LeftMargin', 12, 'TopMargin', 20, 'PrintScale', 1);

% Create @axesgrid object
this.AxesGrid = ctrluis.axesgrid(gridsize, ax, ...
   'Visible',     'off', ...
   'Geometry',    geometry, ...
   'LimitFcn',  {@updatelims this}, ...
   'Title',    'Residuals', ...
   'XLabel',  'Time',...
   'YLabel',  'Error',...
   'XUnit',  'sec');
this.AxesGrid.RowLabelStyle.Interpreter = 'none';
this.AxesGrid.ColumnLabelStyle.Interpreter = 'none';

% Generic initialization
init_graphics(this)

% Add listeners
addlisteners(this)

% Delete datatips when the axis is clicked
set( allaxes(this), 'ButtonDownFcn', @(hSrc,y) defaultButtonDownFcn(this, hSrc))


% ----------------------------------------------------------------------------- %
function LocalSetPreferences(this, ax)
% Apply preferences to AX
if isunix
    FontSize  = 10;
else
    FontSize  = 8;
end

set( ax, 'XGrid', 'off', ...
         'YGrid', 'off', ...
         'XColor', [0.4 0.4 0.4], ...
         'YColor', [0.4 0.4 0.4], ...
         'FontSize', FontSize, ...
         'FontWeight', 'normal', ...
         'FontAngle', 'normal', ...
         'Selected', 'off');

set( get(ax, 'Title'), 'FontSize', FontSize, ...
                       'FontWeight', 'normal', ...
                       'FontAngle', 'normal');

set( [ get(ax,'XLabel'), get(ax,'YLabel') ],...
     'Color', [0 0 0],...
     'FontSize',   FontSize, ...
     'FontWeight', 'normal', ...
     'FontAngle',  'normal');
