function names = defaultaanames

names={...
    'A : Alanine';...
    'B : Aspartic Acid or Asparagine';...  
    'C : Cysteine';...
    'D : Asparatic Acid';...
    'E : Glutamic Acid';...
    'F : Phenylalanine';...    
    'G : Glycine';...
    'H : Histidine';...
    'I : Isoleucine';...
    'J : unused';...
    'K : Lysine';...    
    'L : Leucine';...
    'M : Methionine';...
    'N : Asparagine ';...
    'O : unused';...
    'P : Proline';...
    'Q : Glutamine';...
    'R : Arginine';...
    'S : Serine';...
    'T : Threonine';...
    'U : unused';...
    'V : Valine';...
    'W : Tryptophan';...
    'X : unused';...
    'Y : tyrosine';...
    'Z : Glutamic Acid or Glutamine'};
    
%   Copyright 2003-2004 The MathWorks, Inc.
%   $Revision: 1.2.4.1 $  $Date: 2004/01/24 09:20:15 $
