function varargout = mv_options_gui(Action,varargin)
%MV_OPTIONS_GUI

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.6.4.4 $  $Date: 2004/04/04 03:32:46 $

switch lower(Action)
case 'create'
   i_CreateFigure;
case 'close'
   i_Close
case 'cancel'
   i_Cancel
end

function i_CreateFigure
fh = mvf('Options');
if ~isempty(fh)
   delete(fh);
end

AP= mbcprefs('mbc');

ud.options.files = getpref(AP,'FileDefaults');
ud.options.user = initfromprefs(mbcuser);

fs = [400,220];
screensize = get(0,'screensize');

fh= xregdialog('position',[50,screensize(4)-fs(2)-50,fs],...
   'resize','off',...
   'Tag','MBCModelOptions',...
   'name','Model Browser Preferences');
xregpersistfigpos(fh,'key','MBCModelOptions');
xregmoveonscreen(fh);

% File location tab
ud.Hand.File.ModelDir = xregGui.labelcontrol('parent',fh,...
   'visible','off',...
   'string','Models:',...
   'labelsizemode','absolute',...
   'controlsizemode','relative',...
   'labelsize',70,...
   'controlsize',1,...
   'border',[0 1 0 1],...
   'Control',xregGui.uicontrol('parent',fh,...
   'style','edit',...
   'string',ud.options.files.Models,...
   'horizontalalign','left',...
   'backgroundcolor',[1 1 1]));

ud.Hand.File.ProjectDir = xregGui.labelcontrol('parent',fh,...
   'visible','off',...
   'string','Projects:',...
   'labelsizemode','absolute',...
   'controlsizemode','relative',...
   'labelsize',70,...
   'controlsize',1,...
   'border',[0 1 0 1],...
   'Control',xregGui.uicontrol('parent',fh,...
   'style','edit',...
   'string',ud.options.files.Projects,...
   'horizontalalign','left',...
   'backgroundcolor',[1 1 1]));

ud.Hand.File.DataDir = xregGui.labelcontrol('parent',fh,...
   'visible','off',...
   'string','Data files:',...
   'labelsizemode','absolute',...
   'controlsizemode','relative',...
   'labelsize',70,...
   'controlsize',1,...
   'border',[0 1 0 1],...
   'Control',xregGui.uicontrol('parent',fh,...
   'style','edit',...
   'string',ud.options.files.Data,...
   'horizontalalign','left',...
   'backgroundcolor',[1 1 1]));

ud.Hand.File.TemplateDir = xregGui.labelcontrol('parent',fh,...
   'visible','off',...
   'string','Templates:',...
   'labelsizemode','absolute',...
   'controlsizemode','relative',...
   'labelsize',70,...
   'controlsize',1,...
   'border',[0 1 0 1],...
   'Control',xregGui.uicontrol('parent',fh,...
   'style','edit',...
   'string',ud.options.files.Designs,...
   'horizontalalign','left',...
   'backgroundcolor',[1 1 1]));

ud.Hand.File.Push(1)= xregGui.iconuicontrol('parent',fh,...
   'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
	'transparentColor', [0 255 0],...
   'callback',{@i_GetFile,'ModelDir'});
ud.Hand.File.Push(2)= xregGui.iconuicontrol('parent',fh,...
   'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
	'transparentColor', [0 255 0],...
   'callback',{@i_GetFile,'ProjectDir'});
ud.Hand.File.Push(3)= xregGui.iconuicontrol('parent',fh,...
   'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
	'transparentColor', [0 255 0],...
   'callback',{@i_GetFile,'DataDir'});
ud.Hand.File.Push(4)= xregGui.iconuicontrol('parent',fh,...
   'imageFile',[xregrespath,filesep,'fileOpen.bmp'],...
	'transparentColor', [0 255 0],...
   'callback',{@i_GetFile,'TemplateDir'});

okbtn = uicontrol('parent',fh,...
	'style','pushbutton',...
   'callback','set(gcbf,''visible'',''off'',''tag'',''ok'');',...
   'string','OK');
cancbtn = uicontrol('parent',fh,...
	'style','pushbutton',...
   'callback','set(gcbf,''visible'',''off'');',...
   'string','Cancel');

filegrd = xreggridbaglayout(fh,...
   'packstatus','off',...
   'dimension',[4 2],...
   'gapx',5,...
   'gapy',7,...
   'border',[10 10 10 15],....
   'rowsizes',[22 22 22 22],...
   'colsizes',[-1 22],...
   'elements',{ud.Hand.File.ModelDir, ud.Hand.File.Push(1); ud.Hand.File.ProjectDir, ud.Hand.File.Push(2);...
      ud.Hand.File.DataDir, ud.Hand.File.Push(3); ud.Hand.File.TemplateDir, ud.Hand.File.Push(4)});

userobj = createguiobject(ud.options.user,'edit',fh);
userlyt = xreglayerlayout(fh,'border',[10 10 10 15],...
   'elements',{userobj});

tabs = xregtablayout2(fh,'numcards',2,...
   'tablabels',{'File Locations','User Information'});
attach(tabs,filegrd,1);
attach(tabs,userlyt,2);

lyt = xreggridbaglayout(fh,...
   'dimension',[2 3],...
   'rowsizes',[-1 25],...
   'colsizes',[-1 65 65],...
   'gapy',10,...
   'gapx',7,...
   'border',[7 7 7 7],...
   'mergeblock',{[1 1],[1 3]},...
   'elements',{tabs,[],[],okbtn,[],cancbtn});
   

fh.LayoutManager = lyt;
set(lyt,'packstatus','on');
fh.Userdata = ud;
fh.showDialog(okbtn);

status = get(fh,'tag');
if strcmp(status,'ok')
   ud.options.files.Models = get(ud.Hand.File.ModelDir.Control,'string');
   ud.options.files.Projects = get(ud.Hand.File.ProjectDir.Control,'string');
   ud.options.files.Data = get(ud.Hand.File.DataDir.Control,'string');
   ud.options.files.Designs = get(ud.Hand.File.TemplateDir.Control,'string'); 
   ud.options.user = initfromguiobject(ud.options.user,userobj);
   
   AP= mbcprefs('mbc');
   setpref(AP,'FileDefaults',ud.options.files);
   
   sendtoprefs(ud.options.user);
end
delete(fh);


function i_GetFile(h,evt,prefname)
fh = get(h,'parent');
ud = get(fh,'userdata');

edt = get(ud.Hand.File.(prefname),'Control');
oldpath = get(edt,'string');
newpath = uigetdir(oldpath,'Select path:');
if newpath~=0
   set(edt,'string',newpath);
end