function figh = viewcenters( m )
%XREGRBF/VIEWCENTERS   Display the centers of an RBF model.
%   VIEWCENTERS(M) displays a plot showing the centers of the RBF model M. 

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.2.6.2 $    $Date: 2004/02/09 07:57:30 $ 

% get infomation about model
nf = get( m, 'nfactors' );
centers = invcode( m, get( m, 'centers' ) );
ncenters = size( centers, 1 );

% set up figure window
scr = get( 0, 'screensize' );
figsize = [scr(3)*0.35, scr(4)*0.6];
i_deleteold;
figh = xregfigure('tag',i_hash_fig_tag,...
    'Visible', 'off',...
    'Name', 'View Centers',...
    'Renderer', 'zbuffer');
xregcenterfigure( figh, figsize );

% Set up graph
if nf > 3,
    gr  = mvgraph4d( figh, 'Visible', 'off' );
    set(gr,'factorselection','exclusive');
elseif nf == 3,
    gr = mvgraph3d( figh, 'Visible', 'off' );
    set( gr, 'factorselection', 'exclusive' );
elseif nf == 2,   
    gr = mvgraph2d( figh, 'Visible', 'off' );
    set( gr, 'factorselection', 'exclusive' );
else
    gr = mvgraph1d( figh, 'Visible', 'off' );
end   
set( gr, 'data', centers);
set( gr, 'factors', get( m, 'symbol' ) );


% set up table
tb = xregtable( double( figh ),...
    'Visible', 'off',...
    'position', [0, 0, 100, 70],...
    'redrawmode', 'basic',...
    'frame.visible', 'off',...
    'frame.vborder', [0,0],...
    'frame.hborder', [0,0],...
    'DefaultCellType', 'uiemuedit0',...
    'rows.number', ncenters+1,...
    'cols.number', nf+1,...
    'rows.fixed', 1,...
    'cols.fixed', 1 );
tb.redraw;
set(tb,...
    'cells.rowselection',[1,1],...
    'cells.colselection',[1,1],...
    'cells.string','--',...
    'cells.rowselection',[1,1],...
    'cells.colselection',[2,nf+1],...
    'cells.string',get(m,'symbol'),...
    'cells.rowselection',[2,ncenters+1],...
    'cells.colselection',[1,1],...
    'cells.value',1:ncenters,...
    'cells.rowselection',[2,ncenters+1],...
    'cells.colselection',[2,nf+1],...
    'cells.value',centers,...
    'cells.backgroundcolor',[1 1 1]);
set(tb,'enable','inactive');
panel = xregpanellayout( figh,...
    'center',tb,...
    'packstatus','off',...
    'innerborder',[0 0 0 0]);

% setup buttons
closebutton = xreguicontrol( double( figh ),...
    'String','Close',...
    'Callback',{@i_close, figh});
helpbutton = mv_helpbutton( figh, 'xreg_rbfViewCentres' );
buttonGrd = xreggridlayout(figh,...
    'dimension',[1,3],...
    'elements',{[],closebutton,helpbutton},...
    'correctalg','on',...
    'colsizes',[-1,65,65],...
    'gapx',7);

% main layout   
b = xreggridlayout( figh,...
    'dimension', [3,1],...
    'correctalg','on',...
    'rowsizes',[-1,-1,25],...
    'gapy',10,...
    'border',[20,10,20,20],...
    'packstatus','off',...
    'elements',{gr, panel, buttonGrd});
figh.layoutmanager = b;

set( b, 'packstatus', 'on' );
set( tb, 'redrawmode', 'normal' );
tb.redraw;
set( b, 'Visible', 'on' );
set( figh , 'Visible', 'on' );

return

%------------------------------------------------------------------------------|
function i_close( src, evt, figh );
close( figh );
return

%------------------------------------------------------------------------------|
function i_deleteold
h = findobj( allchild(0), 'flat', 'tag', i_hash_fig_tag );
if ~isempty( h )
   h = handle( h );
   delete( h );
end
return
%------------------------------------------------------------------------------|
function s = i_hash_fig_tag
s = 'XregrbfViewCenters';
return
%------------------------------------------------------------------------------|
% EOF
%------------------------------------------------------------------------------|
