% Nise, N.S. 
% Control Systems Engineering, 3rd ed. 
% John Wiley & Sons, New York, NY, 10158-0012
%
% Control Systems Engineering Toolbox Version 3.0 
% Copyright © 2000 by John Wiley & Sons, Inc.
%   
% Chapter 2: Modeling in the Frequency Domain
%    
% (ch2p1): Bit strings will be used to identify parts of this tutorial on the 
% computer output. Bit strings are represented by the text enclosed in 
% apostrophes, such as 'ab'. Comments begin with % and are ignored by MATLAB. 
% Numbers are entered without any other characters. Arithmetic can be 
% performed using the proper arithmetic operator. Numbers can be assigned
% using a left-hand argument and an equals sign.

'(ch2p1)'                           % Display label.
'How are you?'                      % Display string.
-3.96                               % Display scalar number -3.96.
-4+7i                               % Display complex number -4+7i.
-5-6j                               % Display complex number -5-6i.
(-4+7i)+(-5-6i)                     % Add two complex numbers and 
                                    % display sum.                                                                                                                                    
(-4+7j)*(-5-6j)                     % Multiply two complex numbers and                                                       
                                    % display product.
M=5                                 % Assign 5 to M and display.
N=6                                 % Assign 6 to N and display.
P=M+N                               % Assign M+N to P and display.
