% Nise, N.S. 
% Control Systems Engineering, 3rd ed. 
% John Wiley & Sons, New York, NY, 10158-0012
%
% Control Systems Engineering Toolbox Version 3.0 
% Copyright © 2000 by John Wiley & Sons, Inc.
%																													
% (ch2p3): Running the previous statements causes MATLAB to display the results. 
% Ending the command with a semicolon suppresses the display. Typing an expression 
% without a left-hand assignment and without a semicolon causes the expression to 
% be evaluated and the result displayed. Enter P2 in the MATLAB Command Window 
% after execution.

'(ch2p3)'                           % Display label.
P2=[3 5 7 8];                       % Assign 3s^3 + 5s^2 +7s + 8 to P2 
                                    % without displaying.    
3*5                                 % Evaluate 3*5 and display result.
