% Nise, N.S. 
% Control Systems Engineering, 3rd ed. 
% John Wiley & Sons, New York, NY, 10158-0012
%
% Control Systems Engineering Toolbox Version 3.0 
% Copyright © 2000 by John Wiley & Sons, Inc.
%
% Chapter 3: Modeling in the Time Domain 
%
% (ch3p1): The square system matrix, A =    [0  1  0
%                                            0  0  1			
%                                           -9 -8 -7],
% is written with a space or comma separating the elements of each row. The next 
% row is indicated with a semicolon or carriage return. The entire matrix is then 
% enclosed in a pair of square brackets. 

'(ch3p1)'                           % Display label.
A=[0 1 0;0 0 1;-9 -8 -7]            % Represent A.
'or'
A=[0 1 0
0 0 1
-9 -8 -7]                           % Represent A.
