% Nise, N.S. 
% Control Systems Engineering, 3rd ed. 
% John Wiley & Sons, New York, NY, 10158-0012
%
% Control Systems Engineering Toolbox Version 3.0 
% Copyright © 2000 by John Wiley & Sons, Inc.
%
% (ch3p2): A row vector, such as the output matrix C, can be represented 
% with elements separated by spaces or commas and enclosed in square brackets. A 
% column vector, such as input matrix B, can be written as elements separated by 
% semicolons or carriage returns, or as the transpose (') of a row vector.

'(ch3p2)'                           % Display label.
C=[2 3 4]                           % Represent row vector C.
B=[7;8;9]                           % Represent column vector B.
'or'
B=[7
8
9]                                  % Represent column vector B.
'or'
B=[7 8 9]'                          % Represent column vector B.
