function [LYT, TBLYT, ViewData] = creategui(CGND, info);
%CREATEGUI Create cgbrowser GUI pane
%
%  [LYT, TBLYT, ViewData] = CREATEGUI(CGND, info);

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.9.2.4 $  $Date: 2004/02/09 08:22:42 $

cbs=Callbacks(CGND,'GetHandles');
% d.Options = i_initOptions;

cgb=info.browserH;
% ---------------- Menu setup ------------------------------------------
menus=cgb.createmenu(guid(CGND),2);
set(menus,{'label'},{'&View';'Fe&ature'});
m = menus(1);
set(m, 'Callback',cbs.SetupViewMenu);
Handles.expansionMenuCheck = uimenu(m , 'label' , '&Full Strategy Display' , ...
   'callback' ,cbs.Expansion,...
   'checked','on');

libraries = pGetFeatureLibraries;

for n=1:size(libraries,1)
    fcns = libraries{n,2};
    Handles.LibMenu(n) = uimenu(m,...
        'label', libraries{n,1},...
        'callback', cbs.ToggleLibrary,...
        'enable','off',...
        libraries{n,3}{:},...
        'Userdata',fcns);
end

PUMEEnable = 'off';

m = menus(2);
mm = uimenu(m , 'label' , '&Select Model...' , 'callback' , cbs.SelModel);
Handles.DeselMenu = uimenu(m , 'label' , '&Deselect Model' , 'callback' , cbs.DeselModel);
mm = uimenu(m , 'label' , 'Convert to &Model', 'callback' , cbs.FeatureModel);
mm = uimenu(m , 'label' , 'Graphical Strategy &Editor...' , ...
    'callback' , cbs.SLEdit,...
    'accelerator','E',...
    'separator','on');
Handles.ParseMenu = uimenu(m , 'label' , '&Parse Strategy Diagram' , ...
    'callback' , cbs.SLUpdate,...
    'enable','off');
mm = uimenu(m , 'label' , '&Clear Strategy' , ...
    'callback' , cbs.Clear); 
Handles.InitialiseMenu = uimenu(m , 'label' , '&Initialize...' , ...
    'callback' , cbs.Initialise,...
    'separator','on');
Handles.FillMenu = uimenu(m , 'label' , '&Fill...' , ...
    'callback' , cbs.Fill);
Handles.OptimiseMenu = uimenu(m , 'label' , '&Optimize...' , ...
    'callback' , cbs.Optimise);

% ---------------- Toolbar setup ------------------------------------------
icons{1,1} = cgresload('reinitialise.bmp','bmp');
icons{2,1} = cgresload('fill.bmp','bmp');
icons{3,1} = cgresload('optimise.bmp','bmp');
callbacks = {cbs.Initialise; cbs.Fill; cbs.Optimise};

tooltips = {'Initialize Feature';...
        'Fill Feature';...
        'Optimize Feature'};

transpclr = {[255 255 0];...
        [255 255 0];...
        [255 255 0]};

[TBLYT,btns] = xregtoolbar(info.Figure,{'uipush','uipush','uipush'},...
        {'Cdata'},icons,...
        {'ClickedCallback'},callbacks,...
        {'ToolTipString'},tooltips,...
        {'TransparentColor'},transpclr);
     
Handles.Toolbar.Initialise = btns(1);
Handles.Toolbar.Fill = btns(2);
Handles.Toolbar.Optimise = btns(3);

% ---------------- Main UI setup ------------------------------------------
Handles.equationview = cgtools.equationview('Parent',info.Figure,...
    'Title','Strategy: ',...
    'NoInputsText','No strategy defined',...
    'NoEquationText','Use the Graphical Strategy Editor to define a strategy.');

label2 = xreguicontrol('style' , 'text' , ...
   'enable','inactive',...
	'visible','off',...
	'parent' , info.Figure , ...
	'horizontalalignment' , 'left' , ...
	'string' , 'Model:' , ...
	'parent' , info.Figure);
Handles.ModText = xreguicontrol('style' , 'text' , ...
   'enable','inactive',...
	'visible','off',...
	'parent' , info.Figure , ...
	'horizontalalignment' , 'left' , ...
	'string' , '' , ...
	'parent' , info.Figure);
Handles.ModEdit = xreguicontrol('style' , 'push' , ...
	'visible','off',...
	'parent' , info.Figure , ...
	'enable' , 'on' , ...
	'position' , [1 1 120 30] , ...
	'string' , 'Select Model...' , ...
	'tooltipstring' , 'Associate a Model with this Feature' , ...
	'callback' , cbs.SelModel , ...
	'parent' , info.Figure);
Handles.ModDeselect = xreguicontrol('style' , 'push' , ...
	'visible','off',...
	'parent' , info.Figure , ...
	'enable' , 'on' , ...
	'position' , [1 1 120 30] , ...
	'string' , 'Deselect Model' , ...
	'tooltipstring' ,  'Deselect the Model of this Feature' , ...
	'callback' , cbs.DeselModel , ...
	'parent' , info.Figure);

% ---- Comments Manager ----
h = xregGui.listview([-10 -10 5 5],info.Figure,...
   {'MouseMove','MotionManager';...
   'click',cbs.HistoryListClick;...
   'AfterLabelEdit',cbs.HistoryLabelEdit});

h.Parent= double(info.Figure);
set(h,'View',3,'multiselect',1,'LabelEdit',0,'hideselection',0,'enabled',0,'sorted',0,'fullrowselect',1);
set(h.Font,'Name','Arial','Size',7);

cols = {'Comment / Action','Date and Time'};
width = [390,120];
hCols= h.ColumnHeaders;
for i = 1:length(cols)
	hItem= hCols.Add;
	set(hItem,'text',cols{i});
	set(hItem,'width',width(i));
end

Handles.History = actxcontainer(h);
set(Handles.History,'visible','off');
Handles.HistoryDelete = xreguicontrol('parent',info.Figure,...
	'visible','off',...
	'String','Remove',...
	'enable','on',...
	'position',[0 0 65 25],...
	'horizontalalign','left',...
	'callback',cbs.HistoryEdit);
Handles.HistoryAdd = xreguicontrol('parent',info.Figure,...
	'visible','off',...
	'String','Add',...
	'enable','on',...
	'position',[0 0 65 25],...
	'horizontalalign','left',...
	'callback',cbs.HistoryEdit);
label(2) = xreguicontrol('style','text',...
	'visible','off',...
   'enable','inactive',...
	'parent',info.Figure,...
	'string', 'Details:',...
	'horizontalalignment','left');
Handles.Details = xreguicontrol('style','edit',...
	'visible','off',...
	'parent',info.Figure,...
	'String','',...
	'max' , 2 , ...
	'min' , 0 , ...
	'horizontalalign','left',...
	'backgroundcolor',[1 1 1],...
    'callback',cbs.HistoryDetails); 

f = xreggridbaglayout(info.Figure,	'packstatus','off','visible','off',...
   'elements',{Handles.History,[],[],[],label(2),Handles.Details,[],...
      Handles.HistoryAdd,Handles.HistoryDelete},...
	 'dimension',[7 2],...
    'colsizes',[-1 65],...
    'rowsizes',[25 25 -1 1 15 20 -1],...
    'rowratios',[0 0 2 0 0 0 1],...
    'gap',5,...
    'mergeblock',{[1 3],[1 1]},'mergeblock',{[5 5],[1 2]},'mergeblock',{[6 7],[1 2]});
layer4 = xregframetitlelayout(info.Figure,	'visible','off',...
   'title','Feature History',...
   'center',f,...
   'innerborder',[10 5 5 5]);
LYT = xreggridbaglayout(info.Figure,...
   'visible','off' ,...
   'elements',{ Handles.equationview, [],              [],                  [] ; ...
                []                    [],              [],                  [] ; ...
                label2,               Handles.ModText, [],                  [] ; ...
                [],                   Handles.ModEdit, Handles.ModDeselect, [] ; ...
                layer4,               [],              [],                  [] },...
   'gap' , 5 ,...
   'dimension' , [5 4],...
   'rowsizes',[155 5 25 25 -1],...
   'colsizes', [60 85 85 -1],...
   'mergeblock',{[1 1],[1 4]},...
   'mergeblock',{[3 3],[2 4]},...
   'mergeblock',{[5 5],[1 4]},...
   'border',[5 5 5 5]);

LYT = xregpanellayout(info.Figure,'innerborder',[0 0 0 0],...
   'center',LYT);

% View data initialisation
d.Handles = Handles;
d.Find.str='';
d.Find.blocks={};
d.Find.index=[];
d.Find.criteria = [0 0 0 0];
d.sys = [];

pF = getdata(CGND);

% For speed, no longer create optmgrs here. Instead just set the enable/disable if both
% a model and an equation are specified.
% Create storage for the optmgrs
d.InitialisationManager  = [];
d.FillManager  = [];
d.OptimisationManager  = [];


if isempty(pF.get('equation')) | isempty(pF.get('model'))
   set(d.Handles.Toolbar.Initialise,'enable','off');
   set(d.Handles.Toolbar.Fill,'enable','off');
   set(d.Handles.Toolbar.Optimise,'enable','off');
end


% store for any message strings
d.Handles.MessageID = [];
ViewData = d;


