function obj = xregframe3dlayout(varargin)
%  Synopsis
%     function obj = xregframe3dlayout(parameter,value,parameter,....)
%     function obj = xregframe3dlayout(fig,parameter,value,parameter,....)
%
%  Description
%     Creates a xregframe3dlayout container in the (optional) figure fig.
%
%  See also
%     xregframe3dlayout/set

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.2.2.2 $  $Date: 2004/02/09 07:36:07 $

fig=[];
if nargin
    if ~ischar(varargin{1}) ...
            && ishandle(varargin{1}) ...
            && strcmp(get(varargin{1},'type'),'figure')
        fig = varargin{1};
        varargin(1) = [];
    end
end
if isempty(fig)
    fig=gcf;
end
% default position
pos=[10 10 100 100];

c = xregcontainer(fig,'position',pos);
ud.borders=[10 10 10 10];
obj.axes=getbgaxes(xregGui.figureaxes,fig);
sc=xregGui.SystemColorsDbl;
obj.background = xregpatch('parent',obj.axes,...
    'selectionhighlight','off',...
    'hittest','off',...
    'edgecolor','none',...
    'facecolor','w',...
    'visible','off',...
    'layer',-1);
obj.cbobject=xregpatch('parent',obj.axes,...
    'selectionhighlight','off',...
    'edgecolor','none',...
    'facecolor','w',...
    'visible','off',...
    'layer',-1);
obj.blackline=xregline('parent',obj.axes,...
    'color',sc.CTRL_DK_SHADOW,...
    'hittest','off',...
    'visible','off');
obj.darkline=xregline('parent',obj.axes,...
    'color',sc.CTRL_SHADOW,...
    'hittest','off',...
    'visible','off');
obj.midline=xregline('parent',obj.axes,...
    'color',sc.CTRL_HILITE,...
    'hittest','off',...
    'visible','off');
obj.lightline=xregline('parent',obj.axes,...
    'color',sc.CTRL_LT_HILITE,...
    'hittest','off',...
    'visible','off');
obj.tagback=xregpatch('parent',obj.axes,...
    'hittest','off',...
    'facecolor',sc.CTRL_BACK,...
    'edgecolor','none',...
    'visible','off');
obj.tagtext=xregtext(0,1,'','parent',obj.axes,...
    'visible','off',...
    'hittest','off',...
    'verticalalignment','top',...
    'horizontalalignment','left',...
    'string','',...
    'units','pixels');
connectdata(c, [obj.background, obj.cbobject, obj.darkline, obj.blackline, ...
    obj.midline, obj.lightline, obj.tagback, obj.tagtext]);

ud.sel=0;
ud.buttondownfcn='';
% indicator for tag object being used - also the room it needs
ud.tagtext=0;
ud.tagextent=[0 0 0 0];
set(obj.blackline,'userdata',ud);
obj = class(obj,'xregframe3dlayout',c);

builtin('set',obj.background,'userdata',obj);

% look for a visible set in remaining args
if ~any(strcmp('visible',lower(varargin(1:2:end))))
    % set ui objects to visible
    set([obj.background;obj.cbobject;obj.blackline;obj.darkline;obj.midline;obj.lightline],'visible','on');
end
if length(varargin)
    obj = set(obj,varargin{:});
end
