function schema()
%SCHEMA  Class constructor function (for ECoderDemos.CustomRTWInfo_Parameter).

% Copyright 2004 The MathWorks, Inc.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTE:
% - This file was automatically generated by the Simulink data class designer.
% - The contents of this file are arranged so that the Simulink data class
%   designer can load the associated classes for editing.
% - Hand modification of this file is not recommended as it may prevent the
%   Simulink class designer from loading the associated classes.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% - Generated on:   11-Mar-2004 12:54:40
% - MATLAB version: 7.0.0.00001 (R14) Prerelease
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% Get handles of associated packages and classes
hDeriveFromPackage = findpackage('Simulink');
hDeriveFromClass   = findclass(hDeriveFromPackage, 'CustomRTWInfo');
hCreateInPackage   = findpackage('ECoderDemos');

%%%% Construct class
hThisClass = schema.class(hCreateInPackage, 'CustomRTWInfo_Parameter', hDeriveFromClass);

%%%% Add enumerated type for CustomStorageClass property
if isempty(findtype('ECoderDemos_CustomStorageClassList_for_Parameter'))
  cscList = processcsc('GetNamesForParameter', 'ECoderDemos');
  schema.EnumType('ECoderDemos_CustomStorageClassList_for_Parameter', cscList);
else
  warning('A type named ''ECoderDemos_CustomStorageClassList_for_Parameter'' already exists.');
end

%%%% Add CustomStorageClass property to this class
hThisProp = schema.prop(hThisClass, 'CustomStorageClass', 'ECoderDemos_CustomStorageClassList_for_Parameter');

%%%% Create CustomStorageClass listeners
createcsclisteners(hThisClass);