function tid = writeasync(obj, values)
%WRITEASYNC Asynchronously write values to group or items.
%   TransID = WRITEASYNC(GObj,Values) and 
%   TransID = WRITEASYNC(IObj,Values) asynchronously writes values to all
%   the items contained in the dagroup object GObj or to the vector of
%   daitem objects specified by IObj. Values is a cell array of values the
%   same size as the number of items in GObj or IObj. TransID is a unique
%   transaction ID for the asynchronous request.
%
%   To ensure that a specific value is written to the correct item object,
%   you should construct the Values cell array based on the order of the
%   items returned by the Item property. Because the values are written to
%   the device, this operation might be time consuming.
%
%   The data types of the values do not need to match the canonical data
%   type of the associated items. If a data type conversion cannot be
%   performed a warning is issued.
%
%   When the asynchronous write operation completes, a WriteAsync event is
%   generated by the server. If an M-file callback function is specified
%   for the WriteAsyncFcn property, then the function executes when the
%   event is generated.
%
%   Examples
%       da = opcda('localhost', 'Matrikon.OPC.Simulation');
%       connect(da);
%       grp = addgroup(da, 'ExWrite');
%       itm = additem(grp, {'Bucket Brigade.Real8', 'Bucket Brigade.String'});
%       grp.WriteAsyncFcn = 'r=read(grp,''device'')';
%       writeasync(grp, {123.456, 'MATLAB is great!'})
%
%   See also DAGROUP/CANCELASYNC, DAGROUP/READ, DAGROUP/READASYNC, 
%            DAGROUP/REFRESH, DAGROUP/WRITE.

% Copyright 2003-2004 OPTI-NUM solutions (Pty) Ltd.
% $Revision: 1.1.6.8 $  $Date: 2004/03/24 20:43:22 $

% Object must be a scalar
if length(obj) > 1
   rethrow(mkerrstruct('opc:writeasync:vecnotsupported'));
end

% Group must be valid
if ~isvalid(obj)
    rethrow(mkerrstruct('opc:writeasync:objinvalid'));
end

% Group must be connected
if ~strcmpi(get(get(obj,'Parent'),'Status'),'connected')
    rethrow(mkerrstruct('opc:writeasync:parentdisconnected'));
end

% Group must contain items
if isempty(get(obj, 'Item')),
    rethrow(mkerrstruct('opc:writeasync:emptygroup'));
end

% Values must be a cell array or must be one item
if ~iscell(values) && length(get(obj,'Item'))>1,
    rethrow(mkerrstruct('opc:writeasync:valuescell'));
end
if ~iscell(values),
    values = {values};
end
if length(values)~=length(get(obj,'Item')),
    rethrow(mkerrstruct('opc:writeasync:valueslength'));
end

% Perform the write
try
    tid = udwriteasync(getudd(obj),values);
catch
    rethrow(mkerrstruct(lasterror));
end
