%DBCONT	Resume execution from the current breakpoint.
%	The DBCONT command resumes execution of an M-file following a stop in
%	execution caused by either a DBSTOP or DBSTEP command.  Execution will
%	continue until either another breakpoint is encountered, an error
%	occurs, or MATLAB returns to the base workspace prompt.
%
%	See also DBSTEP, DBSTOP, DBCLEAR, DBTYPE, DBSTACK, DBUP,
%	DBDOWN, DBSTATUS.

%	Steve Bangert, 6-25-91.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
