%DBDOWN	Change the local workspace context to the called M-file function.
%	The DBDOWN command is used in conjunction with the DBUP command to
%	change the workspace context when in the debug mode.  The DBDOWN
%	command reverses the context shift done by DBUP.	
%
%	See also DBSTEP, DBSTOP, DBCONT, DBCLEAR, DBTYPE, DBSTACK, DBUP,
%       and DBSTATUS.

%	Steve Bangert, 6-25-91.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
