%DBQUIT	Quit debug mode.
%	The DBQUIT command immediately terminates debug mode and returns
%	control to the base workspace prompt.  The M-file being processed
%	is NOT completed and no results are returned.
%	
%	See also DBSTOP, DBCONT, DBSTEP, DBCLEAR, DBTYPE, DBSTACK, DBUP,
%	DBDOWN, and DBSTATUS.

%	Steve Bangert, 1-3-92.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
