%DBSTACK	List who called whom from M-file breakpoint to base workspace.
%	The DBSTACK command displays the M-file function name and line number
%	where the breakpoint occurred, the name and line number of the M-file 
%	caller, the caller's caller, etc., until the top-most M-file function
%	is reached.
%
%	See also DBSTEP, DBSTOP, DBCONT, DBCLEAR, DBTYPE, DBUP, DBDOWN,
%	and DBSTATUS.

%	Steve Bangert, 6-25-91.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
