%DBTYPE	List an M-file with line numbers.
%	The DBTYPE command is used to list an M-file function with 
%	line numbers to aid the user in setting breakpoints.  There are
%	two forms to this command.  They are:
%
%	DBTYPE Mfilename
%	DBTYPE Mfilename start:end
%
%	where Mfilename is the name of the M-file function in question and 
%	start and end are line numbers.
%
%	See also DBSTEP, DBSTOP, DBCONT, DBCLEAR, DBSTACK, DBUP, DBDOWN,
%	and DBSTATUS.

%	Steve Bangert, 6-25-91.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
