%DBUP	Change the local workspace context to the M-file function caller.
%	The DBUP command allows the user to change the workspace context, 
%	while the user is in the debug mode, to that of the calling M-file 
%	or the base workspace.
%
%	See also DBSTEP, DBSTOP, DBCONT, DBCLEAR, DBTYPE, DBSTACK,
%	DBDOWN, and DBSTATUS.

%	Steve Bangert, 6-25-91.
%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
