% Debugging commands.
%
%   dbstop     - Set breakpoint.
%   dbclear    - Remove breakpoint.
%   dbcont     - Resume execution.
%   dbdown     - Change local workspace context.
%   dbstack    - List who called whom.
%   dbstatus   - List all breakpoints.
%   dbstep     - Execute one or more lines.
%   dbtype     - List M-file with line numbers.
%   dbup       - Change local workspace context.
%   dbquit     - Quit debug mode.

%	Copyright (c) 1984-94 by The MathWorks, Inc.

