%INPUT	Prompt for user input. 
% 	INPUT('How many apples') gives the user the prompt in the
% 	text string and then waits for input from the keyboard.
%	The input can be any MATLAB expression, which is evaluated,
%	using the variables in the current workspace, and the result
%	returned as the value of the function.
%
% 	INPUT('What is your name','s') gives the prompt in the text
% 	string and waits for character string input.  The typed input
%	is not evaluated; the characters are simply returned as a 
%	MATLAB string.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
