%KEYBOARD Invoke the keyboard as if it were a Script-file.
%	KEYBOARD invokes the keyboard as if it were a Script-file.
% 	When placed in an M-file, KEYBOARD stops execution of the
% 	file and gives control to the user's keyboard. The special 
% 	status is indicated by a double prompt. Variables may be 
% 	examined or changed - all MATLAB commands are valid. The 
% 	keyboard mode is terminated by executing the command RETURN
% 	(i.e. typing the six letters R-E-T-U-R-N and pressing the
% 	return key).  Control returns to the invoking M-file.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
