%PAUSE	Wait for user response.
%	PAUSE causes a procedure to stop and wait for the user to 
% 	strike any key before continuing.
%	PAUSE(n) pauses for n seconds before continuing.
%	PAUSE OFF indicates that any subsequent PAUSE or PAUSE(n)
%	commands should not actually pause.  This allows normally
%	interactive scripts to run unattended.
%	PAUSE ON indicates that subsequent PAUSE commands should pause.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
