%SCRIPT	Scripts M-files.
%	A  SCRIPT file is an external file that contains a sequence
%	of MATLAB statements.  By typing the filename, subsequent 
%	MATLAB input is obtained from the file.  SCRIPT files have
%	a filename extension of ".m" and are often called "M-files". 
%	To make a SCRIPT file into a function, see FUNCTION.
%
%	See also TYPE, ECHO.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
