function h1 = DigitalKarma()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.



h1 = figure(...
'Color',[0.925490196078431 0.913725490196078 0.847058823529412],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','Digital Karma:  State Graphing Software',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[76 105 704 604],...
'Renderer',get(0,'defaultfigureRenderer'),...
'RendererMode','manual',...
'WindowButtonDownFcn','mouse_click_button_down;',...
'WindowButtonMotionFcn','mouse_click_button_move;',...
'WindowButtonUpFcn','mouse_click_button_up;',...
'CreateFcn','opening_variables;',...
'Tag','digital_karma',...
'UserData',zeros(1,0));

setappdata(h1, 'GUIDEOptions', struct(...
'active_h', 2.990002e+002, ...
'taginfo', struct(...
'figure', 2, ...
'text', 38, ...
'edit', 46, ...
'frame', 10, ...
'pushbutton', 23, ...
'radiobutton', 15, ...
'axes', 8, ...
'popupmenu', 3, ...
'slider', 4, ...
'checkbox', 9, ...
'listbox', 2, ...
'togglebutton', 23), ...
'override', 1, ...
'release', 13, ...
'resize', 'simple', ...
'accessibility', 'callback', ...
'mfile', 0, ...
'callbacks', 1, ...
'singleton', 1, ...
'syscolorfig', 1));


h2 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.928977272727273 0.943708609271523 0.0582386363636364 0.054635761589404],...
'String',{ 'Rows' 'Shown' },...
'Style','text',...
'Tag','text8');


h3 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.920454545454546 0.864238410596026 0.0752840909090909 0.0264900662251656],...
'String','Iterations',...
'Style','text',...
'Tag','text9');


h4 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.934659090909091 0.783112582781457 0.0553977272727273 0.0264900662251656],...
'String','Delay',...
'Style','text',...
'Tag','text10');


h5 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.938920454545455 0.610927152317881 0.0497159090909091 0.0314569536423841],...
'String','High',...
'Style','text',...
'Tag','text11');


h6 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[-0.00142045454545455 0.0960264900662252 0.0894886363636364 0.0281456953642384],...
'String',' 1-D Initial',...
'Style','text',...
'Tag','text13');


h7 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','set(findobj(''Tag'',''rulepopup2''),''Value'',1); chooser1value=get(gcbo, ''Value''); set(findobj(''Tag'',''rulepopup1''),''Value'',chooser1value); chooser2value=1; run chooser;',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',1000000000000,...
'Min',-1000000000000,...
'Position',[0.669034090909091 0.0943708609271523 0.231 0.0347682119205298],...
'String',{ '1-D Rules' 'Custom' 'CA 18' 'Nearest Neighbor' 'Reversible Nearest-2' 'Next Nearest' 'Nearest Totalistic' 'Next Nearest Totalistic' },...
'Style','popupmenu',...
'Value',1,...
'Tag','rulepopup1');


h8 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','rowsinputscript; if exist(''a''); opening_iteration; CA_Display; end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.912251655629139 0.0795454545454545 0.033112582781457],...
'String','20',...
'Style','edit',...
'CreateFcn','rowsinputscript; if exist(''a''); opening_iteration; CA_Display; end;',...
'Tag','rowsinputbox');


h9 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','iterationsinputbox;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.916193181818182 0.83112582781457 0.0795454545454545 0.033112582781457],...
'String','10',...
'Style','edit',...
'CreateFcn','iterationsinputbox;',...
'Tag','iterationsinput');


h10 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','delayinputbox;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.748344370860927 0.0795454545454545 0.033112582781457],...
'String','0',...
'Style','edit',...
'CreateFcn','delayinputbox;',...
'Tag','delayinput');


h11 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','highinputscript;  if exist(''a''); opening_iteration; CA_Display; end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.582781456953642 0.0795454545454545 0.033112582781457],...
'String','1',...
'Style','edit',...
'CreateFcn','highinputscript;  if exist(''a''); opening_iteration; CA_Display; end;',...
'Tag','highinput');


h12 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','if isempty(str2num(get(gcbo,''string''))) ; set(gcbo, ''String'', ''1 2 3 4''); initial1d = str2num(get(gcbo,''string'')); errordlg(''1-D Initial State must be an array of numbers'',''Error''); else; initial1d = str2num(get(gcbo,''string'')); end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.0838068181818182 0.0960264900662252 0.367897727272727 0.033112582781457],...
'String','0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0',...
'Style','edit',...
'CreateFcn','if isempty(str2num(get(gcbo,''string''))) ; set(gcbo, ''String'', ''1 2 3 4''); initial1d = str2num(get(gcbo,''string'')); errordlg(''1-D Initial State must be an array of numbers'',''Error''); else; initial1d = str2num(get(gcbo,''string'')); end;',...
'Tag','InitialInput');


h13 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.941761363636364 0.698675496688742 0.0511363636363636 0.0264900662251656],...
'String','Low',...
'Style','text',...
'Tag','text19');


h14 = axes(...
'Parent',h1,...
'ALim',get(0,'defaultaxesALim'),...
'ALimMode','manual',...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode','manual',...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode','manual',...
'CameraUpVector',[0 1 0],...
'CameraUpVectorMode','manual',...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode','manual',...
'CLim',get(0,'defaultaxesCLim'),...
'CLimMode','manual',...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'DataAspectRatio',get(0,'defaultaxesDataAspectRatio'),...
'DataAspectRatioMode','manual',...
'PlotBoxAspectRatio',get(0,'defaultaxesPlotBoxAspectRatio'),...
'PlotBoxAspectRatioMode','manual',...
'Position',[0.0639204545454545 0.16887417218543 0.832386363636364 0.79635761589404],...
'TickDir',get(0,'defaultaxesTickDir'),...
'TickDirMode','manual',...
'XColor',get(0,'defaultaxesXColor'),...
'XLim',get(0,'defaultaxesXLim'),...
'XLimMode','manual',...
'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'XTickLabel',{ '0  ' '0.1' '0.2' '0.3' '0.4' '0.5' '0.6' '0.7' '0.8' '0.9' '1  ' },...
'XTickLabelMode','manual',...
'XTickMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YLim',get(0,'defaultaxesYLim'),...
'YLimMode','manual',...
'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
'YTickLabel',{ '0  ' '0.1' '0.2' '0.3' '0.4' '0.5' '0.6' '0.7' '0.8' '0.9' '1  ' },...
'YTickLabelMode','manual',...
'YTickMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'ZLim',get(0,'defaultaxesZLim'),...
'ZLimMode','manual',...
'ZTick',[0 0.5 1],...
'ZTickLabel',{ '0  ' '0.5' '1  ' },...
'ZTickLabelMode','manual',...
'ZTickMode','manual',...
'Tag','axes1',...
'UserData',zeros(1,0),...
'Visible','off');


h15 = get(h14,'title');

set(h15,...
'Parent',h14,...
'Color',[0 0 0],...
'HorizontalAlignment','center',...
'Position',[0.498960498960499 1.01351351351351 1.00005459937205],...
'VerticalAlignment','bottom',...
'HandleVisibility','off',...
'Visible','off');

h16 = get(h14,'xlabel');

set(h16,...
'Parent',h14,...
'Color',[0 0 0],...
'HorizontalAlignment','center',...
'Position',[0.498960498960499 -0.0488565488565487 1.00005459937205],...
'VerticalAlignment','cap',...
'HandleVisibility','off',...
'Visible','off');

h17 = get(h14,'ylabel');

set(h17,...
'Parent',h14,...
'Color',[0 0 0],...
'HorizontalAlignment','center',...
'Position',[-0.0602910602910603 0.497920997920998 1.00005459937205],...
'Rotation',90,...
'VerticalAlignment','bottom',...
'HandleVisibility','off',...
'Visible','off');

h18 = get(h14,'zlabel');

set(h18,...
'Parent',h14,...
'Color',[0 0 0],...
'HorizontalAlignment','right',...
'Position',[-0.203742203742204 1.04054054054054 1.00005459937205],...
'HandleVisibility','off',...
'Visible','off');

h19 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','set(findobj(''Tag'',''rulepopup1''),''Value'',1); chooser2value=get(gcbo, ''Value''); set(findobj(''Tag'',''rulepopup2''),''Value'',chooser2value); chooser1value=1; run chooser;',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',1000000000000,...
'Min',-1000000000000,...
'Position',[0.458806818181818 0.0927152317880795 0.201704545454545 0.0364238410596026],...
'String',{ '2-D Rules' 'Custom' 'Game of Life' 'Nearest Totalistic' 'Nearest Total-Wrap' },...
'Style','popupmenu',...
'Value',1,...
'Tag','rulepopup2');


h20 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','try; set(findobj(''Tag'',''sliderbar''), ''value'', round(get(findobj(''Tag'',''sliderbar''),''value''))); currentiteration=get(findobj(''Tag'',''sliderbar''),''value''); CA_Display; catch; set(findobj(''Tag'',''sliderbar''), ''value'', round(get(findobj(''Tag'',''sliderbar''),''value''))); currentiteration=get(findobj(''Tag'',''sliderbar''),''value''); opening_iteration; CA_Display; end;',...
'ListboxTop',0,...
'Max',0.1,...
'Position',[0.00284090909090909 0.129139072847682 0.0284090909090909 0.869205298013245],...
'String',{ '' },...
'Style','slider',...
'Tag','sliderbar');


h21 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','File',...
'Tag','filemenu');

h22 = uimenu(...
'Parent',h21,...
'Callback','%automatic',...
'Label','Load',...
'Tag','loadmenu');

h23 = uimenu(...
'Parent',h22,...
'Callback','startingstatus=[''load'']; load_state;',...
'Label','Load State',...
'Tag','loadstatemenu');

h24 = uimenu(...
'Parent',h22,...
'Callback','[loadingname, loadingpath]=uigetfile(''*.mat'',''Load Saved Rule/Colors'',5,5); load([loadingpath,loadingname]);',...
'Label','Load Rule/Colors',...
'Tag','loadrulecolorsmenu');

h25 = uimenu(...
'Parent',h21,...
'Callback','%automatic',...
'Label','Save',...
'Tag','savemenu');

h26 = uimenu(...
'Parent',h25,...
'Callback','%automatic',...
'Label','Save State',...
'Tag','savestatemenu');

h27 = uimenu(...
'Parent',h26,...
'Callback','savingvalue=1; run savestate;',...
'Label','Entire Matrix',...
'Tag','savematrixmenu');

h28 = uimenu(...
'Parent',h26,...
'Callback','savingvalue=2; run savestate;',...
'Label','Graphed Values',...
'Tag','savegraphedmenu');

h29 = uimenu(...
'Parent',h26,...
'Callback','savingvalue=3; run savestate;',...
'Label','Selection Only',...
'Tag','saveselectionmenu');

h30 = uimenu(...
'Parent',h25,...
'Callback','run save_rule_colors;',...
'Label','Save Rule/Colors',...
'Tag','saverulecolorsmenu');

h31 = uimenu(...
'Parent',h21,...
'Callback','edit(rule)',...
'Label','Edit Rule',...
'Tag','editrulemenu');

h32 = uimenu(...
'Parent',h21,...
'Callback','initial2d = xlsread(''Two_D_CA_Initial_State.xls'');',...
'Label','Load 2-D Initial State from Excel',...
'Tag','load2Dinitialmenu');

h33 = uimenu(...
'Parent',h21,...
'Callback','edit a_initial_states',...
'Label','Open Command Line Initial States',...
'Separator','on',...
'Tag','initialstatesmenu');

h34 = uimenu(...
'Parent',h21,...
'Callback','loadingpath=uigetdir; winopen([loadingpath,''\'',''Two_D_CA_Initial_State.xls'']);',...
'Label','Open Excel Initial States',...
'Tag','twodinitialmenu');

h35 = uimenu(...
'Parent',h21,...
'Callback','%automatic',...
'Label','Export',...
'Tag','exportmenu');

h36 = uimenu(...
'Parent',h35,...
'Callback','save_jpg;',...
'Label','as JPG',...
'Tag','savejpgmenu');

h37 = uimenu(...
'Parent',h35,...
'Callback','%automatic',...
'Label','as Excel(CSV) file',...
'Tag','excelexportmenu');

h38 = uimenu(...
'Parent',h37,...
'Callback','exportingvalue=1; run export_values;',...
'Label','Entire matrix',...
'Tag','exportmatrixmenu');

h39 = uimenu(...
'Parent',h37,...
'Callback','exportingvalue=2; run export_values;',...
'Label','Graphed Values',...
'Tag','exportgraphedmenu');

h40 = uimenu(...
'Parent',h37,...
'Callback','exportingvalue=3; run export_values;',...
'Label','Selection Only',...
'Tag','exportselectionmenu');

h41 = uimenu(...
'Parent',h35,...
'Callback','print;',...
'Label','Print',...
'Tag','print_out');

h42 = uimenu(...
'Parent',h35,...
'Callback','timenow=num2str(datestr(now,30)); aviobj = avifile([''Iteration_Movie_'',num2str(timenow(1,10:11)),''.'', num2str(timenow(1,12:13)),''.'', num2str(timenow(1,14:15)),''__'', num2str(timenow(1,5:6)),''.'', num2str(timenow(1,7:8)),''.'', num2str(timenow(1,1:4)),''.'',''avi''],''fps'',2); making_avi=1;',...
'Label','Record AVI',...
'Tag','recordavimenu');

h43 = uimenu(...
'Parent',h35,...
'Callback','aviobj = close(aviobj); making_avi=0;',...
'Label','Stop Record',...
'Tag','stopavimenu');

h44 = uimenu(...
'Parent',h21,...
'Callback','generatedrulenumber=int2str(rulenumberencoder(rulenumberbinary, rulecolors))',...
'Label','Generate Rule Number',...
'Tag','generaterulenumbermenu');

h45 = uimenu(...
'Parent',h21,...
'Callback','open(''Help.htm'')',...
'Label','Help',...
'Separator','on',...
'Tag','helpmenu');

h46 = uimenu(...
'Parent',h21,...
'Callback','stopiteration=1; close ''Digital Karma:  State Graphing Software'';',...
'Label','Close',...
'Tag','closemenu');

h47 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Actions',...
'Tag','actionsmenu');

h48 = uimenu(...
'Parent',h47,...
'Callback','startingstatus=[''new'']; load_state;',...
'Label','Start New',...
'Tag','startmenu');

h49 = uimenu(...
'Parent',h47,...
'Callback','stopiteration=1; CA_Display;',...
'Label','Stop/Pause',...
'Tag','stopmenu');

h50 = uimenu(...
'Parent',h47,...
'Callback','if exist(''rule''); CA_iteration; else; errordlg(''Select a Rule'',''Error''); end;',...
'Label','Resume',...
'Tag','resumemenu');

h51 = uimenu(...
'Parent',h47,...
'Callback','undo; if exist(''a''); computeiterations; opening_iteration; CA_Display; end;',...
'Label','Undo',...
'Separator','on',...
'Tag','undomenu');

h52 = uimenu(...
'Parent',h47,...
'Callback','redo; if exist(''a''); computeiterations; opening_iteration; CA_Display; end;',...
'Label','Redo',...
'Tag','redomenu');

h53 = uimenu(...
'Parent',h47,...
'Callback','opening_iteration; CA_Display;',...
'Label','Refresh Graph',...
'Separator','on',...
'Tag','refreshmenu');

h54 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Settings',...
'Tag','Settingsmenu');

h55 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''onedmenu''), ''checked'', ''on''); set(findobj(''Tag'',''twodmenu''), ''checked'', ''off''); dimension=1; set(findobj(''Tag'',''rulepopup2''),''Value'',1); set(findobj(''Tag'',''rulepopup1''),''Value'',1); set(findobj(''Tag'',''onedimensiontoggle''), ''value'', 1);set(findobj(''Tag'',''twodimensiontoggle''), ''value'', 0); clear rule;',...
'Checked','on',...
'Label','1-D',...
'Tag','onedmenu');

h56 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''twodmenu''), ''checked'', ''on''); set(findobj(''Tag'',''onedmenu''), ''checked'', ''off''); dimension=2; set(findobj(''Tag'',''rulepopup1''),''Value'',1); set(findobj(''Tag'',''rulepopup2''),''Value'',1); set(findobj(''Tag'',''onedimensiontoggle''), ''value'', 0); set(findobj(''Tag'',''twodimensiontoggle''), ''value'', 1); clear rule;',...
'Label','2-D',...
'Tag','twodmenu');

h57 = uimenu(...
'Parent',h54,...
'Callback','if casizelimit==0; set(findobj(''Tag'',''casizelimitmenu''), ''checked'', ''on''); casizelimit=1; casizelimitvalue=(inputdlg(''Number of Iterations to Save Including Initial State'')); casizelimitvalue=str2num(casizelimitvalue{1})+1; if dimension==1; casizelimitvalue; end; else; set(findobj(''Tag'',''casizelimitmenu''), ''checked'', ''off''); casizelimit=0; end;',...
'Label','Limit Iterations Saved',...
'Separator','on',...
'Tag','casizelimitmenu');

h58 = uimenu(...
'Parent',h54,...
'Callback','if structurenumbersizelimit==0; set(findobj(''Tag'',''structurenumbersizelimitmenu''), ''checked'', ''on''); structurenumbersizelimit=1; else; set(findobj(''Tag'',''structurenumbersizelimitmenu''), ''checked'', ''off''); structurenumbersizelimit=0; end;',...
'Checked','on',...
'Label','Limit Structure Number Size (Rounding Error)',...
'Tag','structurenumbersizelimitmenu');

h59 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''changer_safety_on''), ''checked'', ''on''); set(findobj(''Tag'',''changer_safety_off''), ''checked'', ''off''); changersafety=1; set(findobj(''Tag'',''historytoggle''), ''value'', 1); set(findobj(''Tag'',''historychangeabletoggle''), ''value'', 0);',...
'Checked','on',...
'Label','Hisory Unchangeable',...
'Separator','on',...
'Tag','changer_safety_on');

h60 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''changer_safety_off''), ''checked'', ''on''); set(findobj(''Tag'',''changer_safety_on''), ''checked'', ''off''); changersafety=0; set(findobj(''Tag'',''historytoggle''), ''value'', 0);set(findobj(''Tag'',''historychangeabletoggle''), ''value'', 1);',...
'Label','Allow History Change',...
'Tag','changer_safety_off');

h61 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''copymovemenu''), ''checked'', ''on''); set(findobj(''Tag'',''cutmovemenu''), ''checked'', ''off''); movetype=[''copy''];',...
'Label','Copy Move',...
'Separator','on',...
'Tag','copymovemenu');

h62 = uimenu(...
'Parent',h54,...
'Callback','set(findobj(''Tag'',''copymovemenu''), ''checked'', ''off''); set(findobj(''Tag'',''cutmovemenu''), ''checked'', ''on''); movetype=[''cut''];',...
'Checked','on',...
'Label','Cut Move (Input Value)',...
'Tag','cutmovemenu');

h63 = uimenu(...
'Parent',h54,...
'Callback','if findfeedbackdisplay==0; set(findobj(''Tag'',''searchfeedbackdisplaymenu''), ''checked'', ''on''); findfeedbackdisplay=1; else; set(findobj(''Tag'',''searchfeedbackdisplaymenu''), ''checked'', ''off''); findfeedbackdisplay=0; end;',...
'Label','Search Feedback Display',...
'Separator','on',...
'Tag','searchfeedbackdisplaymenu');

h64 = uimenu(...
'Parent',h54,...
'Callback','if squareforce==1; set(findobj(''Tag'',''squareforcemenu''), ''checked'', ''off''); squareforce=0; if exist (''a''); opening_iteration; end; else; set(findobj(''Tag'',''squareforcemenu''), ''checked'', ''on''); squareforce=1; if exist (''a''); opening_iteration; end; end;',...
'Checked','on',...
'Label','Force to Square',...
'Tag','squareforcemenu');

h65 = uimenu(...
'Parent',h54,...
'Callback','if autoscaleon==0; set(findobj(''Tag'',''autoscalemenu''), ''checked'', ''on''); autoscaleon=1; run colorsetmine; if exist (''a''); opening_iteration; CA_Display; end; else; set(findobj(''Tag'',''autoscalemenu''), ''checked'', ''off''); autoscaleon=0; run colorsetmine; if exist (''a''); opening_iteration; CA_Display; end; end;',...
'Checked','on',...
'Label','Auto Scale',...
'Tag','autoscalemenu');

h66 = uicontextmenu(...
'Parent',h1,...
'Callback','%automatic',...
'Tag','rightclick');

set(h1,'uicontextmenu',h66)


h67 = uimenu(...
'Parent',h66,...
'Callback','startingstatus=[''new'']; load_state;',...
'Label','Start New',...
'Tag','startcontextmenu');

h68 = uimenu(...
'Parent',h66,...
'Callback','stopiteration=1; CA_Display;',...
'Label','Stop/Pause',...
'Tag','stopcontextmenu');

h69 = uimenu(...
'Parent',h66,...
'Callback','ruletest=exist(''rule''); if ruletest==1; CA_iteration; else; errordlg(''Select a Rule'',''Error''); end;',...
'Label','Resume',...
'Tag','resumecontextmenu');

h70 = uimenu(...
'Parent',h66,...
'Callback','edit(rule)',...
'Label','Edit Rule',...
'Separator','on',...
'Tag','editrulecontextmenu');

h71 = uimenu(...
'Parent',h66,...
'Callback','edit a_initial_states',...
'Label','Command Line Initial States',...
'Tag','initialstatesmenu');

h72 = uimenu(...
'Parent',h66,...
'Callback','undo; if exist(''a''); computeiterations; opening_iteration; CA_Display; end;',...
'Label','Undo',...
'Tag','undocontextmenu');

h73 = uimenu(...
'Parent',h66,...
'Callback','currentmousetool=[''selection'']; check_marks_click;',...
'Checked','on',...
'Label','Selection',...
'Separator','on',...
'Tag','selectionmenu');

h74 = uimenu(...
'Parent',h66,...
'Callback','%automatic',...
'Label','Zoom',...
'Tag','zoomcontextmenu');

h75 = uimenu(...
'Parent',h74,...
'Callback','zoomvalue=[''zoomin'']; run zoom_custom;',...
'Label','Zoom In',...
'Tag','zoomincontextmenu');

h76 = uimenu(...
'Parent',h74,...
'Callback','zoomvalue=[''zoomselection'']; run zoom_custom;',...
'Label','Zoom into Selection',...
'Tag','zoomselectioncontextmenu');

h77 = uimenu(...
'Parent',h74,...
'Callback','zoomvalue=[''zoomout'']; run zoom_custom;',...
'Label','Zoom Out',...
'Tag','zoomoutcontextmenu');

h78 = uimenu(...
'Parent',h74,...
'Callback','zoomvalue=[''zoomback'']; run zoom_custom;',...
'Label','Zoom Backward',...
'Tag','zoombackwardcontextmenu');

h79 = uimenu(...
'Parent',h74,...
'Callback','firstcolumn=1; columnsshown=columns; if dimension==2; firstrow=1; rowsshown=totalrows; end; opening_iteration; CA_Display;',...
'Label','Zoom Max',...
'Tag','zoommaxcontextmenu');

h80 = uimenu(...
'Parent',h66,...
'Callback','%automatic',...
'Label','Settings',...
'Separator','on',...
'Tag','settingscontextmenu');

h81 = uimenu(...
'Parent',h80,...
'Callback','set(findobj(''Tag'',''onedmenu''), ''checked'', ''on''); set(findobj(''Tag'',''twodmenu''), ''checked'', ''off''); dimension=1; set(findobj(''Tag'',''rulepopup2''),''Value'',1); run chooser;',...
'Checked','on',...
'Label','1-D',...
'Tag','onedmenu');

h82 = uimenu(...
'Parent',h80,...
'Callback','set(findobj(''Tag'',''twodmenu''), ''checked'', ''on''); set(findobj(''Tag'',''onedmenu''), ''checked'', ''off''); dimension=2; set(findobj(''Tag'',''rulepopup1''),''Value'',1); run chooser;',...
'Label','2-D',...
'Tag','twodmenu');

h83 = uimenu(...
'Parent',h80,...
'Callback','initial2d = xlsread(''Two_D_CA_Initial_State.xls'');',...
'Label','Load 2-D Initial from Excel',...
'Tag','load2Dinitialcontextmenu');

h84 = uimenu(...
'Parent',h80,...
'Callback','set(findobj(''Tag'',''colormenu''), ''checked'', ''on''); set(findobj(''Tag'',''graymenu''), ''checked'', ''off''); colorchosen=1; colorsetmine; if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','Color',...
'Separator','on',...
'Tag','colormenu');

h85 = uimenu(...
'Parent',h80,...
'Callback','set(findobj(''Tag'',''graymenu''), ''checked'', ''on''); set(findobj(''Tag'',''colormenu''), ''checked'', ''off''); colorchosen=2; colorsetmine; if exist (''a''); opening_iteration; CA_Display; end;',...
'Checked','on',...
'Label','Grayscale',...
'Tag','graymenu');

h86 = uimenu(...
'Parent',h80,...
'Callback','if colorbarvalue==1; set(findobj(''Tag'',''colorbarvaluemenu''), ''checked'', ''off''); colorbarvalue=0; if exist (''a''); opening_iteration; CA_Display; end; else; set(findobj(''Tag'',''colorbarvaluemenu''), ''checked'', ''on''); colorbarvalue=1; if exist (''a''); colorbar; end; end;',...
'Label','Show Scale',...
'Separator','on',...
'Tag','colorbarvaluemenu');

h87 = uimenu(...
'Parent',h80,...
'Callback','if suppressdisplay==1; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''off''); suppressdisplay=0; CA_Display; elseif suppressdisplay==0; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''on''); suppressdisplay=1; end;',...
'Label','Suppress Graph',...
'Tag','suppressdisplaymenu');

h88 = uimenu(...
'Parent',h66,...
'Callback','stopiteration=1; close ''Digital Karma:  Cellular Automaton and Color Cell Graphing'';',...
'Label','Close',...
'Separator','on',...
'Tag','closecontextmenu');

h89 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.934659090909091 0.528145695364238 0.0525568181818182 0.0281456953642384],...
'String','Scale',...
'Style','text',...
'Tag','text26');


h90 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','colorsetmine;  if exist(''a''); opening_iteration; CA_Display; end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.5 0.0795454545454545 0.033112582781457],...
'String','256',...
'Style','edit',...
'CreateFcn','colorsetmine;  if exist(''a''); opening_iteration; CA_Display; end;',...
'Tag','rangescaleinput');


h91 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',1000000000000,...
'Min',-1000000000000,...
'Position',[0.0127840909090909 0.0033112582781457 0.626420454545455 0.088],...
'Style','edit',...
'Tag','box1',...
'UserData',zeros(1,0));


h92 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Display',...
'Tag','displaymenu');

h93 = uimenu(...
'Parent',h92,...
'Callback','set(findobj(''Tag'',''colormenu''), ''checked'', ''on''); set(findobj(''Tag'',''graymenu''), ''checked'', ''off''); colorchosen=1; colorsetmine; if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','Color',...
'Tag','colormenu');

h94 = uimenu(...
'Parent',h92,...
'Callback','set(findobj(''Tag'',''graymenu''), ''checked'', ''on''); set(findobj(''Tag'',''colormenu''), ''checked'', ''off''); colorchosen=2; colorsetmine; if exist (''a''); opening_iteration; CA_Display; end;',...
'Checked','on',...
'Label','Grayscale',...
'Tag','graymenu');

h95 = uimenu(...
'Parent',h92,...
'Callback','if colorreverse==1; set(findobj(''Tag'',''reversescalemenu''), ''checked'', ''off''); colorreverse=0; else; set(findobj(''Tag'',''reversescalemenu''), ''checked'', ''on''); colorreverse=1;end; colorsetmine; if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','Reverse Scale',...
'Tag','reversescalemenu');

h96 = uimenu(...
'Parent',h92,...
'Callback','if suppressdisplay==1; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''off''); suppressdisplay=0; set(findobj(''Tag'',''suppressgraphtoggle''), ''value'', 0); CA_Display; elseif suppressdisplay==0; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''on''); set(findobj(''Tag'',''suppressgraphtoggle''), ''value'', 1); suppressdisplay=1; end;',...
'Label','Suppress Graph',...
'Separator','on',...
'Tag','suppressdisplaymenu');

h97 = uimenu(...
'Parent',h92,...
'Callback','%automatic',...
'Label','Display Values',...
'Tag','displayvaluesmenu');

h98 = uimenu(...
'Parent',h97,...
'Callback','if displayselectionvalues==1; set(findobj(''Tag'',''displayselectionmenu''), ''checked'', ''off''); displayselectionvalues=0; else; displayselectionvalues=1; set(findobj(''Tag'',''displayselectionmenu''), ''checked'', ''on''); end;  if exist (''a''); CA_Display; end;',...
'Label','Selected Values',...
'Tag','displayselectionmenu');

h99 = uimenu(...
'Parent',h97,...
'Callback','if bytevalueson==1; set(findobj(''Tag'',''bytevaluesdisplaymenu''), ''checked'', ''off''); bytevalueson=0; else; bytevalueson=1; set(findobj(''Tag'',''bytevaluesdisplaymenu''), ''checked'', ''on''); end;  if exist (''a''); CA_Display; end;',...
'Label','Byte Values',...
'Tag','bytevaluesdisplaymenu');

h100 = uimenu(...
'Parent',h97,...
'Callback','if displaygraphvalues==1; set(findobj(''Tag'',''displaygraphedvaluesmenu''), ''checked'', ''off''); displaygraphvalues=0; else; displaygraphvalues=1; set(findobj(''Tag'',''displaygraphedvaluesmenu''), ''checked'', ''on''); end;  if exist (''a''); CA_Display; end;',...
'Label','Currently Graphed',...
'Tag','displaygraphedvaluesmenu');

h101 = uimenu(...
'Parent',h97,...
'Callback','if displayallvalues==1; set(findobj(''Tag'',''displaymatrixmenu''), ''checked'', ''off''); displayallvalues=0; else; displayallvalues=1; set(findobj(''Tag'',''displaymatrixmenu''), ''checked'', ''on''); end;  if exist (''a''); CA_Display; end;',...
'Label','Entire Matrix',...
'Tag','displaymatrixmenu');

h102 = uimenu(...
'Parent',h97,...
'Callback','if displaytotaliterations==1; set(findobj(''Tag'',''totaliterationsdisplaymenu''), ''checked'', ''off''); displaytotaliterations=0; else; displaytotaliterations=1; set(findobj(''Tag'',''totaliterationsdisplaymenu''), ''checked'', ''on''); end;  if exist (''a''); CA_Display; end;',...
'Label','Total Iterations Completed',...
'Tag','totaliterationsdisplaymenu');

h103 = uimenu(...
'Parent',h92,...
'Callback','if gridlinesvalue==1; set(findobj(''Tag'',''gridlinesmenu''), ''checked'', ''off''); gridlinesvalue=0; if exist (''a''); opening_iteration; CA_Display; end; else; set(findobj(''Tag'',''gridlinesmenu''), ''checked'', ''on''); gridlinesvalue=1; if exist (''a''); opening_iteration; CA_Display; end; end;',...
'Label','Grid Lines',...
'Separator','on',...
'Tag','gridlinesmenu');

h104 = uimenu(...
'Parent',h92,...
'Callback','if colorbarvalue==1; set(findobj(''Tag'',''colorbarvaluemenu''), ''checked'', ''off''); colorbarvalue=0; if exist (''a''); opening_iteration; CA_Display; end; else; set(findobj(''Tag'',''colorbarvaluemenu''), ''checked'', ''on''); colorbarvalue=1; if exist (''a''); colorbar; end; end;',...
'Label','Show Scale',...
'Tag','colorbarvaluemenu');

h105 = uimenu(...
'Parent',h92,...
'Callback','%automatic',...
'Label','Rotate Display (1-D)',...
'Tag','rotatedisplaymenu');

h106 = uimenu(...
'Parent',h105,...
'Callback','iterationdirection=[''up'']; set(findobj(''Tag'',''rotatenormalmenu''), ''checked'', ''on''); set(findobj(''Tag'',''rotate90menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate180menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate270menu''), ''checked'', ''off''); if exist (''a''); opening_iteration; CA_Display; end;',...
'Checked','on',...
'Label','Normal',...
'Tag','rotatenormalmenu');

h107 = uimenu(...
'Parent',h105,...
'Callback','iterationdirection=[''left'']; set(findobj(''Tag'',''rotatenormalmenu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate90menu''), ''checked'', ''on''); set(findobj(''Tag'',''rotate180menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate270menu''), ''checked'', ''off''); if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','90',...
'Tag','rotate90menu');

h108 = uimenu(...
'Parent',h105,...
'Callback','iterationdirection=[''down'']; set(findobj(''Tag'',''rotatenormalmenu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate90menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate180menu''), ''checked'', ''on''); set(findobj(''Tag'',''rotate270menu''), ''checked'', ''off''); if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','180',...
'Tag','rotate180menu');

h109 = uimenu(...
'Parent',h105,...
'Callback','iterationdirection=[''right'']; set(findobj(''Tag'',''rotatenormalmenu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate90menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate180menu''), ''checked'', ''off''); set(findobj(''Tag'',''rotate270menu''), ''checked'', ''on''); if exist (''a''); opening_iteration; CA_Display; end;',...
'Label','270',...
'Tag','rotate270menu');

h110 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','set(findobj(''Tag'',''sliderbarcols''), ''value'', round(get(findobj(''Tag'',''sliderbarcols''),''value''))); firstcolumn=get(findobj(''Tag'',''sliderbarcols''),''value''); opening_iteration; CA_Display;',...
'ListboxTop',0,...
'Max',1.1,...
'Min',1,...
'Position',[0.0355113636363636 0.134105960264901 0.866477272727273 0.0264900662251656],...
'String',{ '' },...
'Style','slider',...
'Value',1,...
'Tag','sliderbarcols');


h111 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.920454545454546 0.437086092715232 0.0738636363636364 0.0645695364238411],...
'String',{ 'Columns' 'Shown' },...
'Style','text',...
'Tag','text30');


h112 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','columnsinputscript;  if exist(''a''); opening_iteration; CA_Display; end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.417218543046358 0.0795454545454545 0.033112582781457],...
'Style','edit',...
'CreateFcn','columnsinputscript;  if exist(''a''); opening_iteration; CA_Display; end;',...
'Tag','columnsinputbox');


h113 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','if dimension==2; set(findobj(''Tag'',''sliderbarrows''), ''value'', round(get(findobj(''Tag'',''sliderbarrows''),''value''))); firstrow=get(findobj(''Tag'',''sliderbarrows''),''value''); opening_iteration; CA_Display; end',...
'ListboxTop',0,...
'Max',1.1,...
'Min',1,...
'Position',[0.0355113636363636 0.167218543046358 0.0241477272727273 0.380794701986755],...
'String',{ '' },...
'Style','slider',...
'Value',1,...
'Tag','sliderbarrows');


h114 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','displaybox_callback;',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',1000000000000,...
'Min',-1000000000000,...
'Position',[0.659090909090909 0.0033112582781457 0.214488636363636 0.088],...
'Style','edit',...
'Tag','displaybox',...
'UserData',zeros(1,0));


h115 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','zoomvalue=[''zoomin'']; run zoom_custom;',...
'ListboxTop',0,...
'Position',[0.353693181818182 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','In',...
'Tag','togglebutton1');


h116 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','shiftclickvariable=[''move'']; check_marks_shift;',...
'ListboxTop',0,...
'Position',[0.176136363636364 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Mov',...
'Style','togglebutton',...
'Value',1,...
'Tag','movetoggle');


h117 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','shiftclickvariable=[''changer'']; check_marks_shift;',...
'ListboxTop',0,...
'Position',[0.211647727272727 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Chg',...
'Style','togglebutton',...
'Tag','changertoggle');


h118 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','shiftclickvariable=[''pan'']; check_marks_shift;',...
'ListboxTop',0,...
'Position',[0.247159090909091 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Pan',...
'Style','togglebutton',...
'Tag','pantoggle');


h119 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','zoomvalue=[''zoomselection'']; run zoom_custom;',...
'ListboxTop',0,...
'Position',[0.389204545454545 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Sel',...
'Tag','togglebutton11');


h120 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','zoomvalue=[''zoomout'']; run zoom_custom;',...
'ListboxTop',0,...
'Position',[0.424715909090909 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Out',...
'Tag','togglebutton12');


h121 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','zoomvalue=[''zoomback'']; run zoom_custom;',...
'ListboxTop',0,...
'Position',[0.460227272727273 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Bck',...
'Tag','togglebutton13');


h122 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','if exist(''rule''); CA_iteration; else; errordlg(''Select a Rule'',''Error''); end;',...
'ListboxTop',0,...
'Position',[0.105113636363636 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Res',...
'Tag','pushbutton18');


h123 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','stopiteration=1; CA_Display;',...
'ListboxTop',0,...
'Position',[0.0696022727272727 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Stp',...
'Tag','pushbutton19');


h124 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','startingstatus=[''new'']; load_state;',...
'ListboxTop',0,...
'Position',[0.0340909090909091 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Strt',...
'Tag','pushbutton20');


h125 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','undo; if exist(''a''); computeiterations; opening_iteration; CA_Display; end;',...
'ListboxTop',0,...
'Position',[0.637784090909091 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Und',...
'Tag','pushbutton21');


h126 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','set(findobj(''Tag'',''changer_safety_on''), ''checked'', ''on''); set(findobj(''Tag'',''changer_safety_off''), ''checked'', ''off''); changersafety=1; set(findobj(''Tag'',''historytoggle''), ''value'', 1); set(findobj(''Tag'',''historychangeabletoggle''), ''value'', 0);',...
'ListboxTop',0,...
'Position',[0.815340909090909 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','His',...
'Style','togglebutton',...
'Value',1,...
'Tag','historytoggle');


h127 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','if suppressdisplay==1; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''off''); suppressdisplay=0; set(findobj(''Tag'',''suppressgraphtoggle''), ''value'', 0); CA_Display; elseif suppressdisplay==0; set(findobj(''Tag'',''suppressdisplaymenu''), ''checked'', ''on''); set(findobj(''Tag'',''suppressgraphtoggle''), ''value'', 1); suppressdisplay=1; end;',...
'ListboxTop',0,...
'Position',[0.886363636363636 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Sup',...
'Style','togglebutton',...
'Tag','suppressgraphtoggle');


h128 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','set(findobj(''Tag'',''changer_safety_off''), ''checked'', ''on''); set(findobj(''Tag'',''changer_safety_on''), ''checked'', ''off''); changersafety=0; set(findobj(''Tag'',''historytoggle''), ''value'', 0);set(findobj(''Tag'',''historychangeabletoggle''), ''value'', 1);',...
'ListboxTop',0,...
'Position',[0.850852272727273 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Chg',...
'Style','togglebutton',...
'Tag','historychangeabletoggle');


h129 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','set(findobj(''Tag'',''onedmenu''), ''checked'', ''on''); set(findobj(''Tag'',''twodmenu''), ''checked'', ''off''); dimension=1; set(findobj(''Tag'',''rulepopup2''),''Value'',1); set(findobj(''Tag'',''rulepopup1''),''Value'',1); set(findobj(''Tag'',''onedimensiontoggle''), ''value'', 1);set(findobj(''Tag'',''twodimensiontoggle''), ''value'', 0); clear rule;',...
'ListboxTop',0,...
'Position',[0.708806818181818 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','1D',...
'Style','togglebutton',...
'Value',1,...
'Tag','onedimensiontoggle');


h130 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','set(findobj(''Tag'',''twodmenu''), ''checked'', ''on''); set(findobj(''Tag'',''onedmenu''), ''checked'', ''off''); dimension=2; set(findobj(''Tag'',''rulepopup1''),''Value'',1); set(findobj(''Tag'',''rulepopup2''),''Value'',1); set(findobj(''Tag'',''onedimensiontoggle''), ''value'', 0); set(findobj(''Tag'',''twodimensiontoggle''), ''value'', 1); clear rule;',...
'ListboxTop',0,...
'Position',[0.744318181818182 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','2D',...
'Style','togglebutton',...
'Tag','twodimensiontoggle');


h131 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','%Must be calculated each time by the calling functions.  Calculating at enter maxes it stagnant.',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Max',1000000000000,...
'Min',-1000000000000,...
'Position',[0.896306818181818 0 0.0980113636363636 0.088],...
'String','1',...
'Style','edit',...
'Tag','box3',...
'UserData',zeros(1,0));


h132 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','shiftclickvariable=[''wrap'']; check_marks_shift;',...
'ListboxTop',0,...
'Position',[0.282670454545455 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Wrp',...
'Style','togglebutton',...
'Tag','wraptoggle');


h133 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.921875 0.0894039735099338 0.0497159090909091 0.0264900662251656],...
'String','Input',...
'Style','text',...
'Tag','text35');


h134 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'FontSize',10,...
'HorizontalAlignment','left',...
'ListboxTop',0,...
'Position',[0.938920454545455 0.365894039735099 0.0497159090909091 0.0298013245033113],...
'String','Byte',...
'Style','text',...
'Tag','text36');


h135 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.334437086092715 0.0795454545454545 0.033112582781457],...
'String','row',...
'Style','edit',...
'Tag','byteinput');


h136 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','if bytevaluemouseover==0; bytevaluemouseover=1; else; bytevaluemouseover=0; end; check_marks_mouseover;',...
'ListboxTop',0,...
'Position',[0.602272727272727 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Byt',...
'Style','togglebutton',...
'Tag','bytevaluestoggle');


h137 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Graphical Tools',...
'Tag','graphcialtoolsmenu');

h138 = uimenu(...
'Parent',h137,...
'Label','Auto Selection',...
'Tag','autoselectionmenu');

h139 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''all'']; auto_selection_script;',...
'Label','All',...
'Tag','selectallmenu');

h140 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''graphed'']; auto_selection_script;',...
'Label','Currently graphed',...
'Tag','currentlygraphedautoselectmenu');

h141 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''row'']; auto_selection_script;',...
'Label','Row',...
'Tag','selectrowmenu');

h142 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''column'']; auto_selection_script;',...
'Label','Column',...
'Tag','selectcolumnmenu');

h143 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''plane'']; auto_selection_script;',...
'Label','Current Plane',...
'Tag','selectcurrentplanemenu');

h144 = uimenu(...
'Parent',h138,...
'Callback','autoselection=[''none'']; auto_selection_script;',...
'Label','None',...
'Tag','selectnonemenu');

h145 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Zoom',...
'Tag','zoommenu');

h146 = uimenu(...
'Parent',h145,...
'Callback','zoomvalue=[''zoomin'']; run zoom_custom;',...
'Label','Zoom In',...
'Tag','zoominmenu');

h147 = uimenu(...
'Parent',h145,...
'Callback','zoomvalue=[''zoomselection'']; run zoom_custom;',...
'Label','Zoom into Selction',...
'Tag','zoomselection');

h148 = uimenu(...
'Parent',h145,...
'Callback','zoomvalue=[''zoomout'']; run zoom_custom;',...
'Label','Zoom Out',...
'Tag','zoomoutmenu');

h149 = uimenu(...
'Parent',h145,...
'Callback','zoomvalue=[''zoomback'']; run zoom_custom;',...
'Label','Zoom Backward',...
'Tag','zoombackmenu');

h150 = uimenu(...
'Parent',h145,...
'Callback','firstcolumn=1; columnsshown=columns; if dimension==2; firstrow=1; rowsshown=totalrows; end; opening_iteration; CA_Display;',...
'Label','Zoom Max',...
'Tag','zoommaxmenu');

h151 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Selection Shift-Click',...
'Separator','on',...
'Tag','shiftclickmenu');

h152 = uimenu(...
'Parent',h151,...
'Callback','shiftclickvariable=[''move'']; check_marks_shift;',...
'Checked','on',...
'Label','Move',...
'Tag','movemenu');

h153 = uimenu(...
'Parent',h151,...
'Callback','shiftclickvariable=[''changer'']; check_marks_shift;',...
'Label','Value Changer (Input Value)',...
'Tag','changermenu');

h154 = uimenu(...
'Parent',h151,...
'Callback','shiftclickvariable=[''pan'']; check_marks_shift;',...
'Label','Pan',...
'Tag','panmenu');

h155 = uimenu(...
'Parent',h151,...
'Callback','shiftclickvariable=[''wrap'']; check_marks_shift;',...
'Label','Wrap Matrix',...
'Tag','wrapmenu');

h156 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Mouse-Over',...
'Tag','mouseovermenu');

h157 = uimenu(...
'Parent',h156,...
'Callback','if cellvaluemouseover==0; cellvaluemouseover=1; else; cellvaluemouseover=0; end; check_marks_mouseover;',...
'Checked','on',...
'Label','Cell Values',...
'Tag','cellvaluesmenu');

h158 = uimenu(...
'Parent',h156,...
'Callback','if selectionvaluemouseover==0; selectionvaluemouseover=1; else; selectionvaluemouseover=0; end; check_marks_mouseover;',...
'Checked','on',...
'Label','Selection Values',...
'Tag','selectionvaluesmenu');

h159 = uimenu(...
'Parent',h156,...
'Callback','if bytevaluemouseover==0; bytevaluemouseover=1; else; bytevaluemouseover=0; end; check_marks_mouseover;',...
'Label','Byte Values',...
'Tag','bytevaluesmenu');

h160 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Click Tools',...
'Tag','mouseclickmenu');

h161 = uimenu(...
'Parent',h160,...
'Callback','currentmousetool=[''selection'']; check_marks_click;',...
'Checked','on',...
'Label','Selection',...
'Tag','selectionmenu');

h162 = uimenu(...
'Parent',h160,...
'Callback','currentmousetool=[''none'']; check_marks_click;',...
'Label','None',...
'Tag','notoolsmenu');

h163 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Copy',...
'Separator','on',...
'Tag','Copymenu');

h164 = uimenu(...
'Parent',h163,...
'Callback','run copy_selection;',...
'Label','Copy Selection',...
'Tag','copyselectionmenu');

h165 = uimenu(...
'Parent',h163,...
'Callback','cuton=1; run copy_selection; opening_iteration; CA_Display;',...
'Label','Cut',...
'Tag','cutmenu');

h166 = uimenu(...
'Parent',h163,...
'Callback','run paste_selection; CA_Display;',...
'Label','Paste',...
'Tag','Pasteselectionmenu');

h167 = uimenu(...
'Parent',h163,...
'Callback','run save_undo; a=acopiedselection{end}; run computeiterations; currentiteration=0; run opening_iteration; currentlyselecting=0; run CA_Display;',...
'Label','Paste into New State',...
'Separator','on',...
'Tag','pasteintonewmenu');

h168 = uimenu(...
'Parent',h163,...
'Callback','clear acopiedselection;',...
'Label','Empty Copy Storage',...
'Tag','empty copy menu');

h169 = uimenu(...
'Parent',h137,...
'Callback','run crop;',...
'Label','Crop Selection',...
'Tag','cropmenu');

h170 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Insert (Input Value)',...
'Tag','insertmenu');

h171 = uimenu(...
'Parent',h170,...
'Callback','insertvalue=[''iterations'']; run insert_matrix;',...
'Label','Iterations',...
'Tag','insertiterationmenu');

h172 = uimenu(...
'Parent',h170,...
'Callback','insertvalue=[''rows'']; run insert_matrix;',...
'Label','Rows',...
'Tag','insertrowsmenu');

h173 = uimenu(...
'Parent',h170,...
'Callback','insertvalue=[''columns'']; run insert_matrix;',...
'Label','Columns',...
'Tag','insertcolumnsmenu');

h174 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Delete',...
'Tag','deletemenu');

h175 = uimenu(...
'Parent',h174,...
'Callback','deletevalue=[''iterations'']; run delete_matrix;',...
'Label','Iterations',...
'Tag','deleteiterationsmenu');

h176 = uimenu(...
'Parent',h174,...
'Callback','deletevalue=[''rows'']; run delete_matrix;',...
'Label','Rows',...
'Tag','deleterowsmenu');

h177 = uimenu(...
'Parent',h174,...
'Callback','deletevalue=[''columns'']; run delete_matrix;',...
'Label','Columns',...
'Tag','deletecolumnsmenu');

h178 = uimenu(...
'Parent',h137,...
'Callback','%automatic',...
'Label','Drawing',...
'Tag','drawingmenu');

h179 = uimenu(...
'Parent',h178,...
'Callback','arrow;',...
'Label','Arrow',...
'Tag','arrowmenu');

h180 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Analysis',...
'Tag','analysismenu');

h181 = uimenu(...
'Parent',h180,...
'Callback','%automatic',...
'Label','Analysis Area',...
'Tag','analysisareamenu');

h182 = uimenu(...
'Parent',h181,...
'Callback','analysisarealabel=[''matrix'']; set(findobj(''Tag'',''entirematrixmenu''), ''checked'', ''on''); set(findobj(''Tag'',''graphedvaluesmenu''), ''checked'', ''off''); set(findobj(''Tag'',''selectedvaluesmenu''), ''checked'', ''off''); analysis_area;',...
'Checked','on',...
'Label','Entire Matrix',...
'Tag','entirematrixmenu');

h183 = uimenu(...
'Parent',h181,...
'Callback','analysisarealabel=[''graphed'']; set(findobj(''Tag'',''entirematrixmenu''), ''checked'', ''off''); set(findobj(''Tag'',''graphedvaluesmenu''), ''checked'', ''on''); set(findobj(''Tag'',''selectedvaluesmenu''), ''checked'', ''off''); analysis_area;',...
'Label','Graphed Values',...
'Tag','graphedvaluesmenu');

h184 = uimenu(...
'Parent',h181,...
'Callback','analysisarealabel=[''selection'']; set(findobj(''Tag'',''entirematrixmenu''), ''checked'', ''off''); set(findobj(''Tag'',''graphedvaluesmenu''), ''checked'', ''off''); set(findobj(''Tag'',''selectedvaluesmenu''), ''checked'', ''on''); analysis_area;',...
'Label','Selected Values',...
'Tag','selectedvaluesmenu');

h185 = uimenu(...
'Parent',h180,...
'Callback','%automatic',...
'Label','Search',...
'Separator','on',...
'Tag','search');

h186 = uimenu(...
'Parent',h185,...
'Callback','clear foundvaluelocations; findandselectnext=0; findandselect;',...
'Label','Find',...
'Tag','findmenu');

h187 = uimenu(...
'Parent',h185,...
'Callback','findandselectnext=1; findandselect;',...
'Label','Find Next',...
'Tag','findnextmenu');

h188 = uimenu(...
'Parent',h185,...
'Callback','find_replace;',...
'Label','Replace (Input Value)',...
'Separator','on',...
'Tag','replacemenu');

h189 = uimenu(...
'Parent',h185,...
'Callback','replace_all;',...
'Label','Replace All',...
'Tag','replaceallmenu');

h190 = uimenu(...
'Parent',h185,...
'Callback','open(''help.htm'')',...
'Label','Find Help',...
'Separator','on',...
'Tag','findhelpmenu');

h191 = uimenu(...
'Parent',h180,...
'Label','Structure(pattern) Search',...
'Tag','structuresearchmenu');

h192 = uimenu(...
'Parent',h191,...
'Callback','structure_search;',...
'Label','Find',...
'Tag','structuresearch');

h193 = uimenu(...
'Parent',h191,...
'Callback','edit structure_search_strings;',...
'Label','Search Strings',...
'Tag','structuresearchstringsmenu');

h194 = uimenu(...
'Parent',h180,...
'Callback','comparison_detailed;',...
'Label','Compare, Detailed',...
'Separator','on',...
'Tag','comparedetailedmenu');

h195 = uimenu(...
'Parent',h180,...
'Callback','comparison_simplified;',...
'Label','Compare, Simplified',...
'Tag','comparesimplifiedmenu');

h196 = uimenu(...
'Parent',h180,...
'Callback','matrix_statistics; clc; disp(statsmatrixheading), disp(num2str(statsmatrix))',...
'Label','Cell Statistics',...
'Separator','on',...
'Tag','statisticsmenu');

h197 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','findandselectnext=1; findandselect;',...
'ListboxTop',0,...
'Position',[0.566761363636364 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','F N',...
'Tag','togglebutton22');


h198 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'Callback','find_replace;',...
'ListboxTop',0,...
'Position',[0.53125 0.968543046357616 0.0369318181818182 0.0298013245033113],...
'String','Rpl',...
'Tag','pushbutton22');


h199 = uicontrol(...
'Parent',h1,...
'Units','normalized',...
'BackgroundColor',[1 1 1],...
'Callback','lowinputscript; if exist(''a''); opening_iteration; CA_Display; end;',...
'FontSize',10,...
'HorizontalAlignment','right',...
'ListboxTop',0,...
'Position',[0.914772727272727 0.665562913907285 0.0795454545454545 0.033112582781457],...
'String','0',...
'Style','edit',...
'CreateFcn','lowinputscript; if exist(''a''); opening_iteration; CA_Display; end;',...
'Tag','lowinput');


h200 = uimenu(...
'Parent',h1,...
'Callback','%automatic',...
'Label','Window',...
'Tag','windowmenu');

h201 = uimenu(...
'Parent',h200,...
'Callback','new_window;',...
'Label','New Window',...
'Tag','newwindowmenu');

h202 = uimenu(...
'Parent',h200,...
'Callback','delete_window;',...
'Label','Delete Window',...
'Tag','deletewindowmenu');

h203 = uimenu(...
'Parent',h200,...
'Callback','switch_window;',...
'Label','1',...
'Separator','on',...
'Tag','1');
