function varargout= OptionsGUI(m,action, varargin)
%OPTIONSGUI

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.5.2.3 $  $Date: 2004/02/09 07:58:10 $


switch lower(action)
case 'create'
   varargout{1}= i_create(m);
end


function fH= i_create(m)   
fH = findobj('name','Optimization GUI Options');
if ~isempty(fH)
   figure(fH);
   return
end


Opts= get(m,'FitOptions');
Param=Opts.Param;
Init_Pop=Param.Init_Pop;
switch Opts.Algorithm;
case 'LSQnonlin'
   Percent_Opt=Param.Percent_Opt;
   Max_Iter= Param.Max_Iter;
   Max_Func=Param.Max_Func;
   Popup_Val=1;
   Bit_Len=16;
   Max_Gen=50;
case 'GA'
   Bit_Len=Param.Bit_Len;
   Max_Gen= Param.Max_Gen;
   Popup_Val=2;
   Percent_Opt=3;
   Max_Iter=150;
   Max_Func=150;
case 'FminCon'
   Percent_Opt=Param.Percent_Opt;
   Max_Iter= Param.Max_Iter;
   Max_Func=Param.Max_Func;
   Popup_Val=3;
   Bit_Len=16;
   Max_Gen=50;
end


col= get(0,'defaultuicontrolbackgroundcolor');
ScrPos= get(0,'screensize');
fPos(1:2)= ScrPos(3:4)/2-[150 200];
xfig=xregfigure('visible','off');
fH=double(xfig);
set(fH,...
   'Name','Optimisation GUI Options',...
   'menubar','none',...
   'visible','off',...
   'numbertitle','off',...
   'resize','off',...
   'color',col,...
   'WindowStyle','normal',...
   'position',[fPos 250 400]);

mainLyt = xreggridlayout(fH,'dimension',[3,1]);
xfig.layoutManager=mainLyt;

% The Popup menu with the choice of algorithm
Opt_alg= {'LSQNONLIN',...
      'Genetic Algorithm',...
      'FMINCON'};
ud.hand.Popup=uicontrol('parent',fH,...
   'style','popup',...
   'BackGroundColor',[1 1 1],...
   'string',Opt_alg,...
   'Value',Popup_Val,...
   'HorizontalAlignment','left',...
   'Callback',@i_changeoptspage);

% Popup menu goes into a frametitleLayout
popFr= xregframetitlelayout(fH,...
   'center',ud.hand.Popup,...
   'Title','Optimisations Algorithm',...
   'innerborder',[20 30 0 30]);

% Draw the Tab with the different options panels.
TabObj= xregcardlayout(fH,'numcards',length(Opt_alg));

% Draw the options for LSQNONLIN/FMINUNC
string= {'Initial Population',...
      'Percent Used in Optimisation',...
      'Maximum Number of Iterations',...
      'Maximum Function Evaluations'};
value={Init_Pop,...
      Percent_Opt,...
      Max_Iter,...
      Max_Func};
cbstr= {'xregCheckIsNum(''int'',''on'',''range'',[1 1000])'
   'xregCheckIsNum(''range'',[0 100])'
   'xregCheckIsNum(''int'',''on'',''range'',[1 1e4])'
   'xregCheckIsNum(''int'',''on'',''range'',[1 1e4])'};
for i=1:length(string)
   t(i)=xreguicontrol('parent',fH,...
      'style','text',...
      'visible','on',...
      'HorizontalAlignment','left',...
      'BackGroundColor',col,...
      'String',string{i});
   ud.hand.e(i)=uicontrol('parent',fH,...
      'style','edit',...
      'String',value{i},...
      'userdata',value{i},...
      'callback',cbstr{i},...
      'Tag','Init Pop',...
      'BackGroundColor',[1 1 1]);
end

% Put all of these into a Grid layout
els = num2cell([t(:), ud.hand.e(:)]);
els(end+1,:) = {[],[]};
LSQoptsGrd= xreggridlayout(fH,...
   'dimension',size(els),...
   'gapy',20,...
   'gapx',0,...
   'border',[0 0 0 10],...
   'elements',els(:)',...
   'correctalg','on',...
   'rowsizes',[repmat(20,[1, length(string)]), -1],...
   'colratios',[0.8 0.2]);

LSQfr= xregframetitlelayout(fH,...
   'Title','Optimisation Settings',...
   'Center',LSQoptsGrd,...
   'position',[10 100 230 200]);

attach(TabObj,LSQfr,3);
attach(TabObj,LSQfr,1);

% Draw the options for the GA page
string= {'Initial Population',...
      'Bit Length',...
      'Maximum Number of Generations'};
Init_PopGA= max(30,Init_Pop);
value={Init_PopGA,...
      Bit_Len,...
      Max_Gen};
cbstr= {'xregCheckIsNum(''int'',''on'',''range'',[30 1000])'
   'xregCheckIsNum(''int'',''on'',''range'',[1 1024])'
   'xregCheckIsNum(''int'',''on'',''range'',[1 1000])'};
for i=1:length(string)
   t2(i)=xreguicontrol('parent',fH,...
      'style','text',...
      'HorizontalAlignment','left',...
      'BackGroundColor',col,...
      'String',string{i});
   ud.hand.e(4+i)=uicontrol('parent',fH,...
      'style','edit',...
      'String',value{i},...
      'userdata',value{i},...
      'callback',cbstr{i},...
      'Tag','Init Pop',...
      'BackGroundColor',[1 1 1]);
end
els2 = num2cell([t2(:) , ud.hand.e(5:end)']);
els2(end+1,:) = {[],[]};
% Put all of these into a Grid layout
GAoptsGrd= xreggridlayout(fH,...
   'dimension',size(els2),...
   'gapy',20,...
   'gapx',0,...
   'border',[0 0 0 10],...
   'elements',els2(:)',...
   'correctalg','on',...
   'rowsizes',[repmat(20,[1, length(string)]), -1],...
   'colratios',[0.8 0.2]);

GAfr= xregframetitlelayout(fH,...
   'Title','Optimisation Settings',...
   'Center',GAoptsGrd,...
   'position',[10 150 230 150]);

attach(TabObj,GAfr,2);

set(TabObj,'currentcard',Popup_Val);
ud.TabObj=TabObj;

ud.hand.ok= uicontrol('parent',fH,...
   'style','push',...
   'position',[95 40 60 25],...
   'String','OK',...
   'backgroundcolor',col,...
   'Callback',@i_changeoptions);
ud.hand.cancel= uicontrol('parent',fH,...
   'style','push',...
   'position',[180 40 60 25],...
   'String','Cancel',...
   'backgroundcolor',col,...
   'Callback','delete(gcbf)');
OKlyt = xreggridlayout(fH,'dimension',[1,3],...
   'elements',{[],ud.hand.ok,ud.hand.cancel},...
   'correctalg','on',...
   'border',[10 20 10 0],...
   'colsizes',[-1,60,60],...
   'gapx',20);
   
set(mainLyt,'elements',{popFr,TabObj,OKlyt},...
   'correctalg','on',...
   'gapy',20,...
   'rowsizes',[70,-1,45]);

set(fH,'visible','on','user',ud);
set(mainLyt,'packstatus','on');


% -----------------------------------------
% function i_changeoptspage
% -----------------------------------------
function i_changeoptspage(src, evt)
ud = get(get(src, 'Parent'),'userdata');
val = get(src,'value');
set(ud.TabObj,'currentcard',val);


% -----------------------------------------
% function i_changeoptions
% -----------------------------------------
function i_changeoptions(src, evt)
ud = get(get(src, 'Parent'),'user');

mbh=MBrowser;
p=mbh.CurrentNode;

Opts.Param.Max_Knots=length(get(p.model,'knots'));
Opts.Param.Init_Pop=str2num(get(ud.hand.e(1),'string'));
switch get(ud.hand.Popup,'value');
case 1
   Opts.Param.Percent_Opt=str2num(get(ud.hand.e(2),'string'));
   Opts.Param.Max_Iter=str2num(get(ud.hand.e(3),'string'));
   Opts.Param.Max_Func=str2num(get(ud.hand.e(4),'string'));
   Opts.Algorithm='LSQnonlin';
case 2
   Opts.Param.Init_Pop=str2num(get(ud.hand.e(5),'string'));
   Opts.Param.Bit_Len=   str2num(get(ud.hand.e(6),'string'));
   Opts.Param.Max_Gen=str2num(get(ud.hand.e(7),'string'));
   Opts.Algorithm= 'GA';
case 3
   Opts.Param.Percent_Opt=str2num(get(ud.hand.e(2),'string'));
   Opts.Param.Max_Iter=str2num(get(ud.hand.e(3),'string'));
   Opts.Param.Max_Func=str2num(get(ud.hand.e(4),'string'));
   Opts.Algorithm='FminCon';
end

close(gcbf);

m= p.model;
m= set(m,'FitOptions',Opts);
p.model(m);
