function clearEstimInfo(this)
% CLEARESTIMINFO Clears the estimation results

% Author(s): Bora Eryilmaz
% Revised:
% Copyright 1986-2003 The MathWorks, Inc.
% $Revision: 1.1.6.3 $ $Date: 2004/04/11 00:42:08 $

% Estimation info
this.EstimInfo = struct( 'Cost',       [], ...
                         'Covariance', [], ...
                         'FCount',     [], ...
                         'FirstOrd',   [], ...
                         'Gradient',   [], ...
                         'Iteration',  [], ...
                         'Procedure',  [], ...
                         'StepSize',   [], ...
                         'Values',     [] );
