%Lin1 Interactive tool for visualization of linearization.
%	
%	Author:  J.F. Gardner
%	
%	Programmed using MATLAB's GUI, this allows users to
%	interactively select the a normal operating point and
%	relative error tolerance for the linearization of
%	a cubic polynomial (x^3-x).
%
%	Companion file for: "Dynamic Modeling and Control of
%	Engineering Systems", 2nd ed. by Shearer, Kulakowski and
%	Gardner.
%

%	Author:  J.F. Gardner
%	Created: February, 1997
%	Copyright 1997 by J.F. Gardner
%	
%
fig=gcf;
clf
xmin=-10.0;
xmax=10.0;
xnom=1.0;
etol=0.1;
%
%
%
sli_x0 = uicontrol(fig,...
	'Style','slider',...
	'Position',[15 30 150 20],...
	'Min',xmin,'Max',xmax,'Value',xnom,...
	'CallBack',[...
		'xnom=get(sli_x0,''Val'');,',...
		'etol=get(sli_tol,''Val'');,',...
		'set(x0_cur,''String'',num2str(xnom)),',...
		'plotnl(xmin,xmax,xnom,etol);','grid']);
%
xnom_label = uicontrol(fig,...
	'style','text',...
	'Pos',[15 60 75 50],...
	'String','Normal Operating Point');
%
x0_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[100 70 50 20],...
	'String',num2str(get(sli_x0,'Value')));
%
sli_tol = uicontrol(fig,...
	'Style','slider',...
	'Position',[200 30 150 20],...
	'Min',0,'Max',1.00,'Value',etol,...
	'CallBack',[...
		'etol=get(sli_tol,''Val'');,',...
		'xnom=get(sli_x0,''Val'');,',...
		'set(tol_cur,''String'',num2str(etol)),',...
		'plotnl(xmin,xmax,xnom,etol);','grid']);
%
tol_label = uicontrol(fig,...
	'style','text',...
	'Pos',[200 70 75 50],...
	'String','Relative Error Tolerance');
%
tol_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[285 70 50 20],...
	'String',num2str(get(sli_tol,'Value')));

%

%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Close',...
	'Position',[400 30 120 25],...
	'CallBack','close(fig)');
%
%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Help',...
	'Position',[400 80 120 25],...
	'CallBack','help ex1hlp');
%
set(gca,'Position',[0.13 0.35 0.77 0.5]);
%
%axis([-10 10 -1000 1000]);
%axis(AXIS);
%
plotnl(xmin,xmax,xnom,etol);
grid;
%