%STEP1	Interactive tool for first order step responses.
%	
%	Author:  J.F. Gardner
%	
%	Programmed using MATLAB's GUI, this allows users to
%	interactively select the time constant and gain of a
%	first order system and observe it's effect on the system
%	step response.  The program will also plot the line tangent 
%	to the response at time t=0 and the line corresponding to
%	63% of the total response.
%
%	Companion file for "Dynamic Modeling and Control of Engineering
%	Systems", 2nd ed. Printice Hall, 1997.
%	
%	Copyright 1997 by J.F. Gardner
%
fig=gcf;
clf
%
%
%
sli_tau = uicontrol(fig,...
	'Style','slider',...
	'Position',[15 30 150 20],...
	'Min',0,'Max',4.0,'Value',1.0,...
	'CallBack',[...
		'tau=get(sli_tau,''Val'');,',...
		'gain=get(sli_gain,''Val'');,',...
		'set(tau_cur,''String'',num2str(tau)),',...
		'plotit(forder(tau,gain,1));','grid']);
%
tau_label = uicontrol(fig,...
	'style','text',...
	'Pos',[15 60 75 40],...
	'String','Time Constant');
%
tau_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[100 70 50 20],...
	'String',num2str(get(sli_tau,'Value')));
%
sli_gain = uicontrol(fig,...
	'Style','slider',...
	'Position',[200 30 150 20],...
	'Min',0,'Max',10.0,'Value',1.0,...
	'CallBack',[...
		'gain=get(sli_gain,''Val'');,',...
		'tau=get(sli_tau,''Val'');,',...
		'set(gain_cur,''String'',num2str(gain)),',...
		'plotit(forder(tau,gain,1));','grid']);
%
gain_label = uicontrol(fig,...
	'style','text',...
	'Pos',[200 70 75 20],...
	'String','Gain');
%
gain_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[285 70 50 20],...
	'String',num2str(get(sli_gain,'Value')));

%

%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Close',...
	'Position',[400 30 120 25],...
	'CallBack','close(fig)');
%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Show Lines',...
	'Position',[400 55 120 25],...
	'CallBack',[...
		'gain=get(sli_gain,''Val'');,',...
		'tau=get(sli_tau,''Val'');,',...		
		'hold on,',...
		'plot([0 tau tau],[0 gain 0],''g'');,',...
		'plot([0 5],[0.6321*gain 0.6321*gain],''r'');,',...
		'hold off']);
%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Help',...
	'Position',[400 80 120 25],...
	'CallBack','help step1h');
%
set(gca,'Position',[0.13 0.35 0.77 0.5]);
%
axis([0 4 0 1.2]);
axis(axis);
%
plotit(forder(1,1,1));
grid;
%