%STEP2	Interactive demonstration of 2nd order step response
%	
%	Authore:  J.F. Gardner
%	
%	Uses MATLAB's GUI interface to allow user to interactively
%	modify natural frequncy, damping ratio and gain while
%	observing results on screen
%	
%	Companion file for "Dynamic Modeling and Control of Engineering
%	Systems", 2nd ed. Printice Hall, 1997.
%	
%	Copyright 1997 by J.F. Gardner
%
fig=gcf;
clf
%
%
%
sli_omega = uicontrol(fig,...
	'Style','slider',...
	'Position',[15 30 150 20],...
	'Min',.10,'Max',10.0,'Value',1.0,...
	'CallBack',[...
		'omega=get(sli_omega,''Val'');,',...
		'zeta=get(sli_zeta,''Val'');,',...
		'set(omega_cur,''String'',num2str(omega)),',...
		'plotit(sorder(omega,zeta,1,1));','grid']);
%
omega_label = uicontrol(fig,...
	'style','text',...
	'Pos',[15 60 75 30],...
	'String','Natural Frequency');
%
omega_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[100 70 50 20],...
	'String',num2str(get(sli_omega,'Value')));
%
sli_zeta = uicontrol(fig,...
	'Style','slider',...
	'Position',[200 30 150 20],...
	'Min',0.001,'Max',2.0,'Value',0.5,...
	'CallBack',[...
		'zeta=get(sli_zeta,''Val'');,',...
		'omega=get(sli_omega,''Val'');,',...
		'set(zeta_cur,''String'',num2str(zeta)),',...
		'plotit(sorder(omega,zeta,1,1));','grid']);
%
gain_label = uicontrol(fig,...
	'style','text',...
	'Pos',[200 70 75 20],...
	'String','Damping');
%
zeta_cur = uicontrol(fig,...
	'Style','text',...
	'Pos',[285 70 50 20],...
	'String',num2str(get(sli_zeta,'Value')));

%

%
ph_close=uicontrol(fig,...
	'Style','push',...
	'String','Close',...
	'Position',[400 30 120 25],...
	'CallBack','close(fig)');
%
ph_lines=uicontrol(fig,...
	'Style','push',...
	'String','Show Lines',...
	'Position',[400 55 120 25],...
	'CallBack',[...
		'omega=get(sli_omega,''Val'');,',...
		'zeta=get(sli_zeta,''Val'');,',...	
		'if zeta<1 tset=4/zeta/omega; else tset=0; end;,',...	
		'tf=ceil(5/zeta/omega);,',...
		'if zeta<1 mpp=1+exp(-pi*zeta/(sqrt(1-zeta*zeta)));else mpp=1.0; end;,',...
		'hold on,',...
		'plot([tset tset],[0 mpp ],''g'');,',...
		'plot([0 tf],[mpp mpp],''r'');,',...
		'hold off']);
%
ph_helpe=uicontrol(fig,...
	'Style','push',...
	'String','Help',...
	'Position',[400 80 120 25],...
	'CallBack','help step2h');
%
set(gca,'Position',[0.13 0.35 0.77 0.5]);
%
axis([0 4 0 1.2]);
axis(axis);
%
plotit(sorder(1,0.5,1,1));
grid;
%