vent=figure(...
    'Position',[200 200 400 300],...
    'Color',[0.2 0.5 0.8],...
    'MenuBar','none',...
    'Name','Operaciones fundamentales',...
    'NumberTitle','off',...
    'Resize','off'...
    );

uicontrol(...
    'Style','text',...
    'Position',[20 250 130 20],...
    'BackgroundColor',[0.2 0.5 0.8],...
    'ForegroundColor','y',...
    'String','Primer Numero:',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );
num1=uicontrol(...
    'Style','edit',...
    'Position',[150 250 100 20],...
    'BackgroundColor','w',...
    'ForegroundColor','b',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );

uicontrol(...
    'Style','text',...
    'Position',[20 200 140 20],...
    'BackgroundColor',[0.2 0.5 0.8],...
    'ForegroundColor','y',...
    'String','Segundo Numero:',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );
num2=uicontrol(...
    'Style','edit',...
    'Position',[150 200 100 20],...
    'BackgroundColor','w',...
    'ForegroundColor','b',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );

uicontrol(...
    'Style','text',...
    'Position',[20 150 130 20],...
    'BackgroundColor',[0.2 0.5 0.8],...
    'ForegroundColor','y',...
    'String','Operacion:',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );
opera=uicontrol(...
    'Style','popupmenu',...
    'Position',[150 150 130 20],...
    'BackgroundColor','w',...
    'ForegroundColor','b',...
    'String','Sumar|Restar|Multiplicar|Dividir',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );

uicontrol(...
    'Style','text',...
    'Position',[20 100 130 20],...
    'BackgroundColor',[0.2 0.5 0.8],...
    'ForegroundColor','y',...
    'String','Resultado:',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );
res=uicontrol(...
    'Style','edit',...
    'Position',[150 100 100 20],...
    'BackgroundColor','w',...
    'ForegroundColor','b',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman'...
    );

ejec=uicontrol(...
    'Style','pushbutton',...
    'Position',[150 50 100 20],...
    'BackgroundColor',[0.8 0.8 0.8],...
    'ForegroundColor','k',...
    'String','Ejecutar',...
    'FontSize',12,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontName','Times New Roman',...
    'CallBack','ejecutar(num1,num2,opera,res);'...
    );