function [out1,out2] = cg_moviehandler(varargin)
% constructor for movie handler object
% call with i_Create(dad,'fixed',pos)
%  or       i_Create(dad,'frame',vis_action,invis_action)
% if dad is array, first entry is taken as dad; others are stuffed into figurelist - this sets
%  the pointer to watch when a movie is being made for these windows
%
%  returns moviehandler object, and handle to gridlayout object containing uicontrols

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.2.2.2 $  $Date: 2004/02/09 08:24:34 $

args = {varargin{2:end}};
Handles.Figure = args{1}(1);
MovieStuff.FigureList = args{1};
switch args{2}
case 'fixed'
    pos = args{3};
    do_frame = 0;
    MovieStuff.VisibleAction = [];
    MovieStuff.InvisibleAction = [];
case 'frame'
    pos = [0 0 150 200];    %dummy
    do_frame = 1;
    if length(args)>3
        MovieStuff.VisibleAction = args{3};
        MovieStuff.InvisibleAction = args{4};
    end
end

varW = pos(3)-100;
off = pos(2)+pos(4);
figW = pos(3);

bgCol = get(0 , 'defaultuicontrolbackgroundcolor');
bgCol = get(Handles.Figure,'color');

%Now to make the required uicontrols for the movie controlling stuff...
MovieStuff.titletext = xreguicontrol('style' , 'text' , ...
   'parent' , Handles.Figure , ...
   'horizontalalignment' , 'left' , ...
   'position' , [20 off-30 60 20] , ...
   'fontweight' , 'demi' , ...
   'backgroundcolor' , bgCol , ...
   'visible','off',...
   'string' , 'Movies');

off = off-40;
MovieStuff.Heading(1) = xreguicontrol('style' , 'text' , ...
   'parent' , Handles.Figure , ...
   'units' , 'pixels' , ...
   'position', [20 off-30 varW-20 20],...
   'string' , 'Variable' , ...
   'backgroundcolor' , bgCol , ...
   'horizontalalignment' , 'left' , ...
   'fontweight' , 'bold');
MovieStuff.objstore = MovieStuff.Heading(1);

MovieStuff.Heading(2) = xreguicontrol('style' , 'text' , ...
   'parent' , Handles.Figure , ...
   'string' , 'X' , ...
   'position', [varW+20 off-30 20 20] , ...
   'backgroundcolor' , bgCol , ...
   'foregroundcolor' , [1 0 0] , ...
   'horizontalalignment' , 'left' , ...
   'fontweight' , 'bold');

MovieStuff.Heading(3) = xreguicontrol('style' , 'text' , ...
   'parent' , Handles.Figure , ...
   'position', [varW+40 off-30 20 20] , ...
   'string' , 'Y' , ...
   'backgroundcolor' , bgCol , ...
   'horizontalalignment' , 'left' , ...
   'foregroundcolor' , [0 0 1] , ...
   'fontweight' , 'bold');

MovieStuff.Heading(4) = xreguicontrol('style' , 'text' , ...
   'parent' , Handles.Figure , ...
   'position', [varW+60 off-30 20 20] , ...
   'backgroundcolor' , bgCol , ...
   'string' , 'T' , ...
   'horizontalalignment' , 'left' , ...
   'fontweight' , 'bold');

for i = 1:3
   MovieStuff.Names(i)=xreguicontrol('style' , 'text' , ...
      'parent' , Handles.Figure , ...
      'position', [20 off-30-i.*20 varW-20 20] , ...
      'string' , '' , ...
       'backgroundcolor' , bgCol , ...
      'horizontalalignment' , 'left');
   for j = 1:3
      MovieStuff.Radio(i,j) = xreguicontrol('style' , 'radio' , ...
         'parent' , Handles.Figure , ...
         'position', [varW+j.*20 off-30-i.*20 20 20] , ...
         'backgroundcolor' , bgCol , ...
         'callback' , ['moviehandler(get(' sprintf('%20.15f',MovieStuff.objstore) ',''userdata'') , ''handle_radio'')' ]);
   end
end

%set(MovieStuff.Radio(1,1) , 'value' , 1);
%set(MovieStuff.Radio(2,2) , 'value' , 1);
%set(MovieStuff.Radio(3,3) , 'value' , 1);

off = off+130;
MovieStuff.B1 = xreguicontrol('style' , 'push' , ...
   'parent' , Handles.Figure , ...
   'position', [figW-20-65-65-10 off-130 65 30] , ...
   'string' , 'Make Movie' , ...
   'callback' , ['moviehandler(get(' sprintf('%20.15f',MovieStuff.objstore) ',''userdata'') , ''make_movie'')' ]);

MovieStuff.ReplayMovie = xreguicontrol('style' , 'push' , ...
   'parent' , Handles.Figure , ...
   'position', [figW-20-65 off-130 65 30] , ...
   'string' , 'Replay' , ...
   'callback' , ['moviehandler(get(' sprintf('%20.15f',MovieStuff.objstore) ',''userdata'') , ''replay_movie'')' ],...
   'enable' , 'off');

MovieStuff.B3 = xreguicontrol('style' , 'text' , 'parent' , Handles.Figure,'visible','off');

MovieStuff.MovieVec = [MovieStuff.Heading(:) ; MovieStuff.Radio(:) ; ...
        MovieStuff.Names(:) ; MovieStuff.B1 ; MovieStuff.ReplayMovie];
MovieStuff.TwoDVec = [MovieStuff.Heading(1:2) ; MovieStuff.Radio(1:2,1:2) ; ...
        MovieStuff.Names(1:2)];
MovieStuff.TwoDVec = [MovieStuff.TwoDVec(:); MovieStuff.Heading(3) ];
MovieStuff.Buttons = [MovieStuff.B1 MovieStuff.ReplayMovie];

MovieStuff.InputList = xreglistctrl(Handles.Figure , 'CellHeight' , 20,'visible','off',...
    'position',[20 off-30-60-150 figW-40 105]);
MovieStuff.ShowInputList = 0;

if do_frame
thing = ...
   {MovieStuff.Heading(1) MovieStuff.Names(1) MovieStuff.Names(2) MovieStuff.Names(3) ...
      MovieStuff.Heading(2) MovieStuff.Radio(1,1) MovieStuff.Radio(2,1) MovieStuff.Radio(3,1)...
      MovieStuff.Heading(3) MovieStuff.Radio(1,2) MovieStuff.Radio(2,2) MovieStuff.Radio(3,2)...
      MovieStuff.Heading(4) MovieStuff.Radio(1,3) MovieStuff.Radio(2,3) MovieStuff.Radio(3,3)};

WestBot = xreggridlayout(Handles.Figure , 'elements' , thing , 'dimension' , [4,4] , 'gap' , 5' , 'correctalg' , 'on' , ...
   'colsizes' , [-1 15 15 15] , 'rowsizes' , [20 20 20 20] , 'packstatus' , 'off');

WestBot = xreglayerlayout(Handles.Figure,'elements',{WestBot , MovieStuff.InputList});

WestBotRight = xreggridlayout(Handles.Figure , 'elements' , {MovieStuff.B1 MovieStuff.ReplayMovie MovieStuff.B3} ,...
    'gap' , 10 , 'dimension' , [3,1] , 'correctalg' , 'on' , ...
   'rowsizes' , [30 30 -1] , 'packstatus' , 'off');

WestBot = xreggridlayout(Handles.Figure , 'elements' , {WestBot WestBotRight} , 'gap' , 10 , 'dimension' , [1 2] , ...
   'correctalg' , 'on' , 'colsizes' , [-1 90] , 'packstatus' , 'on');

out2 = WestBot;
MovieStuff.frame = WestBot;
else
    set(MovieStuff.titletext,'visible','on');
    out2 = 0;
    MovieStuff.frame = [];
end

MovieStuff.child = [];
MovieStuff.display = [];
set(MovieStuff.Heading(1),'tag','MovieHandle');

MovieStuff.Figure = Handles.Figure;
MovieStuff.datadisplay = [];

out1 = class(MovieStuff, 'cgmoviehandler');
set(MovieStuff.objstore,'UserData',out1);

