function [lh,lyt] = pr_CreateList(fig,callbacks,ud,IL)
% [lh,lyt] = pr_CreateList(fig,callbacks,ud,IL)

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.3.2.3 $  $Date: 2004/02/09 08:22:21 $


% top factor list
lPos = [-2 -2 1 1]; 
lh = xregGui.listview(lPos , fig, callbacks);
lh.InsertSmallIcons(IL);
set(lh , 'view' , 3 ,...
   'multiselect' , 1 ,...
   'labeledit' , 1 ,...
   'hideselection' , 0 ,...
   'sorted' , 1,...
   'userdata',ud,...
   'Appearance',0,...
   'BorderStyle',0,...
   'Parent',double(fig));
lh_cont = actxcontainer(lh);
lh_cont.Visible = 'off';

lyt = xregpaneltitlelayout(fig, ...
    'packstatus', 'off', ...
    'visible', 'off', ...
    'center', lh_cont);
