function advgreek()
%ADVGREEK Financial Expo option portfolio sensitivities.

%       Author(s): C.F. Garvin, 3-07-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.10 $   $Date: 2002/04/14 21:42:47 $

SCR = get(0,'screensize');
if SCR(3) < 1024
  figure('Numbertitle','off','Name','Option Sensitivity - Portfolio',...
         'tag','OSP','position',[SCR(3)*.1 SCR(4)*.05 SCR(3)*.8 SCR(4)*.85]);
else
  figure('Numbertitle','off','Name','Option Sensitivity - Portfolio',...
         'tag','OSP','position',[SCR(3)*.2 SCR(4)*.25 SCR(3)*.6 SCR(4)*.65]);
end
 
set(gcf,'pointer','watch')
FigPos = get(gcf,'position');

mycolor = hsv;
colormap(mycolor(1:55,:))

Bheight = 20;
if SCR(3) < 1024
  Bspace = 3;
else
  Bspace = 6;
end
BGap = Bheight+Bspace;
Top = FigPos(4)-BGap;
Right = FigPos(3);
Bwidth = 80;
LeftCol = Right-(Bspace+Bwidth);
CButWidth = 20;
Min = LeftCol - 10;
Max = LeftCol + 60;
FWidth = 20;
FHght = 15;
ForColor = 'black';

sens = ['Delta';'Gamma';'Rho  ';'Theta';'Vega '];

Head(1) = uicontrol('style','text','string','Height',...
                  'position',[LeftCol FigPos(4)-BGap Bwidth Bheight],...
                  'backgroundcolor','black','foregroundcolor',ForColor);
Head(2) = uicontrol('style','text','string','Color',...
                  'position',[LeftCol-(Bspace+Bwidth) FigPos(4)-BGap Bwidth Bheight],...
                  'horizontalalignment','right',...
                  'backgroundcolor','black','foregroundcolor',ForColor);
set(Head,'units','norm')
%radio buttons that determine height measure
HTags = str2mat('delta','gamma','rho','theta','vega');
for i = 1:5
UI(i) = uicontrol('position',[LeftCol Top-i*BGap Bwidth Bheight],...
                  'tag',HTags(i,:),...
                  'style','radio','max',12,...
                  'string',sens(i,:)...
                  );
end

set(UI(2),'value',12);

% Build initial display
seoption(20:90,[75 70 50 55 75 50 40 75 60 35],.1,[36 36 36 27 18 18 18 9 9 9],...
         .35,1000*[4 8 3 5 5.5 2 4.8 3 4.8 2.5],'blsgamma');
set(gca,'position',[.125 .1 .675 .75])
set(gca,'box','on','tag','mainaxis')
title('Call Option Sensitivity Measures - Portfolio')
xlabel('Stock Price ($)')
ylabel('Time')
zlabel('Gamma')
o=seoption(20:90,[75 70 50 55 75 50 40 75 60 35],.1,[36 36 36 27 18 18 18 9 9 9],...
         .35,1000*[4 8 3 5 5.5 2 4.8 3 4.8 2.5],'blsdelta');
set(findobj(gcf,'tag','sensmesh'),'Cdata',o)

% Sliders and additional graphics controls
PC(1) = uicontrol('position',[LeftCol Top-6*BGap Bwidth Bheight],...
                  'style','text','string','Return',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(2) = uicontrol('position',[LeftCol Top-8*BGap Bwidth Bheight],...
                  'style','text','string','0.1',...
                  'tag','ratevalue',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(3) = uicontrol('position',[LeftCol Top-7*BGap Bwidth Bheight],...
                  'style','slider',...
                  'tag','retslid',...
                  'visible','on',...
                  'value',.1,'min',.01,'max',.4...
                  );
PC(4) = uicontrol('position',[LeftCol Top-9*BGap Bwidth Bheight],...
                  'style','text','string','Volatility ',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(5) = uicontrol('position',[LeftCol Top-11*BGap Bwidth Bheight],...
                  'tag','volvalue',...
                  'style','text','string','0.35',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(6) = uicontrol('position',[LeftCol Top-10*BGap Bwidth Bheight],...
                  'style','slider',...
                  'tag','volslid',...
                  'visible','on',...
                  'value',.35,'min',.05,'max',.8...
                  );
PC(7) = uicontrol('style','check',...
                  'position',[LeftCol Top-12*BGap Bwidth Bheight],...
                  'userdata',0,...
                  'callback',[...
                  'if get(gco,''userdata'') == 0,'...
                    'rotate3d on,'...
                    'u = findobj(gcf,''type'',''uicontrol'');'...
                    'set(u,''enable'',''off''),'...
                    'set(gco,''enable'',''on''),'...
                    'set(gco,''userdata'',1),'...
                  'else,'...
                    'rotate3d off,'...
                    'u = findobj(gcf,''type'',''uicontrol'');'...
                    'set(u,''enable'',''on''),'...
                    'set(u,''visible'',''off''),'...
                    'set(u,''visible'',''on''),'...
                    'set(gco,''userdata'',0),'...
                    'axes(findobj(gcf,''tag'',''mainaxis''));'...
                  'end,'...
                  ],...  
                  'string','Rotate'...
                  );
out1 = str2mat(...
' In this four-dimensional graph, MATLAB and its Financial and Statistics ',...
' Toolboxes depict the sensitivity of a portfolio of European call options ',...
' using various Black-Scholes measures.  Two axes of the graph are preset:  ',...
' the price of the underlying asset ranges from 20 to 90 dollars on the X-',...
' axis, and the time to maturity ranges from 0 to 36 months on the Y-axis.',...
'.',...
' The default graph shows delta, the sensitivity of the portfolio''s value ',...
' to the price of the underlying stock, as the color scheme; and gamma, ',...
' the sensitivity of the portfolio''s value to delta, on the Z-axis (height)',...
' The risk-free rate of return is 10%, and volatility (sigma) of the underlying');
out2 = str2mat(... 
' stock price is 35%.',...
'.',...
' You can examine other option sensitivities in two ways:',...
'.',...
' 1. Choose which of the sensitivities to show on the Z-axis (height) and ',...
'    as the color scheme.  To select the Z axis, click on the button in the',...
'    Height column next to the sensitivity you want.  To select the color scheme,',...
'    click on the button in the Color column next to the desired sensitivity.',...
'.',...
'    The sensitivities you can select are:');
out3 = str2mat(...
'.',...
'    Delta:  Sensitivity of option''s value to price of the underlying stock.',...
'.',...
'    Gamma:  Sensitivity of delta to price of the underlying stock.',...
'.',...
'    Rho:    Sensitivity of option''s value to the risk-free rate of return.',...
'.',...
'    Theta:  Sensitivity of option''s value to time remaining to maturity.',...
'.',...
'    Vega:   Sensitivity of option''s value to the volatility (sigma) of the underlying stock.');
out4 = str2mat(...
'.',...
' 2. Change the risk-free rate of Return and the Volatility (sigma) of the ',...
'    underlying stock price.  Click the left or right arrow buttons for ',...
'    incremental changes, or drag the slider for larger changes.',...
'.',...
' Click the Run button to see the new graph after you change parameters.',...
'.',...
' Click on the Rotate button to see the flexibility of MATLAB''s Handle ',...
' Graphics.  Move the mouse cursor into the graph area, and press and hold ');
out5 = str2mat(...
' the primary mouse button.  You will see an outline of the graph.  ',...
' Continue holding the mouse button, and move the mouse to rotate and tilt ',...
' the outline as desired.  Release the mouse button to see the new view.  ',...
' Click the Rotate button again to turn off this feature.',...
'.',...
' Click the Movie button to see a five-dimensional graph:  stock price vs. ',...
' time vs. gamma vs. theta, as volatility ranges from 0.10 to 0.90.',...
'.',...
' ');

HelpDlgString = str2mat(out1,out2,out3,out4,out5);
PC(8) = uicontrol('position',[LeftCol Top-14*BGap Bwidth Bheight],...
                  'string','Help',...
                  'userdata',HelpDlgString,...
          'callback',['set(gcf,''pointer'',''watch''),'...
          'helpwin(get(gco,''userdata''),''Option Sensitivity Help'');'...
          'set(findobj(0,''tag'',''OSP''),''pointer'',''arrow'')']);
PC(9) = uicontrol('visible','off','position',[LeftCol Top-16*BGap Bwidth Bheight],...
                  'string','Main Map',...
                  'callback',[...
                  'colormap(hsv);close;'...
                  'figure(findobj(0,''tag'',''MAINMAP''));']);
PC(10) = uicontrol('position',...
                   [LeftCol Top-99*BGap Bwidth Bheight],...
                   'visible','off');
PC(11) = uicontrol('position',[LeftCol Top-15*BGap Bwidth Bheight],...
                  'callback',[...
                  'set(gcf,''pointer'',''watch''),'...
                  'set(findobj(gcf,''value'',12),''value'',0),'...
                  'set(findobj(gcf,''value'',3),''value'',0),'...
                  'set(min(findobj(gcf,''tag'',''gamma'')),''value'',12),'...
                  'set(max(findobj(gcf,''tag'',''Theta'')),''value'',3),'...
                  'drawnow,'...
                  'load portmov,'...
                  'set(gca,''position'',[.125 .2312 .675 .6188]),'...
                  'set(gca,''box'',''on'',''tag'',''mainaxis''),'...
                  'title(''Call Option Sensitivity Measures - Portfolio''),'...
                  'xlabel(''Stock Price ($)''),'...
                  'ylabel(''Time''),'...
                  'zlabel(get(findobj(gcf,''value'',12),''string'')),'...
                  'colorbar,'...
                  'cax = findobj(gcf,''tag'',''colorax'');'...
                  'set(get(cax,''Xlabel''),''string'',get(findobj(gcf,''value'',3),''tag'')),'...
                  'set(cax,''ytick'',[]),'...
                  'set(gcf,''nextplot'',''add''),'...
                  'cla,'...
                  'set(gca,''visible'',''off''),'...
                  'movie(M,-3),'...
                  'set(gcf,''pointer'',''arrow''),'...
                  ],... 
                  'string','Movie'...
                  );
PC(12) = uicontrol('position',[Min Top-6.2*BGap FWidth FHght],...
                  'style','text','string','.01',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(13) = uicontrol('position',[Max Top-6.2*BGap FWidth FHght],...
                  'style','text','string','.40',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(14) = uicontrol('position',[Min Top-9.2*BGap FWidth FHght],...
                  'style','text','string','.05',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(15) = uicontrol('position',[Max Top-9.2*BGap FWidth FHght],...
                  'style','text','string','.80',...
                  'foregroundcolor',ForColor,'backgroundcolor','black');
PC(16) = uicontrol('position',[LeftCol Top-13*BGap Bwidth Bheight],...
                  'string','Run',...
                  'callback',[...
               'fun=[''bls'',lower(get(findobj(gcf,''value'',12),''tag''))];'...
               'func=[''bls'',lower(get(findobj(gcf,''value'',3),''tag''))];'...
                  'r = get(findobj(gcf,''tag'',''retslid''),''value'');'...
                  'v = get(findobj(gcf,''tag'',''volslid''),''value'');'...
                  'seoption(20:90,[75 70 50 55 75 50 40 75 60 35],'...
                  'r,[36 36 36 27 18 18 18 9 9 9],v,'...
                  '1000*[4 8 3 5 5.5 2 4.8 3 4.8 2.5],fun);'...
                  'o = seoption(20:90,[75 70 50 55 75 50 40 75 60 35],'...
                  'r,[36 36 36 27 18 18 18 9 9 9],v,'...
                  '1000*[4 8 3 5 5.5 2 4.8 3 4.8 2.5],func);'...
                  'set(findobj(gcf,''tag'',''sensmesh''),''Cdata'',o),'...
                  'set(gca,''position'',[.125 .2312 .675 .6188]),'...
                  'set(gca,''box'',''on'',''tag'',''mainaxis''),'...
                  'title(''Call Option Sensitivity Measures - Portfolio''),'...
                  'xlabel(''Stock Price ($)''),'...
                  'ylabel(''Time''),'...
                  'fun(1:3) = [];'...
                  'zlabel(get(findobj(gcf,''value'',12),''string'')),'...
                  'colorbar,'...
                  'cax = findobj(gcf,''tag'',''colorax'');'...
                  'set(get(cax,''Xlabel''),''string'',get(findobj(gcf,''value'',3),''tag'')),'...
                  'set(cax,''ytick'',[]),'...
                  'set(gcf,''nextplot'',''add''),'...
                  'set(gca,''xcolor'',''k'',''ycolor'',''k'',''zcolor'',''k''),'...
                  'set(findobj(gcf,''tag'',''sensmesh''),''edgecolor'',''flat''),'...
                  'set(gcf,''pointer'',''arrow'')'...
                  ]);

set(PC,'units','normal')

for i = 1:5
 set(UI(i),'userdata',[UI(:,[1:(i-1),(i+1):5]),PC(2),PC(5),PC(10)])
end

% Callback for radio buttons
call = ['set(gcf,''pointer'',''watch''),'...
        'zbut = findobj(gcf,''value'',12);'...
        'set(zbut,''value'',0),'...
        'set(gco,''value'',12),'...
        'set(gcf,''pointer'',''arrow''),'...
        ];
scall = [...
        'set(gcf,''pointer'',''watch''),'...
        'b = get(gco,''userdata'');'...
        'set(b(1),''string'',num2str(get(b(2),''value'')));'...
        'set(b(3),''string'',num2str(get(b(4),''value'')));'...
        'set(gcf,''pointer'',''arrow''),'...
        ];

set(UI,'callback',call,'units','normal')
set(PC([3,6]),'userdata',[PC(2),PC(3),PC(5),PC(6),PC(10)],'callback',scall);

% Radio buttons control color measure
Cbut(1) = uicontrol('style','radio','max',3,...
               'value',3,...
               'tag','Delta',...
               'pos',[LeftCol-Bspace-CButWidth Top-BGap CButWidth Bheight],...
               'horizontalalignment','left'...
               );
Cbut(2) = uicontrol('style','radio','max',3,...
               'tag','Gamma',...
               'pos',[LeftCol-Bspace-CButWidth Top-2*BGap CButWidth Bheight],...
               'horizontalalignment','left'...
               );
Cbut(3) = uicontrol('style','radio','max',3,...
               'tag','Rho',...
               'pos',[LeftCol-Bspace-CButWidth Top-3*BGap CButWidth Bheight],...
               'horizontalalignment','left'...
               );
Cbut(4) = uicontrol('style','radio','max',3,...
               'tag','Theta',...
               'pos',[LeftCol-Bspace-CButWidth Top-4*BGap CButWidth Bheight],...
               'horizontalalignment','left'...
               );
Cbut(5) = uicontrol('style','radio','max',3,...
               'tag','Vega',...
               'pos',[LeftCol-Bspace-CButWidth Top-5*BGap CButWidth Bheight],...
               'horizontalalignment','left'...
               );

% Color measure radio button callback
cbutcall = ['set(gcf,''pointer'',''watch''),',...
        'if(get(gco,''value'')==3),',...
          'set(get(gco,''userdata''),''value'',0),',...
        'else,',...
          'set(gco,''value'',3),',...
          'set(get(gco,''userdata''),''value'',0),',...
        'end,'...
        'set(gcf,''pointer'',''arrow''),'...
        ];

for i = 1:5
 set(Cbut(i),'userdata',Cbut(:,[1:(i-1),(i+1):5]))
end

set(Cbut,'units','normal','callback',cbutcall)

% Display colorbar
colorax = colorbar('horiz');
set(colorax,'position',[.1 .1 .7 .0562])
set(get(colorax,'Xlabel'),'string',get(findobj(gcf,'value',3),'tag'))
set(colorax,'ytick',[],'tag','colorax')
set(gcf,'nextplot','add')
TXT = findobj(gcf,'style','text');
set(TXT,'backgroundcolor',get(gcf,'color'))
set(gcf,'pointer','arrow')
