function fig = bondspecgui(varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%    This is private file of the BDT Demo and is not meant to be called
%    directly by the user.
%
%Author: C. Bassignani, 05-20-98 
%   Copyright 1995-2002 The MathWorks, Inc. 
%$Revision: 1.7 $   $Date: 0000/00/00 00:00:00

load bondspecgui

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[300 250 479 447], ...
	'NumberTitle', 'off', ...
	'MenuBar', 'none', ...
	'Name', 'Bond Specifications Editor', ...
	'Tag','BondGUI');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[90 227.25 75 18], ...
	'String','09-Sep-1998', ...
	'Style','edit', ...
	'Tag','EditMaturity');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[88.5 183 75 18], ...
	'Style','edit', ...
	'Tag','EditFirstCouponDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[89.25 161.25 75 18], ...
	'Style','edit', ...
	'Tag','EditLastCouponDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[89.25 138.75 75 18], ...
	'Style','edit', ...
	'Tag','EditStartDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[89.25 250.5 75 18], ...
	'String','09-Sep-1995', ...
	'Style','edit', ...
	'Tag','EditSettle');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[89.25 204.75 75 18], ...
	'Style','edit', ...
	'Tag','EditIssueDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[8.25 225.75 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Maturity', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[9 204 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Issue', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[9 182.25 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','First Coupon', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[9 160.5 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Last Coupon', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[9 138 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Start', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[9 248.25 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Settlement', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[183 273 153.75 18.75], ...
	'String','Embedded Options', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[182.25 231.75 120 19.5], ...
	'String',mat1, ...
	'Style','popupmenu', ...
	'Tag','PopCallOptionType', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[91.5 93.75 77.25 19.5], ...
	'String',mat2, ...
	'Style','popupmenu', ...
	'Tag','PopBasis', ...
	'Value',2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 210 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Call Start Date', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 187.5 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Call Expiry Date', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 165.75 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Call Strike Price', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[9.75 71.25 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Coupon Rate', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 91.5 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Put Start Date', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 69.75 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Put Expiry Date', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 47.25 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Put Strike Price', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[9.75 48 73.5 18], ...
	'HorizontalAlignment', 'right', ...
	'String','Face Value', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[9 273.75 153.75 18.75], ...
	'String','Base Date Parameters', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[183 255 98.25 13.5], ...
	'String','Call Option Parameters', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[266.25 210.75 75 18], ...
	'Style','edit', ...
	'Tag','EditCallStartDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[265.5 166.5 75 18], ...
	'Style','edit', ...
	'Tag','EditCallStrikePrice');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[266.25 189 75 18], ...
	'Style','edit', ...
	'Tag','EditCallExpiryDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[183 137.25 98.25 13.5], ...
	'String','Put Option Parameters', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[266.25 69 75 18], ...
	'Style','edit', ...
	'Tag','EditPutExpiryDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[266.25 46.5 75 18], ...
	'Style','edit', ...
	'Tag','EditPutStrikePrice');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[266.25 90 75 18], ...
	'Style','edit', ...
	'Tag','EditPutStartDate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[183 113.25 100 19.5], ...
	'String',mat3, ...
	'Style','popupmenu', ...
	'Tag','PopPutOptionType', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[9.75 93 77.25 19.5], ...
	'String',mat4, ...
	'Style','popupmenu', ...
	'Tag','PopFrequency', ...
	'Value',3);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[90.75 48.75 75 18], ...
     'Style','edit', ...
     'String','100.00', ...
     'HorizontalAlignment', 'center', ...
	'Tag','EditFace');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[90.75 71.25 75 18], ...
     'Style','edit', ...
     'String','0.05', ...
     'HorizontalAlignment', 'center', ...
	'Tag','EditCouponRate');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','bondspecguicall', ...
	'FontSize',9, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[250 13.5 73.5 22.5], ...
	'String','Done', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
     'FontWeight','bold',...
     'FontSize', 10,...
	'ForegroundColor',[0 0.501960784313725 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[10 300 300 20], ...
	'String','Bond Parameter Specifications', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[11.25 17.25 156 18.75], ...
	'Style','edit', ...
	'Tag','EditBondSpecErrorMessage');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[90.75 115.5 75 17.25], ...
	'String','Basis', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[9.75 115.5 75 17.25], ...
	'String','Period', ...
	'Style','text', ...
	'Tag','StaticText5');
if nargout > 0, fig = h0; end

% adjust the positions of the uicontrols
bdtmainaction('adjustres')



if (nargin > 0) %GUI has already been built and the bond is being passed to it
     
IBond = varargin{1};     
     
%Get the handles of all the date paramter fields                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
SettleHandle =  findobj('Tag', 'EditSettle');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
MaturityHandle =  findobj('Tag', 'EditMaturity');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
IssueDateHandle =  findobj('Tag', 'EditIssueDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
FirstCouponDateHandle =  findobj('Tag', 'EditFirstCouponDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
LastCouponDateHandle =  findobj('Tag', 'EditLastCouponDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
CallStartDateHandle =  findobj('Tag', 'EditCallStartDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
CallExpiryDateHandle =  findobj('Tag', 'EditCallExpiryDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
CallStrikePriceHandle =  findobj('Tag', 'EditCallStrikePrice');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
PutStartDateHandle =  findobj('Tag', 'EditPutStartDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
PutExpiryDateHandle =  findobj('Tag', 'EditPutExpiryDate');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
PutStrikePriceHandle =  findobj('Tag', 'EditPutStrikePrice');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

%Get the values of the other bond paramters                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
CallOptionTypeHandle =  findobj( 'Tag', 'PopCallOptionType');       
PutOptionTypeHandle =  findobj('Tag', 'PopPutOptionType');                
FrequencyHandle =  findobj('Tag', 'PopFrequency');
BasisHandle =  findobj('Tag', 'PopBasis');
CouponRateHandle = findobj('Tag', 'EditCouponRate');
FaceHandle = findobj('Tag', 'EditFace');


Settle = IBond.Settle;
Maturity = IBond.Maturity;
Period = IBond.Period;
Basis = IBond.Basis;
EndMonthRule = IBond.EndMonthRule;
IssueDate = IBond.IssueDate;
FirstCouponDate = IBond.FirstCouponDate;
LastCouponDate = IBond.LastCouponDate;

CallStartDate = IBond.CallStartDate;
CallExpiryDate = IBond.CallExpiryDate;
CallStrike = IBond.CallStrike;
CallType = IBond.CallType;
PutStartDate = IBond.PutStartDate;
PutExpiryDate = IBond.PutExpiryDate;
PutStrike = IBond.PutStrike;
PutType = IBond.PutType;

CouponRate = IBond.CouponRate;
Face = IBond.Face;

%Convert all dates to date strings
if(~isempty(Settle))
     Settle = datestr(Settle);
end

if(~isempty(Maturity))
     Maturity = datestr(Maturity);
end

if(~isempty(FirstCouponDate))
     FirstCouponDate = datestr(FirstCouponDate);
end

if(~isempty(IssueDate))
     IssueDate = datestr(IssueDate);
end

if(~isempty(LastCouponDate))
     LastCouponDate = datestr(LastCouponDate);
end

if(~isempty(CallStartDate))
     CallStartDate = datestr(CallStartDate);
end

if(~isempty(CallExpiryDate))
     CallExpiryDate = datestr(CallExpiryDate);
end

if(~isempty(PutStartDate))
     PutStartDate = datestr(PutStartDate);
end

if(~isempty(PutExpiryDate))
     PutExpiryDate = datestr(PutExpiryDate);
end


%Write all parameters to the GUI
set(SettleHandle , 'String', Settle);
set(MaturityHandle , 'String', Maturity);
set(IssueDateHandle , 'String', IssueDate);
set(FirstCouponDateHandle , 'String', FirstCouponDate);
set(LastCouponDateHandle , 'String', LastCouponDate);
set(CallStartDateHandle , 'String', CallStartDate);
set(CallExpiryDateHandle , 'String', CallExpiryDate);
set(CallStrikePriceHandle , 'String', CallStrike);
set(PutStartDateHandle , 'String', PutStartDate);
set(PutExpiryDateHandle , 'String', PutExpiryDate);
set(PutStrikePriceHandle , 'String', PutStrike);


if (isempty(CallType))
     CallOptionTypeValue = 1;
elseif (CallType == 1)
     CallOptionTypeValue = 2;
elseif (CallType == 0)
     CallOptionTypeValue = 3;
end

if (isempty(PutType))
     PutOptionTypeValue = 1;
elseif (PutType == 1)
     PutOptionTypeValue = 2;
elseif (PutType == 0)
     PutOptionTypeValue = 3;
end

if (isempty(Period))
     FrequencyValue = 1;
elseif (Period == 1)
     FrequencyValue = 2;
elseif (Period == 2)
     FrequencyValue = 3;
elseif (Period == 4)
     FrequencyValue = 4;
elseif (Period == 12)
     FrequencyValue = 5;
end

if (isempty(Basis))
     BasisValue = 1;
elseif (Basis == 0)
     BasisValue = 2;
elseif (Basis == 1)
     BasisValue = 3;
elseif (Basis == 2)
     BasisValue = 4;
elseif (Basis == 3)
     BasisValue = 5;
end

if (~isempty(CallType))
     set(CallOptionTypeHandle , 'Value', CallOptionTypeValue);
end

if (~isempty(PutType))
     set(PutOptionTypeHandle , 'Value', PutOptionTypeValue);
end

if (~isempty(CouponRate))
     set(CouponRateHandle , 'String', CouponRate);
end

if (~isempty(Basis))
     set(BasisHandle , 'Value', BasisValue);
end

if (~isempty(Face))
     set(FaceHandle , 'String', Face);
end

if (~isempty(Period))
     set(FrequencyHandle , 'Value', FrequencyValue);
end
drawnow;

end

return

