function fig = degatool()
%DEGATOOL Optimization GUI Demo using Genetic Algorithm methodology.
%

% Author(s): R.A. Baker, 06/18/98
% Copyright 1995-2002 The MathWorks, Inc. 
% $Revision: 1.10 $   $Date: 2002/04/14 21:45:37 $

% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load degatool

h0 = figure('Color',[0 0 0], ...
	'Colormap',mat0, ...
	'Name','Differential Evolutionary Parameter Estimation', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[20 50 845 768], ...
	'Resize','off', ...
	'Tag','DEwindow', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[63 423 220.5 107.25], ...
	'Style','frame', ...
	'Tag','Frame3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[345 150.75 222 341.25], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[62.25 39.75 222 186.75], ...
	'Style','frame', ...
	'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'ListboxTop',0, ...
	'Position',[62.25 250.5 222 142.5], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback',mat1, ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[78 480.75 191.25 33], ...
	'String','Specify Fitness Function', ...
	'Tag','Pushbutton1', ...
	'TooltipString','Click this button to select a fitness (objective) function M-file to maximize.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat2, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[445.5 420.75 75 17.25], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','NPvalue', ...
	'TooltipString',mat3);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[371.25 414.75 66.75 28.5], ...
	'String','Number of Individuals', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[372 381 66 24.75], ...
	'String','Number of Generations', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat4, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[445.5 384.75 76.5 16.5], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','nGenerationsValue', ...
	'TooltipString',mat5);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.45 0.5], ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[361.25 463.5 188.25 21], ...
	'String','Population Parameters', ...
	'Style','text', ...
	'Tag','StaticText3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.45 0.5], ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[78.75 363 187.5 21], ...
	'String','Control Parameters', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[79.5 327.75 78.75 24], ...
	'String','Mutation Scale Factor (F)', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[78.75 289.5 78.75 24], ...
	'String','Crossover Constant (CR)', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat6, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[174.75 327 90 21], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','Fvalue', ...
	'TooltipString','Edit this field to adjust the weight applied to mutation.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat7, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[174.75 291 90 21], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','CRvalue', ...
	'TooltipString',mat8);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[79.5 257.25 78.75 24], ...
	'String','Convergence Tolerance Limit', ...
	'Style','text', ...
	'Tag','StaticText5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',mat9, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[174 258 90 21], ...
	'String','0.00001', ...
	'Style','edit', ...
	'Tag','similarityLimitValue');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','[optimalParamaterEstimates , control , infoCellArray] = runbuttoncallback;', ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[415.875 90 76.5 33.75], ...
	'String','Run', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Click here to run the DE maximization process with your inputs.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close( gcf);', ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[415.875 41.25 76.5 33.75], ...
	'String','Exit', ...
	'Tag','Pushbutton2', ...
	'TooltipString','Click here to close the DE command window interface.');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(1,1) = str2double(get(findobj(gcf,''tag'',''p1min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 288 62.25 14.25], ...
	'String','-3', ...
	'Style','edit', ...
	'Tag','p1min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(1,2) = str2double(get(findobj(gcf,''tag'',''p1max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 288 62.25 14.25], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','p1max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(2,1) = str2double(get(findobj(gcf,''tag'',''p2min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 273.75 62.25 14.25], ...
	'String','-3', ...
	'Style','edit', ...
	'Tag','p2min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(3,1) = str2double(get(findobj(gcf,''tag'',''p3min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 259.5 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p3min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(4,1) = str2double(get(findobj(gcf,''tag'',''p4min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 245.25 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p4min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(5,1) = str2double(get(findobj(gcf,''tag'',''p5min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 231 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p5min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(6,1) = str2double(get(findobj(gcf,''tag'',''p6min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 216.75 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p6min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(7,1) = str2double(get(findobj(gcf,''tag'',''p7min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 202.5 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p7min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(8,1) = str2double(get(findobj(gcf,''tag'',''p8min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 188.25 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p8min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(10,1) = str2double(get(findobj(gcf,''tag'',''p10min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 159.75 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p10min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(9,1) = str2double(get(findobj(gcf,''tag'',''p9min'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[389.25 174 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p9min');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(2,2) = str2double(get(findobj(gcf,''tag'',''p2max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 273.75 62.25 14.25], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','p2max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(3,2) = str2double(get(findobj(gcf,''tag'',''p3max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 259.5 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p3max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(4,2) = str2double(get(findobj(gcf,''tag'',''p4max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 245.25 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p4max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(5,2) = str2double(get(findobj(gcf,''tag'',''p5max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 231 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p5max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(6,2) = str2double(get(findobj(gcf,''tag'',''p6max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 216.75 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p6max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(7,2) = str2double(get(findobj(gcf,''tag'',''p7max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 202.5 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p7max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(9,2) = str2double(get(findobj(gcf,''tag'',''p9max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 174 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p9max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(10,2) = str2double(get(findobj(gcf,''tag'',''p10max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 159.75 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p10max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','%parameterRanges(8,2) = str2double(get(findobj(gcf,''tag'',''p8max'') , ''string''));', ...
	'ListboxTop',0, ...
	'Position',[453.75 188.25 62.25 14.25], ...
	'Style','edit', ...
	'Tag','p8max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[384 309.75 139.5 15.75], ...
	'String','Lower Bound    Upper Bound', ...
	'Style','text', ...
	'Tag','StaticText6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[362.25 326.25 189 39], ...
	'String','Parameter Bounds for Seeding the Initial Population', ...
	'Style','text', ...
	'Tag','StaticText7');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[67.5 158.25 209.25 33.75], ...
	'String',' Average Population Fitness by Generation', ...
	'Style','checkbox', ...
	'Tag','plotAverage', ...
	'TooltipString',mat10, ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[67.5 120 208.5 35.25], ...
	'String',' Fittest Individual by Generation', ...
	'Style','checkbox', ...
	'Tag','plotFittest', ...
	'TooltipString',mat11);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[68.25 81 207.75 36], ...
	'String',' Convergence Criteria by Generation', ...
	'Style','checkbox', ...
	'Tag','plotConvergence', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.45 0.5], ...
	'FontSize',15, ...
	'ListboxTop',0, ...
	'Position',[78.75 195 187.5 21], ...
	'String','Graphical Analysis', ...
	'Style','text', ...
	'Tag','StaticText4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0], ...
	'FontSize',15, ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[79.5 441.75 188.25 21.75], ...
	'String','mypeaks', ...
	'Style','text', ...
	'Tag','currentFitnessFunction', ...
	'TooltipString',mat12);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.2 0.7 0.7], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[68.25 42 207.75 36], ...
	'String','Evolutionary Progression (3-D Only)', ...
	'Style','checkbox', ...
	'Tag','plotEvolution', ...
	'TooltipString',mat13, ...
	'Value',1);
if nargout > 0, fig = h0; end
