function fuzdem()
%FUZDEM Fuzzy Logic Demonstration UI for Financial Expo.

%       Author(s): C.F. Garvin, 9-25-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.10 $   $Date: 2002/04/14 21:45:40 $

SCR = get(0,'screensize');
FuzWin = figure('numbertitle','off','name',...
       'Fuzzy Logic - Price Behavior','position',...
       [SCR(3)*.25 SCR(4)*.05 SCR(3)*.7 SCR(4)*.9]);
set(gcf,'pointer','watch')
FigPos = get(gcf,'position');

Top = FigPos(4);
Right = FigPos(3);
if SCR(3) < 1024
  Bheight = 18;
  Bspace = 2;
  Bwidth = 85;
else
  Bwidth = 85;
  Bheight = 20;
  Bspace = 5;
end
Bvgap = Bspace+Bheight;
Bhgap = Bspace+Bwidth;

load ibm.dat

PushStr = str2mat('GENFIS2');
method = str2mat('genfis2');

HeadUI(1) = uicontrol('style','text','string','Method','position',...
                        [Right-Bhgap Top-Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
MethodUI(1) = uicontrol('style','radio','value',0,'max',12,...
                 'value',12,...
                 'position',...
                 [Right-Bhgap Top-2*Bvgap Bwidth Bheight],...
                 'userdata','method','string',PushStr(1,:),...
                 'tag',method(1,:),'callback',[...
                 'set(gco,''value'',12),'...
                 ]);

OutputUI(1) = uicontrol('style','text','string','Output','position',...
                        [Right-Bhgap Top-3*Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
OutputUI(2) = uicontrol('style','check','string','Close','value',1,...
                        'callback','set(gco,''value'',1)',...
                        'position',[Right-Bhgap Top-4*Bvgap Bwidth Bheight]);
datastr = str2mat('Date','High','Low','Close','Volume','Close*Volume');
InputUI(1) = uicontrol('style','text','string','Input','position',...
                        [Right-Bhgap Top-5*Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
for i = 2:7
   InputUI(i) = uicontrol('style','check','value',0,...
                         'tag','off',...
                         'position',...
                         [Right-Bhgap Top-(i+4)*Bvgap Bwidth Bheight],...
                         'userdata',i-1,'string',datastr(i-1,:),'callback',[...
                         'stat = get(gco,''tag'');'...
                         'if stat(1:2) == ''on'','...
                          'set(gco,''tag'',''off''),'...
                          'set(gco,''value'',0),'...
                         'elseif stat(1:2) == ''of'','...
                          'set(gco,''tag'',''on''),'...
                          'set(gco,''value'',1),'...
                         'end,'...
                         'inon = findobj(gcf,''tag'',''on'');'...
                         'del(1) = findobj(gcf,''tag'',''det'');'...
                         'del(2) = findobj(gcf,''tag'',''delbox'');'...
                         'if length(inon) == 1,'...
                            'set(del,''enable'',''on''),'...
                         'else,'...
                            'set(del,''enable'',''off''),'...
                         'end,'...
                         ]);
end
set(InputUI(5),'value',1,'tag','on')

load ibm.dat
fuzfunc([diff(ibm(:,4)) diff(ibm(:,4))],100,4);
a = findobj(gcf,'type','axes');
set(a(2),'position',[.1 .6 .65 .35])
set(a(1),'position',[.1 .1 .65 .35])

CoeffUI(1) = uicontrol('style','text','string','# Points',...
                       'position',...
                       [Right-Bhgap Top-12*Bvgap Bwidth Bheight]);
CoeffUI(2) = uicontrol('style','edit','string','100',...
                    'position',...
                    [Right-Bhgap Top-13*Bvgap Bwidth Bheight],...
                    'tag','ptsbox');
CoeffUI(3) = uicontrol('style','text','string','Delay',...
                       'tag','det','position',...
                       [Right-Bhgap Top-14*Bvgap Bwidth Bheight]);
CoeffUI(4) = uicontrol('style','edit','string','4',...
                    'position',...
                    [Right-Bhgap Top-15*Bvgap Bwidth Bheight],...
                    'tag','delbox');

otherstr = str2mat('Zoom','Run','Help','Main Map');
for i = 1:4
  OtherUI(i) = uicontrol('string',otherstr(i,:),...
                         'position',...
                         [Right-Bhgap Top-(i+16)*Bvgap Bwidth Bheight]);
end

set(OtherUI(1),'style','checkbox','callback',[...
          'if get(gco,''value'') == 0,'...
            'zoom off,'...
            'set(gcf,''pointer'',''arrow''),'...
          'else,'...
            'zoom on,'... 
            'set(gcf,''pointer'',''circle''),'...
          'end,'...
          ]);
set(OtherUI(2),'callback',[...
       'load ibm.dat,'...
       'duis = findobj(gcf,''tag'',''on'');'...
       'if isempty(duis),'...
          'errordlg(''Please specify at least one Input.'');'...
          'return,'...
       'end,'...
       'ins = length(duis);'...
       'index = [];'...
       'for i = 1:ins,'...
         'index(i) = get(duis(i),''userdata'');'...
       'end,'...
       '[row,col] = size(ibm);'...
       'indata = [diff(ibm(:,4)) ibm(1:row-1,index)];'...
       'coeff1 = str2double(get(findobj(gcf,''tag'',''ptsbox''),''string''));'...
       'if coeff1 > 400,'...
         'coeff1 = 400;'...
         'set(findobj(gcf,''tag'',''ptsbox''),''string'',''400''),'...
       'elseif coeff1 < 3,'...
         'coeff1 = 3;'...
         'set(findobj(gcf,''tag'',''ptsbox''),''string'',''3''),'...
       'end,'...
       'coeff2 = str2double(get(findobj(gcf,''tag'',''delbox''),''string''));'...
       'if coeff2 > 25,'...
         'coeff2 = 25;'...
         'set(findobj(gcf,''tag'',''delbox''),''string'',''25''),'...
       'elseif coeff2 < 1,'...
         'coeff2 = 1;'...
         'set(findobj(gcf,''tag'',''delbox''),''string'',''1''),'...
       'end,'...
       'fuzfunc(indata,coeff1,coeff2),'...
       'a = findobj(gcf,''type'',''axes'');'...
       'a = sort(a);'...
       'set(a(1),''position'',[.1 .6 .65 .35]),'...
       'set(a(2),''position'',[.1 .1 .65 .35]),'...
       ]);

out1 = str2mat(...
' This demonstration uses the Fuzzy Logic Toolbox to estimate the daily  ',...
' price change difference in closing stock prices.  Specifically, it  ',...
' generates a fuzzy inference system matrix using subtractive clustering  ',...
' (the GENFIS2 function).  Given 100 actual closing stock prices as default  ',...
' input data, it extracts a set of rules that models the data behavior.   ',...
' It then uses the rulebase to estimate future values of the closing stock  ',...
' price.  The underlying data set contains IBM stock price data for about  ',...
' 450 trading days. ',...
'.',...
' The top graph shows actual and estimated results.  The bottom graph  ');
out2 = str2mat(...
' shows the estimation error, or the difference between actual and  ',...
' estimated results. ',...
'.',...
' You can change parameters to refine the estimation: ',...
'.',...
'    Select (click on) one or more Inputs to use in estimating the output.   ',...
'    Inputs consist of trading dates; high, low, and closing prices;  ',...
'    trading volume; and closing price times volume from the IBM stock  ',...
'    data set. ',...
'.');
out3 = str2mat(...
'    Edit the number of Points used in the data set.  For example, 100  ',...
'    uses the first 100 Input values.  The first 75 points are used to ',...
'    generate the model, and the remaining 25 points are used to test the ',...
'    accuracy of the model. ',...
'.',...
'    Edit the Delay, or the number of points used to estimate the next  ',...
'    point.  A Delay of 4 uses points 1 through 4 to estimate the 5th  ',...
'    point, points 2 through 5 to estimate the 6th point, and so on.  If  ',...
'    you select more than one Input, the Delay is automatically set to 1. ',...
'.');
out4 = str2mat(...
'    Click the Run button to see the new results after you change  ',...
'    parameters. ',...
'.',...
' You can magnify any portion of a chart.  Click Zoom and move the cursor  ',...
' to the desired area.  The cursor changes to a circle.  To zoom in  ',...
' (magnify), click the primary mouse button.  To zoom back out, click the  ',...
' secondary mouse button.  Click Zoom again to turn off the zoom function. ',...
'.',...
' Click the Main Map button to return to the Main Map. ');

helpstr = str2mat(out1,out2,out3,out4);
set(OtherUI(3),'userdata',helpstr,'callback',[...
               'helpwin(get(gco,''userdata''),''Fuzzy Logic Help'');'...
    ])
set(OtherUI(4),'callback','close;figure(findobj(0,''tag'',''MAINMAP''));')

set([HeadUI(:);MethodUI(:);OutputUI(:);InputUI(:);OtherUI(:);CoeffUI(:)],...
    'units','normal')
TXT = findobj(gcf,'style','text');
set(TXT,'backgroundcolor',get(gcf,'color'))
set(gcf,'pointer','arrow')
