function getcreditcrvguicall()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%    This is private file of the BDT Demo and is not meant to be called
%    directly by the user.
%
%Author: C. Bassignani, 05-20-98 
%   Copyright 1995-2002 The MathWorks, Inc. 
%$Revision: 1.6 $   $Date: 0000/00/00 00:00:00

%Load the zero curve from disk by calling the LDZEROCRV subroutine
global GCREDITCURVE;

CreditCurve = ldcreditcrv;

GCREDITCURVE = CreditCurve;

%If the zero curve is not empty, plot it in the correct axes
if (~isempty(CreditCurve))
     
     CreditCurveAxesHandle = findobj('Tag', 'AxesCreditCurve');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
     
     axes(CreditCurveAxesHandle);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
     
     CurveDates = CreditCurve.CurveDates;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
     CreditRates =CreditCurve.CreditRates;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
     
     plot(CurveDates, CreditRates);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
     
     %Scale the plot within the axes so it fits the axes area
     plotscale(0.10);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
     
     set(gca, 'Tag', 'AxesCreditCurve');
     

     set(gca, 'XTick', []);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
     set(gca, 'YTick', []);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                     **********SUBROUTINES************
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function CreditCurve = ldcreditcrv()
%LDCREDITCURVE Load Credit Curve from Disk and Report Errors to GUI


%Set the output variable initially to an empty matrix
CreditCurve = [];

ErrorFlag = 0;

%Make sure that no error message is displayed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
EditErrorMsgHandle = findobj(gcbf, 'Tag', 'EditCreditCurveErrorMessage');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ErrorMessage = '';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
set(EditErrorMsgHandle, 'String', ErrorMessage);
drawnow;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Get the file location, name and the name of the bond                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
FileLocHandle = findobj(gcbf, 'Tag', 'EditCreditCurveFileLocation');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
FileLocString = get(FileLocHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
FileNameHandle = findobj(gcbf, 'Tag',  'EditCreditCurveFileName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
FileNameString = get(FileNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
CurveNameHandle = findobj(gcbf, 'Tag', 'EditCreditCurveName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
CurveNameString = get(CurveNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Build the absolute file name from the data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
AbsFileName = strcat(FileLocString, FileNameString);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set the bond type explicity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CurveType = 'creditcurve';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

%Build the main command string                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
CommandString = [ 'CreditCurve = ldcrvstruct(CurveNameString,' ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
     ' CurveType, AbsFileName);'];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set a new error message in case of a failure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ErrorMessage = 'File not found or curve invalid!';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
CatchString = ['ErrorFlag = 1;'];

eval(CommandString, CatchString);

if (ErrorFlag)
     set(EditErrorMsgHandle, 'String', ErrorMessage);
     drawnow;
else
     %Close the GUI
     close(gcbf);
end

