function getzerocrvguicall()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%    This is private file of the BDT Demo and is not meant to be called
%    directly by the user.
%
%Author: C. Bassignani, 05-20-98 
%   Copyright 1995-2002 The MathWorks, Inc. 
%$Revision: 1.7 $   $Date: 0000/00/00 00:00:00

%Load the zero curve from disk by calling the LDZEROCRV subroutine
global GZEROCURVE;

ZeroCurve = ldzerocrv;
GZEROCURVE = ZeroCurve;

%If the zero curve is not empty, plot it in the correct axes
if (~isempty(ZeroCurve))
     
     ZeroCurveAxesHandle = findobj('Tag', 'AxesZeroCurve');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
     
     axes(ZeroCurveAxesHandle);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
     
     CurveDates = ZeroCurve.CurveDates;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
     ZeroRates =ZeroCurve.ZeroRates;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
     
     % ZeroCurveLineHandle = findobj(ZeroCurveAxesHandle, 'type', 'line');
     % if (isempty(ZeroCurveLineHandle))
     %     line(CurveDates, ZeroRates);
     % else
     %     set(ZeroCurveLineHandle, 'XData', CurveDates, 'YData', ZeroRates);
     % end
     
     plot(CurveDates, ZeroRates);
     
     set(gca, 'Tag', 'AxesZeroCurve');

     %Scale the plot within the axes so it fits the axes area
     plotscale(0.10);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
     
     set(gca, 'XTick', []);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
     set(gca, 'YTick', []);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%                     **********SUBROUTINES************
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function ZeroCurve = ldzerocrv()
%LDZEROCURVE Load Zero Curve from Disk and Report Errors to GUI

%Set the output variable initially to an empty matrix
ZeroCurve = [];

ErrorFlag = 0;

%Make sure that no error message is displayed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
EditErrorMsgHandle = findobj(gcbf, 'Tag', 'EditZeroCurveErrorMessage');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ErrorMessage = '';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
set(EditErrorMsgHandle, 'String', ErrorMessage);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
drawnow;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Get the file location, name and the name of the bond                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
FileLocHandle = findobj(gcbf, 'Tag', 'EditZeroCurveFileLocation');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
FileLocString = get(FileLocHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
FileNameHandle = findobj(gcbf, 'Tag',  'EditZeroCurveFileName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
FileNameString = get(FileNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
CurveNameHandle = findobj(gcbf, 'Tag', 'EditZeroCurveName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
CurveNameString = get(CurveNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Build the absolute file name from the data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
AbsFileName = strcat(FileLocString, FileNameString);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set the curve type explicity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CurveType = 'zerocurve';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

%Build the main command string                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
CommandString = [ 'ZeroCurve = ldcrvstruct(CurveNameString,' ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
     ' CurveType, AbsFileName);'];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set a new error message in case of a failure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ErrorMessage = 'File not found or curve invalid!';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
CatchString = ['ErrorFlag = 1;'];

%Try to load the specified curve and catch any errors
eval(CommandString, CatchString);

%Check to see if an error occurred and report the results back to the GUI
if (ErrorFlag)
     set(EditErrorMsgHandle, 'String', ErrorMessage);
     drawnow;
else
     %If no error occurred, close the GUI
     close(gcbf);
end

