function greekdem()
%GREEKDEM Financial Expo single option sensitivities.

%       Author(s): C.F.Garvin, 3-07-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.12 $   $Date: 2002/04/14 21:46:01 $

SCR = get(0,'screensize');
fp = get(0,'defaultfigureposition');
Fig = figure('Numbertitle','off','Name','Option Sensitivity - Individual',...
             'position',[fp(1)-25 fp(2)-25 fp(3) fp(4)],...
				 'tag','greekdemo');
set(gcf,'pointer','watch')

% Set colormap to eliminate redundancy
mycolor = hsv;
colormap(mycolor(1:55,:))

% UI Spacing parameters
Top = fp(4);
Right = fp(3);
BWidth = 70;
HBWidth = 500;
BHeight = 20;
if SCR(3) < 1024
  BSpace = 2;
else
  BSpace = 5;
end
BGap = BHeight+BSpace;
CButWidth = 20;
left = Right-(BWidth+BSpace);
bott = Top-BGap;
rdbot = Top - 40;
middleright = Right-(2*BSpace+BWidth);
middleleft = middleright-(HBWidth+CButWidth);
farleft = BSpace;
FWidth = 20;
FLeft = left - 10;
FRight = left + 57;
FHght = 15;

% Build initial display
set(gcf,'pointer','watch')
prange = 10:70;
pspan = length(prange);
j = 1:.5:12;
newj = j(ones(pspan,1),:)'/12;
jspan = ones(length(j),1);
newprange = prange(jspan,:);
pad = ones(size(newj));
c = blsprice(newprange,40*pad,.1*pad,newj,.35*pad);
cc = blsprice(newprange,40*pad,.1*pad,newj,.35*pad);
set(gca,'drawmode','fast')
MSH = mesh(10:70,1:.5:12,c,cc);
set(MSH,'tag','sensmesh')
xlabel('Stock Price ($)')
ylabel('Time (months)')
zlabel('Price')
title('Call Option Sensitivity Measures - Individual')
axis([10 70 1 12 -inf inf])
set(gca,'box','on','position',[.125 .1 .675 .75])

Head(1) = uicontrol('style','text','string','Height',...
                  'position',[left Top-BHeight BWidth BHeight],...
                  'foregroundcolor','black');
Head(2) = uicontrol('style','text','string','Color',...
                  'position',[left-(BSpace+BWidth) Top-BHeight BWidth BHeight],...
                  'horizontalalignment','right',...
                  'foregroundcolor','black');
set(Head,'units','norm')
% Radio buttons control height measure
HStrings = str2mat('Price','Delta','Gamma','Rho','Theta','Vega','Lambda');
for i = 1:7
  g(i) = uicontrol('style','radio','string',HStrings(i,:),'max',12,...
    'pos',[left rdbot-(i-1)*BGap BWidth BHeight],'horizontalalignment','left'...
               );
end
set(g,'units','normal')
set(g(1),'value',12)

% Sliders and additional uicontrols
h(1) = uicontrol('style','text','position',[left 174/384*fp(4) BWidth BHeight],...
          'foregroundcolor','black',...
          'string','Strike');
h(2) = uicontrol('style','text','position',[left 108/384*fp(4) BWidth BHeight],...
          'foregroundcolor','black',...
          'string','Return');
h(3) = uicontrol('style','text','position',[left 42/384*fp(4) BWidth BHeight],...
          'foregroundcolor','black',...
          'string','Volatility ');
set(h,'units','normal')

slidercall = ['set(gcf,''pointer'',''watch''),'...
      'drawnow,'...
      'Kids = get(gcf,''children'');'...
      'if any(findobj(Kids,''value'',12)),'...
        'f = [''bls'',lower(get(findobj(Kids,''value'',12),''string''))];'...
        'fc = [''bls'',get(findobj(Kids,''value'',3),''tag'')];'...
        'x = get(findobj(Kids,''string'',''strikeslider''),''value'');'...
        'r = get(findobj(Kids,''string'',''rateslider''),''value'');'...
        'sig = get(findobj(Kids,''string'',''volslider''),''value'');'...
        'prange = 10:70;'...
        'pspan = length(prange);'...
        'j = 1:.5:12;'...
        'newj = j(ones(pspan,1),:)''/12;'...
        'jspan = ones(length(j),1);'...
        'newprange = prange(jspan,:);'...
        'pad = ones(size(newj));'...
        'eval([''c='',lower(f),''(newprange,x*pad,r*pad,newj,sig*pad);'']),'...
        'eval([''cc='',lower(fc),''(newprange,x*pad,r*pad,newj,sig*pad);'']),'...
        'set(gca,''drawmode'',''fast''),'...
        'MSH = mesh(10:70,1:.5:12,c(1:23,:),cc(1:23,:));'...
        'set(MSH,''tag'',''sensmesh''),'...
        'xlabel(''Stock Price ($)''),'...
        'title(''Call Option Sensitivity Measures - Individual''),'...
        'ylabel(''Time (months)''),',...
        'zlabel(get(findobj(gcf,''value'',12),''string'')),'...
        'axis([10 70 1 12 -inf inf]),'...
        'set(gca,''box'',''on'',''position'',[.125 .25 .675 .6]),',...
        'colorbar,set(gcf,''nextplot'',''add''),'...
        'colorlab = findobj(gcf,''value'',3);'...
        'cax = findobj(gcf,''tag'',''colorax'');'...
        'set(cax,''ytick'',[]),'...
        'set(get(cax,''xlabel''),''string'',get(colorlab,''tag'')),'...
        'set(gcf,''pointer'',''arrow''),'...
      'else,'...
        'set(gcf,''pointer'',''arrow''),'...
        'errordlg(''Choose a sensitivity measure from list'');,'...
    'set(findobj(gcf,''type'',''uicontrol''),''backgroundcolor'',''white''),'...
      'end;'...
      ];
             
s(1) = uicontrol('style','text','position',[left 134/384*fp(4) BWidth BHeight],...
               'userdata','striketext',...
               'foregroundcolor','black',...
               'string','40','horizontalalignment','center');
s(2) = uicontrol('style','slider','position',[left 154/384*fp(4) BWidth BHeight],...
             'string','strikeslider',...
             'horizontalalignment','center','value',40,...
             'min',20,'max',60,...
             'tag','striketext',...
             'callback',[...
             'set(findobj(gcf,''userdata'',''striketext''),''string'','...
             'num2str(get(gco,''value''))),'...
             ]);
s(3) = uicontrol('style','text','position',[left 68/384*fp(4) BWidth BHeight],...
                  'userdata','ratetext',...
                  'foregroundcolor','black',...
                  'string','0.12','horizontalalignment','center');
s(4) = uicontrol('style','slider','position',[left 88/384*fp(4) BWidth BHeight],...
                 'string','rateslider',...
                 'horizontalalignment','center','value',.12,...
                 'min',.03,'max',.30,...
                 'tag','ratetext',...
                 'callback',[...
                 'set(gco,''value'',min(get(gco,''value''),.2999999999999)),'...
                 'set(findobj(gcf,''userdata'',''ratetext''),''string'','...
                 'num2str(get(gco,''value''))),'...
                 ]);
s(5) = uicontrol('style','text','position',[left 2/384*fp(4) BWidth BHeight],...
                  'userdata','voltext',...
                 'foregroundcolor','black',...
                 'string','0.30','horizontalalignment','center');
s(6) = uicontrol('style','slider','position',[left 22/384*fp(4) BWidth BHeight],...
                 'string','volslider',...
                 'horizontalalignment','center','value',.3,...
                 'min',.03,'max',.80,...
                 'tag','voltext',...
                 'callback',[...
                 'set(findobj(gcf,''userdata'',''voltext''),''string'','...
                 'num2str(get(gco,''value''))),'...
                 ]);
s(7) = uicontrol('style','text','position',[FLeft 174/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','20','horizontalalignment','center');
s(8) = uicontrol('style','text','position',[FRight 174/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','60','horizontalalignment','center');
s(9) = uicontrol('style','text','position',[FLeft 42/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','.03','horizontalalignment','center');
s(10) = uicontrol('style','text','position',[FRight 42/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','.80','horizontalalignment','center');
s(11) = uicontrol('style','text','position',[FLeft 108/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','.03','horizontalalignment','center');
s(12) = uicontrol('style','text','position',[FRight 108/384*fp(4) FWidth FHght],...
               'foregroundcolor','black',...
               'string','.30','horizontalalignment','center');
set(s,'units','normal')

for i = 1:7
 set(g(i),'userdata',g(:,[1:(i-1),(i+1):7]))
end

% Radio buttons' callback
set(g,'callback',['set(gcf,''pointer'',''watch''),',...
                  'zbut = findobj(gcf,''value'',12);'...
                  'set(zbut,''value'',0),'...
                  'set(gco,''value'',12),'...
                  'set(gcf,''pointer'',''arrow''),'...
                  ]);

out1 = str2mat(...
' In this four-dimensional graph, MATLAB and its Financial and Statistics ',...
' Toolboxes depict the sensitivity of a single European call option using ',...
' various Black-Scholes measures.  Two axes of the graph are preset:  the ',...
' price of the underlying asset ranges from 10 to 70 dollars on the X-axis,',...
' and the time to maturity ranges from 1 to 12 months on the Y-axis.',...
'.',...
' The default graph shows the current option price on both the Z-axis ',...
' (height) and as the color scheme.  The option strike price is 40, the ',...
' risk-free rate of return is 12%, and volatility (sigma) of the ',...
' underlying stock price is 30%.');
out2 = str2mat(...
'.',...
' You can examine other option sensitivities in two ways:',...
'.',...
' 1. Choose which of the sensitivities to show on the Z-axis (height) and ',...
'    as the color scheme.  To select the Z axis, click on the button in ',...
'    the Height column next to the sensitivity you want.  To select the ',...
'    color scheme, click on the button in the Color column next to the ',...
'    desired sensitivity.',...
'.',...
'    The sensitivities you can select are:');
out3 = str2mat(...
'.',...
'    Price:  Current value of the call option.',...
'.',...
'    Delta:  Sensitivity of option''s value to price of the underlying stock.',...
'.',...
'    Gamma:  Sensitivity of delta to price of the underlying stock.',...
'.',...
'    Rho:    Sensitivity of option''s value to the risk-free rate of return.',...
'.',...
'    Theta:  Sensitivity of option''s value to time remaining to maturity.');
out4 = str2mat(...
'.',...
'    Vega:   Sensitivity of option''s value to the volatility (sigma) ',...
'            of the underlying stock.',...
'.',...
'    Lambda: Percentage of change in the option''s value per percentage ',...
'            change in the price of the underlying stock (elasticity).',...
'.',...
' 2. Change the Strike (exercise) price of the option, the risk-free rate ',...
'    of Return, and the Volatility (sigma) of the underlying stock price.  ',...
'    Click the left or right arrow buttons for incremental changes, or ');
out5 = str2mat(...
'    drag the slider for larger changes.',...
'.',...
' Click the Run button to see the new graph after you change parameters.',...
'.',...
' Click the Movie button to see a five-dimensional graph:  stock price vs. ',...
' time vs. gamma vs. theta, as volatility ranges from 0.10 to 0.90.',...
'.',...
' ');
HelpDlgString = str2mat(out1,out2,out3,out4,out5);

u(1)=uicontrol('position',[farleft bott BWidth*0.75 BHeight],'string','Run',...
               'callback',slidercall);
u(2)=uicontrol('position',[farleft bott-BGap BWidth*0.75 BHeight],'string','Help',...
               'userdata',HelpDlgString,...
					'callback','helpwin(get(gco,''userdata''),''Option Sensitivity Help'');');
u(3) = uicontrol('position',[farleft bott-2*BGap BWidth*0.75 BHeight],...
        'string','Movie',...
        'callback',['set(gcf,''pointer'',''watch''),'...
                    'set(gcf,''menubar'',''none''),'...
                    'set(findobj(gcf,''value'',12),''value'',0),'...
                    'set(findobj(gcf,''value'',3),''value'',0),'...
                    'set(findobj(findobj(gcf,''type'',''uicontrol''),''string'',''Gamma ''),''value'',12),'...
                    'set(findobj(gcf,''tag'',''Theta ''),''value'',3),'...
		              'hiddenfig = figure(''visible'',''off'',''tag'',''hiddenfigure'');'...
		              'figure(findobj(''tag'',''greekdemo'')),'...
						  'set(gca,''tag'',''meshplot''),'...
		              'co = copyobj([gca; findobj(gcf,''tag'',''colorax'')], hiddenfig);'...
                    'set(gca,''xcolor'',''k'',''ycolor'',''k'',''zcolor'',''k''),'...
                    'set(findobj(gcf,''tag'',''sensmesh''),''edgecolor'',''none''),'...
                    'cax = findobj(gcf,''tag'',''colorax'');'...
                    'set(get(cax,''xlabel''),''string'',''Theta''),'...
                    'load gammamov,movie(gamMov,-3),'...
                    'set(gcf,''pointer'',''arrow''),'...
		              'set(findobj(gcf,''tag'',''resetdemobutton''),''enable'',''on'')'],...
	     'tag','moviebutton');
u(4) = uicontrol('enable','off','position',[farleft bott-3.75*BGap BWidth*0.5 BHeight*2],...
                 'string','Reset',...
                 'callback',['delete(findobj(gcf,''tag'',''meshplot''));'...
                             'delete(findobj(gcf,''tag'',''colorax''));'...
                             'co = copyobj(get(findobj(''tag'',''hiddenfigure''),''children''), gcf);'...
					              'set(gcf,''menubar'', ''figure''),'...
					              'set(findobj(gcf,''tag'',''resetdemobutton''),''enable'',''off''),'...
									  'delete(findobj(''tag'',''hiddenfigure''));'],...
					  'tag','resetdemobutton');
set(u,'units','normal')

% Radio buttons that control color measure
for i = 1:7
  Cbut(i) = uicontrol('style','radio','max',3,...
          'tag',HStrings(i,:),...
          'value',0,...
          'pos',[left-(BSpace+CButWidth) rdbot-(i-1)*BGap CButWidth BHeight],...
          'horizontalalignment','left'...
           );
end
for i = 1:7
 set(Cbut(i),'userdata',Cbut(:,[1:(i-1),(i+1):7]))
end
set(Cbut(1),'value',3)
set(Cbut,'units','normal')

% Color Radio Button callback
set(Cbut,'callback',['set(gcf,''pointer'',''watch''),',...
                     'cbut = findobj(gcf,''value'',3);'...
                     'set(cbut,''value'',0),'...
                     'set(gco,''value'',3),'...
                     'set(gcf,''pointer'',''arrow''),'...
                     ]);
set(gcf,'pointer','arrow')

% Display colorbar
colorax = colorbar('horiz');
set(get(colorax,'Xlabel'),'string',get(findobj(gcf,'value',3),'tag'))
set(colorax,'ytick',[],'tag','colorax')
set(gcf,'nextplot','add')
TXT = findobj(gcf,'style','text');
set(TXT,'backgroundcolor',get(gcf,'color'))
set(gcf,'pointer','arrow')
