function VolatilityCurve = ldvolatilitycrv()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%    This is private file of the BDT Demo and is not meant to be called
%    directly by the user.
%
%Author: C. Bassignani, 05-20-98 
%   Copyright 1995-2002 The MathWorks, Inc. 
%$Revision: 1.5 $   $Date: 0000/00/00 00:00:00


%Set the output variable initially to an empty matrix
VolatilityCurve = [];

%Make sure that no error message is displayed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
EditErrorMsgHandle = findobj(gcbf, 'Tag', 'EditVolatilityCurveErrorMessage');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
ErrorMessage = '';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
set(EditErrorMsgHandle, 'String', ErrorMessage);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Get the file location, name and the name of the bond                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
FileLocHandle = findobj(gcbf, 'Tag', 'EditVolatilityCurveFileLocation');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
FileLocString = get(FileLocHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
FileNameHandle = findobj(gcbf, 'Tag',  'EditVolatilityCurveFileName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
FileNameString = get(FileNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
CurveNameHandle = findobj(gcbf, 'Tag', 'EditVolatilityCurveName');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
CurveNameString = get(CurveNameHandle, 'String');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Build the absolute file name from the data                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
AbsFileName = strcat(FileLocString, FileNameString);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set the bond type explicity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CurveType = 'volatilitycurve';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

%Build the main command string                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
CommandString = [ 'VolatilityCurve = ldcrvstruct(CurveNameString,' ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
     ' CurveType, AbsFileName);'];                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
%Set a new error message in case of a failure                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
ErrorMessage = 'File not found or curve invalid!';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
CatchString = ['ErrorFlag = 1;'];

eval(CommandString, CatchString);

ErrorFlag = 0;
if (ErrorFlag)
     set(EditErrorMsgHandle, 'String', ErrorMessage);
else
     %Close the GUI
     close(gcbf);
end
