function montehel()
%MONTEHEL Help for Monte Carlo Simulation (MONTECAR).

%       Author(s): C.F. Garvin, 3-10-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.8 $   $Date: 2002/04/14 21:43:14 $


help1 = str2mat(...
' This demonstration uses SIMULINK building blocks to model a business ',...
' that builds and sells electric cars, to determine if it''s a good ',...
' investment.  The variables that influence the project are market size, ',...
' market share, unit price, unit cost, fixed cost, the opportunity cost of ',...
' capital, and the initial investment.',...
'.',...
' The initial investment is $150 Million ($1.5 x 10^8).  The function ',...
' NORMRND from the Statistics Toolbox generates 10,000 random numbers from ',...
' the normal distribution for each project variable.  The simulation runs ',...
' for 10 years and produces a graph showing the distribution of net ');

help2 = str2mat(...
' present values for each of 10,000 10-year cash flow totals.',...
'.',...
'    Double click the Start box to run the simulation.',...
'.',...
' The graph shows that the likely outcomes will be less than the initial ',...
' investment, so the investment would be unwise.  Assuming the business ',...
' model is valid, SIMULINK has just saved you tens of millions of dollars!',...
'.',...
' If you re-run the simulation, you will get a slightly different ',...
' distribution; but the investment implications will be the same.');

help3 = str2mat(...
'.',...
' Click the Close button in the graphic window to close it.',...
'.',...
' Pull down the File menu and click Close to return to the Main Map.');
helptext = str2mat(help1,help2,help3);
helpwin(helptext,'Business Model Help');
