function oneopt(Input1)
%ONEOPT Binomial Tree and Black-Scholes demonstration for equity options.
%   Constructs and views Cox-Ross-Rubinstein binomial trees, and views the
%   price and hedge parameters of a single American or European option.
%
%   oneopt(0) : invoke binomial tree construction
%   oneopt(1) : invoke price and hedge parameter viewing
%
%   See also BLSDEMOS, PAYOFF, SMILE.
%

%
% Created by Greg Portmann (May 1997)
%


%       Copyright 1995-2002 The MathWorks, Inc.  
%       $Revision: 1.12 $   $Date: 2002/04/14 21:46:57 $ 

% Calls:  oneoptfn, oneopth
% Called by:  

if nargin < 1
   Input1 = 0;
end

%Turn WARNINGS OFF.
swarn = warning('off');

%[.4 .5 .7]
%load colormap1                   
%	'Colormap',mat0, ...
%	'PointerShapeCData',mat1, ...
a = figure('Units','normalized', ...
   'Color',[.8 .8 .8], ...
   'Interruptible','off', ...
	'MenuBar','none', ...
	'Name','Option Valuation (Black-Scholes Formula)', ...
	'NumberTitle','off', ...
	'Position',[0.3 0.3 0.4 0.62], ...
   'ResizeFcn',['oneoptfn(''Resize'');', ...
                'if get(findobj(gcbf,''Tag'',''RadioTree''),''Value'') == 1 ;', ...
                '  oneoptfn(''ReDrawTree'');', ...
                'end;'], ...
   'Visible','off', ...
	'Tag','Black/Scholes Diagram');

b = axes('Parent',a, ...
	'Units','points', ...
	'Position',[43.2 122.8 298.8 158], ...
   'Tag','Axes1', ...
   'Interruptible','off', ...
	'Visible','off');

set(a,'Units','Points');
FigSize = get(a,'position');
FigWidth  = FigSize(3);
FigHeight = FigSize(4);
SliderWidth = 12;  % Points

h_slider_horizontal = uicontrol(...
   'Style','slider', ...
   'units','points', ...
   'Position',[SliderWidth  0 FigWidth-2*SliderWidth  SliderWidth], ...
   'Callback', 'oneoptfn(''ReDrawTree'');', ......
   'Userdata', [], ...
   'Tag','SliderHorizontal');


h_slider_vertical = uicontrol(...
   'Style','slider', ...
   'units','points', ...
   'Position',[FigWidth-SliderWidth  SliderWidth SliderWidth  FigHeight-SliderWidth], ...
   'Callback', 'oneoptfn(''ReDrawTree'');', ......
   'Userdata', [], ...
   'Tag','SliderVertical');



% Tree independent variable 1
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor','b', ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','', ...
   'Position',[0 FigHeight-20 85 15], ...
	'FontSize', 9, ...
   'String',str2mat('Symbols','Asset Price','Option Value'), ...
	'Style','popupmenu', ...
	'Tag','PopupTree1', ...
   'Value',1, ...
	'Visible','on');
% Tree independent variable 2
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor','r', ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','', ...
   'Interruptible','off', ...
   'Position',[0 FigHeight-25 85 15], ...
	'FontSize', 9, ...
   'String',str2mat('Symbols','Asset Price','Option Value'), ...
	'Style','popupmenu', ...
	'Tag','PopupTree2', ...
	'Value',2, ...
	'Visible','on');
% Tree text u,d,p
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ForegroundColor','k', ...
	'HorizontalAlignment','left', ...
   'Position',[0 FigHeight-45 70 15], ...
	'String',' ', ...
	'Style','text', ...
	'Tag','TextTree');



% Frame
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'Interruptible','off', ...
	'Position',[6.5 1.5 155+42 81.75+22+1], ...
	'Style','frame', ...
	'Tag','Frame1');

% Text strings
height = 15.75;
offset = 4.5;
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset+5*height 105 12.75], ...
	'FontSize', 9, ...
	'String','Current Asset Price', ...
	'Style','text', ...
	'Tag','TextAssetPrice');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset+4*height 105 12.75], ...
	'FontSize', 9, ...
	'String','Annualized Payout Return', ...
	'Style','text', ...
	'Tag','TextAssetReturn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset+3*height 105 12.75], ...
	'FontSize', 9, ...
	'String','Annualized Riskless Return', ...
	'Style','text', ...
	'Tag','TextRisklessReturn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset+2*height 105 12.75], ...
	'FontSize', 9, ...
	'String','Years-to-Expiration', ...
	'Style','text', ...
	'Tag','TextExpiration');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset+height 105 12.75], ...
	'FontSize', 9, ...
	'String','Annualized Volatility', ...
	'Style','text', ...
   'Tag','TextVolatility');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[8.5 offset 105 12.75], ...
	'FontSize', 9, ...
	'String','Strike Price', ...
	'Style','text', ...
   'Tag','TextStrikePrice');

% Header strings for edit text
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[118 offset+6*height-5 45 11], ...
	'FontSize', 9, ...
	'String','Value', ...
	'Style','text', ...
   'Tag','TextCommonInputs');


% Edit texts
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextAssetPrice''),''string'',''100'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+5*height 45 12.75], ...
	'FontSize', 9, ...
	'String','100', ...
	'Style','edit', ...
   'Tag','EditTextAssetPrice');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextAssetReturn''),''string'',''1.00'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+4*height 45 12.75], ...
	'FontSize', 9, ...
	'String','1.00', ...
	'Style','edit', ...
   'Tag','EditTextAssetReturn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextRisklessReturn''),''string'',''1.15'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+3*height 45 12.75], ...
	'FontSize', 9, ...
	'String','1.15', ...
	'Style','edit', ...
   'Tag','EditTextRisklessReturn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextExpiration''),''string'',''1.00'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+2*height 45 12.75], ...
	'FontSize', 9, ...
	'String','1.00', ...
	'Style','edit', ...
   'Tag','EditTextExpiration');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextVolatility''),''string'',''.30'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+1*height 45 12.75], ...
	'FontSize', 9, ...
	'String','.30', ...
	'Style','edit', ...
	'Tag','EditTextVolatility');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextStrikePrice''),''string'',''100'');', ...
   'Interruptible','off', ...
	'Position',[118 offset+0*height 45 12.75], ...
	'FontSize', 9, ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditTextStrikePrice');

% Header strings for +-
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[165 offset+6*height-5 35 11], ...
	'FontSize', 9, ...
	'String','Range', ...
	'Style','text', ...
   'Tag','TextRange');

% +- Input edit texts
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextAssetPriceRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+5*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
   'Tag','EditTextAssetPriceRange');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextAssetReturnRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+4*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
   'Tag','EditTextAssetReturnRange');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextRisklessReturnRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+3*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
   'Tag','EditTextRisklessReturnRange');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextExpirationRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+2*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
   'Tag','EditTextExpirationRange');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextVolatilityRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+1*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
	'Tag','EditTextVolatilityRange');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''EditTextStrikePriceRange''),''string'',''10%'');', ...
   'Interruptible','off', ...
	'Position',[165 offset+0*height 35 12.75], ...
	'FontSize', 9, ...
	'Style','edit', ...
	'Tag','EditTextStrikePriceRange');


% Hedging diagram
xoffset = 16;
% Dependent Variable
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','', ...
   'Interruptible','off', ...
	'Position',[30-xoffset 111 75 15], ...
	'FontSize', 9, ...
   'String',str2mat('Value','Delta','Gamma','Theta','Vega','Rho','Omega'), ...
	'Style','popupmenu', ...
	'Tag','PopupVar3', ...
	'Value',1, ...
	'Visible','on');
% Independent variable 1
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','', ...
   'Interruptible','off', ...
   'Position',[138-xoffset 111 85 15], ...
	'FontSize', 9, ...
   'String',str2mat('Asset Price','Payout Return','Riskless Return','Years-to-Expiration','Volatility','Strike Price'), ...
	'Style','popupmenu', ...
	'Tag','PopupVar1', ...
   'Value',1, ...
	'Visible','on');
% Independent variable 2
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
	'CreateFcn','', ...
   'Interruptible','off', ...
	'Position',[236-xoffset 111 85 15], ...
	'FontSize', 9, ...
   'String',str2mat('Asset Price','Payout Return','Riskless Return','Years-to-Expiration','Volatility','Strike Price','None'), ...
	'Style','popupmenu', ...
	'Tag','PopupVar2', ...
	'Value',7, ...
	'Visible','on');
% Hedging text
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
   'FontSize',10, ...
   'FontUnits','pixels', ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[110-xoffset 111 25 17], ...
	'String','= f (', ...
	'Style','text', ...
	'Tag','HedgingText1', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'FontSize',10, ...
   'FontUnits','pixels', ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[226-xoffset 111 10 18], ...
	'String',',', ...
	'Style','text', ...
	'Tag','HedgingText2', ...
	'Visible','on');
b = uicontrol('Parent',a, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'FontSize',10, ...
   'FontUnits','pixels', ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[321-xoffset 111 10 17], ...
	'String',')', ...
	'Style','text', ...
	'Tag','HedgingText3', ...
	'Visible','on');


% Option type radio buttons
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
   'Interruptible','off', ...
	'Position',[208 59-1 52+2 47+1], ...
	'Style','frame', ...
	'Tag','FramePutCall');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Callback', ['set(findobj(gcbf,''Tag'',''RadioCall''),''Value'',1);', ...
      'set(findobj(gcbf,''Tag'',''RadioPut''),''Value'',0);', ...
      'oneoptfn(''PlotPortfolio'');'], ...
   'Units','points', ...
	'Position',[210 74 50 15], ...
	'FontSize', 9, ...
	'String','Call', ...
   'Style','radiobutton', ...
   'Value',1, ...
	'Tag','RadioCall');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Callback', ['set(findobj(gcbf,''Tag'',''RadioCall''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''RadioPut''),''Value'',1);', ...
                'oneoptfn(''PlotPortfolio'');'], ...
	'Units','points', ...
	'Position',[210 59 50 15], ...
	'FontSize', 9, ...
	'String','Put', ...
	'Style','radiobutton', ...
   'Value',0, ...
	'Tag','RadioPut');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
	'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[210 90 50 15], ...
	'FontSize', 9, ...
	'String','Option Type', ...
	'Style','text', ...
	'Tag','TextCallPut');

% Valuation radio buttons 
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
   'Interruptible','off', ...
	'Position',[270 59-1 88 47+1], ...
	'Style','frame', ...
	'Tag','FrameMethod');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
   'Callback', ['set(findobj(gcbf,''Tag'',''RadioBLS''),''Value'',1);', ...
                'set(findobj(gcbf,''Tag'',''RadioBIN''),''Value'',0);', ...
                'set(gcbf,''Name'',''Option Valuation (Black-Scholes Formula)'');', ...
                'set(findobj(gcbf,''Tag'',''RadioGraph''),''Value'',1);', ...
                'set(findobj(gcbf,''Tag'',''RadioGraph''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''RadioTree''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''RadioTree''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''RadioEuro''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''RadioEuro''),''Value'',1);', ...
                'set(findobj(gcbf,''Tag'',''RadioAmerican''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''RadioAmerican''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''TextTreeSize''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''EditTextTreeSize''),''Enable'',''off'');', ...
                'set(findobj(gcbf,''Tag'',''TextTreeText''),''Enable'',''off'');', ...
                'oneoptfn(''Setup Graph'');', ...
                'oneoptfn(''PlotPortfolio'');'], ...
   'Units','points', ...
	'Position',[272 74 80 15], ...
	'FontSize', 9, ...
	'String','Black-Scholes', ...
   'Style','radiobutton', ...
   'Value',1, ...
	'Tag','RadioBLS');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Callback', ['set(findobj(gcbf,''Tag'',''RadioBLS''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''RadioBIN''),''Value'',1);', ...
                'set(gcbf,''Name'',''Option Valuation (Binomial Tree)'');', ...
                'set(findobj(gcbf,''Tag'',''RadioGraph''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''RadioTree''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''RadioEuro''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''RadioAmerican''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''TextTreeSize''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''EditTextTreeSize''),''Enable'',''on'');', ...
                'set(findobj(gcbf,''Tag'',''TextTreeText''),''Enable'',''on'');', ...
                'oneoptfn(''PlotPortfolio'');'], ...
	'Units','points', ...
	'Position',[272 59 80 15], ...
	'FontSize', 9, ...
	'String','Binomial Tree', ...
	'Style','radiobutton', ...
   'Value',0, ...
	'Tag','RadioBIN');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
	'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[274 90 80 15], ...
	'FontSize', 9, ...
	'String','Valuation Method', ...
	'Style','text', ...
	'Tag','TextMethod');


% Display radio buttons
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[.8 .8 .8], ...
   'Interruptible','off', ...
	'Position',[209-1 1.5 150 54], ...
	'Style','frame', ...
	'Tag','FrameTree');


b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
   'Callback', ['set(findobj(gcbf,''Tag'',''RadioGraph''),''Value'',1);', ...
                'set(findobj(gcbf,''Tag'',''RadioTree''),''Value'',0);', ...
                'oneoptfn(''Setup Graph'');', ...
                'oneoptfn(''PlotPortfolio'');'], ...
   'Enable','off', ...
   'Units','points', ...
	'Position',[209 20+11 50 15], ...
	'FontSize', 9, ...
	'String','Graph', ...
   'Style','radiobutton', ...
   'Value',1, ...
	'Tag','RadioGraph');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Callback', ['set(findobj(gcbf,''Tag'',''RadioGraph''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''RadioTree''),''Value'',1);', ...
                'oneoptfn(''Setup Tree'');', ...
                'oneoptfn(''PlotPortfolio'');'], ...
   'Enable','off', ...
	'Units','points', ...
	'Position',[209 20 50 12], ...
	'FontSize', 9, ...
	'String','Tree', ...
	'Style','radiobutton', ...
   'Value',0, ...
	'Tag','RadioTree');

% Euro/American radio buttons
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
   'Callback', ['set(findobj(gcbf,''Tag'',''RadioEuro''),''Value'',1);', ...
                'set(findobj(gcbf,''Tag'',''RadioAmerican''),''Value'',0);', ...
                'oneoptfn(''PlotPortfolio'');'], ...
   'Enable','off', ...
   'Units','points', ...
	'Position',[275 20+11 80 15], ...
	'FontSize', 9, ...
	'String','European', ...
   'Style','radiobutton', ...
   'Value',1, ...
	'Tag','RadioEuro');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[.8 .8 .8], ...
	'Callback', ['set(findobj(gcbf,''Tag'',''RadioEuro''),''Value'',0);', ...
                'set(findobj(gcbf,''Tag'',''RadioAmerican''),''Value'',1);', ...
                'oneoptfn(''PlotPortfolio'');'], ...
   'Enable','off', ...
	'Units','points', ...
	'Position',[275 20 80 12], ...
	'FontSize', 9, ...
	'String','American', ...
	'Style','radiobutton', ...
   'Value',0, ...
	'Tag','RadioAmerican');

% Tree size
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'Enable','off', ...
	'HorizontalAlignment','center', ...
   'Interruptible','off', ...
	'Position',[230 44 99 10], ...
	'FontSize', 9, ...
	'String','Binomial Inputs', ...
	'Style','text', ...
   'Tag','TextTreeText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'Enable','off', ...
	'HorizontalAlignment','right', ...
   'Interruptible','off', ...
	'Position',[210 offset 40 12], ...
	'FontSize', 9, ...
	'String','Tree Size', ...
	'Style','text', ...
   'Tag','TextTreeSize');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','oneoptfn(''PlotPortfolio'');', ...
   'Enable','off', ...
   'Interruptible','off', ...
	'Position',[210+45 offset 40 13], ...
	'FontSize', 9, ...
	'String','5', ...
	'Style','edit', ...
	'Tag','EditTextTreeSize');


% File menu
b = uimenu('Parent',a, ...
	'Label','&File', ...
   'Tag','FileMenu');
c = uimenu('Parent',b, ...
	'Callback','print -dsetup', ...
	'Label','Print Setup', ...
	'Tag','FileMenu3');
c = uimenu('Parent',b, ...
	'Callback','printfn(gcbf);', ...
	'Label','Print', ...
   'Tag','FileMenu4');
c = uimenu('Parent',b, ...
	'Callback',';', ...
	'Label','Open', ...
	'Separator','on', ...
   'Tag','FileOpen');
d = uimenu('Parent',c, ...
	'Callback','oneopt(1);', ...
	'Label','Black-Scholes Formula', ...
	'Separator','off', ...
   'Tag','FileLaunchBLS');
d = uimenu('Parent',c, ...
	'Callback','oneopt(0);', ...
	'Label','Binomial Trees', ...
	'Separator','off', ...
   'Tag','FileLaunchTree');
d = uimenu('Parent',c, ...
	'Callback','payoff;', ...
	'Label','Profit/Loss Diagram', ...
	'Separator','off', ...
   'Tag','FileLaunchPayoff');
d = uimenu('Parent',c, ...
	'Callback','payoff(''Prob'');', ...
	'Label','Probability Function', ...
	'Separator','off', ...
   'Tag','FileLaunchProb');
d = uimenu('Parent',c, ...
	'Callback','payoff(''CDF'');', ...
	'Label','Cumulative Distribution Function', ...
	'Separator','off', ...
   'Tag','FileLaunchCDF');
d = uimenu('Parent',c, ...
	'Callback','payoff(''Hedging'');', ...
	'Label','Hedging Diagram', ...
	'Separator','off', ...
   'Tag','FileLaunchHedging');
d = uimenu('Parent',c, ...
	'Callback','smile;', ...
	'Label','Implied Volatility Smiles', ...
	'Separator','off', ...
   'Tag','FileLaunchSmiles');
c = uimenu('Parent',b, ...
	'Callback','close(gcbf);', ...
	'Label','Close', ...
	'Separator','on', ...
   'Tag','Closeoneopt');



% Axis menu
b = uimenu('Parent',a, ...
	'Label','&Axis', ...
   'Tag','MenuAxis');

CallbackAxisTool = [... 
'if strcmp(lower(get(findobj(gcbf,''Tag'',''MenuAxisTool''),''Checked'')),''on'')==1;', ...
'  set(findobj(gcbf,''Tag'',''MenuAxisTool''),''Checked'',''off'');', ...
'  close(get(findobj(gcbf,''Tag'',''MenuAxisTool''),''Userdata''));', ...
'else;', ...
'  set(findobj(gcbf,''Tag'',''MenuAxisTool''),''Checked'',''on'');', ...
'  set(findobj(gcbf,''Tag'',''MenuAxisTool''),''Userdata'',axisgui(gca));', ...
'end;', ...
];


% Userdata contains the handle for the resize figure
c = uimenu('Parent',b, ...
	'Callback', CallbackAxisTool, ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''MenuAxisTool''),''Checked'',''off'');', ...
   'DeleteFcn','if strcmp(lower(get(findobj(gcbf,''Tag'',''MenuAxisTool''),''Checked'')),''on'')==1;FigHandle=get(findobj(gcbf,''Tag'',''MenuAxisTool''),''Userdata'');close(FigHandle);end;', ...
   'Label','Axis Tool', ...
   'Userdata', [], ...
   'Tag','MenuAxisTool');

c = uimenu('Parent',b, ...
	'Callback','grid on;set(findobj(gcbf,''Tag'',''MenuGridOn''),''Checked'',''on'');set(findobj(gcbf,''Tag'',''MenuGridOff''),''Checked'',''off'');', ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''MenuGridOn''),''Checked'',''off'');', ...
	'Label','Grid On', ...
	'Separator','on', ...
	'Tag','MenuGridOn');
c = uimenu('Parent',b, ...
	'Callback','grid off;set(findobj(gcbf,''Tag'',''MenuGridOn''),''Checked'',''off'');set(findobj(gcbf,''Tag'',''MenuGridOff''),''Checked'',''on'');', ...
	'CreateFcn','grid off;set(findobj(gcbf,''Tag'',''MenuGridOff''),''Checked'',''on'');', ...
	'Label','Grid Off', ...
   'Tag','MenuGridOff');

b = uimenu('Parent',a, ...
	'Label','&Help', ...
	'Tag','HelpMenu');
c = uimenu('Parent',b, ...
	'CreateFcn','set(findobj(gcbf,''Tag'',''HelpMenu1''),''Checked'',''off'');', ...
	'Callback','if strcmp(lower(get(findobj(gcbf,''Tag'',''HelpMenu1''),''Checked'')),''off'')==1;set(findobj(gcbf,''Tag'',''HelpMenu1''),''Checked'',''on'');set(findobj(gcbf,''Tag'',''HelpMenu''),''Userdata'',oneopth);else;set(findobj(gcbf,''Tag'',''HelpMenu1''),''Checked'',''off'');close(get(findobj(gcbf,''Tag'',''HelpMenu''),''Userdata''));end', ...
	'Label','Help', ...
	'Tag','HelpMenu1');


if Input1
   set(findobj(a,'Tag','RadioGraph'),'Value',1);
   set(findobj(a,'Tag','RadioTree'),'Value',0);
   oneoptfn('Setup Graph');
   oneoptfn('Initialize');
   oneoptfn('PlotPortfolio');
else
   set(findobj(a,'Tag','RadioGraph'),'Value',0);
   drawnow;
   set(findobj(a,'Tag','RadioTree'),'Value',1);
      
   set(findobj(a,'Tag','RadioBLS'),'Value',0);
   set(findobj(a,'Tag','RadioBIN'),'Value',1);
   set(a,'Name','Option Valuation (Binomial Tree)');
   set(findobj(a,'Tag','RadioGraph'),'Enable','on');
   set(findobj(a,'Tag','RadioTree'),'Enable','on');
   set(findobj(a,'Tag','RadioEuro'),'Enable','on');
   set(findobj(a,'Tag','RadioAmerican'),'Enable','on');
   set(findobj(a,'Tag','TextTreeSize'),'Enable','on');
   set(findobj(a,'Tag','EditTextTreeSize'),'Enable','on');
   set(findobj(a,'Tag','TextTreeText'),'Enable','on');
   
   oneoptfn('Setup Tree');   
   oneoptfn('Initialize');
   oneoptfn('PlotPortfolio');
end
