function opthelp()
%OPTHELP Help for Option Valuation Model in the Financial Expo.

%       Author(s): C.F. Garvin, 3-10-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.7 $   $Date: 2002/04/14 21:43:33 $


out1 = str2mat(...
' This demonstration shows how you can create and run mathematical models ',...
' using SIMULINK building blocks.  It uses Monte Carlo methods to value',...
' an option by modeling and simulating the path of a stock''s price over time.',...
'.',...
'    Double click the Start box to run the simulation.',...
'.',...
' A MATLAB graphic window shows the price path of each random walk as a ',...
' different colored line.  The simulation also returns and displays four ',...
' variables in the MATLAB workspace:');
out2 = str2mat(...
'.',...
'    fovalues = future stock price - exercise price',...
'    povalues = present value of fovalues',...
'    standev =  standard deviation of povalues',...
'    average =  mean of povalues',...
'.',...
' Average, the mean of povalues, is the fair option price for this run.',...
'.',...
' To change the simulation parameters:  Double click on a SIMULINK block ',...
' to open it; edit the parameters; click OK to close and save the changes.');
out3 = str2mat(...
'.',...
'    Open Asset Value and set the stock''s Initial Value (default = 90).',...
'.',...
'    Open Random Walk and set the Volatility (default = 0.0185) and Rate ',...
'    of Return (default = 0.0021) of the stock per time step.  (The ',...
'    default values are based on 250 time steps, or 250 trading days per ',...
'    year; i.e., annual volatility 462.5%, annual return 52.5%.)  Also ',...
'    specify the Number of Walks (paths) to be simulated (default = 5).',...
'.',...
'    Open Option Value and enter the Exercise Price (default = 90) and ');
out4 = str2mat(...
'    Type of option:  1 for a call option (default), -1 for a put option.',...
'.',...
'    Open PV (present value) and specify the Risk-free Interest Rate ',...
'    (default = 0.08) and the option''s Time until Maturity (default = 0.5 ',...
'    years).',...
'.',...
'    Pull down the Simulation menu and choose Parameters.  In the Stop ',...
'    Time box, enter the number of time steps to be simulated.  (The ',...
'    default is 125, which represents 125 trading days out of the default ',...
'    250 per year).  Click OK to close and save.');
out5 = str2mat(...
'.',...
'    Double click the Start box to run the simulation with new parameters.',...
'.',...
' Click the Close button in the graphic window to close it.',...
'.',...
' Pull down the File menu and click Close to return to the Main Map.');
HelpDlgString = str2mat(out1,out2,out3,out4,out5);
helpwin(HelpDlgString,'Option Valuation Help');
