function a = smileh
%SMILEH Helper function for SMILE.

%       Copyright 1995-2002 The MathWorks, Inc.  
%       $Revision: 1.6 $   $Date: 2002/04/14 21:44:10 $ 

% Created by Greg Portmann (1997)

a = figure( ...
   'CreateFcn','set(gca,''visible'',''off'');', ...
   'Color',[.8 .8 .8], ...
   'DeleteFcn','set(findobj(get(gcbf,''Userdata''),''Tag'',''HelpMenu1''),''Checked'',''off'');', ...
   'MenuBar','None', ...
   'Name','Help', ...
	'NumberTitle','off', ...
   'Units','Normal', ...
   'Position',[.1 .5 .4 .5], ...
   'Resize','on', ...
   'Userdata',gcbf);  % Figure handle of the calling figure
   
b = uicontrol('Parent',a, ...
   'Units','Normal', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[.025-.01 .1-.01 1-.05+.02 .85+.02], ...
	'Style','frame', ...
   'Tag','Frame2');

b = uicontrol('Parent',a, ...
   'Units','Normal', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
   'CreateFcn','set(findobj(gcbf,''Tag'',''ListboxHelp''),''String'',smilefn(''Directions'',gcbf));', ...
	'Position',[.025 .1 1-.05 .85], ...
	'Style','listbox', ...
	'Tag','ListboxHelp', ...
   'Value',1);

b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','close(gcbf);', ...
   'Units','Normal', ...
	'Position',[.35 .01 .3 .07], ...
	'String','Close', ...
   'Tag','SmileCloseHelp');


% Inches
height = 4;
width = 4.5;

height = height;
set(a,'Units','Inches');
p = get(a,'Position');
set(a,'Position',[.5 p(2)+p(4)-height-.5 width height]);

