function sysid()
%SYSID Financial Expo System Identification Demo.
%   SYSID Financial Expo System Identification Demo.  This demonstration
%   performs time series analysis on a data set representing a stock's daily
%   closing price.  Through MATLAB HandleGraphics (tm), the model type and 
%   parameters are specified.

%       Author(s): C.F. Garvin, 6-15-95
%       Copyright 1995-2002 The MathWorks, Inc. 
%       $Revision: 1.12 $   $Date: 2002/04/14 21:45:58 $

SCR = get(0,'screensize');
SysIDWin = figure('numbertitle','off','name',...
       'System Identification - Time Series Analysis','position',...
       [SCR(3)*.15 SCR(4)*.1 SCR(3)*.7 SCR(4)*.9]);
set(gcf,'pointer','watch')
FigPos = get(gcf,'position');

Top = FigPos(4);
Right = FigPos(3);
if SCR(3) < 1024
  Bheight = 16;
  Bspace = 2;
  Bwidth = 85;
else
  Bwidth = 85;
  Bheight = 20;
  Bspace = 5;
end
Bvgap = Bspace+Bheight;
Bhgap = Bspace+Bwidth;
Slidoff = 30;

load ibm.dat

PushStr = str2mat('AR','ARX','ARMAX','IV4','OE',...
                  'BJ','PEM');
method = str2mat('ar','arx','armax','iv4','oe','bj','pem');

HeadUI(1) = uicontrol('style','text','string','Model Type','position',...
                        [Right-Bhgap Top-Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
for i = 1:7
   MethodUI(i) = uicontrol('style','radio','value',0,'max',12,...
                 'position',...
                 [Right-Bhgap Top-(i+1)*Bvgap Bwidth Bheight],...
                 'userdata','modeltype','string',PushStr(i,:),...
                 'tag',method(i,:),'callback',[...
                 'muis = findobj(gcf,''userdata'',''modeltype'');'...
                 'duis = findobj(gcf,''tag'',''on'');'...
                 'set(muis,''value'',0),'... 
                 'set(gco,''value'',12),'...
                 'mtype = get(gco,''string'');'...
                 'if mtype(1:3) == ''AR '','...
                  'set(duis,''value'',0,''tag'',''off''),'...
                 'end,'...
                 ]);
end

OutputUI(1) = uicontrol('style','text','string','Output','position',...
                        [Right-Bhgap Top-9*Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
OutputUI(2) = uicontrol('style','check','string','Close','value',1,...
                        'callback','set(gco,''value'',1)',...
                        'position',[Right-Bhgap Top-10*Bvgap Bwidth Bheight]);
datastr = str2mat('Date','High','Low','Close','Volume','Close*Volume');
InputUI(1) = uicontrol('style','text','string','Input','position',...
                        [Right-Bhgap Top-11*Bvgap Bwidth Bheight],...
                        'foregroundcolor','black'); 
for i = 2:7
   InputUI(i) = uicontrol('style','check','value',0,...
                         'tag','off',...
                         'position',...
                         [Right-Bhgap Top-(i+10)*Bvgap Bwidth Bheight],...
                         'userdata',i,'string',datastr(i-1,:),'callback',[...
                         'stat = get(gco,''tag'');'...
                         'if stat(1:2) == ''on'','...
                          'set(gco,''tag'',''off''),'...
                          'set(gco,''value'',0),'...
                         'elseif stat(1:2) == ''of'','...
                          'set(gco,''tag'',''on''),'...
                          'set(gco,''value'',1),'...
                         'end,'...
                         ]);
end
set(MethodUI(1),'value',12)
sysident('ar   ',ibm(:,4),5)
a = findobj(gcf,'type','axes');
set(a(2),'position',[.1 .6 .65 .35])
set(a(1),'position',[.1 .1 .65 .35])

CoeffUI(1) = uicontrol('style','text','string','Model Order',...
                       'position',...
                       [Right-Bhgap Top-18*Bvgap Bwidth Bheight]);
CoeffUI(2) = uicontrol('style','edit','string','5',...
                    'position',...
                    [Right-Bhgap Top-19*Bvgap Bwidth Bheight],...
                    'tag','coeffbox');

otherstr = str2mat('Zoom','Run','Help','Main Map');
for i = 1:4
  OtherUI(i) = uicontrol('string',otherstr(i,:),...
                         'position',...
                         [Right-Bhgap Top-(i+20)*Bvgap Bwidth Bheight]);
end

set(OtherUI(1),'style','checkbox','callback',[...
          'if get(gco,''value'') == 0,'...
            'zoom off,'...
            'set(gcf,''pointer'',''arrow''),'...
          'else,'...
            'zoom on,'... 
            'set(gcf,''pointer'',''circle''),'...
          'end,'...
          ]);
set(OtherUI(2),'callback',[...
       'load ibm.dat,'...
       'model = get(findobj(gcf,''value'',12),''tag'');'...
       'duis = findobj(gcf,''tag'',''on'');'...
       'mtype = get(findobj(gcf,''value'',12),''string'');'...
       'if mtype(1:3) == ''AR '' & ~isempty(duis),'...
         'errordlg(''Please specify no Inputs.  Output is used as Input.'');'...
    'set(findobj(gcf,''type'',''uicontrol''),''backgroundcolor'',''white''),'...
         'return,'...
       'end,'...
       'if mtype(1) ~= ''A'' & isempty(duis),'...
         'errordlg(''Please specify at least one Input.'');'...
    'set(findobj(gcf,''type'',''uicontrol''),''backgroundcolor'',''white''),'...
         'return,'...
       'end,'...
       'ins = length(duis);'...
       'index = [];'...
       'for i = 1:ins,'...
         'index(i) = get(duis(i),''userdata'')-1;'...
       'end,'...
       'indata = [ibm(:,4) ibm(:,index)];'...
       'coeff = str2double(get(findobj(gcf,''tag'',''coeffbox''),''string''));'...
       'out = sysident(model,indata,coeff);'...
       'if isempty(out),'... 
          'return,'...
       'end,'...
       'a = findobj(gcf,''type'',''axes'');'...
       'a = sort(a);'...
       'set(a(1),''position'',[.1 .6 .65 .35]),'...
       'set(a(2),''position'',[.1 .1 .65 .35]),'...
       ]);
out1 = str2mat(...
' This demonstration uses the System Identification Toolbox to model ',...
' closing stock prices.  As default input, it uses the closing prices from',...
' a data set that contains IBM stock price and volume data for about 450',...
' trading days.',...
'.',...
' The top graph shows actual and estimated results.  The bottom graph ',...
' shows the estimation error, or the difference between actual and',...
' estimated results.',...
'.',...
' You can use seven different estimation models:');
out2 = str2mat(...
'.',...
'    AR - Builds an autoregressive model for scalar time series data, ',...
'           using variants of the least-squares method (default model).  ',...
'.',...
'    ARX - Builds an autoregressive model using the least-squares method.',...
'.',...
'    ARMAX - Builds an autoregressive moving average model, using a ',...
'                  prediction error method.',...
'.',...
'    IV4 - Builds an ARX model using approximately optimal four-stage ');
out3 = str2mat(...
'            instrumental variable procedures.',...
'.',...
'    OE - Builds an output-error model.',...
'.',...
'    BJ - Builds a Box-Jenkins model.',...
'.',...
'    PEM - Builds a general linear model.',...
'.',...
'    To use a different model, click on the Model Type selection then ',...
'    click the Run button.  The last four models require at least one Input.');
out4 = str2mat(...
'.',...
' You can change parameters to refine an estimation:',...
'.',...
'    Select (click on) one or more Inputs to use in modeling the output.',...
'    Inputs consist of trading dates; high, low, and closing prices; trading',...
'    volume; and closing price times volume from the IBM stock data set.',...
'.',...
'    Edit the Model Order:  the order of the polynomials used by the ',...
'    model.  For example, entering 5 uses variables from the first through ',...
'    the fifth power.  In theory, a higher order yields a better estimation.');
out5 = str2mat(...
'.',...
'    Click the Run button to see the new results after changing parameters.',...
'.',...
' You can magnify any portion of a chart.  Click Zoom and move the cursor ',...
' to the desired area.  The cursor changes to a circle.  To zoom in ',...
' (magnify), click the primary mouse button.  To zoom back out, click the ',...
' secondary mouse button.  Click Zoom again to turn off the zoom function.',...
'.',...
' Click the Main Map button to return to the Main Map.');
helpstr = str2mat(out1,out2,out3,out4,out5);
set(OtherUI(3),'userdata',helpstr,'callback',[...
             'helpwin(get(gco,''userdata''),''System Identification Help'');'])
set(OtherUI(4),'callback','close;figure(findobj(0,''tag'',''MAINMAP''));')

set([HeadUI(:);MethodUI(:);OutputUI(:);InputUI(:);OtherUI(:);CoeffUI(:)],...
    'units','normal')
TXT = findobj(gcf,'style','text');
set(TXT,'backgroundcolor',get(gcf,'color'))
set(gcf,'pointer','arrow')
