%HESS	Hessenberg form.
%	The Hessenberg form of a matrix is zero below the first
%	subdiagonal. If the matrix is symmetric or Hermitian,
%	the form is tridiagonal.  [P,H] = HESS(A) produces a unitary
%	matrix P and a Hessenberg matrix H so that A = P*H*P' and
%	P'*P = EYE(SIZE(P)).  By itself, HESS(A) returns H.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
