%QZ  	Generalized eigenvalues.
% 	[AA, BB, Q, Z, V] = QZ(A,B) for square matrices A and B,
% 	produces upper triangular matrices AA and BB, matrices Q
% 	and Z containing the products of the left and right trans-
% 	formations, such that Q*A*Z = AA, and Q*B*Z = BB, and the
% 	generalized eigenvector matrix V. 
% 	The alphas and betas comprising the generalized eigenvalues
% 	are the diagonal elements of AA and BB so that 
% 	A*V*diag(BB) = B*V*diag(AA).

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
