%RCOND	LINPACK reciprocal condition estimator.
%	RCOND(X) is an estimate for the reciprocal of the
% 	condition of X in the 1-norm obtained by the LINPACK
% 	condition estimator. If X is well conditioned, RCOND(X)
% 	is near 1.0. If X is badly conditioned, RCOND(X) is
% 	near 0.0.
%
%	See also COND, NORM, CONDEST, NORMEST.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
