%GuiDm_9  Check Box
% Copyright S. Nakamura, 1995
clear,close
h1=figure(2);
set(h1,'Position',[130,350,300,200], ...
    'Color',[0,0.5, 0.5],'Name','GuiDm_9',...
    'NumberTitle','off');
hold on
x=0:0.1:10;plot(x,sin(x))
j=uicontrol('Position',[ 5,0,250,15], ...
    'Style','checkbox',...
        'Value',1,...
    'String','Push here to toggle axis' ,...
    'Callback',...
    [ ...
      'if get(j,''Value'')==0, axis off; ',...
      'elseif get(j,''Value'')==1, axis on, end' ...
    ]);

