function plotGUI
close all
clc
% plot domain
xmin=0;
xmax=4*pi;
% some colors
figure_color=[0.8,0.9,0.8];
panel_color=[1,0.9,0.8];
buttongroup_color=[0.9,0.9,0.8];
hFigure=figure(...
’Units’,’Pixels’,...
’Position’, [100 100 700 500],...
’Color’,figure_color,...
’MenuBar’,’none’,...
’ToolBar’,’none’,...
’NumberTitle’,’off’,...
’Name’,’Plot GUI’);
hAxes=axes(...
’Parent’,hFigure,...
’Units’,’Pixels’,...
’Position’,[50 50 400 400],...
’Xlim’,[xmin,xmax],...
’XGrid’,’on’,...
’YGrid’,’on’);
hPanel=uipanel(...
’Parent’,hFigure,...
’Units’,’Pixels’,...
’Position’,[475,50,200,400],...
’BackgroundColor’,panel_color);

hButtonGroup=uibuttongroup(...
’Parent’,hPanel,...
’Units’,’Pixels’,...
’Position’,[10,275,180,100],...
’BackgroundColor’,buttongroup_color,...
’SelectionChangeFcn’,@colorSelection_callback);
r1=uicontrol(...
’Style’,’Radio’,...
’Parent’,hButtonGroup,...
’Units’,’Pixels’,...
’Position’, [10,10,160,20],...
’String’,’Blue’,...
’BackgroundColor’,buttongroup_color);
r2=uicontrol(...
’Style’,’Radio’,...
’Parent’,hButtonGroup,...
’Units’,’Pixels’,...
’Position’, [10,37,160,20],...
’String’,’Green’,...
’BackgroundColor’,buttongroup_color);
r3=uicontrol(...
’Style’,’Radio’,...
’Parent’,hButtonGroup,...
’Units’,’Pixels’,...
’Position’, [10,65,160,20],...
’String’,’Red’,...
’BackgroundColor’,buttongroup_color);
hLineStyleText=uicontrol(...
’Style’,’text’,...
’Parent’,hPanel,...
’Position’, [10 240 180 20],...
’String’, ’LineStyle Choices’,...
’HorizontalAlignment’,’Left’,...
’BackgroundColor’, panel_color);

hLineStylePopup=uicontrol(...
’Style’,’popup’,...
’Parent’,hPanel,...
’Units’,’Pixels’,...
’Position’, [10 225 180 15],...
’String’,{’Solid’ ’Dotted’ ’DashDot’ ’Dashed’ ’None’},...
’BackgroundColor’, buttongroup_color,...
’Callback’, @LineStylePopup_callback);
hLineWidthText=uicontrol(...
’Style’,’text’,...
’Parent’,hPanel,...
’Position’, [10 180 180 20],...
’String’, ’Enter Desired LineWidth: (1-10)’,...
’HorizontalAlignment’,’Left’,...
’BackgroundColor’, panel_color);
hLineWidthEditbox=uicontrol(...
’Style’,’edit’,...
’Parent’,hPanel,...
’Units’,’Pixels’,...
’Position’, [10 150 180 25],...
’String’,’1’,...
’BackgroundColor’, buttongroup_color,...
’Callback’, @LineWidthEditbox_callback);
% plot data
x=linspace(xmin,xmax);
y=sin(2*x);
hLine=line(x,y);
function colorSelection_callback(hObject,eventdata)
lineColor=get(eventdata.NewValue, ’String’);
switch lineColor
case ’Red’
set(hLine,’Color’,’r’)
case ’Green’
set(hLine,’Color’,’g’)
case ’Blue’
set(hLine,’Color’,’b’)
end
end % end colorSelection_callback

function LineStylePopup_callback(hObject,eventdata)
lineStyleChoices=get(hObject,’String’);
lineStyleChoice=get(hObject,’Value’);
lineStyle=lineStyleChoices{lineStyleChoice};
switch lineStyle
case ’Solid’
set(hLine,’LineStyle’,’-’)
case ’Dotted’
set(hLine,’LineStyle’,’:’)
case ’DashDot’
set(hLine,’LineStyle’,’-.’)
case ’Dashed’
set(hLine,’LineStyle’,’--’)
case ’None’
set(hLine,’LineStyle’,’none’)
end
end % end LineStylePopup_callback
