%1. Plot a function.
%2. Provide radio buttons to change the color of the graph of the function, offering
%choices of red, green, or blue.
%3. Provide a popup menu with choices of different line styles for the plot: solid,
%dotted, etc.
%4. Provide an edit box that allows the user to change the linewidth.
%Let’s begin. Open the editor and enter the following lines, then save the
%function M-file as plotGUI.m.

function plotGUI
close all
clc
% plot domain
xmin=0;
xmax=4*pi;
% some colors
figure_color=[0.8,0.8,0.8];
panel_color=[1,0.9,0.8];
buttongroup_color=[0.9,0.9,0.8];
hFigure=figure('Units','Pixels','Position', [100 100 500 300],'Color',figure_color,...
'MenuBar','none',...
'ToolBar','none',...
'NumberTitle','off',...
'Name','Plot GUI');
hAxes=axes(...
'Parent',hFigure,...
'Units','Pixels',...
'Position',[50 50 400 400],...
'Xlim',[xmin,xmax],...
'XGrid','on',...
'YGrid','on');
% plot data
x=linspace(xmin,xmax);
y=sin(2*x);
hLine=line(x,y);
function colorSelection_callback(hObject,eventdata)
lineColor=get(eventdata.NewValue, 'String');
switch lineColor
    case 'Red'
set(hLine,'Color','r')
    case 'Green'
set(hLine,'Color','g')
    case 'Blue'
set(hLine,'Color','b')
end % end colorSelection_callback
function LineStylePopup_callback(hObject,eventdata)
lineStyleChoices=get(hObject,'String');
lineStyleChoice=get(hObject,'Value');
lineStyle=lineStyleChoices{lineStyleChoice};
switch lineStyle
    case 'Solid'
set(hLine,'LineStyle','-')
    case 'Dotted'
set(hLine,'LineStyle',':')
    case 'DashDot'
set(hLine,'LineStyle','-.')
    case 'Dashed'
set(hLine,'LineStyle','--')
    case 'None'
set(hLine,'LineStyle','none')
end
% end LineStylePopup_callback
function LineWidthEditbox_callback(hObject,eventdata)
lineWidth=str2double(get(hObject,’String’));
if (lineWidth>=1) && (lineWidth<=10)
set(hLine,’LineWidth’,lineWidth);
else
set(hObject,’String’,’Invalid Input---Try again’);
end
end % end LineStyleEditbox_callback
end % end plotGUI
hPanel=uipanel(...
'Parent',hFigure,...
'Units','Pixels',...
'Position',[475,50,200,400],...
'BackgroundColor',panel_color);
hButtonGroup=uibuttongroup(...
'Parent',hPanel,...
'Units','Pixels',...
'Position',[10,275,180,100],...
'BackgroundColor',buttongroup_color)
r1=uicontrol(...
'Style','Radio',...
'Parent',hButtonGroup,...
'Units','Pixels',...
'Position', [10,10,160,20],...
'String','Blue',...
'BackgroundColor',buttongroup_color);
r2=uicontrol(...
'Style','Radio',...
'Parent',hButtonGroup,...
'Units','Pixels',...
'Position', [10,37,160,20],...
'String','Green',...
'BackgroundColor',buttongroup_color);
r3=uicontrol(...
'Style','Radio',...
'Parent',hButtonGroup,...
'Units','Pixels',...
'Position', [10,65,160,20],...
'String','Red',...
'BackgroundColor',buttongroup_color);
hLineStyleText=uicontrol(...
'Style','text',...
'Parent',hPanel,...
'Position', [10 240 180 20],...
'String', 'LineStyle Choices',...
'HorizontalAlignment','Left',...
'BackgroundColor', panel_color);
hButtonGroup=uibuttongroup(...
'Parent',hPanel,...
'Units','Pixels',...
'Position',[10,275,180,100],...
'BackgroundColor',buttongroup_color,...
'SelectionChangeFcn',@colorSelection_callback);




hLineStylePopup=uicontrol(...
'Style','popup',...
'Parent',hPanel,...
'Units','Pixels',...
'Position', [10 225 180 15],...
'String',{'Solid' 'Dotted' 'DashDot' 'Dashed' 'None'},...
'BackgroundColor', buttongroup_color,...
'Callback', @LineStylePopup_callback);