clf
hsl = uicontrol('Position',[200 260 200 20], ...
	'Style','slider',...
	'Value',0.5,...
	'CallBack','set(hed,''String'',get(hsl,''value''))');
hed = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',[200 240 70 20], ...
	'String','0.5', ...
	'Style','edit',...
	'CallBack','set(hsl,''Value'',str2num(get(hed,''String'')))');

%	'CallBack','set(hed,''String'',num2str(get(hsl,''value''),2))');
