uicontrol('Callback','ezplot(''sin(x)'')', ...
        'Position',[508 351 51 26], ...
        'String','Sine');
uicontrol('Callback','ezplot(''cos(x)'')', ...
        'Position',[508 322 51 26], ...
        'String','Cos');
uicontrol('Callback','ezplot(''tan(x)'')', ...
        'Position',[508 293 51 26], ...
        'String','Tan');
