function v = vivaldi
% VIVALDI   Antonio Vivaldi, Spring from the Four Seasons
%  Usage:
%  pianoex(vivaldi)

C = 0; D = 2; E = 4; F = 5; G = 7; A = 9; B = 11;
e = 1/4; q = 1/2; h = 1; t = 3/2;

v = {C q; [C E] q; [C E] q; [C E] q; D e; C e; [E G] t; ...
     G e; F e; [C E] q; [C E] q; [C E] q; D e; C e; [E G] t; ...
     G e; F e; [C E] q; F e; G e; [D F] q; [C E] q; D h; [] q; ...
     C q; [C E] q; [C E] q; [C E] q; D e; C e; [E G] t; ...
     G e; F e; [C E] q; [C E] q; [C E] q; D e; C e; [E G] t; ...
     G e; F e; [C E] q; F e; G e; [D F] q; [C E] q; D h; [] q; ...
     C q; [E G] q; F e; E e; F q; G q; [F A] q; [G E] h; ...
     C q; [E G] q; F e; E e; F q; G q; [F A] q; [G E] h; ...
     C q; [F A] q; [E G] h; F q; E q; D e; C e; D h; C t;};
