function varargout= gui_diagstats(m,Action,varargin)
% xreginterprbf/GUI_DIAGSTATS
% 
% GUI Tool for displaying ANOVA Table and other Statistics
% This is based on the statistics calculated by
% s = stats(m,'stepwise').
% This tool makes extensive use of UITABLES
%
% See also xreglinear/STATS, UITABLE

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.2.6.1 $    $Date: 2004/02/09 07:48:46 $ 


switch lower(Action)
case 'create'
   % create tool
   varargout{1}=i_Create(varargin{:});
case 'display'
   % Update Table Values
   i_Display(m,varargin{:});
case 'nofit'
   i_NoFit(m,varargin{:});
case 'id'
   varargout{1}='xreginterprbf';
end

% -------------------------------------------------------------------------|
function Tool = i_Create(hFig);
% create Stats tables

Stbl = xregtable(hFig,...
   'visible','off',...
   'defaultcelltype','uitext',...
   'defaultcellformat','%.3g',...
   'hslider.width',13,...
   'vslider.width',13,...
   'rows.size',12,...
   'cols.size',80,...  
   'rows.spacing',2,...
   'cols.spacing',2,...    
   'rows.number',1,...
   'cols.number',2,...
   'cols.fixed',1,...
   'zeroindex',[1 2],...
   'frame.hborder',[2 2],...
   'frame.vborder',[2 2],...
   'frame.box','on',...
   'frame.visible','off',...
   'redrawmode','basic',...
   'position',[-200 -200 100 60]);
Tool.InterpRbfStats = Stbl;

set(Tool.InterpRbfStats,...
   'cells.rowselection',[1 1],...
   'cells.colselection',[1 1],...
   'cells.type','uitext',...
   'cells.horizontalalignment','left',...
   'cells.string',{'Condition'},...
   'cells.colselection',[2 2],...
   'cells.rowselection',[1 1],...
   'cells.horizontalalignment','right');

Tool.layout = xregframetitlelayout(hFig,...
   'title','Diagnostic statistics',...
   'Center',Stbl,...
   'innerborder',[10 0 0 5],...
   'visible','off',...
   'packstatus','off');

set(Tool.InterpRbfStats,'redrawmode','normal');

%%% Tool.layout= xregcontainer(hFig);

return

% -------------------------------------------------------------------------|
function i_Display(Model,Tool)

Tool.InterpRbfStats(:,1)= condest(Model);

return

% -------------------------------------------------------------------------|
function i_NoFit(m,Tool)

Tool.InterpRbfStats(:,1)= NaN;

return

% -------------------------------------------------------------------------|

% EOF
