%FIGURE Create Figures (graph windows).
% 	FIGURE, by itself, opens a new Figure (graph window), and returns
%	an integer handle.
% 
% 	FIGURE(H) makes the H'th Figure the current Figure for 
% 	subsequent plotting commands.  If Figure H does not exist, a new 
%	one is created using the first available Figure handle.
%
%   	GCF returns the handle to the current figure.
%
%   	Execute GET(H) to see a list of figure object properties and
%   	their current values. Execute SET(H) to see a list of figure
%   	object properties and legal property values.
%
%	See also SUBPLOT, AXES, GCF, CLF.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
