%HARDCOPY Save figure window to file.
%   	HARDCOPY(H,'filename','format') saves the figure window
%   	with handle H to the designated filename in the 
%   	specified format.
%
%   	Legal formats are -dps,-deps,-dps2,-deps2. See
%   	PRINT for more information.
%
%   	Do NOT use this function directly. Use PRINT instead.
%   	This function is temporary and will be replaced with
%   	a different mechanism in future releases of MATLAB.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
