%WAITFORBUTTONPRESS Wait for key/buttonpress over figure.
%	T = WAITFORBUTTONPRESS stops program execution until a key or
%	mouse button is pressed over a figure window.  Returns 0
%	when terminated by a mouse buttonpress, or 1 when terminated
%	by a keypress.  Additional information about the terminating
%	event is available from the current figure.
%
%	See also GINPUT, GCF.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.

