function [queuefig] = queue_output(title_bar, title, results)

% Display results for Queueing Models
global  num_qpmf numq_pmfa
num_qpmf = results{8};
num_qpmfa = results{9};

% global variables (handles only)
global QPmf_handles

% Main figure
queuefig = figure('Name', title_bar, ...
                 'Units','normalized', ...
	              'Color',[0.8 0.8 0.8], ...
	              'MenuBar','none', ...
	              'NumberTitle','off', ...
	              'Position',[0.471354 0.0405093 0.522569 0.875], ...
	              'Tag','Queue_Output');

% Menu options for this figure
exit = uimenu(queuefig, ...
              'Label', 'Close Figure',...
              'Tag','CloseFig', ...
              'Callback','close') ;
save = uimenu(queuefig, ...
              'Label', 'Save Results', ...
              'Callback', sprintf('printto(''queue'', ''file'') ;'), ...
              'Tag', 'SaveFig') ;
prnt = uimenu(queuefig, ...
              'Label', 'Print Results', ...
              'Callback', sprintf('printto(''queue'', ''printer'') ;'), ...
              'Tag', 'PrintFig') ;

% Title
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.5, ...
	       'Position',[0.0980066 0.960317 0.800664 0.037037], ...
	       'Style','text', ...
          'String', title, ...
	       'Tag','Title') ;

% Area Text Labels and Value boxes
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
	       'Position',[0.0681395 0.907407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Mean Number in System', ...
          'Tag','MeanNumSys');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.907407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{1}), ...
	       'Tag','MeanNumSysVal');

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
          'Position',[0.0681395 0.857407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Mean Number in Queue', ...
          'Tag','MeanNumQue');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.857407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{2}), ...
	       'Tag','MeanNumQueVal');
      
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
          'Position',[0.0681395 0.807407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Mean Waiting Time of Entering Cust.', ...
          'Tag','MeanWait');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.807407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{3}), ...
	       'Tag','MeanWaitVal');

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
          'Position',[0.0681395 0.757407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Mean Queueing Time  of Entering Cust.', ...
          'Tag','MeanQue');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.757407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{4}), ...
	       'Tag','MeanQueVal');

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
	       'Position',[0.0681395 0.707407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Mean Number of Busy Servers', ...
          'Tag','MeanBusySer');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.707407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{5}), ...
	       'Tag','MeanBusySerVal');

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
	       'Position',[0.0681395 0.657407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Blocking Probability (System Full)', ...
          'Tag','BlockProb');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.657407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{6}), ...
	       'Tag','BlockProbVal');

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
	       'Position',[0.0681395 0.607407 0.5 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'Probability of All Servers Busy', ...
          'Tag','ProbAllSer');
uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'BackgroundColor',[1 1 1], ...
	       'Position',[0.5681395 0.607407 0.35 0.03330688], ...
	       'Style','edit', ...
          'String', sprintf('%g', results{7}), ...
	       'Tag','ProbAllSerVal');
% Display distribuion boxes if needed
% Determine number of CDF and PMF boxes required
if ~isempty(num_qpmf) %indicates that pmf is available
pmf_size = size(num_qpmf, 1) ;
vdim = min(pmf_size, 10) ;

uicontrol('Parent',queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
          'Position',[0.2 0.557407 0.3 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'P(<=j in the system)', ...
	       'Tag','QDist');
uicontrol('Parent', queuefig, ...
	       'Units','normalized', ...
	       'FontUnits','normalized', ...
	       'BackgroundColor',[0.8 0.8 0.8], ...
	       'FontSize',0.4, ...
          'Position', [0.6 0.557407 0.4 0.0330688], ...
          'HorizontalAlignment', 'left', ...
	       'Style','text', ...
          'String', 'P(arrival sees <=j in the system)', ...
          'Tag', 'QStarDist') ;


for k = 1:vdim
  pmf1(k) = uicontrol('Parent',queuefig, ...
	                   'Units','normalized', ...
	                   'BackgroundColor',[1 1 1], ...
	                   'Position',[.20 .50-((k-1)*.05) .10 .04], ...
	                   'Style','edit', ...
                      'String', sprintf('%i', num_qpmf(k, 1)), ...
	                   'Tag',sprintf('PMF1_%i', k));
  pmf2(k) = uicontrol('Parent',queuefig, ...
	                   'Units','normalized', ...
	                   'BackgroundColor',[1 1 1], ...
	                   'Position',[.30 .50-((k-1)*.05) .15 .04], ...
    	                'Style','edit', ...
                      'String', sprintf('%5.5f', sum(num_qpmf(1:k, 2))), ...
                      'Tag',sprintf('PMF2_%i', k));
  pmf3(k) = uicontrol('Parent',queuefig, ...
	                   'Units','normalized', ...
	                   'BackgroundColor',[1 1 1], ...
	                   'Position',[.70 .50-((k-1)*.05) .10 .04], ...
	                   'Style','edit', ...
                      'String', sprintf('%i', num_qpmfa(k, 1)), ...
	                   'Tag',sprintf('PMF3_%i', k));
  pmf4(k) = uicontrol('Parent',queuefig, ...
	                   'Units','normalized', ...
	                   'BackgroundColor',[1 1 1], ...
	                   'Position',[.80 .50-((k-1)*.05) .15 .04], ...
    	                'Style','edit', ...
                      'String', sprintf('%5.5f', sum(num_qpmfa(1:k, 2))), ...
	                   'Tag',sprintf('PMF4_%i', k));

                end
                
QPmf_handles = [pmf1; pmf2; pmf3; pmf4]' ;
 
if pmf_size > vdim

  if pmf_size - vdim == 1
    eachstep = .99 ;
  else
    eachstep = 1 / (pmf_size - vdim) ;
  end

    % pmf slider
  uicontrol('Parent',queuefig, ...
  	         'Units','normalized', ...
	         'Position',[.53 .05 .04 .49], ...
	         'Style','slider', ...
            'SliderStep', [eachstep 1], ...
            'Value', 1, ...
            'Callback', sprintf('scroll_queue_pmf(%d)', vdim), ...
	         'Tag','PMF_Slider') ;
      end
end;
   
  