
# File : makefile
#
# Abstract :
# 	Makefile to build 555 and 56x standard libraries
# 
# Copyright 2002-2003 The MathWorks, Inc.
#


.PHONY : all

all : 
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=555 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=561 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=562 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=563 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=564 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=565 all
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=566 all
	
clean: 
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=555 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=561 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=562 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=563 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=564 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=565 clean
	$(MAKE) -f makefile.5xx MPC5XX_VARIANT=566 clean
