function [obj, ok] = guiAddNewTable(obj)
%GUIADDNEWTABLE Create a new table and add to the tradeoff
%
%  [OBJ, OK] = GUIADDNEWTABLE(OBJ) creates a new table and adds it to the
%  tradeoff.  If the tradeoff already contains tables, the user will be
%  asked for a table name and a value to initialise it with.  If the
%  tradeoff is empty, they will be presented with the standard new 2D table
%  dialog.  In both cases there will also be an input for specifying the
%  fill item.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.1.6.3 $    $Date: 2004/04/04 03:36:28 $ 

PROJ = project(obj);

hFig = xregdialog('Name', 'Table Setup', ...
        'Resize', 'off');
    
if numTables(obj)==0
    xregcenterfigure(hFig, [300 213]);
    
    % Use the standard 2D table creation panel for setting up a new table
    hTableEdit = cgtools.tablecreator('Parent', hFig, ...
        'Dimensions', 2, ...
        'VariableDictionary', getdd(PROJ));
else
    % Pop up a small dialog that just asks for a name and default value
    SC = xregGui.SystemColorsDbl;
    xregcenterfigure(hFig, [300 157]);

    hName = xregGui.labelcontrol('parent',hFig,...
        'labelsize',70,...
        'labelsizemode','absolute',...
        'string','Name:',...
        'controlsize',1,...
        'controlsizemode','relative',...
        'gap',5,...
        'Control',uicontrol('parent',hFig,...
        'style','edit',...
        'string', 'New_2D_Table', ...
        'userdata', 'New_2D_Table', ...
        'backgroundcolor',SC.WINDOW_BG,...
        'horizontalalignment','left',...
        'callback',@i_disallowempty));

    hValue = xregGui.labelcontrol('parent',hFig,...
        'labelsize',70,...
        'labelsizemode','absolute',...
        'string','Initial value:',...
        'controlsize',75,...
        'controlsizemode','absolute',...
        'gap',5,...
        'Control',xregGui.clickedit('parent', hFig, ...
        'enable','off'));

    % Construct a layout for the cut-down table editing elements
    hTableEdit = xreggridbaglayout(hFig, ...
        'packstatus', 'off', ...
        'dimension', [2 1], ...
        'rowsizes', [20 20], ...
        'gapy', 6, ...
        'elements', {hName, hValue}); 
end

% Construct the table-filling UI items
hFill = xregGui.labelcontrol('parent',hFig,...
    'labelsize',70,...
    'labelsizemode','absolute',...
    'string','Fill table with:',...
    'controlsize',1,...
    'controlsizemode','relative',...
    'gap',5,...
    'Control',uicontrol('parent',hFig,...
    'style','edit',...
    'horizontalalignment','left', ...
    'userdata', xregpointer, ...
    'enable', 'inactive'));
hFillSelect = uicontrol('Parent', hFig, ...
    'style', 'pushbutton', ...
    'string', 'Select...', ...
    'callback', {@i_selectfillitem, hFill, obj});
hFillClear = uicontrol('Parent', hFig, ...
    'style', 'pushbutton', ...
    'string', 'Clear', ...
    'callback', {@i_clearfillitem, hFill});

% Control buttons
hOK = uicontrol('style', 'pushbutton', ...
    'parent', hFig, ...
    'string', 'OK', ...
    'callback', 'set(gcbf, ''tag'', ''ok'', ''visible'', ''off'');');
hCancel = uicontrol('style', 'pushbutton', ...
    'parent', hFig, ...
    'string', 'Cancel', ...
    'callback', 'set(gcbf, ''visible'', ''off'');');
hHelp = cghelpbutton(hFig, 'CGTRADEOFFNEWTABLE');

% Main Layout
layout = xreggridbaglayout(hFig, ...
    'packstatus', 'off', ...
    'dimension', [9, 4], ...
    'rowsizes', [-1 6 3 20 2 3 25 15 25], ...
    'colsizes', [-1 65 65 65], ...
    'gapx', 7, ...
    'border', [7 7 7 7], ...
    'mergeblock', {[1 1], [1 4]}, ...
    'mergeblock', {[4 4], [1 3]}, ...
    'mergeblock', {[3 5], [4 4]}, ...
    'elements', {hTableEdit, [], [], hFill, [], [], [], [], [], ...
    [], [], [], [], [], [], [], [], hOK, ...
    [], [], [], [], [], [], [], [], hCancel, ...
    [], [], hFillSelect, [], [], [], hFillClear, [], hHelp});

hFig.Layout = layout;
set(layout, 'packstatus', 'on');

hFig.showDialog(hOK);

tg = get(hFig, 'tag');
ok = false;
if strcmp(tg, 'ok')
    if numTables(obj)==0
        pT = hTableEdit.createTable;
        [obj, ok] = addTable(obj, pT);
        
        % Add items to project
        pNx = pT.get('x');
        pNy = pT.get('y');
        if ok
            addtoproject(obj, pNx);
            addtoproject(obj, pNy);
            addtoproject(obj, pT);
        else
            freeptr([pT pNx pNy]);
        end
    else
        Name = get(hName.Control, 'String');
        Value = get(hValue.Control, 'Value');
        [obj, pT, ok] = addNewTable(obj, Name, Value);
    end
    
    pNewFill = get(hFill.Control, 'userdata');
    if ~isnull(pNewFill)
        obj = setFillExpression(obj, pT, pNewFill);
    end
end
delete(hFig);



function i_disallowempty(src,evt)
% Prevent user from having an invalid string in the edit box
str = get(src,'string');
if ~isvarname(str)
   set(src,'string',get(src,'userdata'));
else
   set(src,'userdata',str);
end


function i_selectfillitem(src, evt, hFill, obj)
[pNewFill, ok] = pGuiGetFillExpression(obj);
if ok
    set(hFill.Control, 'userdata', pNewFill);
    set(hFill.Control, 'string', pNewFill.getname);
end


function i_clearfillitem(src, evt, hFill)
set(hFill.Control, 'userdata', xregpointer);
set(hFill.Control, 'string', '');

