%STRINGS Character strings in MATLAB.
% 	X = 'Any Characters' is a vector whose components are the ASCII codes
%	for the characters.  The length of X is the number of characters.
%	X = ABS(X) sets the vector to its decimal ASCII representation.
%	X = SETSTR(X) sets it back to a string.
%	A quote within the string is indicated by two quotes.
%	ISSTR(X) tells if X is a string variable.

%	Copyright (c) 1984-94 by The MathWorks, Inc.

