function design_plot(design_problem, parameter_name, x,g)

%Plots the objective function


plotfig = figure('Name', 'Plot of the Objective Function', ...
                 'Color',[0.8 0.8 0.8], ...
                 'Units', 'normalized', ...
	              'Position', [.45 .1 .54 .75], ...
                 'Menubar', 'none', ...
                 'NumberTitle', 'off', ...
	              'Tag','plotfig');

% Menu options for this figure
exit = uimenu(plotfig, ...
              'Label', 'Close Figure',...
              'Tag','CloseFig', ...
              'Callback','close') ;
prnt = uimenu(plotfig, ...
              'Label', 'Print Graph', ...
              'Tag', 'PrintGraph', ...
              'Callback', [sprintf('title(''%s'');', design_problem), ...
                           'print -dwin -v']) ;

% Titles
uicontrol('Parent',plotfig, ...
          'Units','normalized', ...
          'Position',[.1 .93 .8 .07], ...
          'BackgroundColor',[0.8 0.8 0.8], ...
          'Fontsize', 12, ...
          'Style','text', ...
          'String', design_problem, ...
          'Tag','Title');

       plot(x,g,'-');
       xlabel(parameter_name);
       ylabel('cost rate');
       