function exradio(action)
if nargin==0
  clf
  uicontrol('Position',[200 321 90 25], ...
      'String','JJJ', ...
      'Style','radiobutton',...
      'CallBack','exradio(1)')
  uicontrol('Position',[200 296 90 25], ...
      'String','ABC-FM', ...
      'Style','radiobutton',...
      'CallBack','exradio(1)')
  uicontrol('Position',[200 271 90 25], ...
      'String','SAFM', ...
      'Style','radiobutton',...
      'CallBack','exradio(1)')
  uicontrol('Position',[200 246 90 25], ...
      'String','5AD', ...
      'Style','radiobutton',...
      'CallBack','exradio(1)')
else
  h = findobj('style','radiobutton');
  ind = find(h~=gco);
  set(h(ind),'value',0)
end
   