function exradio2(action)
global h
if nargin==0
  clf
  h1 = uicontrol('Position',[200 321 90 25], ...
      'String','JJJ', ...
      'Style','radiobutton',...
      'CallBack','exradio2(1)');
  h2 = uicontrol('Position',[200 296 90 25], ...
      'String','ABC-FM', ...
      'Style','radiobutton',...
      'CallBack','exradio2(1)');
  h3 = uicontrol('Position',[200 271 90 25], ...
      'String','SAFM', ...
      'Style','radiobutton',...
      'CallBack','exradio2(1)');
  h4 = uicontrol('Position',[200 246 90 25], ...
      'String','5AD', ...
      'Style','radiobutton',...
      'CallBack','exradio2(1)');
  h = [h1 h2 h3 h4];
else
  ind = find(h~=gco);
  set(h(ind),'value',0);
end
   