function sliders()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

load sliders                           

a = figure('Color',[0.95 0.9 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'PaperPosition',[0.634517 6.34517 20.3046 15.2284], ...
	'PaperType','a4letter', ...
	'PaperUnits','centimeters', ...
	'Position',[14 29 560 420], ...
	'Renderer','zbuffer', ...
	'Tag','Fig1', ...
	'WindowButtonDownFcn','rotate3d(''down'')', ...
	'WindowButtonUpFcn','rotate3d(''up'')');
b = axes('Parent',a, ...
	'CameraUpVector',[0 0 1], ...
	'ColorOrder',mat1, ...
	'DataAspectRatioMode','manual', ...
	'DrawMode','fast', ...
	'HandleVisibility','off', ...
	'LineWidth',0.01, ...
	'Position',[0.577977 0.11 0.327023 0.343902], ...
	'Tag','rotaObj', ...
	'UserData',mat2, ...
	'View',[47 26], ...
	'Visible','off', ...
	'WarpToFill','off', ...
	'XColor',[0 0 0], ...
	'XLim',[-5 7.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[-1 1], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZLim',[0 1.5], ...
	'ZLimMode','manual');
c = line('Parent',b, ...
	'Clipping','off', ...
	'Color',[1 0 0], ...
	'EraseMode','xor', ...
	'HandleVisibility','off', ...
	'LineWidth',0.1, ...
	'Tag','Line1', ...
	'Visible','off', ...
	'XData',mat3, ...
	'YData',mat4, ...
	'ZData',mat5);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[5.46631 -2.76873 0], ...
	'Tag','Text20', ...
	'VerticalAlignment','top', ...
	'Visible','off');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'Position',[9.28038 -0.69775 0], ...
	'Tag','Text21', ...
	'VerticalAlignment','top', ...
	'Visible','off');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-7.23938 -0.975218 0], ...
	'Rotation',90, ...
	'Tag','Text22', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-5.47815 6.23659 0], ...
	'Tag','Text23', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.95 0.9 0.8], ...
	'FontSize',12, ...
	'HandleVisibility','off', ...
	'Position',[2 2 130 20], ...
	'String','Az:   47 El:   26', ...
	'Style','text', ...
	'Tag','StaticText1', ...
	'Visible','off');
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'ColorOrder',mat6, ...
	'DataAspectRatioMode','manual', ...
	'LineWidth',0.01, ...
	'NextPlot','add', ...
	'Position',[0.13 0.581098 0.327023 0.343902], ...
	'Tag','Axes1', ...
	'WarpToFill','off', ...
	'XColor',[0 0 0], ...
	'XLim',[-1 1], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[0.00010203 1], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'LineWidth',0.1, ...
	'Tag','Line2', ...
	'XData',mat7, ...
	'YData',mat8);
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'LineStyle','none', ...
	'LineWidth',0.1, ...
	'Marker','x', ...
	'Tag','Line3', ...
	'XData',0, ...
	'YData',0.25);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HorizontalAlignment','center', ...
	'Position',[0 0.3 0], ...
	'String','Focus', ...
	'Tag','Text1', ...
	'VerticalAlignment','bottom');
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HorizontalAlignment','right', ...
	'Position',[0.75 0.5625 0], ...
	'String','y = x^2', ...
	'Tag','Text2', ...
	'VerticalAlignment','bottom');
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.00549451 -0.192257 0], ...
	'Tag','Text3', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-1.25824 0.500051 0], ...
	'Rotation',90, ...
	'Tag','Text4', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-1.7967 1.63192 0], ...
	'Tag','Text5', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.00549451 1.07148 0], ...
	'Tag','Text6', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'CameraUpVector',[0 0 1], ...
	'CLimMode','manual', ...
	'ColorOrder',mat9, ...
	'LineWidth',0.01, ...
	'NextPlot','add', ...
	'Position',[0.5 0.5 0.5 0.5], ...
	'Tag','Axes2', ...
	'View',[-32 60], ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on');
c = surface('Parent',b, ...
	'CData',mat10, ...
	'EdgeColor','none', ...
	'Tag','Surface1', ...
	'VertexNormals',mat11, ...
	'XData',mat12, ...
	'YData',mat13, ...
	'ZData',mat14);
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'LineWidth',0.1, ...
	'Tag','Line4', ...
	'XData',[0 0], ...
	'YData',[0 0], ...
	'ZData',[0 1]);
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'LineStyle','none', ...
	'LineWidth',0.1, ...
	'Marker','x', ...
	'Tag','Line5', ...
	'XData',0, ...
	'YData',0, ...
	'ZData',0.25);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HorizontalAlignment','center', ...
	'Position',[0 0 0.3], ...
	'String','Focus', ...
	'Tag','Text7', ...
	'VerticalAlignment','bottom');
c = line('Parent',b, ...
	'Color',[1 0 0], ...
	'LineWidth',0.1, ...
	'Tag','Line6', ...
	'XData',mat15, ...
	'YData',mat16, ...
	'ZData',mat17);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'Position',[-1.68584 -5.75494 0], ...
	'Tag','Text16', ...
	'VerticalAlignment','top', ...
	'Visible','off');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-5.78542 -2.39894 0], ...
	'Tag','Text17', ...
	'VerticalAlignment','top', ...
	'Visible','off');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-3.52406 6.51387 0], ...
	'Rotation',90, ...
	'Tag','Text18', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[5.62624 9.00386 0], ...
	'Tag','Text19', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'ColorOrder',mat18, ...
	'Layer','top', ...
	'LineWidth',0.01, ...
	'Position',[0.13 0.11 0.327023 0.343902], ...
	'Tag','Axes3', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 320.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 200.5], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0]);
c = image('Parent',b, ...
	'CData',mat19, ...
	'Tag','Image1', ...
	'XData',[1 320], ...
	'YData',[1 200]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[159.621 224.976 0], ...
	'Tag','Text12', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-46.0934 100.5 0], ...
	'Rotation',90, ...
	'Tag','Text13', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-126.973 -320.479 0], ...
	'Tag','Text14', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[159.621 -8.59091 0], ...
	'Tag','Text15', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'CameraUpVector',[0 0 1], ...
	'ColorOrder',mat20, ...
	'DataAspectRatioMode','manual', ...
	'LineWidth',0.01, ...
	'Position',[0.577977 0.11 0.327023 0.343902], ...
	'Tag','Axes4', ...
	'View',[47 26], ...
	'WarpToFill','off', ...
	'XColor',[0 0 0], ...
	'XLim',[-5 7.5], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[-1 1], ...
	'YLimMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZLim',[0 1.5], ...
	'ZLimMode','manual');
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[1 2 7 6], ...
	'Tag','Patch1', ...
	'VertexNormals',mat21, ...
	'Vertices',mat22);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[2 3 8 7], ...
	'Tag','Patch2', ...
	'VertexNormals',mat23, ...
	'Vertices',mat24);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[3 8 9 4], ...
	'Tag','Patch3', ...
	'VertexNormals',mat25, ...
	'Vertices',mat26);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[4 9 10 5], ...
	'Tag','Patch4', ...
	'VertexNormals',mat27, ...
	'Vertices',mat28);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[1 5 10 6], ...
	'Tag','Patch5', ...
	'VertexNormals',mat29, ...
	'Vertices',mat30);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[6 7 8 9 10], ...
	'Tag','Patch6', ...
	'VertexNormals',mat31, ...
	'Vertices',mat32);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',[1 2 3 4 5], ...
	'Tag','Patch7', ...
	'VertexNormals',mat33, ...
	'Vertices',mat34);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',mat35, ...
	'Tag','Patch8', ...
	'VertexNormals',mat36, ...
	'Vertices',mat37);
c = patch('Parent',b, ...
	'EdgeColor',[0.35 0.375 0.375], ...
	'FaceColor',[0.7 0.75 0.75], ...
	'Faces',mat38, ...
	'Tag','Patch9', ...
	'VertexNormals',mat39, ...
	'Vertices',mat40);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[5.46631 -2.76873 0], ...
	'Tag','Text8', ...
	'VerticalAlignment','top');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'Position',[9.28038 -0.69775 0], ...
	'Tag','Text9', ...
	'VerticalAlignment','top');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-7.23938 -0.975218 0], ...
	'Rotation',90, ...
	'Tag','Text10', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-5.47815 6.23659 0], ...
	'Tag','Text11', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'FontSize',12, ...
	'Position',[265.976 20.3294 172.8 15.2471], ...
	'Style','slider', ...
	'Tag','Slider1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'FontSize',12, ...
	'Position',[440.471 37.2706 15.2471 138.071], ...
	'Style','slider', ...
	'Tag','Slider1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',12, ...
	'Position',[288 6.77647 128.753 14.4], ...
	'Style','text', ...
	'Tag','StaticText2');
