bdwidth = 5;
topbdwidth = 10;
set(0,'Units','pixels')
screensize = get(0,'ScreenSize');
figwidth = screensize(3)/2 - 2*bdwidth;
figheight = screensize(4)/2 - 2*(bdwidth + topbdwidth);
pos1 = [bdwidth,...
	bdwidth,...
	figwidth,...
	figheight];
pos2 = [screensize(3)/2+bdwidth,...
	pos1(2),...
	figwidth,...
	figheight];
pos3 = [screensize(3)/2+bdwidth,...
	screensize(4)/2+bdwidth,...
	figwidth,...
	figheight];
figure('Position',pos1)
figure('Position',pos2)
figure('Position',pos3)
