function contact2
%CONTACT2 How to reach The MathWorks, Inc. by email.

%	Ned Gulley, 6-21-93
%	Copyright (c) 1984-94 by The MathWorks, Inc.

ttlStr='Contacting The MathWorks by E-Mail';
txtStr1= ...                                                          
    ['                                                         '  
     ' The MathWorks is pleased to provide convenient          '  
     ' access from the Internet by electronic mail. Use any    '  
     ' of the following addresses, as appropriate, to reach us.'  
     '                                                         '  
     '                                                         '  
     ' Suggestions or comments.                                '  
     '         suggest@mathworks.com                           '  
     '                                                         '  
     '                                                         '  
     ' Sales, pricing, and general information.                '  
     '         info@mathworks.com                              '  
     '                                                         '  
     '                                                         '  
     ' Technical support.                                      '  
     '         support@mathworks.com                           '  
     '                                                         '  
     '                                                         '  
     ' Subscribing user registration.                          '  
     '         subscribe@mathworks.com                         '  
     '                                                         '  
     '                                                         '  
     ' Order status, license renewals, passcodes.              '  
     '         service@mathworks.com                           '  
     '                                                         '  
     '                                                         '];
txtStr2= ...                                                              
    ['                                                             '  
     ' Training and Short Courses.                                 '  
     '         courses@mathworks.com                               '  
     '                                                             '  
     '                                                             '  
     ' Users Group and conference information.                     '  
     '         mug@mathworks.com                                   '];

xppage(ttlStr,txtStr1,txtStr2);

