function contact1
%CONTACT1 How to reach the The MathWorks, Inc.

%	Ned Gulley, 6-21-93
%	Copyright (c) 1984-94 by The MathWorks, Inc.

ttlStr='Contacting The MathWorks';


txtStr= ...                                                                  
    ['                                                                 '  
     ' If you''re interested in further information about any of        '  
     ' our products, training, or if you''d like to make comments       '  
     ' about MATLAB, SIMULINK, any of the Toolboxes or                 '  
     ' the MATLAB Expo itself, please give us a call at                '  
     '                                                                 '  
     ' The MathWorks, Inc.                                             '  
     ' 24 Prime Park Way                                               '  
     ' Natick, Massachusetts 01760                                     '
     '                                                                 '  
     ' Phone: (508) 653-1415                                           '  
     ' FAX: (508) 653-2997                                             '  
     ' Email: info@mathworks.com                                       '
     '                                                                 '  
     ' To speak with your MathWorks representative, please call        '  
     ' (508) 653-2452, extension 400.                                  '];

xppage(ttlStr,txtStr);
