function d = pr_CreateContextMenu(fig, d)
% CGOPTIMNODE/PR_CREATECONTEXTMENU Create the context menus for the objective,DS and constraint lists

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.3.6.1 $    $Date: 2004/02/09 08:27:30 $


CGBH = cgbrowser;
pN = CGBH.CurrentNode;
cb=Callbacks(pN.info,'GetHandles');


%%%%%% Objective List Context Menu %%%%%%%%%%%%%%%
m = uicontextmenu('parent',fig,'visible','off');

CMhndls.ObjCM = m;

CMhndls.AddObj = uimenu(m,'label','&Add Objective', ...
    'enable', 'on', ...
    'callback', cb.AddObj);
CMhndls.SelObj = uimenu(m,'label','&Edit Objective', ...
    'enable', 'on', ...
    'callback', cb.SelObj);
CMhndls.DelObj = uimenu(m, 'label', '&Delete Objective', ...
    'enable', 'off', ...
    'callback', cb.DelObj);

%%%%%% Data Set List Context Menu %%%%%%%%%%%%%%%
m = uicontextmenu('parent',fig,'visible','off');

CMhndls.DSLCM = m;
CMhndls.AddDS = uimenu(m,'label','&Add Operating Point Set', ...
    'enable', 'on', ...
    'callback', cb.AddDS);
CMhndls.SelDS = uimenu(m,'label','&Edit Operating Point Set', ...
    'enable', 'on', ...
    'callback', cb.SelDS);
CMhndls.DelDS = uimenu(m,'label','&Delete Operating Point Set', ...
    'enable', 'off', ...
    'callback', cb.DelDS);

%%%%%% Constraint List Context Menu %%%%%%%%%%%%%%%
m = uicontextmenu('parent',fig,'visible','off');

CMhndls.ConCM = m;
CMhndls.AddCon = uimenu(m,'label','&Add Constraint', ...
    'enable', 'on', ...
    'callback', cb.AddCo);
CMhndls.EditCon = uimenu(m,'label','&Edit Constraint', ...
    'enable', 'on', ...
    'callback', cb.EditCo);
CMhndls.DelCon = uimenu(m,'label','&Delete Constraint', ...
    'enable', 'off', ...
    'callback', cb.DelCo);

d.Handles.Contextmenu = CMhndls;