clc; disp('Non-Linear Frequency Domain support utilities:'); 
disp(' '); disp('Implemented using the Describing Function Methods:');
disp(' '); disp('Back_lsh'); disp('Dead_zn'); disp('Relays'); disp(' ');
disp('Non-linear System Simulation available through Simulink Toolbox');
disp('See demo # 6 (Linear, Time Domain) for further details');
disp(' '); disp('Press any key to continue'); pause;
eval('mcstd51');
eval('mcstd52');
eval('mcstd53');
