function varargout = DrawDlg(varargin)
%DRAWDLG

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.3.2.3 $  $Date: 2004/02/09 08:21:29 $

d = varargin{2};
d.Dlg = struct('Wizard',0,...
    'DeleteExcluded',1,...
    'tmp',[],...
    'colclick',@i_ColClick);
varargout{1} = d;
varargout{2} = i_GetCallbacks;

return


%-----------------------------------------------------------------------
function cb = i_GetCallbacks
%-----------------------------------------------------------------------
cb = [];
cb.Draw = @i_Draw;


%-----------------------------------------------------------------------
function [d,fig] = i_Draw(d)
%-----------------------------------------------------------------------
fig = xregfigure('visible', 'off', 'WindowStyle', 'Modal'); %dialog
% Register the figure with CAGE
CGBH = cgbrowser;
CGBH.registersubfigure(double(fig), 'current');
fig.ResourceLocation = cgrespath;
[d,lyt] = i_DrawLyt(d,fig);
fig.LayoutManager = lyt;
set(lyt,'packstatus','on');

%-----------------------------------------------------------------------
function [d,lyt] = i_DrawLyt(d,fig)
%-----------------------------------------------------------------------
ILmanager = get(cgbrowser,'ILmanager');
IL=ILmanager.IL;

Handles = d.Dlg;
Handles.Figure = fig;

mfile = 'cgdatasetnodecb';
callbacks = {'rightclick',mfile;...
        'columnclick',mfile;...
        'click',mfile;...
        'keyup',mfile;...
        'dblclick',mfile;...
        'MouseMove','MotionManager'};

[Handles.LeftList,Handles.LeftListLyt] = ...
    pr_CreateList(double(fig), callbacks, 'top',IL);

[Handles.RightList,Handles.RightListLyt] = ...
    pr_CreateList(double(fig), callbacks, 'bottom',IL);

Handles.TopButton = xregGui.iconuicontrol('parent',fig,'visible','off');

Handles.BottomButton = xregGui.iconuicontrol('parent',fig,'visible','off');

lists = xreggridbaglayout(fig, ...
    'packstatus', 'off', ...
    'visible','off',...
    'dimension',[5 3],...
    'colsizes',[-1 32 -1],...
    'rowsizes', [-1 32 20 32 -1], ...
    'gapx', 20, ...
    'mergeblock', {[1 5], [1 1]}, ...
    'mergeblock', {[1 5], [3 3]}, ...
    'elements',{Handles.LeftListLyt , [], [], [], [], ...
        [], Handles.TopButton, [], Handles.BottomButton, [], ...
        Handles.RightListLyt});

Handles.Check1 = xregGui.uicontrol('parent',fig,'visible','off',...
    'style','checkbox');
Handles.Check2 = xregGui.uicontrol('parent',fig,'visible','off',...
    'style','checkbox');
Handles.Checks = xreggridlayout(fig,'visible','off',...
    'correctalg','on',...
    'dimension',[2 2],...
    'elements',{Handles.Check1 Handles.Check2 [] []});

Handles.MsgPane = xregGui.uicontrol('parent',fig,'visible','off',...
    'style','text',...
    'horizontalalignment','left',...
    'enable','inactive');
panel = xregpanellayout(fig, ...
    'visible', 'off', ...
    'center',Handles.MsgPane);
Handles.OK = xregGui.uicontrol('parent',fig,'visible','off',...
    'string','OK',...
    'callback',@i_OK);
Handles.Cancel = xregGui.uicontrol('parent',fig,'visible','off',...
    'string','Cancel',...
    'callback',@i_Cancel);
buttons1 = xreggridlayout(fig,'visible','off',...
    'correctalg','on',...
    'dimension',[1 3],...
    'colsizes',[-1 65 65], ...
    'gapx',10,...
    'elements',{panel Handles.OK Handles.Cancel});

Handles.MsgPane(2) = xregGui.uicontrol('parent',fig,'visible','off',...
    'style','text',...
    'horizontalalignment','left',...
    'enable','inactive');
panel = xregpanellayout(fig,'center',Handles.MsgPane,...
    'visible','off');
Handles.Back = xregGui.uicontrol('parent',fig,'visible','off',...
    'string','<- Back');
Handles.Next = xregGui.uicontrol('parent',fig,'visible','off',...
    'string','Next ->');
Handles.Cancel(2) = xregGui.uicontrol('parent',fig,'visible','off',...
    'string','Cancel');
buttons2 = xreggridlayout(fig,'visible','off',...
    'correctalg','on',...
    'dimension',[1 4],...
    'colsizes',[-1 65 65 65],...
    'gapx', 10, ...
    'elements',{panel Handles.Back Handles.Next Handles.Cancel(2)});

buttons = xregcardlayout(fig,'numcard2',2);
attach(buttons, buttons1, 1);
attach(buttons, buttons2, 2);
Handles.ButtonCard = buttons;

title = xregGui.uicontrol('parent',fig, ...
    'visible','off',...
    'style','text',...
    'horizontalalignment','left',...
    'enable','inactive');
Handles.Title = title;

Handles.MainLyt = xreggridlayout(fig,'visible','off',...
    'correctalg','on',...
    'dimension',[3 1],...
    'elements',{title lists []},...
    'gapy',10,...
    'rowsizes',[20 -1 0]);

frame = xregframetitlelayout(fig,'visible','off',...
    'center',Handles.MainLyt,...    
    'border',[0 5 0 0]);

lyt = xregborderlayout(fig,'visible','off',...
    'center',frame,...
    'south',buttons,...
    'innerborder',[0 25 0 0],...
    'border',[5 5 5 5]);

Handles.Lyt = lyt;

d.Dlg = Handles;

%-----------------------------------------------------------------------
function i_ColClick(d,list,col)
%-----------------------------------------------------------------------
switch lower(list)
case 'top'
    list = d.Dlg.LeftList;
case 'bottom'
    list = d.Dlg.RightList;
otherwise
    return
end

if list.ListItems.Count>0
    i = get(col,'subitemindex');
    oi = get(list,'sortkey');
    if i==oi
        v = get(list,'sortorder');
        v = 1-v;
    else
        v = 0;
    end
    set(list,'sortorder',v);
    set(list,'sortkey',i);
    set(list,'sorted',-1);
    s = get(list,'selecteditem');
    EnsureVisible(s);
end

