function [d, lyt] = DrawTabFillBtm(dsnd, d, IL, callbacks)
%DRAWTABFILLBTM

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.4.2.3 $  $Date: 2004/02/09 08:21:30 $

%------ Get the fill table callback ----
cb = FillTable(dsnd, 'get_callbacks');

%------ Figure Handle ------------------
fig = d.Handles.Figure;

%------ Create the lists ----------------
[d.Handles.TFListLeft,d.Handles.TFListLytLeft] = ...
    pr_CreateList(fig, callbacks, 'top',IL);
set(d.Handles.TFListLeft, 'FullRowSelect',1);
set(d.Handles.TFListLeft, 'userdata', 'tables');

[d.Handles.TFListMid,d.Handles.TFListLytMid] = ...
    pr_CreateList(fig, callbacks, 'top',IL);
set(d.Handles.TFListMid, 'FullRowSelect',1);
set(d.Handles.TFListMid, 'userdata', 'factors');

[d.Handles.TFListRight,d.Handles.TFListLytRight] = ...
    pr_CreateList(fig, callbacks, 'top',IL);
set(d.Handles.TFListRight, 'FullRowSelect',1);
set(d.Handles.TFListRight, 'userdata', 'rules');

%------ The Show Table Hist check box ---
d.Handles.TFCheck = xreguicontrol('parent', fig, ...
    'style', 'checkbox', ...
    'visible', 'off', ...
    'string', 'Show table history after fill', ...
    'value', 1);
        
%------ The Fill Table Button -----------
d.Handles.TFFillButton = xregGui.uicontrol('parent',fig, ...
    'style', 'pushbutton', ...
    'visible','off',...
    'string','Fill Table', ...
    'callback', cb.Fill);

%------ Create the overall layout -------

controlsLyt = xreggridbaglayout(fig, ...
    'packstatus', 'off', ...
    'dimension', [3 3], ...
    'colsizes', [150 -1 65], ...
    'rowsizes', [3 20 2], ...
    'mergeblock', {[1 3], [3 3]}, ...
    'elements', {[], d.Handles.TFCheck, [], [], [], [],  d.Handles.TFFillButton});

% centerLyt = xreggridbaglayout(fig, ...
%     'dimension', [2 3], ...
%     'rowsizes', [-1 25], ...
%     'gap', 10, ...
%     'border', [10 10 10 10], ...
%     'mergeblock', {[2 2], [1 3]}, ...
%     'elements', {d.Handles.TFListLytLeft, controlsLyt, ...
%     d.Handles.TFListLytMid, [], ...
%     d.Handles.TFListLytRight});

centerLyt = xreggridbaglayout(fig, ...
    'dimension', [3 2], ...
    'rowsizes', [-1 -1 25], ...
    'rowratios', [2 1 0], ...
    'colsizes', [-1 -1], ...
    'gap', 10, ...
    'border', [10 10 10 10], ...
    'mergeblock', {[2 2], [1 2]}, ...
    'mergeblock', {[3 3], [1 2]}, ...
    'elements', {d.Handles.TFListLytLeft, d.Handles.TFListLytRight, controlsLyt, ...
    d.Handles.TFListLytMid});

centerpanel = xregpanellayout(fig, ...
    'visible', 'off', ...
    'state', 'out', ...
    'center', centerLyt, ...
    'innerborder', [0 0 0 0]);

d.Handles.TFTextTop = xregpaneltitlelayout(fig, ...
    'visible','off', ...
    'titleheight', 30, ...
    'titlefontsize', 12, ...
    'titleborder', [0 0 0 -2], ...
    'center', centerpanel);
    
lyt = d.Handles.TFTextTop;
