function [lyt, tblyt, View]=CreateGui(P, info)
% CREATEGUI  Create the gui for testplan
%
%  [LYT, TBLYT, VIEWDATA]=CreateGui(TP, info)
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.
%   $Revision: 1.10.4.4 $  $Date: 2004/02/09 08:03:24 $



% Created 10/4/2001

hFig=info.Figure;
mbH= MBrowser;


%%% Menus %%%
View.menus.tools=mbH.CreateMenu(guid(P),1);
set(View.menus.tools,'label','&Data');
View.menus.view=mbH.CreateMenu(guid(P),1);
set(View.menus.view,'label','&View');

prfs = getpref(mbcprefs('mbc'), 'mdevproject');

t1 = xreguicontrol('parent',hFig,...
	'style','text',...
	'HorizontalAlign','left',...
	'string',' Data Sets',...
	'fontname','helvetica',...
	'FontSize',14,...
	'position',[0 0 80 25],...
	'visible','off',...
	'enable','inactive');

panelDatasetText = xregpanellayout(hFig,...
	'packstatus','off',...
	'packgroup','MDEVPROJ',...  
	'state', 'out',...
	'center', t1);

t2 = xreguicontrol('parent',hFig,...
	'style','text',...
	'HorizontalAlign','left',...
	'string',' Notes',...
	'fontname','helvetica',...
	'FontSize',14,...
	'position',[0 0 80 25],...
	'visible','off',...
	'enable','inactive');

panelNoteText = xregpanellayout(hFig,...
	'packgroup','MDEVPROJ',...  
	'state', 'out',...
	'center', t2);

% Get imageList info for the List Control
dataImageList = xregGui.ILmanager;
dataImageList.ResourceLocation = xregrespath;
dataImageList.bmp2ind('dataicon.bmp');
dataImageList.bmp2ind('testplandata.bmp');
dataImageList.IL.maskColor =  uint32(255*256);

dataList = xregGui.listview([10 10 10 10], hFig,...
	{'AfterLabelEdit' 'mdevproject_actxcallbacks';...
	'DblClick' 'mdevproject_actxcallbacks';...
	'KeyUp' 'mdevproject_actxcallbacks';...
	'MouseMove' 'MotionManager'});

dataList.InsertSmallIcons(dataImageList.IL);
dataList.Parent = hFig;
dataList.View = 3;
dataList.HideSelection = 0;
dataList.Sorted = 0;
dataList.LabelEdit = 0;
dataList.BorderStyle = 0;
dataList.Appearance = 0;
hCols = dataList.ColumnHeaders;
cols = {'Name' 'Records' 'Variables' 'Tests'};
width = [300 75 75 75];
align = {'lvwColumnLeft','lvwColumnRight','lvwColumnRight','lvwColumnRight'};
tag = {'','num','num','num'};
for k = 1:length(cols)
	hItem = hCols.Add;
   set(hItem,'Text',cols{k},...
      'Width',width(k),...
      'Alignment',align{k},...
      'Tag',tag{k});
end
% Set the userdata to identify the control in the callback
dataList.userdata = 'dataList';

View.dataList = dataList;

% Get imageList info for the List Control
noteImageList = xregGui.ILmanager;
noteImageList.ResourceLocation = xregrespath;
noteImageList.bmp2ind('note.bmp');
noteImageList.bmp2ind('note_lock.bmp');
noteImageList.IL.maskColor = uint32(255*256);

noteList = xregGui.listview([10 10 10 10], hFig,...
	{'AfterLabelEdit' 'mdevproject_actxcallbacks';...
	'KeyUp' 'mdevproject_actxcallbacks';...
	'MouseMove' 'MotionManager'});
noteList.InsertSmallIcons(noteImageList.IL);
noteList.Parent = hFig;
noteList.View = 3;
noteList.HideSelection = 0;
noteList.Sorted = 0;
noteList.LabelEdit = 0;
noteList.BorderStyle = 0;
noteList.Appearance = 0;
hCols = noteList.ColumnHeaders;
cols = {'Note' 'User' 'Company' 'Department' 'Contact Information' 'Date' 'Time'};
width = [400 100 100 100 100 75 75];
colstoshow = prfs.NotesListColumns;
for k = find(colstoshow)
	hItem = hCols.Add;
	hItem.Text = cols{k};
	hItem.Width = width(k);
end
% Set the userdata to identify the control in the callback
noteList.userdata = 'noteList';

View.noteList = noteList;

topGrid = xreggridbaglayout(hFig,...
	'dimension', [2 1],...
	'packgroup','MDEVPROJ',...  
	'elements', {panelDatasetText actxcontainer(dataList)},...
	'rowsizes',[25 -1]);

topPanel = xregpanellayout(hFig,...
	'packgroup','MDEVPROJ',...  
	'state', 'in',...
	'innerborder', [0 0 0 0],...
	'center', topGrid);

bottomGrid = xreggridbaglayout(hFig,...
	'dimension', [2 1],...
	'packgroup','MDEVPROJ',...  
	'elements', {panelNoteText actxcontainer(noteList)},...
	'rowsizes',[25 -1]);

bottomPanel = xregpanellayout(hFig,...
	'packgroup','MDEVPROJ',...  
	'state', 'in',...
	'innerborder', [0 0 0 0],...
	'center', bottomGrid);

splitLayout = xregsplitlayout(hFig,...
	'packgroup','MDEVPROJ',...  
	'orientation', 'ud',...
	'top', topPanel,...
	'bottom', bottomPanel,...
	'dividerstyle', 'flat',...
	'dividerwidth', 4,...
	'minwidth', [100 100],...
	'split', [0.5 0.5]);

% Set up the tip-of-the-day layout
tipTitleText = xreguicontrol('parent',hFig,...
	'style','text',...
	'HorizontalAlign','left',...
	'string',' Tip of the day',...
	'fontname','helvetica',...
	'FontSize',12,...
	'position',[0 0 80 25],...
	'visible','off',...
	'enable','inactive');

tipNo = ceil(sum(100*clock));

tipText = xreguicontrol('parent',hFig,...
	'style','text',...
	'HorizontalAlign','left',...
	'string', getTipOfTheDay(tipNo),...
	'userdata', tipNo,...
	'visible','off',...
	'enable','inactive');

btNextTip = xreguicontrol('parent', hFig,...
	'fontname', 'marlett',...
	'fontsize', 12,...
	'tooltipstring', 'Click to show next tip',...
	'string', '4',...
	'callback', {@i_changeTip tipText +1});

btPrevTip = xreguicontrol('parent', hFig,...
	'fontname', 'marlett',...
	'fontsize', 12,...
	'tooltipstring', 'Click to show previous tip',...
	'string', '3',...
	'callback', {@i_changeTip tipText -1});

tipGridLayout = xreggridbaglayout(hFig,...
	'packgroup', 'MDEVPROJ',...
	'dimension', [3 3],...
	'mergeblock', {[1 1] [1 3]},...
	'mergeblock', {[2 2] [1 3]},...
	'elements', {tipTitleText tipText btPrevTip [] [] [] [] [] btNextTip},...
	'border', [5 5 5 5],...
	'gapy', 10,...
	'colsizes', [20 -1 20],...
	'rowsizes', [25 -1 20]);

tipPanelLayout = xregpanellayout(hFig,...
	'packgroup','MDEVPROJ',...  
	'state', 'in',...
	'innerborder', [0 0 0 0],...
	'border', [0 0 -3 0],...
	'center', tipGridLayout);
	
p = getpref(mbcprefs('mbc'), 'mdevproject');

lyt = xregsnapsplitlayout(hFig,...
	'packgroup', 'MDEVPROJ',...
	'barstyle', 1,...
	'orientation', 'lr',...
	'left', splitLayout,...
	'right', tipPanelLayout,...
	'minwidth',[400 120],...
	'state', prfs.SnapSplitLayoutState,...
	'split', [0.8 0.2],...
	'border', [-1 -1 2 -1],...
	'style','toright');

View.layout = lyt;

% Get function handles for callbacks
cbs=Callbacks(P,'GetToolbarHandles');

% Create the toolbar to display with the mdevproject node
hToolbar = xregGui.uitoolbar('parent', hFig,...
	'ResourceLocation', xregrespath);

[tblyt, buttons] = xregtoolbar(hToolbar, {'uipush';'uipush';'uipush';'uipush'},...
	{'imageFile'}, {'newData.bmp';'copyData.bmp';'editData.bmp';'newnote.bmp'},...
	{'Tooltipstring'}, {'New Data Object';'Copy Data Object';'Edit Data Object';'Add New Note'},...
	{'clickedcallback'}, cbs([1 2 3 5]),...
	{'separator'}, {'off';'off';'off';'on'},...
	'transparentcolor', [0 255 0]);
View.toolbarBtns = buttons;

% Create the Tools menu
Labels =  {'&New Data...' '&Copy Data' '&Edit Data...' '&Delete Data'};
CallBacks = cbs([1 2 3 4]);
View.toolsMenuItems = xregmenutool('create', View.menus.tools, 'Label', Labels, 'Callback', CallBacks);

% Create the View menu
Labels =  {'&Tip of the Day','&Note Information...'};
CallBacks = {{cbs{7} View.layout} cbs{8}};
for n = 1:length(Labels)
   hItems(n) = uimenu('parent', View.menus.view, 'Label', Labels{n}, 'Callback', CallBacks{n});
end
View.viewMenuItems = hItems;
if strcmp(prfs.SnapSplitLayoutState,'center')
   set(View.viewMenuItems(1),'checked','on');
end
set(View.menus.view,'callback',{cbs{6},View.layout,hItems(1)});
return


function i_changeTip(src, evt, tipText, direction)

tipNo = get(tipText, 'userdata');
newTipNo = tipNo + direction;
set(tipText, 'string', getTipOfTheDay(newTipNo), 'userdata', newTipNo);
