function gui_notessetup(MP)
%GUI_NOTESSETUP  Pop up a dialog for changing the columns viewed for Notes
%
%  GUI_NOTESSETUP(MP)
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.3.2.4 $  $Date: 2004/04/04 03:31:24 $

% This function will create a small dialog for choosing which columns to
% view in the Notes list in the Model Browser.  The settings are saved in
% the mbc preferences


scr = get(0,'screensize');
pos = [(scr(3)/2)-75 (scr(4)/2)-100 200 250];
hFig = xregdialog('Name','Notes Display Setup',...
   'resize','off');
xregpersistfigpos(hFig,'key','xregProjectNotesSetup','defaultpos',pos);
xregmoveonscreen(hFig);


infotxt = uicontrol('parent',hFig,...
   'style','text',...
   'horizontalalignment','left',...
   'string','Choose the information that you want to display in the project''s Notes list:'); 


prfs = getpref(mbcprefs('mbc'),'mdevproject');
settings = prfs.NotesListColumns;
str = {'Note contents', 'User name', 'Company name', 'Department name', 'Contact Information', 'Date of note', 'Time of note'};
nChecks = length(settings);
hChecks = cell(nChecks,1);
for  k = 1:nChecks
   hChecks{k} = uicontrol('parent',hFig,...
      'style','checkbox',...
      'string',str{k},...
      'value',settings(k));
end
set(hChecks{1},'enable','off');

okbtn = uicontrol('parent',hFig,...
   'style','pushbutton',...
   'string','OK',...
   'callback','set(gcbf,''tag'',''ok'',''visible'',''off'');');
cancbtn = uicontrol('parent',hFig,...
   'style','pushbutton',...
   'string','Cancel',...
   'callback','set(gcbf,''visible'',''off'');');

grid = xreggridbaglayout(hFig,...
   'packstatus','off',...
   'dimension',[7 1],...
   'rowsizes',repmat(20,1,nChecks),...
   'elements',hChecks);
frame = xregframetitlelayout(hFig,...
   'center',grid,...
   'innerborder',[5 5 5 5]);
lyt = xreggridbaglayout(hFig,...
   'packstatus','off',...
   'dimension',[4 3],...
   'colsizes',[-1 65 65],...
   'rowsizes',[30 -1 0 25],...
   'gapy',5,...
   'gapx',7,...
   'border',[7 7 7 7],...
   'mergeblock',{[1 1], [1 3]},...
   'mergeblock',{[2 2], [1 3]},...
   'elements',{infotxt,frame,[],[],[],[],[],okbtn,[],[],[],cancbtn});

hFig.LayoutManager = lyt;
set(lyt,'packstatus','on');
hFig.showDialog(okbtn);

tg = get(hFig,'tag');
if strcmp(tg,'ok')
   vals = get([hChecks{:}],{'value'});
   vals = [vals{:}];
   vals = (vals~=0);
   prfs.NotesListColumns = vals(:)';
   setpref(mbcprefs('mbc'),'mdevproject',prfs);
end
delete(hFig); 