function hpfig = displayftsfcnresult(ftsData, ftsName, ftsFcn)
%DISPLAYFTSFCNRESULT Displays/Plots the resulting timeseries data under FTS GUI.
%

%   Author: P. N. Secakusuma, 01-10-2000
%   Copyright 1995-2003 The MathWorks, Inc.
%   $Revision: 1.5.2.2 $   $Date: 2004/04/06 01:09:41 $

mainFTSGUIWindow = findall(0, 'Type', 'figure', ...
    'Tag', 'FTSGUIMainWindow');
hChildrenFigs = getappdata(mainFTSGUIWindow, 'ChildrenFigures');

hpfig = figure('Visible', 'off');
pidx = mod(hpfig-1, 7) + 1;
sidx = floor((hpfig-1)/7);
set(hpfig, 'NumberTitle', 'off', ...
    'Name', deblank(ftsData.desc), ...
    'Units', 'normal', ...
    'Position', [0.0375+(pidx*0.02)+(sidx*0.15) 0.475-(pidx-1)*0.02 0.3 0.3], ...
    'CloseRequestFcn', ['try, ', ...
    '   mainFTSGUIWindow = findall(0, ''Type'', ''figure'', ', ...
    '									     ''Tag'', ''FTSGUIMainWindow''); ', ...
    '   hChildrenFigs = getappdata(mainFTSGUIWindow, ''ChildrenFigures''); ', ...
    '   hCurrentFigs = find(hChildrenFigs ~= gcf); ', ...
    '   setappdata(mainFTSGUIWindow, ''ChildrenFigures'', hChildrenFigs(hCurrentFigs)); ', ...
    '   infostorage = getappdata(mainFTSGUIWindow, ''FTS_Data''); ', ...
    '   dname_idx = ~strcmp(get(gcf, ''UserData''), infostorage.itemnames); ', ...
    '   infostorage.itemcount = infostorage.itemcount - 1; ', ...
    '   infostorage.itemnames = infostorage.itemnames(dname_idx); ', ...
    '   infostorage.itemdesc  = infostorage.itemdesc(dname_idx); ', ...
    '   infostorage.items     = infostorage.items(dname_idx); ', ...
    '   infostorage.itemtypes = infostorage.itemtypes(dname_idx); ', ...
    '   infostorage.activefts = []; ', ...
    '   infostorage.activefig = []; ', ...
    '   setappdata(mainFTSGUIWindow, ''FTS_Data'', infostorage); ', ...
    '   closereq; ', ...
    '   set(mainFTSGUIWindow, ''Name'', getappdata(mainFTSGUIWindow, ''MainFigureName'')); ', ...
    'catch, ', ...
    '   closereq; ', ...
    'end;'], ...
    'ButtonDownFcn', 'ftsfilemenu(1, 2, '''')', ...
    'CreateFcn', ['mainFTSGUIWindow = findall(0, ''Type'', ''figure'', ', ...
    '                           ''Tag'', ''FTSGUIMainWindow'');', ...
    'infostorage = getappdata(mainFTSGUIWindow, ''FTS_Data'');', ...
    ['infostorage.activefts = ''', ftsName, ''';'], ...
    'setappdata(mainFTSGUIWindow, ''FTS_Data'', infostorage);'], ...
    'UserData', ftsName, ...
    'Visible', 'off', ...
    'Tag', ['Plot_', ftsFcn, ftsName]);
hplot = plot(ftsData);
set(hpfig, 'Visible', 'on');
pause(0);
setappdata(mainFTSGUIWindow, 'ChildrenFigures', [hChildrenFigs, hpfig]);

return
