function h = prefs(varargin)
%PREFS  Class instantiation function (for osek.prefs).

%   Copyright 1994-2002 The MathWorks, Inc.
%   $Revision: 1.2 $  $Date: 2002/10/23 01:49:12 $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTE:
% - This file was automatically generated by the Simulink data class designer.
% - The contents of this file are arranged so that the Simulink data class
%   designer can load the associated classes for editing.
% - Hand modification of this file is not recommended as it may prevent the
%   Simulink class designer from loading the associated classes.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% - Generated on:   05-Sep-2002 09:05:29
% - MATLAB version: 6.5.0.183862a (R13)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%% Instantiate class
h = osek.prefs;

%%%% Initialize property values
% ENTER CLASS INITIALIZATION CODE HERE (optional) ...
h.ToolChain = osek.ToolChain;
file = java.io.File('hello');
