%CLEAR	Clear various quantities from the workspace.
%	CLEAR removes all variables from the workspace.
%	CLEAR VARIABLES does the same thing.
%	CLEAR X removes variable or function X from the workspace.
%	CLEAR FUNCTIONS removes all compiled M-functions.
%	CLEAR MEX removes all links to MEX-files.
%	CLEAR ALL removes all variables, functions and MEX links.
%
%	If X is global, CLEAR X removes X from the current workspace,
%	but leaves it accessible to any functions declaring it global.
%	CLEAR GLOBAL X completely removes the global variable X.
%	CLEAR GLOBAL removes all global variables.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
