%ECHO	Echo commands inside script files. 
%	ECHO ON turns on echoing of commands inside Script-files. 
% 	ECHO OFF turns off echoing.
% 	ECHO file ON where 'file' is a function name causes the
% 	named Function-file to be echoed when it is used.
% 	ECHO file OFF turns it off.
% 	ECHO file toggles it.
% 	ECHO ON ALL turns on the echoing of commands inside all
% 	Function-files. ECHO OFF ALL turns them all off.
%
% 	See also FUNCTION, SCRIPT.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
