%FORMAT	Set output format.
%	All computations in MATLAB are done in double precision.
%	FORMAT may be used to switch between different output
% 	display formats as follows:
% 	  FORMAT         Default. Same as SHORT.
% 	  FORMAT SHORT   Scaled fixed point format with 5 digits.
% 	  FORMAT LONG    Scaled fixed point format with 15 digits.
% 	  FORMAT SHORT E Floating point format with 5 digits.
% 	  FORMAT LONG E  Floating point format with 15 digits.
% 	  FORMAT HEX     Hexadecimal format.
% 	  FORMAT +       The symbols +, - and blank are printed 
% 	                 for positive, negative and zero elements.
% 	                 Imaginary parts are ignored.
% 	  FORMAT BANK    Fixed format for dollars and cents.
% 	  FORMAT COMPACT Suppress extra line-feeds.
% 	  FORMAT LOOSE   Puts the extra line-feeds back in.
%	  FORMAT RAT     Approximation by ratio of small integers.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
