%MEMORY	MATLAB memory limitations.
%	If the OUT OF MEMORY error message is encountered, there is
%	no more room in memory for new variables. You must free up
%	some space before you may proceed. One way to free up space
%	is to delete some variables (see CLEAR). Another is to
%	issue the command PACK (See PACK). PACK compresses the data
%	in memory, opening up larger contiguous blocks.
%
%	Here are some additional system specific tips:
%	MS-Windows: Increase the swap space by opening the Control
%	            Panel, double-clicking on the 386 Enhanced icon,
%	            and pressing the Virtual Memory button.
%   	Macintosh:  Under Multi-Finder, change the application memory
%	            size by using 'Get Info' on the program icon.
%	            Under Single-Finder, install more memory.
%	VAX/VMS:    Ask your system manager to increase your Working Set
%	            and/or Pagefile Quota.
%	Unix:       Ask your system manager to increase your Swap Space.

%	Copyright (c) 1984-94 by The MathWorks, Inc.

