%MORE	Control paged output for the command window.
%	MORE OFF disables paging of the output in the MATLAB command window.
%	MORE ON enables paging of the output in the MATLAB command window.
%	MORE(N) specifies the size of the page to be N lines.
%	The defaults are OFF and N = 23.
%
%	When MORE is enabled and output is being paged, advance to the next
%	line of output by hitting the RETURN key;  get the next page of
%	output by hitting the spacebar. Press the "q" key to exit out
%   	of displaying the current item.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
