%PACK	Consolidate workspace memory.
%	PACK performs memory garbage collection. Extended MATLAB
% 	sessions may cause memory to become fragmented, preventing
% 	large variables from being stored. PACK is a command that
% 	saves all variables on disk, clears the memory, and then
% 	reloads the variables.
%
%	See also MEMORY.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
