%WHAT	List M-, MAT- and MEX-files.
%	The command WHAT, by itself, lists the M-files, MAT-files
%	and MEX-files in the current working directory.
%	The command WHAT DIRNAME lists the files in directory dirname
%	on the MATLABPATH.  It is not necessary to give the full path
%	name of the directory; the last component, or last several
%	components, are sufficient.
%
%	For example, "what general" and "what matlab/general" both
%	list the M-files in directory toolbox/matlab/general.
%
%	See also DIR, WHO, WHICH, LOOKFOR.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
