function [errflag, out] = privatePropDesc(propname,classtype)
%PRIVATEPROPDESC Display property information for OPC objects.
%   PRIVATEPROPDESC(PropertyName,ClassType) displays property information
%   for OPC object property, PropertyName of a given ClassType.
%   PropertyName and ClassType must be a strings.
%
%   Example:
%       privatepropdesc('updaterate','dagroup')
%
%   See also OPCHELP, PROPINFO.

%    PRIVATEPROPDESC is a helper function for OPCHELP.

% Copyright 2003-2004 OPTI-NUM solutions (Pty) Ltd.
% $Revision: 1.1.6.9 $  $Date: 2004/03/24 20:43:50 $

% Initialize variables.
errflag = false;
out=[];

% Check if the property is valid for the specified object type.
if ~isempty(classtype)
   errflag = localValidProp(propname, classtype);
   if errflag
      return;
   end
end

% Create display or error.
[errflag, out] = localDisplay(lower(propname));
if errflag
   return;
end

%******************************************************************
% Determine if the property is valid.
function errflag = localValidProp(propname, classtype)

% Initialize variables.
errflag = false;

propstruct.accessrights = {'daitem'};       
propstruct.active = {'dagroup','daitem'};   
propstruct.cancelasyncfcn = {'dagroup'};    
propstruct.canonicaldatatype = {'daitem'};  
propstruct.datachangefcn = {'dagroup'};     
propstruct.datatype = {'daitem'};           
propstruct.deadbandpercent = {'dagroup'};   
propstruct.errorfcn = {'opcda'};            
propstruct.eventlog = {'opcda'};            
propstruct.eventlogmax = {'opcda'};         
propstruct.grouptype = {'dagroup'};         
propstruct.group = {'opcda'};               
propstruct.host = {'opcda'};                
propstruct.itemid = {'daitem'};             
propstruct.item = {'dagroup'};              
propstruct.languageid = {'dagroup'};        
propstruct.logfilename = {'dagroup'};        
propstruct.logging = {'dagroup'};        
propstruct.loggingmode = {'dagroup'};        
propstruct.logtodiskmode = {'dagroup'};        
propstruct.name = {'opcda','dagroup'};      
propstruct.parent = {'dagroup','daitem'};   
propstruct.quality = {'daitem'};            
propstruct.readasyncfcn = {'dagroup'};      
propstruct.recordsacquired = {'dagroup'};      
propstruct.recordsacquiredfcn = {'dagroup'};      
propstruct.recordsacquiredfcncount = {'dagroup'};      
propstruct.recordsavailable = {'dagroup'};      
propstruct.recordstoacquire = {'dagroup'};      
propstruct.scanrate = {'daitem'};           
propstruct.serverid = {'opcda'};            
propstruct.shutdownfcn = {'opcda'};         
propstruct.startfcn = {'dagroup'};      
propstruct.status = {'opcda'};              
propstruct.stopfcn = {'dagroup'};      
propstruct.subscription = {'dagroup'};      
propstruct.tag = {'opcda','dagroup','daitem'};  
propstruct.timebias = {'dagroup'};          
propstruct.timeout = {'opcda'};             
propstruct.timestamp = {'daitem'};          
propstruct.timerfcn = {'opcda'};            
propstruct.timerperiod = {'opcda'};         
propstruct.type = {'opcda','dagroup','daitem'}; 
propstruct.updaterate = {'dagroup'};        
propstruct.userdata = {'opcda','dagroup','daitem'}; 
propstruct.value = {'daitem'};              
propstruct.writeasyncfcn = {'dagroup'};     

% Determine if the correct class was defined.
validtype = propstruct.(lower(propname));
if ~strcmp(classtype, validtype)
   errflag = true;
   lasterr(['Invalid property ''' classtype '.' propname '''.']);
   return;
end


%******************************************************************
% Create the display for each property.
function [errflag, out] = localDisplay(propname)

errflag = false;

switch lower(propname)
case 'accessrights'
out = sprintf([ ...
'   ACCESSRIGHTS  [ ''read'' | ''write'' | ''read/write'' ] (Read-only: always)\n\n', ...
'   Inherent nature of access to item.\n\n', ...
'   AccessRights represents the server''s ability to access a single OPC \n', ...
'   data item. The property values can be ''read'', ''write'', \n', ...
'   ''read/write''. If AccessRights is ''read'', you can read the data \n', ...
'   item''s value. If AccessRights is ''write'', you can write values to \n', ...
'   the data item. If AccessRights is ''read/write'', you can read and \n', ...
'   change the data item''s value. If you attempt a read or write \n', ...
'   operation on an item that does not have the required access rights, \n', ...
'   the server may return an error.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/REFRESH, \n', ...
'      DAGROUP/WRITE, DAGROUP/WRITEASYNC, Subscription\n', ...
'']);

case 'active'
out = sprintf([ ...
'   ACTIVE  [ ''off'' | {''on''} ] (Read-only: never)\n\n', ...
'   Group or item activation state.\n\n', ...
'   Active can be ''on'' or ''off''. If Active is ''on'', the OPC server \n', ...
'   will return data for the group or item when requested by the READ \n', ...
'   function or when the corresponding data items change (subscriptions). \n', ...
'   If Active is ''off'', the OPC server will not return information about \n', ...
'   the members of a group or a specific item.\n\n', ...
'   By default, Active is set to ''on'' when you create a dagroup or \n', ...
'   daitem object. You would set Active to ''off'' when you are \n', ...
'   temporarily not interested in that daitem or dagroup object''s values. \n', ...
'   You can configure Active for both dagroup (which affects all the \n', ...
'   members of the group) and/or specific daitem objects.\n\n', ...
'   The activation state of a dagroup or daitem object affects reads and \n', ...
'   subscriptions, and depends on whether the data is obtained from the \n', ...
'   cache or from the device. The active state of a group or item affects \n', ...
'   operations as follows:\n\n', ...
'      READ (cache): Both group and items must be active. Inactive items \n', ...
'         in active groups, and all items in inactive groups, return bad \n', ...
'         quality.\n', ...
'      READ (device): The Active property is ignored, and information is \n', ...
'         returned from the device.\n', ...
'      WRITE: The Active property is ignored, and values are written to \n', ...
'         the device.\n', ...
'      Subscription: Both group and items must be active. Inactive items \n', ...
'         in active groups, and all items in inactive groups, return bad \n', ...
'         quality.\n', ...
'      READASYNC: The Active property is ignored, and values are read from \n', ...
'         the device.\n', ...
'   A transition from ''off'' to ''on'' will result in a change in \n', ...
'   quality, and will cause a subscription callback for the item or items \n', ...
'   affected. Changing the Active state from ''on'' to ''off'' will cause \n', ...
'   a change in quality but will not cause a callback since by definition \n', ...
'   callbacks do not occur for inactive items. \n\n', ...
'   You enable subscription callbacks with the Subscription property. Use \n', ...
'   the DataChangeFcn property to specify an M-file callback function to \n', ...
'   execute when a data change event occurs.\n\n', ...
'   Applies To: DAGROUP, DAITEM\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/REFRESH, \n', ...
'      DataChangeFcn, Subscription\n', ...
'']);

case 'cancelasyncfcn'
out = sprintf([ ...
'   CANCELASYNCFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when an asynchronous operation is \n', ...
'   cancelled. \n\n', ...
'   You configure CancelAsyncFcn to execute an M-file callback function \n', ...
'   when a CancelAsync event occurs. A CancelAsync event occurs after an \n', ...
'   asynchronous read or write operation is cancelled. \n\n', ...
'   When a CancelAsync event occurs, the function specified in \n', ...
'   CancelAsyncFcn is passed two parameters: Obj and EventInfo. Obj is the \n', ...
'   object associated with the event, and EventInfo is an event structure \n', ...
'   containing the fields Type and Data. The Type field is set to \n', ...
'   ''CancelAsync''. The Data field contains a structure with the fields:\n\n', ...
'      ''LocalEventTime'' - The time, as a MATLAB date vector, that the \n', ...
'         event occurred.\n', ...
'      ''TransID'' - The transaction ID of the cancelled read or write \n', ...
'         asynchronous operation.\n', ...
'      ''GroupName'' - The group name.\n', ...
'   The default value for CancelAsyncFcn is @opccallback.\n\n', ...
'   CancelAsync event information is stored in the EventLog property.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/CANCELASYNC, OPCCALLBACK, DAGROUP/READASYNC, \n', ...
'      DAGROUP/WRITEASYNC, EventLog\n', ...
'']);

case 'canonicaldatatype'
out = sprintf([ ...
'   CANONICALDATATYPE  string (Read-only: always)\n\n', ...
'   Server''s data type for the item.\n\n', ...
'   CanonicalDataType indicates the data type of the item as stored on the \n', ...
'   OPC server. The MATLAB supported data types are as for the DataType \n', ...
'   property.\n\n', ...
'   You can specify that the item''s value is stored in the daitem object \n', ...
'   using a data type that differs from the canonical data type, by \n', ...
'   setting the DataType property of the item to a value different from \n', ...
'   CanonicalDataType. Translation between the CanonicalDataType and the \n', ...
'   daitem DataType is automatic.\n\n', ...
'   Refer to the DataType property reference for a listing of the COM \n', ...
'   VARIANT data types and their equivalent MATLAB data types.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/ADDITEM, DataType\n', ...
'']);

case 'datachangefcn'
out = sprintf([ ...
'   DATACHANGEFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when a data change event occurs \n\n', ...
'   You configure DataChangeFcn to execute an M-file callback function \n', ...
'   when a data change event occurs. A data change event occurs for \n', ...
'   subscribed active items within an active group when the value or \n', ...
'   quality of the item has changed. The events will happen no faster than \n', ...
'   the time specified for the UpdateRate property of the group. The \n', ...
'   DeadBandPercent property is used to determine what percentage change \n', ...
'   in the value or quality initiates the callback. A data change event is \n', ...
'   only generated when both the Active and Subscription properties are \n', ...
'   ''on''.\n\n', ...
'   When a DataChange event occurs, the function specified in \n', ...
'   DataChangeFcn is passed two parameters: Obj and EventInfo. Obj is the \n', ...
'   object associated with the event, and EventInfo is an event structure \n', ...
'   containing the fields Type and Data. The Type field is set to \n', ...
'   ''DataChange''. The Data field contains a structure with the fields:\n\n', ...
'      ''LocalEventTime'' - The time the event occurred\n', ...
'      ''TransID'' - 0, or the Refresh transaction ID if the DataChange \n', ...
'         event was generated by REFRESH.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''Items'' - A structure containing information about each item \n', ...
'         whose value or quality updated.\n', ...
'   The Items structure contains the following fields.\n\n', ...
'      ''ItemID'' - The fully qualified item name\n', ...
'      ''Value'' - The data value.\n', ...
'      ''Quality'' - The data quality as a string.\n', ...
'      ''TimeStamp'' - The time, as a date vector, the Server''s cache was \n', ...
'         updated.\n', ...
'   DataChange event information is not stored in the EventLog property.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also OPCCALLBACK, DAGROUP/REFRESH, Active, DeadBandPercent, \n', ...
'      Subscription, Updaterate\n', ...
'']);

case 'datatype'
out = sprintf([ ...
'   DATATYPE  string (Read-only: whileLogging)\n\n', ...
'   Client item''s data type .\n\n', ...
'   DataType indicates the data type of the item as stored in the daitem \n', ...
'   object in MATLAB. You specify the data type when the item is created \n', ...
'   using the ADDITEM function. If you do not specify a data type, or if \n', ...
'   the requested data type is rejected by the server, the canonical \n', ...
'   (native) data type is used. The canonical data type is the data type \n', ...
'   that the OPC server uses to store the item value. The \n', ...
'   CanonicalDataType property of a daitem object provides information on \n', ...
'   the canonical data type of that item on the server.\n\n', ...
'   OPC communication uses COM Variant data types to send information \n', ...
'   between the server and client. These are automatically translated to \n', ...
'   an equivalent MATLAB data type for the COM Variant types defined \n', ...
'   below. Any data type not included in this list is returned as \n', ...
'   ''unknown''.\n\n', ...
'      COM Data Type   MATLAB Data Type\n', ...
'      VT_BOOL         logical\n', ...
'      VT_I1           int8\n', ...
'      VT_BOOL         logical\n', ...
'      VT_I1           int8\n', ...
'      VT_I2           int16\n', ...
'      VT_I4           int32\n', ...
'      VT_CY           double\n', ...
'      VT_R4           single\n', ...
'      VT_R8           double\n', ...
'      VT_BSTR         char\n', ...
'      VT_DATE         double\n', ...
'      VT_UI1          uint8\n', ...
'      VT_UI2          uint16\n', ...
'      VT_UI4          uint32\n', ...
'      VT_EMPTY        Empty array\n', ...
'   The value of DataType cannot be modified while the parent dagroup \n', ...
'   object is logging.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/ADDITEM, CanonicalDataType\n', ...
'']);

case 'deadbandpercent'
out = sprintf([ ...
'   DEADBANDPERCENT  [0.0 100] (Read-only: never)\n\n', ...
'   Percentage change in an analogue item value that causes a subscription \n', ...
'   callback.\n\n', ...
'   You configure DeadbandPercent to a value between 0 and 100. The \n', ...
'   default value is 0, which specifies that any value change will update \n', ...
'   the OPC server''s cache. A non-zero value results in the cache value \n', ...
'   being updated only if the difference between the cached value and the \n', ...
'   current value of the item exceeds \n\n', ...
'   DeadbandPercent * (High EU – Low EU) / 100\n\n', ...
'   The DeadbandPercent property only affects items that have an analogue \n', ...
'   data type and ''High EU'' and ''Low EU'' properties defined (Property \n', ...
'   IDs 102 and 103 respectively). You can query data types and item \n', ...
'   properties using SERVERITEMPROPS. \n\n', ...
'   NOTE: OPC Servers may not implement the DeadbandPercent property \n', ...
'   behaviour, even for values that have High EU and Low EU properties \n', ...
'   defined. For servers that do not support DeadBandPercent, an error \n', ...
'   will be generated if you attempt to set the DeadbandPercent property \n', ...
'   to a value other than 0.\n\n', ...
'   DeadbandPercent is applied group wide for all analogue daitem objects, \n', ...
'   and is used to prevent noisy signals from updating the client \n', ...
'   unnecessarily. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also OPCDA/SERVERITEMPROPS, Active, Subscription, UpdateRate\n', ...
'']);

case 'errorfcn'
out = sprintf([ ...
'   ERRORFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when an error event occurs.\n\n', ...
'   You configure ErrorFcn to execute an M-file callback function when an \n', ...
'   error event occurs. An error event is generated when an asynchronous \n', ...
'   transaction fails. For example, an asynchronous read on items that \n', ...
'   cannot be read will generate an error event. An error event is not \n', ...
'   generated for configuration errors such as setting an invalid property \n', ...
'   value, nor for synchronous read and write operations.\n\n', ...
'   When an Error event occurs, the function specified in ErrorFcn is \n', ...
'   passed two parameters: Obj and EventInfo. Obj is the object associated \n', ...
'   with the event, and EventInfo is an event structure containing the \n', ...
'   fields Type and Data. The Type field is set to ''Error''. The Data \n', ...
'   field contains a structure with the fields: \n\n', ...
'      ''LocalEventTime'' - The local time (as a date vector) the event \n', ...
'         occurred.\n', ...
'      ''TransID'' - The transaction ID associated with the event.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''Items'' - A structure containing information about each item \n', ...
'         whose value or quality updated.\n', ...
'   The Items structure contains the following fields.\n\n', ...
'      ''ItemID'' - The fully qualified item name\n', ...
'   – ''Error'' - The error message.\n\n', ...
'   The default value for ErrorFcn is @opccallback. OPCCALLBACK displays \n', ...
'   the event information to the Command Window.\n\n', ...
'   Error event information is stored in the EventLog property. \n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCCALLBACK, SHOWOPCEVENTS, EventLog, TimeOut\n', ...
'']);

case 'eventlog'
out = sprintf([ ...
'   EVENTLOG  structure array (Read-only: always)\n\n', ...
'   Event information log.\n\n', ...
'   EventLog contains a structure array that stores information related to \n', ...
'   OPC Toolbox events. Every element in the structure array corresponds \n', ...
'   to an event.\n\n', ...
'   Each element in the EventLog structure contains the fields Type and \n', ...
'   Data. The Type value can be ''WriteAsync'', ''ReadAsync'', \n', ...
'   ''CancelAsync'', ''Shutdown'', ''Start'', ''Stop'' or ''Error''. \n\n', ...
'   Data stores event-specific information as a structure. For information \n', ...
'   on the fields contained in Data, refer to the associated callback \n', ...
'   property reference pages. For example, to find information on the \n', ...
'   fields contained in Data for a Start event, refer to the StartFcn \n', ...
'   property.\n\n', ...
'   Note that DataChange events are not stored in the EventLog. If you \n', ...
'   want to store DataChange events, you can log data to disk using the \n', ...
'   START function or specify a DataChangeFcn callback.\n\n', ...
'   You specify the maximum number of events to store with the EventLogMax \n', ...
'   property. When the number of events in the event log reaches \n', ...
'   EventLogMax, the event log is emptied. You can execute a callback \n', ...
'   function when an event occurs by specifying a function for the \n', ...
'   associated callback property. For example, to execute a callback when \n', ...
'   a ReadAsync event is generated, you use the ReadAsyncFcn property.\n\n', ...
'   You clear the event log using the CLEAREVENTLOG function.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/CLEAREVENTLOG, DAGROUP/START, CancelCompleteFcn, \n', ...
'      DataChangeFcn, EventLogMax, ErrorFcn, ReadCompleteFcn, StartFcn, \n', ...
'      StopFcn, WriteCompleteFcn\n', ...
'']);

case 'eventlogmax'
out = sprintf([ ...
'   EVENTLOGMAX  [0 Inf] (Read-only: never)\n\n', ...
'   Maximum number of events to store in the event log. \n\n', ...
'   When the number of events in the event log reaches EventLogMax, the \n', ...
'   event log is cleared. By default, EventLogMax is set to 1000. To \n', ...
'   continually store events, specify a value of Inf. To store no events, \n', ...
'   specify a value of 0.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/CLEAREVENTLOG, EventLog\n', ...
'']);

case 'group'
out = sprintf([ ...
'   GROUP  object array (Read-only: always)\n\n', ...
'   Client group array\n\n', ...
'   Group is a vector of dagroup objects contained by the opcda object. \n', ...
'   Group is initially an empty vector. The size of Group increases as you \n', ...
'   add groups with the ADDGROUP function, and decreases as you remove \n', ...
'   groups with the DELETE function.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/ADDGROUP, DAGROUP/DELETE\n', ...
'']);

case 'grouptype'
out = sprintf([ ...
'   GROUPTYPE  [ {''private''} | ''public'' ] (Read-only: always)\n\n', ...
'   Indicates if a dagroup object is public or private.\n\n', ...
'   GroupType indicates whether a group is Private or Public. A private \n', ...
'   group is local to the opcda client, and other clients must create \n', ...
'   their own private groups. A public group is available from the server \n', ...
'   for any other OPC client on the network.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also OPCDA/ADDGROUP, DAGROUP/COPYGROUP\n', ...
'']);

case 'host'
out = sprintf([ ...
'   HOST  string (Read-only: whileConnected)\n\n', ...
'   DNS name or IP address of server.\n\n', ...
'   Host is the name or IP address of the machine hosting the OPC server. \n', ...
'   If you specify the host using an IP address, no name resolution is \n', ...
'   performed on that address.\n\n', ...
'   The value of Host cannot be changed while the object is connected.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA, ServerID\n', ...
'']);

case 'item'
out = sprintf([ ...
'   ITEM  daitem array (Read-only: always)\n\n', ...
'   Group item array.\n\n', ...
'   Item is a vector of daitem objects contained by the dagroup object. \n', ...
'   Item is initially an empty vector. The size of Item increases as you \n', ...
'   add items with the ADDITEM function, and decreases as you remove items \n', ...
'   with the DELETE function.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/ADDITEM, DAITEM/DELETE\n', ...
'']);

case 'itemid'
out = sprintf([ ...
'   ITEMID  string (Read-only: whileConnected)\n\n', ...
'   Fully qualified ID on the OPC server.\n\n', ...
'   ItemID is the fully qualified ID of the data item on the OPC server. \n', ...
'   The server uses the ItemID to return the appropriate data from the \n', ...
'   server''s cache, or to read and send data to a specific device or \n', ...
'   location.\n\n', ...
'   You obtain valid ItemID values for a particular server by querying \n', ...
'   that server’s name space using the GETNAMESPACE or SERVERITEMS \n', ...
'   functions.\n\n', ...
'   The value of ItemID cannot be modified while the parent opcda object \n', ...
'   is connected.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/ADDITEM, OPCDA/GETNAMESPACE, OPCDA/SERVERITEMS\n', ...
'']);

case 'languageid'
out = sprintf([ ...
'   LANGUAGEID  string (Read-only: never)\n\n', ...
'   Language used by the server to send text messages to the client.\n\n', ...
'   The language (localization) ID is the language used for text returned \n', ...
'   from the server. The default value is given by the system default, for \n', ...
'   example, neutral, English, or German.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'']);

case 'logfilename'
out = sprintf([ ...
'   LOGFILENAME  string (Read-only: whileLogging)\n\n', ...
'   Name of disk file to which logged data is written.\n\n', ...
'   When you start a logging operation using the START function, and the\n', ...
'   LoggingMode property is set to ''disk'' or ''disk&memory'', then DataChange\n', ...
'   events (records) are logged to a disk file with the name specified by\n', ...
'   LogFileName. You may specify any value for LogFileName as long as it\n', ...
'   conforms to the operating system file naming conventions. If no\n', ...
'   extension is specified as part of LogFileName, then .olf is used. \n\n', ...
'   The default value for LogFileName is an empty string. If logging is\n', ...
'   started and LogFileName is empty, LogFileName is assigned the value\n', ...
'   ''<GrpName>log.olf'', where <GrpName> is the name of the dagroup object,\n', ...
'   and a warning is issued.\n\n', ...
'   If a log file with the same name as LogFileName already exists when\n', ...
'   logging is started, the LogToDiskMode property is used to determine\n', ...
'   whether to overwrite the existing file, append records to that file, or\n', ...
'   create an indexed file based on LogFileName.\n\n', ...
'   The log file is an ASCII file in comma-separated variable format,\n', ...
'   arranged as follows:\n', ...
'       DataChange: <LocalEventTime>\n', ...
'       ItemID1, Value1, Quality1, TimeStamp1\n', ...
'       ItemID2, Value2, Quality2, TimeStamp2\n', ...
'       ...\n', ...
'       ItemIDN, ValueN, QualityN, TimeStampN\n', ...
'       DataChange: <LocalEventTime>\n', ...
'       ItemID1, Value1, Quality1, TimeStamp1\n', ...
'       ItemID2, Value2, Quality2, TimeStamp2\n', ...
'       ...\n', ...
'       ItemIDN, ValueN, QualityN, TimeStampN\n', ...
'       ...\n\n', ...
'   The value of LogFileName cannot be changed while the object is logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, LoggingMode, LogToDiskMode\n', ...
'']);

case 'logtodiskmode'
out = sprintf([ ...
'   LOGTODISKMODE  [ ''append'' | {''index''} | ''overwrite'' ] (Read-only: whileLogging)\n\n', ...
'   Method of disk file handling for logged data.\n\n', ...
'   LogToDiskMode can be set to ''append'', ''overwrite'' or ''index''. If \n', ...
'   LogToDiskMode is set to ''append'', then data for a logged session is \n', ...
'   added to any data that already exists in the log file when logging is \n', ...
'   started using the START command. If LogToDiskMode is set to \n', ...
'   ''overwrite'', then the log file is overwritten each time START is \n', ...
'   called. If LogToDiskMode is set to ''index'', then a different disk \n', ...
'   file is created each time START is called, according to the following \n', ...
'   rules:\n\n', ...
'   The first log file name attempted is specified by the initial value of \n', ...
'   LogFileName.\n\n', ...
'   If the attempted file name exists, then a numeric identifier is added \n', ...
'   to the value of LogFileName. For example, if LogFileName is initially \n', ...
'   specified as ''groupRlog.olf'', then groupRlog.olf is the first \n', ...
'   attempted file, groupRlog01.olf is the second file name, and so on.\n\n', ...
'   The actual file name used is the first file name that does not exist. \n', ...
'   In this way, each consecutive logging operation is written to a \n', ...
'   different file, and no previous data is lost.\n\n', ...
'   Separate dagroup objects are logged to separate files. If two dagroup \n', ...
'   objects have the same value for LogFileName, then attempting to log \n', ...
'   data from both objects simultaneously will result in the second object \n', ...
'   failing during the START operation.\n\n', ...
'   The value of LogToDiskMode cannot be changed while the object is \n', ...
'   logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, LogFilename, Logging, LoggingMode\n', ...
'']);

case 'logging'
out = sprintf([ ...
'   LOGGING  [ {''off''} | ''on'' ] (Read-only: always)\n\n', ...
'   Indicate whether data is being logged.\n\n', ...
'   Logging is automatically set to ''on'' when you issue a START command. \n', ...
'   Logging is automatically set to ''off'' when you issue a STOP command, \n', ...
'   or when the requested number of records is logged. You specify the \n', ...
'   number of records to log with the RecordsToAcquire property.\n\n', ...
'   When Logging is ''on'', each DataChange event (a record) is stored to \n', ...
'   disk or to memory (the buffer) as defined by the LoggingMode property.\n\n', ...
'   Logging is a read-only property.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, DAGROUP/STOP, DAGROUP/WAIT, LoggingMode, \n', ...
'      RecordsToAcquire\n', ...
'']);

case 'loggingmode'
out = sprintf([ ...
'   LOGGINGMODE  [ ''disk'' | ''disk&memory'' | {''memory''} ] (Read-only: whileLogging)\n\n', ...
'   Specify destination for logged data.\n\n', ...
'   LoggingMode can be set to ''disk'', ''memory'', or ''disk&memory''. If \n', ...
'   LoggingMode is set to ''disk'', DataChange events (records) are stored \n', ...
'   to a disk file as specified by LogFileName. If LoggingMode is set to \n', ...
'   ''memory'', records are stored to memory (the buffer). If LoggingMode \n', ...
'   is set to ''disk&memory'', records are stored to memory and to a disk \n', ...
'   file. LoggingMode defaults to ''memory''.\n\n', ...
'   The disk file or memory buffer contains data logged from the time you \n', ...
'   issue the START command, until the time you issue a STOP command or \n', ...
'   the number of records specified by the RecordsToAcquire property has \n', ...
'   been logged. Each DataChange event constitutes one record, containing \n', ...
'   one or more items. Only items that change value or quality are \n', ...
'   included in a DataChange event. The logged data includes the ItemID, \n', ...
'   Value, Timestamp, and Quality for each item that changed.\n\n', ...
'   Note that when you issue a REFRESH command while the toolbox is \n', ...
'   logging, the results of that operation are included in the log, since \n', ...
'   a REFRESH forces a DataChange event on the OPC server.\n\n', ...
'   You extract data from memory with the GETDATA function. You can return \n', ...
'   the data stored in a log file to the MATLAB workspace with the OPCREAD \n', ...
'   function.\n\n', ...
'   The value of LoggingMode cannot be changed while the object is logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, DAGROUP/STOP, DAGROUP/GETDATA, \n', ...
'      DAGROUP/OPCREAD, DAGROUP/REFRESH, LogFileName, RecordsToAcquire\n', ...
'']);

case 'name'
out = sprintf([ ...
'   NAME  string (Read-only: never)\n\n', ...
'   Descriptive name for OPC Toolbox object.\n\n', ...
'   The default object creation behaviour is to automatically assign a \n', ...
'   Name to all objects. For the opcda object, Name is the default name \n', ...
'   follows the naming scheme ''Host/ServerID''. For the group object, if \n', ...
'   a name is not specified on creation, the name returned by the OPC \n', ...
'   server is used, or a unique name is automatically assigned to the \n', ...
'   group. Automatically assigned group names follow the naming scheme \n', ...
'   ''groupN'' where N is an integer.\n\n', ...
'   You can change the Name of an object at any time. The Name can be any \n', ...
'   string, and is used for display and identification purposes only.\n\n', ...
'   Applies To: OPCDA, DAGROUP\n\n', ...
'   See also OPCDA, OPCDA/ADDGROUP, Host, ItemID, ServerID\n', ...
'']);

case 'name'
out = sprintf([ ...
'   NAME  string (Read-only: never)\n\n', ...
'   Descriptive name for OPC Toolbox object.\n\n', ...
'   The default object creation behaviour is to automatically assign a \n', ...
'   Name to all objects. For the opcda object, Name is the default name \n', ...
'   follows the naming scheme ''Host/ServerID''. For the group object, if \n', ...
'   a name is not specified on creation, the name returned by the OPC \n', ...
'   server is used, or a unique name is automatically assigned to the \n', ...
'   group. Automatically assigned group names follow the naming scheme \n', ...
'   ''groupN'' where N is an integer.\n\n', ...
'   You can change the Name of an object at any time. The Name can be any \n', ...
'   string, and is used for display and identification purposes only.\n\n', ...
'   Applies To: OPCDA, DAGROUP\n\n', ...
'   See also OPCDA/ADDGROUP, OPCDA, Host, ItemID, ServerID\n', ...
'']);

case 'parent'
out = sprintf([ ...
'   PARENT  OPC Toolbox object (Read-only: always)\n\n', ...
'   OPC Toolbox object that contains the dagroup or daitem object.\n\n', ...
'   For dagroup objects, Parent indicates the opcda object that contains \n', ...
'   the group. For daitem objects, Parent indicates the dagroup object \n', ...
'   that contains the daitem object.\n\n', ...
'   Applies To: DAGROUP, DAITEM\n\n', ...
'   See also Group, Item\n', ...
'']);

case 'quality'
out = sprintf([ ...
'   QUALITY  string (Read-only: always)\n\n', ...
'   Quality of the data value.\n\n', ...
'   Quality indicates the quality of the daitem object''s Value property. \n', ...
'   You can use the Quality property to determine if a value is useful or \n', ...
'   not. Quality defaults to an empty string.\n\n', ...
'   The Quality string is made up of a major quality, which can be one of \n', ...
'   ''Good'', ''Bad'', or ''Uncertain'', and a quality sub-status, which \n', ...
'   describes the quality in more detail.  The string is made up from \n', ...
'   ''Major: SubStatus''. For example, a Quality string of ''Bad: Sensor \n', ...
'   Failure'' indicates that the sensor for this item has failed, and the \n', ...
'   value is probably not accurate. Sub-status quality strings are \n', ...
'   described in more detail in the User Manual.\n\n', ...
'   Quality is updated when you perform an asynchronous read or when a \n', ...
'   subscription callback occurs. Quality is also returned during a \n', ...
'   synchronous READ operation.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/REFRESH, \n', ...
'      Subscription, TimeStamp, UpdateRate, Value\n', ...
'']);

case 'readasyncfcn'
out = sprintf([ ...
'   READASYNCFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when an asynchronous read has \n', ...
'   completed. \n\n', ...
'   You configure ReadAsyncFcn to execute an M-file callback function when \n', ...
'   an asynchronous read operation completes. You execute an asynchronous \n', ...
'   read with the READASYNC function. An asynchronous read event occurs \n', ...
'   immediately after the data is returned by the server to MATLAB. \n\n', ...
'   When a ReadAsync event occurs, the function specified in ReadAsyncFcn \n', ...
'   is passed two parameters: Obj and EventInfo. Obj is the object \n', ...
'   associated with the event, and EventInfo is an event structure \n', ...
'   containing the fields Type and Data. The Type field is set to \n', ...
'   ''ReadAsync''. The Data field contains a structure with the fields:: \n\n', ...
'      ''LocalEventTime'' - The time the event occurred.\n', ...
'      ''TransID'' - The transaction ID for the asynchronous read \n', ...
'         operation.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''Items'' - A structure containing information about each item \n', ...
'         whose value or quality updated.\n', ...
'   The Items structure contains the following fields.\n\n', ...
'      ''ItemID'' - The fully qualified item name.\n', ...
'      ''Value'' - The data value.\n', ...
'      ''Quality'' - The data quality as a string.\n', ...
'      ''TimeStamp'' - The time, as a date vector, the OPC Server''s cache \n', ...
'         was updated.\n', ...
'   The default value for ReadAsyncFcn is @opccallback.\n\n', ...
'   ReadAsync event information is stored in the EventLog property. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also OPCCALLBACK, DAGROUP/READASYNC, EventLog\n', ...
'']);

case 'recordsacquired'
out = sprintf([ ...
'   RECORDSACQUIRED  [0 2147483647] (Read-only: always)\n\n', ...
'   The number of records acquired. \n\n', ...
'   RecordsAcquired is continuously updated to reflect the number of \n', ...
'   records acquired since the START function was called. When you issue a \n', ...
'   START command, the group object resets the value of RecordsAcquired to \n', ...
'   0 and flushes the memory buffer.\n\n', ...
'   To find out how many records are available in the buffer, use the \n', ...
'   RecordsAvailable property. You can also configure the \n', ...
'   RecordsAcquiredFcn to generate an event each time a particular number \n', ...
'   of records have been acquired.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, Logging, RecordsAcquiredFcn, RecordsAvailable\n', ...
'']);

case 'recordsacquiredfcn'
out = sprintf([ ...
'   RECORDSACQUIREDFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when a RecordsAcquired event is \n', ...
'   generated. \n\n', ...
'   You configure RecordsAcquiredFcn to execute an M-file callback \n', ...
'   function when a RecordsAcquired event is generated. A RecordsAcquired \n', ...
'   event is generated each time RecordsAcquired reaches a multiple of \n', ...
'   RecordsAcquiredFcnCount.\n\n', ...
'   When a RecordsAcquired event occurs, the function specified in \n', ...
'   RecordsAcquiredFcn is passed two parameters: Obj and EventInfo. Obj is \n', ...
'   the object associated with the event, and EventInfo is an event \n', ...
'   structure containing the fields Type and Data. The Type field is set \n', ...
'   to ''RecordsAcquired''. The Data field contains a structure with the \n', ...
'   fields: \n\n', ...
'      ''LocalEventTime'' - The time the event occurred.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''RecordsAcquired'' - The number of records acquired in the current \n', ...
'         logging session at the time the event occurred.\n', ...
'   The default value for RecordsAcquiredFcn is an empty matrix.\n\n', ...
'   RecordsAcquired event information is not stored in the EventLog \n', ...
'   property. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, RecordsAcquired, RecordsAcquiredFcnCount\n', ...
'']);

case 'recordsacquiredfcncount'
out = sprintf([ ...
'   RECORDSACQUIREDFCNCOUNT  [0 2147483647] (Read-only: whileLogging)\n\n', ...
'   The number of records to acquire before a RecordsAcquired event is \n', ...
'   generated.\n\n', ...
'   A RecordsAcquired event is generated each time the number of records \n', ...
'   acquired reaches a multiple of RecordsAcquiredFcnCount.\n\n', ...
'   The value of RecordsAcquiredFcn cannot be changed while the object is \n', ...
'   logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also RecordsAcquiredFcn, RecordsAcquired\n', ...
'']);

case 'recordsavailable'
out = sprintf([ ...
'   RECORDSAVAILABLE  [0 2147483647] (Read-only: always)\n\n', ...
'   The number of records available in the OPC Toolbox engine. \n\n', ...
'   RecordsAvailable indicates the number of records that are available in \n', ...
'   the OPC Toolbox engine. When you extract records from the engine with \n', ...
'   the GETDATA function, the RecordsAvailable value reduces by the number \n', ...
'   of records extracted. RecordsAvailable is reset to 0 and the OPC \n', ...
'   Toolbox engine is cleared when you issue a START command.\n\n', ...
'   Use the RecordsAcquired property to find out how many records have \n', ...
'   been acquired since the START command was issued.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/GETDATA, DAGROUP/START, RecordsAcquired, \n', ...
'      RecordsToAcquire\n', ...
'']);

case 'recordstoacquire'
out = sprintf([ ...
'   RECORDSTOACQUIRE  [0 Inf] (Read-only: whileLogging)\n\n', ...
'   Maximum number of records for a logging session.\n\n', ...
'   RecordsToAcquire specifies the number of records that must be acquired \n', ...
'   before the engine automatically stops logging. When RecordsAcquired \n', ...
'   reaches RecordsToAcquire, Logging is set to ''off'', and no more \n', ...
'   records are logged. \n\n', ...
'   By default, RecordsToAcquire is set to 120. To continuously log \n', ...
'   records, specify a value of Inf.\n\n', ...
'   The value of RecordsToAcquire cannot be changed while the object is \n', ...
'   logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, RecordsAvailable, Logging\n', ...
'']);

case 'scanrate'
out = sprintf([ ...
'   SCANRATE  double (Read-only: always)\n\n', ...
'   Fastest possible data update rate.\n\n', ...
'   ScanRate describes the fastest possible rate at which a server can \n', ...
'   update an item. The default value is 0, which indicates that the scan \n', ...
'   rate is not known. Note that the scan rate may not be attainable by \n', ...
'   the server due to network load, server load and other factors.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also UpdateRate\n', ...
'']);

case 'serverid'
out = sprintf([ ...
'   SERVERID  string (Read-only: whileConnected)\n\n', ...
'   Server identity.\n\n', ...
'   ServerID is the COM style program ID (ProgID) that the opcda object \n', ...
'   connects to. The ProgID is normally defined during installation of the \n', ...
'   OPC server.\n\n', ...
'   You use OPCSERVERINFO to find a list of available servers and their \n', ...
'   Server IDs.\n\n', ...
'   The value of ServerID cannot be changed while the object is connected.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA, OPCSERVERINFO, Host\n', ...
'']);

case 'shutdownfcn'
out = sprintf([ ...
'   SHUTDOWNFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when the OPC server shuts down. \n\n', ...
'   You configure SHUTDOWNFCN to execute an M-file callback function when \n', ...
'   the OPC server shuts down. Prior to calling the ShutDownFcn callback, \n', ...
'   the Status property of the OPCDA object is changed to disconnected.\n\n', ...
'   When a Shutdown event occurs, the function specified in ShutdownFcn is \n', ...
'   passed two parameters: Obj and EventInfo. Obj is the object associated \n', ...
'   with the event, and EventInfo is an event structure containing the \n', ...
'   fields Type and Data. The Type field is set to ''Shutdown''. The Data \n', ...
'   field contains a structure with the fields: \n\n', ...
'   ''LocalEventTime'' – The local time (as a date vector) the event \n', ...
'   occurred.\n\n', ...
'   ''Reason'' - The reason for the server shutdown.\n\n', ...
'   The default value for ShutdownFcn is @opccallback. OPCCALLBACK \n', ...
'   displays the event information to the Command Window.\n\n', ...
'   Shutdown event information is stored in the EventLog property.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCCALLBACK, EventLog\n', ...
'']);

case 'startfcn'
out = sprintf([ ...
'   STARTFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute immediately before logging is \n', ...
'   started. \n\n', ...
'   You configure StartFcn to execute an M-file callback function when all \n', ...
'   pre-logging steps have been completed. You start logging by calling \n', ...
'   the START function. A Start event occurs immediately before Logging is \n', ...
'   set to ''on''. \n\n', ...
'   When a Start event occurs, the function specified in StartFcn is \n', ...
'   passed two parameters: Obj and EventInfo. Obj is the object associated \n', ...
'   with the event, and EventInfo is an event structure containing the \n', ...
'   fields Type and Data. The Type field is set to ''Start''. The Data \n', ...
'   field contains a structure with the fields: \n\n', ...
'      ''LocalEventTime'' - The time the event occurred.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''RecordsAcquired'' - The total number of records acquired in the \n', ...
'         current session (0).\n', ...
'   The default value of StartFcn is an empty matrix.\n\n', ...
'   Start event information is stored in the EventLog property. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/START, EventLog, Logging\n', ...
'']);

case 'status'
out = sprintf([ ...
'   STATUS  [ ''connected'' | {''disconnected''} ] (Read-only: always)\n\n', ...
'   Status of the connection to the OPC server\n\n', ...
'   Status can be ''disconnected'' or ''connected''. You connect an opcda \n', ...
'   object with the CONNECT function and disconnect with the DISCONNECT \n', ...
'   function. If the opcda object is connected to a server and the server \n', ...
'   shuts down, the Status property will be set to ''disconnected''.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/CONNECT, OPCDA/DISCONNECT, ShutDownFcn\n', ...
'']);

case 'stopfcn'
out = sprintf([ ...
'   STOPFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute immediately after logging has \n', ...
'   stopped. \n\n', ...
'   You configure StopFcn to execute an M-file callback function when \n', ...
'   logging has stopped. Logging stops when you issue a STOP command, or \n', ...
'   when the RecordsAcquired value reaches RecordsToAcquire. \n\n', ...
'   When a Stop event occurs, the function specified in StopFcn is passed \n', ...
'   two parameters: Obj and EventInfo. Obj is the object associated with \n', ...
'   the event, and EventInfo is an event structure containing the fields \n', ...
'   Type and Data. The Type field is set to ''Stop''. The Data field \n', ...
'   contains a structure with the fields: \n\n', ...
'      ''LocalEventTime'' - The time the event occurred.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''RecordsAcquired'' - The number of records acquired in the current \n', ...
'         logging session.\n', ...
'   The default value for StopFcn is an empty matrix.\n\n', ...
'   Stop event information is stored in the EventLog property. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/STOP, EventLog, RecordsAcquired, RecordsToAcquire\n', ...
'']);

case 'subscription'
out = sprintf([ ...
'   SUBSCRIPTION  [ ''off'', {''on''} ] (Read-only: whileLogging)\n\n', ...
'   Enable server update when data changes.\n\n', ...
'   Subscription can be ''on'' or ''off''. If Subscription is ''on'', \n', ...
'   server update notification is enabled for the group. The update occurs \n', ...
'   when the server cache quality or value of the data associated with a \n', ...
'   daitem object contained by the dagroup object, changes. In order for \n', ...
'   the server cache to be updated, the percent change in the item value \n', ...
'   must also be greater than the value specified for the DeadBandPercent \n', ...
'   property. \n\n', ...
'   A Subscription value of ''on'' instructs the server to issue data \n', ...
'   change events when items in the group are updated by the server. \n', ...
'   Additionally, if an M-file callback function is specified for the \n', ...
'   DataChangeFcn property, then that function executes. If Subscription \n', ...
'   is ''off'', the server may still update item values and/or quality \n', ...
'   information, but no data change event is generated. \n\n', ...
'   Note that the REFRESH function is a special case of subscription, \n', ...
'   where refresh forces a data change event for all active items. \n\n', ...
'   The value of Subscription cannot be changed while the object is \n', ...
'   logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/REFRESH, Active, \n', ...
'      DataChangeFcn, DeadBandPercent, UpdateRate\n', ...
'']);

case 'tag'
out = sprintf([ ...
'   TAG  string (Read-only: never)\n\n', ...
'   Label to associate with the OPC Toolbox object.    \n\n', ...
'   You configure Tag to be a string value that uniquely identifies an OPC \n', ...
'   Toolbox object.\n\n', ...
'   Tag is particularly useful when constructing programs that would \n', ...
'   otherwise need to define the OPC Toolbox object as a global variable, \n', ...
'   or pass the object as an argument between callback routines. You can \n', ...
'   return an OPC Toolbox object with the OPCFIND function by specifying \n', ...
'   the Tag property value.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also OPCFIND\n', ...
'']);

case 'tag'
out = sprintf([ ...
'   TAG  string (Read-only: never)\n\n', ...
'   Label to associate with the OPC Toolbox object.    \n\n', ...
'   You configure Tag to be a string value that uniquely identifies an OPC \n', ...
'   Toolbox object.\n\n', ...
'   Tag is particularly useful when constructing programs that would \n', ...
'   otherwise need to define the OPC Toolbox object as a global variable, \n', ...
'   or pass the object as an argument between callback routines. You can \n', ...
'   return an OPC Toolbox object with the OPCFIND function by specifying \n', ...
'   the Tag property value.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also OPCFIND\n', ...
'']);

case 'timebias'
out = sprintf([ ...
'   TIMEBIAS  [-1440 1440] (Read-only: never)\n\n', ...
'   Time bias of the group.\n\n', ...
'   TimeBias indicates the time difference between the server and client \n', ...
'   machines. In some cases the data may have been collected by a device \n', ...
'   operating in a time zone other than that of the client. Then it will \n', ...
'   be useful to know what the time of the device was at the time the data \n', ...
'   was collected (e.g., to determine what shift was on duty at the time).\n\n', ...
'   The time is specified in minutes and can be positive or negative. The \n', ...
'   default value is 0. \n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also TimeStamp\n', ...
'']);

case 'timestamp'
out = sprintf([ ...
'   TIMESTAMP  date vector (Read-only: always)\n\n', ...
'   Time the item was last read.\n\n', ...
'   TimeStamp indicates the time that the Value and Quality was obtained \n', ...
'   by the device (if this is available) or the time the server updated or \n', ...
'   validated the Value and Quality in its cache. TimeStamp is updated \n', ...
'   when you perform an asynchronous or synchronous read operation or when \n', ...
'   a subscription callback occurs. \n\n', ...
'   TimeStamp is stored as a MATLAB date vector. You convert date vectors \n', ...
'   to date strings with the DATESTR function, and to MATLAB date numbers \n', ...
'   with the DATENUM function.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DATESTR, DATENUM, DATEVEC, DAGROUP/READ, DAGROUP/READASYNC, \n', ...
'      DAGROUP/REFRESH, Quality, Subscription, UpdateRate, Value\n', ...
'']);

case 'timeout'
out = sprintf([ ...
'   TIMEOUT  [0 {10} INF] (Read-only: never)\n\n', ...
'   Maximum time to wait for completion of a read or write instruction.\n\n', ...
'   You configure TimeOut to be the maximum time (in seconds) to wait for \n', ...
'   completion of a synchronous read or a synchronous write operation. If \n', ...
'   a timeout occurs, then the read or write operation aborts. The default \n', ...
'   value is 10.\n\n', ...
'   You can use TimeOut to abort functions that block access to the MATLAB \n', ...
'   command line.\n\n', ...
'   For asynchronous read or write operations, Timeout specifies the time \n', ...
'   to wait for the server to acknowledge the request, and does not limit \n', ...
'   the time for the instruction to be completed by the server.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/WRITE, \n', ...
'      DAGROUP/WRITEASYNC\n', ...
'']);

case 'timerfcn'
out = sprintf([ ...
'   TIMERFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute whenever a predefined period of \n', ...
'   time passes.    \n\n', ...
'   You configure TimerFcn to execute an M-file callback function when a \n', ...
'   timer event occurs. A timer event occurs when the time specified by \n', ...
'   the TimerPeriod property passes. Timer events are only generated when \n', ...
'   the Status property is set to connected. Timer events will stop being \n', ...
'   generated when the object''s Status is set to disconnected, either \n', ...
'   from a DISCONNECT call, or when the server shuts down.\n\n', ...
'   Some timer events may not be processed if your system is significantly \n', ...
'   slowed or if the TimerPeriod value is too small. Timer event \n', ...
'   information is not stored in the EVENTLOG property.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/CONNECT, OPCDA/DISCONNECT, TimerPeriod\n', ...
'']);

case 'timerperiod'
out = sprintf([ ...
'   TIMERPERIOD  [0.001 {10} Inf] (Read-only: never)\n\n', ...
'   Period of time between timer events.   \n\n', ...
'   TimerPeriod specifies the time, in seconds that must pass before the \n', ...
'   callback function specified by TimerFcn is called. \n\n', ...
'   The default value is 10 seconds.\n\n', ...
'   Applies To: OPCDA\n\n', ...
'   See also OPCDA/CONNECT, OPCDA/DISCONNECT, TimerFcn\n', ...
'']);

case 'type'
out = sprintf([ ...
'   TYPE  String (Read-only: always)\n\n', ...
'   OPC Toolbox object type.\n\n', ...
'   Type indicates the type of the object. The OPC Toolbox object types \n', ...
'   are opcda, dagroup, and daitem. Once an object is created, the value \n', ...
'   of Type is automatically defined., and cannot be changed.\n\n', ...
'   You can identify OPC Toolbox objects of a given type using the OPCFIND \n', ...
'   function and the Type value.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also OPCFIND\n', ...
'']);

case 'type'
out = sprintf([ ...
'   TYPE  string (Read-only: always)\n\n', ...
'   OPC Toolbox object type.\n\n', ...
'   Type indicates the type of the object. The OPC Toolbox object types \n', ...
'   are opcda, dagroup, and daitem. Once an object is created, the value \n', ...
'   of Type is automatically defined., and cannot be changed.\n\n', ...
'   You can identify OPC Toolbox objects of a given type using the OPCFIND \n', ...
'   function and the Type value.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also OPCFIND\n', ...
'']);

case 'updaterate'
out = sprintf([ ...
'   UPDATERATE  [0.0 2147483647] (Read-only: whileLogging)\n\n', ...
'   Rate, in seconds, at which subscription callbacks occur.\n\n', ...
'   UpdateRate specifies the rate, in seconds, at which subscription \n', ...
'   callbacks occur. Therefore, UpdateRate determines how often the cached \n', ...
'   data can be updated and how often DataChange events can occur. \n', ...
'   Consequently, UpdateRate also controls the rate at which data is \n', ...
'   logged. You start logging DataChange events with the START function.\n\n', ...
'   Data change events can occur only for active items in an active group. \n', ...
'   Additionally, subscription must be enabled for the group. \n\n', ...
'   Note that servers can select an update rate that differs from the \n', ...
'   requested value. If this occurs, UpdateRate is automatically updated \n', ...
'   with the returned value. By specifying an update rate of 0, updates \n', ...
'   will occur as soon as new information becomes available for the daitem \n', ...
'   object. New information is considered to be a change in Quality or a \n', ...
'   change in the data Value that exceeds the DeadBandPercent property \n', ...
'   value.\n\n', ...
'   The value of UpdateRate cannot be changed while the object is logging.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also START, Active, DeadBandPercent, Subscription\n', ...
'']);

case 'userdata'
out = sprintf([ ...
'   USERDATA  any data type (Read-only: never)\n\n', ...
'   Data you want to associate with the OPC Toolbox object.\n\n', ...
'   You configure UserData to store data that you want to associate with \n', ...
'   an OPC Toolbox object. The object does not use this data directly, but \n', ...
'   you can access it using the GET function.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also Tag\n', ...
'']);

case 'userdata'
out = sprintf([ ...
'   USERDATA  any data type (Read-only: never)\n\n', ...
'   Data you want to associate with the OPC Toolbox object.\n\n', ...
'   You configure UserData to store data that you want to associate with \n', ...
'   an OPC Toolbox object. The object does not use this data directly, but \n', ...
'   you can access it using the GET function.\n\n', ...
'   Applies To: OPCDA, DAGROUP, DAITEM\n\n', ...
'   See also Tag\n', ...
'']);

case 'value'
out = sprintf([ ...
'   VALUE  varies (Read-only: always)\n\n', ...
'   Item value.\n\n', ...
'   Value indicates the value that was last obtained from the OPC server \n', ...
'   for the item defined by the ItemID property. The data type of the \n', ...
'   value is given by the DataType property.\n\n', ...
'   The value returned from the server may be different from the value of \n', ...
'   the device to which the ItemID refers, if the DeadBandPercent for the \n', ...
'   daitem object''s parent group is not zero. The value is also updated \n', ...
'   only periodically, based on the parent group''s Active and UpdateRate \n', ...
'   properties.\n\n', ...
'   You determine the validity of the Value by checking the Quality for \n', ...
'   the item.\n\n', ...
'   Value is updated when you perform an asynchronous read or when a \n', ...
'   subscription callback occurs. Value is also returned during a \n', ...
'   synchronous READ operation.\n\n', ...
'   Applies To: DAITEM\n\n', ...
'   See also DAGROUP/READ, DAGROUP/READASYNC, DAGROUP/REFRESH, Active, \n', ...
'      DataType, DeadBandPercent, Quality, Subscription, TimeStamp, \n', ...
'      UpdateRate\n', ...
'']);

case 'writeasyncfcn'
out = sprintf([ ...
'   WRITEASYNCFCN  string, function handle, or cell array (Read-only: never)\n\n', ...
'   M-file callback function to execute when an asynchronous write has \n', ...
'   completed. \n\n', ...
'   You configure WriteAsyncFcn to execute an M-file callback function \n', ...
'   when an asynchronous write operation completes. You execute an \n', ...
'   asynchronous write with the WRITEASYNC function. A WriteAsync event \n', ...
'   occurs immediately after the server notifies the client that data has \n', ...
'   written to the device.\n\n', ...
'   When a WriteAsync event occurs, the function specified in \n', ...
'   WriteAsyncFcn is passed two parameters: Obj and EventInfo. Obj is the \n', ...
'   object associated with the event, and EventInfo is an event structure \n', ...
'   containing the fields Type and Data. The Type field is set to \n', ...
'   ''WriteAsync''. The Data field contains a structure with the fields:: \n\n', ...
'      ''LocalEventTime'' - The time the event occurred.\n', ...
'      ''TransID'' - The transaction ID for the asynchronous write \n', ...
'         operation.\n', ...
'      ''GroupName'' - The group name.\n', ...
'      ''Items'' - A structure containing information about each item \n', ...
'         whose value or quality updated.\n', ...
'   The Items structure contains the following fields.\n\n', ...
'      ''ItemID'' - The fully qualified item name.\n', ...
'   The default value for WriteAsyncFcn is @opccallback.\n\n', ...
'   WriteAsync event information is stored in the EventLog property.\n\n', ...
'   Applies To: DAGROUP\n\n', ...
'   See also OPCCALLBACK, DAGROUP/WRITEASYNC, EventLog\n', ...
'']);

otherwise
   errflag = true;
   lasterr(['Invalid property ''' propname '''.']);
end    
