%FUNCIONES TRIGONOMETRICAS E HIPERBOLICAS
clc
fprintf('Escriba expresiones MATLAB para calcular los siguientes valores.\n');
fprintf('Suponga que x es un escalar y que su valor está en el intervalo\n');
fprintf('de valores correcto par los cáalculos.\n\n');
fprintf('1.  coth x          2.  sec x\n\n');
fprintf('3.  csc x           4.  acoth x\n\n');
fprintf('5.  asech x         6.  acsc x\n\n');
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 1.
fprintf('>> 1. coth x\n\n');
fprintf('coth (45°) =   %f\n',coth(pi/4));
fprintf('coth (90°) =   %f\n',coth(pi/2));
fprintf('coth (180°) =  %f\n\n',coth(pi));
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 2.
fprintf('>> 2. sec x\n\n');
fprintf('sec (45°) =   %f\n',sec(pi/4));
fprintf('sec (90°) =   %f\n',sec(pi/2));
fprintf('sec (180°) =  %f\n\n',sec(pi));
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 3.
fprintf('>> 3. csc x\n\n');
fprintf('csc (45°) =   %f\n',csc(pi/4));
fprintf('csc (90°) =   %f\n',csc(pi/2));
fprintf('csc (180°) =  %f\n\n',csc(pi));
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 4.
fprintf('>> 4. acoth x\n\n');
fprintf('acoth (90°) =   %f\n',acoth(pi/2));
fprintf('acoth (180°) =  %f\n',acoth(pi));
fprintf('acoth (270°) =  %f\n\n',acoth(3*pi/2));
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 5.
fprintf('>> 5. asech x\n\n');
fprintf('asech (15°) =   %f\n',asech(pi/12));
fprintf('asech (30°) =   %f\n',asech(pi/6));
fprintf('asech (45°) =   %f\n\n',asech(pi/4));
fprintf('Presione una tecla para continuar...\n\n');
pause
clc
% 6.
fprintf('>> 6. acsc x\n\n');
fprintf('acsc (90°) =   %f\n',acsc(pi/2));
fprintf('acsc (180°) =   %f\n',acsc(pi));
fprintf('acsc (270°) =  %f\n\n',acsc(3*pi/2));
fprintf('Presione una tecla para terminar...\n\n');
pause
clc
