function generatetb(filterobj, tbtype, varargin)
%GENERATETB Generate an HDL Test Bench.
%   GENERATETB(Hb, TBTYPE) automatically generates VHDL code, Verilog
%   code, or ModelSim .do file, that functionally verifies the filter
%   generated by GENERATEHDL(Hb) using any or all of impulse, step,
%   ramp, chirp, or noise waveforms as input stimulus for the filter.
%   TBTYPE is one of 'VHDL', 'Verilog', or 'ModelSim' or a cell array
%   containing any or all of these.  The default file name is the name
%   of the filter variable with '_tb' added, e.g.  Hb_tb.vhd for VHDL or
%   Hb_tb.v for Verilog or Hb_tb.do for a ModelSim .do file depending on
%   which testbench types are selected. The file is written to the HDL
%   target directory, which defaults to 'hdlsrc' under the current
%   directory.  This directory is created if it does not exist.
%
%   GENERATETB(Hb, TBTYPE, PARAMETER1, VALUE1, PARAMETER2, VALUE2, ...) 
%   generates the test bench with parameter/value pairs. Valid 
%   properties and values for GENERATETB are listed in the Filter 
%   Design HDL Coder documentation section "Property Reference."
%
%   EXAMPLES:
%   % Setup filter
%   h = firceqrip(30,0.4,[0.05 0.03]);
%   Hb = dfilt.dffir(h);
%   Hb.arithmetic = 'fixed';
%   Hb.castbeforesum = false;
%   generatehdl(Hb);
%
%   % Testbench Examples
%   generatetb(Hb, 'ModelSim');
%   generatetb(Hb,'VHDL','TestBenchName','MyTestBench');
%   generatetb(Hb,{'ModelSim','VHDL'}, 'TestBenchStimulus',{'impulse','chirp'});
%   generatetb(Hb,'VHDL','TestBenchUserStimulus', sin(2*pi*[0:0.01:1]));
%
%   See also GENERATEHDL, GENERATETBSTIMULUS.

%   Copyright 2003-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/01 16:19:58 $ 

% M-file help for generatetb method.

% [EOF]

