function p=mmplotpos(m,n)
%MMPLOTPOS Subplot Position Vectors. (MM)
% P=MMPLOTPOS(M,N) returns axes position vectors in normalized
% units for a figure window containing axes generated by calls
% to SUBPLOT(M,N,i). P is an (M*N)-by-4 array, whose i-th row
% contains the normalized position vector of the i-th axes
% in the order they are specified by SUBPLOT.
%
% MMPLOTPOS(Hf) returns axes position vectors in normalized
% units for all axes in the figure having handle Hf.
%
% See also SUBPLOT

% D.C. Hanselman, University of Maine, Orono, ME, 04469
% 3/17/00
% Mastering MATLAB 6, Prentice Hall, ISBN 0-13-019468-9

if nargin==1            % MMPLOTPOS(Hf)
   if ~ishandle(m) | ~strcmp(get(m,'type'),'figure')
      error('Figure Handle Expected.')
   end
   ha=findobj(m,'type','axes');  % axes children
   num=length(ha);
   p=zeros(num,4);
   for i=1:num
      p(i,:)=mmgetpos(ha(i),'normalized');
   end
elseif nargin==2        % MMPLOTPOS(M,N)
   if fix(m)~=m | m<1 | fix(n)~=n | n<1
      error('M and N Must be a Positive Integers.')
   end
   Hf=figure('BackingStore','off',...  % hidden figure to get data from
      'ColorMap',[],...
      'MenuBar','none',...
      'MinColormap',0,...
      'Renderer','painter',...
      'Visible','off');
   num=m*n;
   p=zeros(num,4);
   for i=1:num
      h=subplot(m,n,i);
      p(i,:)=mmgetpos(h,'normalized');
      delete(h)
   end
   delete(Hf)
else
   error('One or Two Input Arguments Required.')
end
