%PREFSPANEL Registers a preferences control panel.
%   PREFSPANEL registers a Preferences Control panel with the MATLAB IDE.
%

%   Copyright 2003-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2004/03/09 16:14:53 $

com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    'phytree',...
    'Phylogenetic tree',...
    {'Export to Newick','Publish to Figure'},...
    {'phytreewrite($1);','plot($1);'} );