function obj = editdlg(obj)
%EDITDLG Open an editing dialog
%
%  OBJ = EDITDLG(OBJ) creates a modal editing dialog and blocks untils the
%  dialog is closed.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.2.6.3 $    $Date: 2004/04/04 03:26:13 $ 

hFig = xregdialog('tag','OptimFuncEditor',...
   'Name','Optimization Functions',...
   'Resize','off');
xregcenterfigure(hFig, [400 200]);

editlyt = createguiobject(obj, hFig);

okH = uicontrol('parent',hFig,...
   'style','pushbutton',...
   'string','OK',...
   'callback','set(gcbf,''visible'',''off'',''userdata'',''ok'');');
cancelH = uicontrol('parent',hFig,...
   'style','pushbutton',...
   'string','Cancel',...
   'callback','set(gcbf,''visible'',''off'');');
lyt = xreggridbaglayout(hFig,...
   'dimension',[2 3],...
   'gapy',10,'gapx',7,...
   'rowsizes',[-1 25],...
   'colsizes',[-1 65 65],...
   'mergeblock',{[1 1],[1 3]},...
   'elements',{editlyt,[],[],okH,[],cancelH},...
   'packstatus','off',...
   'border',[7 7 7 7]);
hFig.LayoutManager = lyt;
set(lyt,'packstatus','on');
hFig.showDialog(okH);

ud = get(hFig,'userdata');
if strcmp(ud,'ok')
   obj = initfromguiobject(obj,editlyt);
end
delete(hFig);
