clear rule;
if chooser1value==2;
    rule=['rules_oned_custom'];
elseif chooser1value==3;
    rule=['rules_oned_neighbor_18'];
elseif chooser1value==4;
    rules_oned_nearest_neighbor_setup;
    rule=['rules_oned_nearest_neightbor'];
elseif chooser1value==5;
    rules_oned_any_nearest_reversible_setup;
    rule=['rules_oned_any_nearest_reversible'];
elseif chooser1value==6;
    rules_oned_next_nearest_neighbor_setup;
    rule=['rules_oned_next_nearest_neightbor'];
elseif chooser1value==7;
    rules_oned_nearest_totalistic_setup;
    rule=['rules_oned_nearest_totalistic'];
elseif chooser1value==8;
    rules_oned_next_nearest_neighbor_setup;
    rule=['rules_oned_next_nearest_totalistic'];
elseif chooser1value==9;
    rules_oned_any_totalistic_next_nearest_setup;
    rule=['rules_oned_any_totalistic_next_nearest'];
end;

if chooser2value==2;
    rule=['rules_twod_custom'];
elseif chooser2value==3;
    rule=['rules_game_of_life'];
elseif chooser2value==4;
    rules_twod_totalistic_setup;
    rule=['rules_twod_totalistic'];
elseif chooser2value==5;
    rules_twod_totalistic_setup;
    rule=['rules_twod_totalistic_wrap'];
end;
