function editfig = figposition(Obj,pos)
% cgprec \ figposition
% Ensures that the changing figures of the precision editors have constant
% figure size

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.5.2.2 $  $Date: 2004/02/09 06:54:41 $

% construct writable checkbox callback string.
editfig = figure(...
    'units','pixels',...
    'position',pos,...
    'numbertitle','off',...
    'visible','on',...
    'name','Table Properties',...
    'resize','off',...
    'tag','TableProperties',...
    'color',get(0,'DefaultUIcontrolBackgroundColor'),...
    'closerequest','global CANCEL_FLAG; CANCEL_FLAG = 1; uiresume(gcf);',...
    'menubar','none',...
    'windowstyle','modal');

global PRECISION_TYPE
PRECISION_TYPE = [];

[types,strings] = precision_classes;
ud.types = types;
val = strmatch(class(Obj),types,'exact');

xreguicontrol(editfig,...
    'style','text',...    
    'String','Precision type',...
    'position',[20 350 80 15],...
    'horizontal','left');

ud.popup = xreguicontrol(editfig,...
    'style','popup',...
    'string',strings,...
    'value',val,...
    'backgroundcolor',[1 1 1],...
    'position',[105 350 160 20],...
    'callback',@i_ChooseType);


ok = xreguicontrol(editfig,...
    'style','push',...
    'string','OK',...
    'position',[160 10 70 25],...
    'callback','uiresume(gcf)');

cancel = xreguicontrol(editfig,...
    'style','push',...
    'position',[240 10 70 25],...
    'string','Cancel',...
    'callback',['global CANCEL_FLAG; CANCEL_FLAG = 1; uiresume(gcf);']);

helpbut = cghelpbutton(editfig,'CGTABLEPROPS','position',[320 10 70 25]);

ud.writable = xreguicontrol(editfig,...
    'style','checkbox',...
    'value',~get(Obj,'writable'),...
    'position',[20 325 160 15],...
    'string','Properties Read-only',...
    'callback',@i_ReadOnly);

set(editfig,'userdata',ud);
% ------------------------------------------------
function i_ReadOnly(src,obj)
% ------------------------------------------------
ud = get(gcf,'user');
if get(ud.writable,'value');
    writeflag = 'off';
else
    writeflag = 'on';
end
set(ud.writeEnableControls,'enable',writeflag);

% -----------------------------------------------------
function i_ChooseType(src,obj)
% ------------------------------------------------------
ud = get(gcf,'user');
val = get(ud.popup,'value');
newtype = ud.types{val};
if ~strcmp(newtype,class(ud.obj))
    global PRECISION_TYPE;
    PRECISION_TYPE = eval(newtype);
    uiresume(gcf);
end
