function tclcmd = osccmds
% MANCHESTERCMDS - Creates Tcl commands for the Simple Osc Model
%   The returned cell array can be passed as parameters ('cmd') to
%   VSIM.  This will lauching ModelSim and build the VHDL
%   source files included with the demo.  
%
% See also VSIM

%   Copyright 2003 The MathWorks, Inc.
%   $Revision: 1.2.6.1 $  $Date: 2004/03/15 22:19:47 $
%   $Revision $ $Date: 2004/03/15 22:19:47 $
%

srcfile1 = fullfile(matlabroot,'toolbox','modelsim','modelsimdemos','vhdl','osc','simple_osc.vhd');
srcfile2 = fullfile(matlabroot,'toolbox','modelsim','modelsimdemos','vhdl','osc','osc_filter.vhd');
srcfile3 = fullfile(matlabroot,'toolbox','modelsim','modelsimdemos','vhdl','osc','osc_top.vhd');

unixsrcfile1 = strrep(srcfile1,'\','/'); 
unixsrcfile2 = strrep(srcfile2,'\','/'); 
unixsrcfile3 = strrep(srcfile3,'\','/'); 

if strcmp(computer,'PCWIN'),
    projdir = tempdir;  % Change to writable directory of your choosing
else
    projdir = tempname;
    mkdir(tempdir,strrep(projdir,tempdir,''));
end
unixprojdir = strrep(projdir,'\','/'); 
tclcmd = {  'catch { wm geometry . 500x200+0+0 }',... % Try moving ModelSim out of the way
           ['cd ',unixprojdir],...            
            'vlib work',... %create library (if necessary)
           ['vcom -performdefaultbinding ' unixsrcfile1],...
           ['vcom -performdefaultbinding ' unixsrcfile2],...
           ['vcom -performdefaultbinding ' unixsrcfile3],...
            'vsimmatlab work.osc_top ',...
            'matlabtb u_osc_filter -mfunc oscfilter',...
            'add wave sim:/osc_top/clk',...
            'add wave sim:/osc_top/clk_enable',...
            'add wave sim:/osc_top/reset',...
           ['add wave -height 100 -radix decimal -format analog-step -scale 0.001 -offset 50000 ',...
            'sim:/osc_top/osc_out'],...
           ['add wave -height 100 -radix decimal -format analog-step -scale 0.00003125 -offset 50000 ',...
            'sim:/osc_top/filter1x_out'],...
           ['add wave -height 100 -radix decimal -format analog-step -scale 0.00003125 -offset 50000 ',...
            'sim:/osc_top/filter4x_out'],...
           ['add wave -height 100 -radix decimal -format analog-step -scale 0.00003125 -offset 50000 ',...
            'sim:/osc_top/filter8x_out'],...
            'catch { wm geometry $vsimPriv(WaveWindows) 1000x660+10+10 }',...% Try moving wave
            'force sim:/osc_top/clk_enable 1 0',...  
            'force sim:/osc_top/reset 1 0, 0 120 ns',...
            'force sim:/osc_top/clk 1 0 ns, 0 40 ns -r 80ns',...
            'run 10000 ns',...
            '.wave.tree zoomfull',...
         };
