function generatetb(filterobj, tbtype, varargin)
%GENERATETB Generate an HDL Test Bench.
%
%   GENERATETB(Hq, TBTYPE) automatically generates VHDL code, 
%   Verilog code, or ModelSim .do file that functionally verifies
%   the filter generated by GENERATEHDL(Hq) using any or all
%   of impulse, step, ramp, chirp, or noise waveforms as input stimulus
%   for the filter.  TBTYPE is one of 'ModelSim' or 'VHDL' or 'Verilog'
%   or a cell array containing any of these.  The default file base 
%   name is 'filter_variable_tb', e.g., Hq_tb.vhd for the VHDL test 
%   bench, Hq_tb.do for the ModelSim .do file, or Hq_tb.v for the 
%   Verilog test bench. The test bench file is written to the HDL 
%   source directory, which defaults to 'hdlsrc' under the current 
%   directory.
%
%   GENERATETB(Hq, TBTYPE, PARAMETER1, VALUE1, PARAMETER2, VALUE2, ...) 
%   generates the test bench with parameter/value pairs. Valid 
%   properties and values for GENERATETB are listed in the Filter Design
%   HDL Coder documentation section "Property Reference."
%
%   EXAMPLES:
%   h = firceqrip(30,0.4,[0.05 0.03]);
%   Hq = qfilt('fir',{h});
%   generatetb(Hq, 'ModelSim');
%   generatetb(Hq,'VHDL','TestBenchName','MyTestBench');
%   generatetb(Hq,{'ModelSim','VHDL'}, 'TestBenchStimulus',{'impulse','chirp'});
%   generatetb(Hq,'Verilog','TestBenchUserStimulus', sin(2*pi*[0:0.01:1]));
%
%   See also GENERATEHDL, GENERATETBSTIMULUS.

%   Copyright 2003-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.4 $  $Date: 2004/04/01 16:09:01 $ 

  global hdl_parameters;

  if isempty(hdl_parameters)
    hdldefaultfilterparameters;  % Set up the default params structure
  end

  if ~isempty(inputname(1))
    hdlparsefilterparameters('testbenchname',[inputname(1) '_tb']); 
  end

  [cando, errstr] = ishdlable(filterobj);
  if cando
    privgeneratetb(filterobj, tbtype, varargin{:});
  else
    error(generatemsgid('unsupportedarch'), errstr);
  end



% [EOF]

