%GuiDm_2  Demonstration of selecting equation form menu.
% Copyright S. Nakamura, 1995
close, clear
fg=figure(1);
set(fg, 'Position',[100 100 350 350],...
   'Color',[0.6, .4, .4],...
   'NumberTitle','off',...
   'Name','GuiDm_2')
x=0:0.1:10;, y=sin(x);
p=plot(x,y);xlabel('x');ylabel('y=sin(x)');
stl = uimenu(gcf,...
     'Label','Select Equation',...
     'BackgroundColor',[0.8, 0.8, 0.8]);
F1  = uimenu(stl, ...
     'Label', 'y=sin(x)',...
     'CallBack',...
  'plot(x,sin(x));xlabel(''x'');ylabel(''y=sin(x)'')');
F2  = uimenu(stl, ...
     'Label', 'y=exp(-x)',...
     'CallBack',...
  'plot(x,exp(-x));xlabel(''x'');ylabel(''y=exp(-x)'')');
F3  = uimenu(stl, ...
     'Label', 'y=cos(x^2)',...
     'CallBack',...
     [
      'plot(x,cos(x.^2));',...
      'xlabel(''x'');ylabel(''y=cos(x.^2)'')'...
     ]);
F4  = uimenu(stl, ...
     'Label', 'y=exp(-x.^2)',...
     'CallBack',...
     [
      'plot(x,exp(-x.^2));',...
      'xlabel(''x'');ylabel(''y=exp(-x.^2)'')'...
     ]);
