%  accum3.m
% Matlab file for Part 3 of the Accumulation module

disp('********************************************')
disp('Part 3:  Accumulation and Area ') 
disp('********************************************')
disp('  ')    

    format short

    disp('Step 1:')
    disp('Find the value of the endpoint b and')
    disp('enter it into MATLAB')
    disp(' ')
    disp('   b= ? ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Compute the triangle area, the area of the')
    disp('circular sector and the sum of these areas.')
    disp(' ')
    disp('Be sure to save this sum for comparison ')
    disp('purposes later.  Call it ''''exact_area''''. ' )
    disp(' ')
    disp('Include computations and comments in your')
    disp('diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('----------------------------------------------')
    disp('Step 2: We''re going to add up a sum using')
    disp('25 subintervals of the interval [0,b], where ')
    disp('each subinterval has length Delta=b/n. ')
    disp(' ')
    disp('Enter n = 25 and Delta= b/n into MATLAB. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('----------------------------------------------')
    clear sum;
    disp('Now we will define x values from 0 to b-Delta')
    disp('in steps of Delta and the corresponding values')
    disp('of y=sqrt(25-x^2) at the x values.  By ')
    disp('multiplying y times Delta, we get a vector of')
    disp('the areas of left rectangles.')
    disp(' ')
    disp('We need to add up all these areas to get our ')
    disp('left hand sum.  We will use the MATLAB sum')
    disp('function that sums the components of a vector.')
    disp(' ')
    disp('Copy the following commands and paste them at')
    disp('a MATLAB prompt, then execute them.')
    disp(' ')
    disp('  xvals=0:Delta:b-Delta;  ')
    disp('  yvals=sqrt(25-xvals.^2); ')
    disp('  areas=yvals*Delta; ')
    disp('  lh_sum=sum(areas) ')
    disp(' ')
    disp('----------------------------------------------')
    disp('How close is your left hand sum approximation ')
    disp('to the exact area you calculated in Step 1. ')
    disp('Answer as MATLAB comments in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 3:')
    disp('You can easily compute right-hand sums by ')
    disp('making a simple change to the left-hand sums ')
    disp('commands. Hint: the xvals should now go from')
    disp('x=Delta to x=b in steps of Delta. ')
    disp(' ')
    disp('Compute the right-hand sum approximation to')
    disp('the area and compare it to the exact area.')
    disp(' ')
    disp('Show computations and MATLAB comments in your')
    disp('diary file.')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 4:')
    disp('Enter n=250 and Delta=b/n into MATLAB')
    disp(' ')
    disp('----------------------------------------------')
    disp('Compute the left-hand and right-hand sum')
    disp('approximations for n=250 to the area ')
    disp('and compare them to the exact area.')
    disp(' ')
    disp('Show computations and MATLAB comments in your')
    disp('diary file.')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 5:')
    disp('Enter n=2500 and Delta=b/n into MATLAB')
    disp(' ')
    disp('----------------------------------------------')
    disp('Compute the left-hand and right-hand sum')
    disp('approximations to the area for n=2500 and')
    disp('compare them to the exact area.  How much do')
    disp('the approximations improve every time you ')
    disp('multiply n by 10? ')
    disp(' ')
    disp('Show computations and MATLAB comments in your')
    disp('diary file.')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Answer the questions in steps 6 and 7.  Write')
    disp('as MATLAB comments in your diary file.')
    disp(' ')
    disp('----------------------------------------------')
    disp('When your description is done, to go on to')
    disp('part 4 of this module, type: accum4.')
    disp(' ')