%  curvfit4.m
% Matlab file for Part 4 of the Curve Fitting module

disp('*********************************************')
disp('Part 4:  Pitfalls of Linearization ')
disp('*********************************************')
disp('  ')

    format short

    disp('Step 1: ') 
    disp('Give your explanation by using MATLAB ')
    disp('comments in your diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;   
    disp(' ')

    disp('-------------------------------------------------')
    disp('Step 2: ') 
    disp('Enter the data vectors for the Small Data Set:')
    disp(' ')
    disp('  t = (1:4)'' ')
    disp('  y = [2.5, 8.0, 19.9, 50.0]'' ')
    disp('  one = ones(4,1); ')
    disp('  ystar = log(y); ')
    disp(' ') 
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;   
    disp(' ')
    
    disp('-------------------------------------------------')
    disp('Step 2 (cont.): ') 
    disp('Solve the least squares problem for the semilog')
    disp('data.  Use your results to solve for the ')
    disp('parameters a and b in the corresponding ')
    disp('exponential fit y = a*exp(b*t).')
    disp(' ')
    disp('Compute the S value and explain your steps by using ')
    disp('MATLAB comments in your diary file. ')
    disp(' ') 
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;   
    disp(' ')
    
    disp('----------------------------------------------------')
    disp('Step 7:')
    disp('Assuming your values of a and b for your exponential')
    disp('fit are entered, the following commands compute and ')
    disp('plot the residuals for each of the two exponential ')
    disp('models.  The one from step 2 is called ''semilog exp''. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  p= a*exp(b*t); ')
    disp('  resid = y - p ')
    disp('  figure(2); clf ')
    disp('  plot(t, resid, ''bo''); hold on ')
    disp('  p0= 0.921*exp(0.999*t); ')
    disp('  resid0 = y - p0 ')
    disp('  plot(t, resid0, ''rs''); ')
    disp('  title(''Compare residual plots for exp fit'') ')
    disp('  legend(''semilog exp'',''0.921*exp(0.999*t)'') ')
    disp('  tvals = 0:0.1:5; ')
    disp('  plot(tvals, zeros(size(tvals,2),1), ''k'') ')
    disp('  axis([0,5, -3,3]); ')
    disp(' ')
    disp('-----------------------------------------------------')
    disp('Compare the S values.  Discuss what they tell you ')
    disp('and tell what you learn from the comparison of the')
    disp('residual plot using MATLAB comments.')
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('To go on to part 5 of this module, ')
    disp('type: curvfit5')
    disp(' ')
