%  equi2.m
% Matlab file for Part 2 of The Equiangular Spiral 
% module

disp('**********************************************')
disp('Part 2: Measuring a Spiral Seashell ')
disp('**********************************************')
disp('  ')    

    format short

    disp('Step 1: ') 
    disp('Fill in the 19 values of r that you have')
    disp('measured into the list (vector) rvals below.')
    disp('Make sure you have 19 values. ')
    disp('Then enter the vector rvals into MATLAB: ')
    disp(' ')
    disp('   rvals=[?, ?, ...] ')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')
    
    disp('---------------------------------------------')
    disp('Step 2: ')
    disp('The vector n below just numbers your r values')
    disp('from 0 to 18 so we can plot the pairs (n,rvals)')
    disp('Let''s make the plot and hold it for later.')  
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('   n=0:18 ')
    disp('   figure(1); clf ')
    disp('   plot(n,rvals,''bo''); hold on ')
    disp(' ')
    disp('---------------------------------------------')
    disp('What sort of growth does this look like?')
    disp('Answer using MATLAB comments in your diary file.')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')
    
    disp('---------------------------------------------')
    disp('Step 3 and 4: ')
    disp('Let''s look at a semilog plot of the data.')
    disp('We will plot the pairs (n,log(rvals)) ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('   figure(2); clf ')
    disp('   plot(n,log(rvals),''ro''); grid on')
    disp(' ')
    disp('---------------------------------------------')
    disp('Estimate the slope and intercept of a line')
    disp('fitting the semilog graph.')
    disp(' ')
    disp('Find the formula R(t) to approximate the ')
    disp('original (n,rvals) data. ')
    disp(' ')
    disp('Give your results using MATLAB comments in your')
    disp('diary file.')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')
    
    disp('---------------------------------------------')
    disp('Step 5: ')
    disp('Fill in your formula R(t) below and then ')
    disp('calculate the (t,R(t)) pairs and plot the ')
    disp('connected curve superimposed on the original ')
    disp('(n,rvals) data.  ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  t = 0:0.1:19; ')
    disp('  R = ???;  % Your formula in terms of t')
    disp('  figure(1) ')
    disp('  plot(t,R,''r'') ')
    disp(' ')
    disp('---------------------------------------------')
    disp('Adjust your formula and replot until you are')
    disp('satisfied with the fit.')
    disp(' ')
    disp(' ')
    disp('-------------------------------------------- ')
    disp('When you are ready to go on to part 3 ')
    disp('of this module, type: equi3.')
    disp(' ')
