%  fundata2.m
% Matlab file for Part 2 of the Functions Defined by Data
% module

disp('********************************************')
disp('Part 2:  The Spread of Aids')
disp('********************************************')
disp('  ')    

    format short

    disp('Below are two lists.  The first is a list')
    disp('of dates measured in months since 1980.')
    disp('The second list gives the number of AIDS')
    disp('cases reported to the Centers for Disease')
    disp('Control as of each date.  Follow the following')
    disp('instructions to enter the lists into MATLAB')
    disp('as row vectors.')
    disp(' ')
    disp('Copy the following commands and paste them as')
    disp('a group at a MATLAB prompt, then execute them.')
    disp(' ')
    disp(' date=[20,21,24,26,29,31,35,37,41,44,49,52 ...')
    disp('  59,62,67,69,73,83,89,98,119,143,151]; ')
    disp(' cases=[110,129,220,257,439,514,878,1029, ...')
    disp('  1756,2057,3512,4115,7025,8229,12067, ...')  
    disp('  14049,16458,28098,36058,56575,113891,...')
    disp('  202843,226252]; ')
    disp(' ')
    disp('After you have entered the lists, check that')
    disp('they match up by entering the command')
    disp('  [date;cases]''  ')
    disp('to see the data in table form.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp('----------------------------------------------')
    disp(' ')

    disp('Make a scatter plot of the data pairs')
    disp('(date,cases).  Be sure to label the axes')
    disp('and give your plot a title.')
    disp('Fill in the skeleton commands below and ')
    disp('enter them: ')
    disp(' ')
    disp('  plot(?? , ?? ,''o'')  ')
    disp('  xlabel(''??'')  ')
    disp('  ylabel(''??'')  ')
    disp('  title(''??'') ')
    disp(' ')
    disp('Write a brief paragraph about the AIDS')
    disp('epidemic graph. Write as MATLAB comments in')
    disp('your diary file.')
    disp(' ') 
    disp('When your paragraph is done, to go on to')
    disp('part 3 of this module, type: fundata3.')
    disp(' ')