%  invfun2.m
% Matlab file for Part 2 of the Inverse Functions module

disp('********************************************')
disp('Part 2: Inverting the Sine Function ') 
disp('********************************************')
disp('  ')    

    format short

    disp('Steps 1 and 2: ')
    disp('Answer the questions as MATLAB comments')
    disp('in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')

    disp('Step 3: ')
    disp('The function f(t) to be integrated is called')
    disp('fun(t) here and is defined in a MATLAB m-file')
    disp('that is provided with this module''s files.')
    disp('The function in fun(t) is originally ')
    disp('    1/sqrt( 1 - t^2 ). ')
    disp(' ')
    disp('To list the m-file, enter: ''''type fun'''' ')
    disp('at a MATLAB prompt. ')
    disp(' ')
    disp('--------------------------------------------')
    disp('The function F(x) is called intf(x) here')
    disp('and is defined in a MATLAB m-file that')
    disp('is provided with this module''s files. ')
    disp(' ')
    disp('intf(x) here computes the area under the ')
    disp('fun(t) = 1/sqrt( 1 - t^2 ) curve above the')
    disp('interval [0,x].')
    disp(' ')
    disp('To list the m-file, enter: ''''type intf'''' ')
    disp('at a MATLAB prompt. ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Evaluate inf(x) at various x values.')
    disp('To compute the values of F(x)=intf(x) at, say,')
    disp('x=0.5 just enter: intf(0.5). ')
    disp(' ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('----------------------------------------------')
    disp('Step 4:')
    disp('To compute the values of F(sin(x)) and sin(F(x)) ')
    disp('at, say, x=0.5, you can just enter: ')
    disp(' ')
    disp(' x=0.5; ')
    disp(' intf(sin(x))  ')
    disp(' sin(intf(x))  ')
    disp(' ')
    disp('Do the calculations for various values of x')
    disp('and record your results in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('----------------------------------------------')
    disp('Step 5: ')
    disp('To graph the function F(sin(x)), use the usual')
    disp('method,i.e., enter the commands below. ')
    disp('   (Note that the numerical integrator')
    disp('    generates lots of error messages because')
    disp('    the integrand is infinite near +1 and -1')
    disp('    but the correct graph is made regardless.) ')
    disp(' ')
    disp(' clf   % clears plot ')
    disp(' x=-3:0.1:3; ')
    disp(' y=intf(sin(x)); ')
    disp(' plot(x,y) ')
    disp(' title(''F(sin(x))'') ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Also graph the function sin(F(x)).')
    disp(' ')
    disp('Answer the the questions about domains.  Give ')
    disp('complete explanations.  Write as MATLAB comments ')
    disp('in your diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('----------------------------------------------')
    disp('Step 6: ')
    disp('Answer the question as MATLAB comments in your')
    disp('diary file.')
    disp(' ')
    disp('----------------------------------------------')
    disp('When you are finished with part 2, to go on to')
    disp('part 3 of this module, type: invfun3.')
    disp(' ')