%  linfilt3.m
% Matlab file for Part 3 of the Linear Filters 
% module

disp('*****************************************')
disp('Part 3: Filtering Frequencies Out')
disp('*****************************************')
disp('  ')    

    format short
  
    disp('Steps 1 and 2: ')
    disp('Solve the auxiliary equation and record your two')
    disp('imaginary roots r1 and r2.')
    disp(' ')
    disp('Below, we check whether r^k is a solution if r=i.')
    disp('Note that y(k+2) + y(k) = r^(k+2) + r^k. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  r = i  ')
    disp('  syms k')
    disp('  result = simple( r^k*r^2 + r^k ) ')
    disp(' ')
    disp('-----------------------------------------------')
    disp('Check your other solution. ')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
       
    disp('-----------------------------------------------')
    disp('Step 3 an 4: ')
    disp('Rewrite your complex solution r1 and r2 in ') 
    disp('''polar'' form.  Then use de Moivre''s Rule ')
    disp('to rewrite the sequences r1^k and r2^k.')
    disp(' ')
    disp('Use MATLAB comments in your diary file to present')
    disp('and explain your results.')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
       
    disp('-----------------------------------------------')
    disp('Step 5:')
    disp('Present your proof by using MATLAB comments in ')
    disp('your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 6:')
    disp('Write your four real solutions.  Use MATLAB')
    disp('comments in your diary file.')
    disp('Below, we show how to check one possible')
    disp('solution.')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  y = inline(''sin(k*pi/2)'')  ')
    disp('  syms k ')
    disp('  result = simple( y(k+2) + y(k) ) ')
    disp(' ')
    disp('--------------------------------------------')
    disp('Check all your claimed solutions. ')
    disp('Explain your results using MATLAB comments in ') 
    disp('your diary file. ')  
    disp(' ')
    disp('To continue afterwards, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Steps 7 and 8:')
    disp('Answer the questions using MATLAB comments in your')
    disp('diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 8 ')
    disp('Follow steps 1 thru 7 to find a linearly ')
    disp('set of signals that are filtered out by the ')
    disp('linear filter: ')
    disp('  y(k+4) - y(k+2) + 2*y(k) = z(k) ')
    disp(' ')
    disp('The following commands will be useful to you: ')
    disp(' ')
    disp('  syms r ')
    disp('  soln = double( solve(r^4 - r^2 + 2) ) ')
    disp('  [theta,R] = cart2pol(real(soln),imag(soln)) ')
    disp(' ')  
    disp('-----------------------------------------------')
    disp('Explain all the steps in your solution and give')
    disp('your results by using MATLAB comments in your ')
    disp('diary file.  (Suggestion:  When comparing to')
    disp)'Part2, you should look at the decimal version') 
    disp('of arctan(7)/2.) ') 
    disp(' ') 
    disp(' ')
    disp('-----------------------------------------------')
    disp('When you are ready to go on to part 4 ')
    disp('of this module, type: linfilt4.')
    disp(' ')
