%  linfilt2.m
% Matlab file for Part 2 of the Linear Filters 
% module

disp('***********************************************')
disp('Part 2: Difference Equations as Linear Filters')
disp('***********************************************')
disp('  ')    

    format short
  
    disp('Step 1: ')
    disp('The commands below graph the y(k) sequence in')
    disp('blue and the z(k) sequence in red for comparison.')
    disp(' ')
    disp('Enter:  ')
    disp(' ')
    disp('  y = inline(''sin(k*pi/2)'')  ')
    disp(' ')
    disp('  k = -10:10;')
    disp('  Y = y(k); ')
    disp('  Z = y(k+4) - y(k+2) + 2*y(k); ')
    disp('  clf ')
    disp('  plot(k,Y,''bo''); grid on; hold on ')
    disp('  plot(k,Z,''ro'') ')
    disp('  legend(''input y(k)'',''output z(k)'') ')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
       
    disp('-----------------------------------------------')
    disp('Step 2: ')
    disp('Modify the procedure of step 1 for the new  ') 
    disp('input sequences. ')
    disp(' ')
    disp('Entering the second sequence definition is a ')
    disp('little tricky.  Try this: ')
    disp(' y = inline(''2.^(k/4).*sin((k/2)*atan(sqrt(7)))'') ')
    disp(' ')
    disp('--------------------------------------------')
    disp('Describe what you learn from the plots and') 
    disp('answer the questions using MATLAB comments in ')
    disp('your diary file.')
    disp(' ')
    disp('To continue, type the word return and ')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
       
    disp('--------------------------------------------------')
    disp('Step 3:')
    disp('MATLAB to verify symbolically your observations')
    disp('from step 2.  Here are the steps for the first')
    disp('of the sequences. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  y = inline(''sin(k*pi/2)'')  ')
    disp('  syms k')
    disp('  z = simple( y(k+4) - y(k+2) + 2*y(k) ) ')
    disp(' ')
    disp('--------------------------------------------')
    disp('Do the same steps for your second formula. ')
    disp('Explain your results using MATLAB comments in ') 
    disp('your diary file. ')  
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('When you are ready to go on to part 3 ')
    disp('of this module, type: linfilt3.')
    disp(' ')
