% lude4.m
% Matlab file for Part 4 of the LU Decomposition module

disp('********************************************')
disp('Part 4:  A Modified Decomposition')
disp('********************************************')
disp('  ')    

    format short
    
    disp('Enter the matrix R to use in steps 1-4')
    disp('by copying the following command, pasting')
    disp('it at a MATLAB prompt, and executing it. ')
    disp(' ')
    disp('     R=[0,3,-2; -1,3,0; 2,3,-5]  ')
    disp(' ')
    disp(' Note: You can get an elementary matrix that')
    disp(' swaps rows 1 and 2 as follows: ')
    disp(' ')
    disp('   E1=eye(3); ')
    disp('   temp=E1(1,:); ');
    disp('   E1(1,:)=E1(2,:);  % Replace row 1 with row 2')
    disp('   E1(2,:)=temp    % Put saved row 1 into row 2')
    disp(' ')
    disp('Be sure to include answers to the questions')
    disp('posed in steps 1-4 as MATLAB comments in your')
    disp('diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('For step 5, use the given commands to first')
    disp('enter matrix S and then clear the first ')
    disp('column of S.')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp(' S=[1,1,-1,0,0; -1,-1,1,-1,0; -1,-1,0,0,-1;...')
    disp('    1,0,-1,1, -1; -1,0,1,-1, -1] ')
    disp(' ')
    disp(' S2=S;  ')
    disp(' S2(2,:)=1*S2(1,:) + S2(2,:);  ')
    disp(' S2(3,:)=1*S2(1,:) + S2(3,:);  ')
    disp(' S2(4,:)=-1*S2(1,:) + S2(4,:); ')
    disp(' S2(5,:)=1*S2(1,:) + S2(5,:) ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Now, we have to do a row exchange and then')
    disp('clear the second column of S2 ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp(' S3=S2;  ')
    disp(' temp=S3(4,:); %Row swap ')
    disp(' S3(2,:)=S3(4,:); ')
    disp(' S3(4,:)=temp ')
    disp(' ')
    disp(' S4=S3;  % Now clear column 2 ')
    disp(' S4(4,:)=-1*S4(2,:) + S4(4,:);  ')
    disp(' S4(5,:)=1*S4(2,:) + S4(5,:)  ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('--------------------------------------------')
    disp('We have U.  Now, explain how to find L. ')
    disp('Include your answer as MATLAB comments ')
    disp('in your diary file.')
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('To go on to part 5 of this module, ')
    disp('type: lude5')
    disp(' ')