%  matops1.m
% Matlab file for Part 1 of the Matrix Operations module

disp('*********************************************')
disp('Part 1:  Properties of Matrix Multiplication')
disp('*********************************************')
disp('  ')    

    format short
    
    disp('Enter the matrices A, B, and C by copying')
    disp('the following commands as a group, pasting ')
    disp('them at a MATLAB prompt, and executing them.')
    disp(' ')
    disp('     A=[1,0,-1,3; 2,1,4,-2;...  ')
    disp('        0,-5,0,1; -1,2,-1,3] ')
    disp('     B=[2,1,0,7; -2,5,1,2;...  ')
    disp('        4,1,3,-6; 4,-4,-1,5] ')
    disp('     C=[2,1,-5,-2; -3,4,-1,3;...  ')
    disp('        0,2,0,1; 7,13,-52,3] ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 1 thru 3: ')
    disp('Compute the product AB.  The ''''*'''' operator ')
    disp('is used for matrix multiplication. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  A*B ')
    disp(' ')
    disp('------------------------------------------------')
    disp('Do all the operations in steps 1-3 and describe ')
    disp('your conclusions by using MATLAB comments in')
    disp('your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 4')
    disp(' ')
    disp('Entering the following commands will generate')
    disp('three random 4 by 4 matrices. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  R=floor( 100*(2*rand(4)-1) ) ')
    disp('  S=floor( 100*(2*rand(4)-1) ) ')
    disp('  T=floor( 100*(2*rand(4)-1) ) ')
    disp(' ')
    disp('------------------------------------------------')
    disp('Do all the operations in step 4 and describe ')
    disp('your conclusions by using MATLAB comments in')
    disp('your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;   
    disp(' ')
    
    disp('----------------------------------------------')
    disp('Step 5 and 6: ')
    disp('Carry out the assigned operations in steps 5 and 6.')
    disp(' ')
    disp('Then re-execute the commands above to get a')
    disp('new set of random matrices R, T, S, and ')
    disp('redo the operations again.')
    disp(' ')
    disp('------------------------------------------------')   
    disp('Describe your conclusions by using MATLAB')
    disp('comments your diary file.')
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('To go on to part 2 of this module, ')
    disp('type: matops2')
    disp(' ')