disp('Part 2.  The product Ax as a linear combination')
disp('  ')
disp('The standard unit vectors are stored as')
disp('matrices e1, e2, e3, and e4.')
disp('If you have not already typed matrix_data,')
disp('do so now to set up those vectors.')
disp('  ')
disp('Remember that you can extract column 3')
disp('from a matrix A by typing A(:,3).')
disp('  ')
disp('When you are ready to go on to Part 3,')
disp('type matrix3.')
disp('  ')

