%  pend3.m
% Matlab file for Part 3 of The Pendulum module
global g m b L

disp('*********************************************')
disp('Part 3:  Period as a Function of Length ')
disp('*********************************************')
disp('  ')    

    format short
    g=9.807; m=1; L=1;

    disp('We return the damping coefficient b to zero')
    disp('and study how the period of the undamped ')
    disp('pendulum depends on its length L.')
    b=0
    disp(' ')
    disp('--------------------------------------------')
    disp('Steps 1 and 2:  Length L = 1.')
    disp('Determine the period for each of the initial')
    disp('displacements theta(0)=0.5 and theta(0)=2 ')
    disp('from the plots.  Tell how you do it by using ')
    disp('MATLAB comments in your diary file.')
    disp(' ')
    disp('We have copied the commands from Part 2 below.')
    disp('Enter: ')
    disp(' ')
    disp('  L = 1 ')
    disp('  figure(1); clf  % Clears figure')
    disp('  [t,z]=ode45(''de_rhs'',[0,10],[0.5,0]); ')
    disp('  theta1=z(:,1); thetap1=z(:,2);  ')
    disp('  plot(t,theta1,''k''); hold on ')
    disp('  [t,z]=ode45(''de_rhs'',[0,10],[2,0]); ')
    disp('  theta2=z(:,1);  thetap2=z(:,2);  ')
    disp('  plot(t,theta2,''r''); grid on ')
    disp('  figure(2); clf ')
    disp('  dirfield(-2,2, -5.5,5.5); hold on ')
    disp('  plot(theta1,thetap1,''k'')  ')
    disp('  plot(theta2,thetap2,''r'')  ')
    disp('  axis equal;axis([-2,2, -5.5,5.5]) ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 3:  Variable L.')
    disp('Determine the period for only the initial')
    disp('displacement theta(0)=0.5 from the plots ')
    disp('for varying L values.')
    disp(' ')
    disp('The relevant commands from above are below.')
    disp('Enter: ')
    disp(' ')
    disp('  L = ?  % fill in ')
    disp('  figure(1); clf  % Clears figure')
    disp('  [t,z]=ode45(''de_rhs'',[0,10],[0.5,0]); ')
    disp('  theta1=z(:,1); thetap1=z(:,2);  ')
    disp('  plot(t,theta1,''k''); grid on ')
    disp('  figure(2); clf ')
    disp('  dirfield(-0.5,0.5, -5,5); hold on ')
    disp('  plot(theta1,thetap1,''k'')  ')
    disp('  axis([-0.5,0.5, -5,5]) ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Redo the plots for L ranging from 0.1 to 2. ')
    disp('Every time you change the length L and determine ')
    disp('the period from the plot, record the ')
    disp('[length, period] pair using a comment in your')
    disp('diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')
    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 3 (continued):')    
    disp('Fill your lengths into a list called length')
    disp('and the corresponding periods into a list ')
    disp('called period.  (Modify the ones below.) ')
    disp('Then make a scatterplot of the [length, period]')
    disp('pairs.')
    disp(' ')
    disp('Complete and enter:')
    disp(' ')
    disp('  length=[0.1, 0.2, 0.3, ?]; ')
    disp('  period=[1, 2, 3, ?]; ')
    disp('  plot(length,period,''bo'') ')
    disp(' ') 
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 4:')    
    disp('Give your conjecture and supporting evidence')
    disp('concerning the relationship between length')
    disp('and period.')
    disp('Use MATLAB comments in your diary file. ')
    disp(' ')
    disp(' ') 
    disp('----------------------------------------------')
    disp('When your answers are done, to go on to')
    disp('part 4 of this module, type: pend4')
    disp(' ')