%  radwas3.m
% Matlab file for Part 3 of the Radioactive Wastes
% module

disp('*********************************************')
disp('Part 3: Isotope Half-Lives')
disp('*********************************************')
disp('  ')    

    format short

    disp('Steps 1 and 2:')
    disp('Show your calculations in your diary file.')
    disp(' ')
    disp('Copy each of the MATLAB comment lines below,')
    disp('fill in the information, and enter for')
    disp('your diary file.')
    disp(' ')
    disp('%Phosphorus-32 (500 mCi) ')
    disp('%  Reference date: ')
    disp('%  Current date: ')
    disp('%  Elapsed time:')
    disp('%  Current amount:')
    disp('%  Lambda value:')
    disp('%  Half-Life:')
    disp('%  Time to reduce to 1 MuCi:')
    disp(' ')
    disp('After you are finished, to continue type')
    disp('the word return and hit enter!')
    disp(' ')

    keyboard
    disp(' ')

    disp('-------------------------------------------') 
    disp('Step 3:  Plot the decay function for')
    disp('Phosphorus-32 over the time interval it')
    disp('takes to decay to below 1 muCi.')
    disp(' ')
    disp('-------------------------------------------')
    disp('How does this decay time compare with the Duke')
    disp('EPD guideline of 10 half-lives? ')
    disp('Answer as MATLAB comments in your diary file.')
    disp(' ')
    disp('After you are finished, to continue type')
    disp('the word return and hit enter!')
    disp(' ')

    keyboard
    disp(' ')
   
    disp('------------------------------------------- ')
    disp('Repeat steps 1 and 2 for 500 mCi of iodine-125')
    disp('Show your calculations in your diary file.')
    disp(' ')
    disp('Copy each of the MATLAB comment lines below,')
    disp('fill in the information, and enter for')
    disp('your diary file.')
    disp(' ')
    disp('%Iodine-125 (500 mCi) ')
    disp('%  Reference date: ')
    disp('%  Current date: ')
    disp('%  Elapsed time:')
    disp('%  Current amount:')
    disp('%  Lambda value:')
    disp('%  Half-Life:')
    disp('%  Time to reduce to 1 MuCi:')
    disp(' ')
    disp('After you are finished, to continue type')
    disp('the word return and hit enter!')
    disp(' ')

    keyboard
    disp(' ')

    disp('-------------------------------------------') 
    disp('Repeat step 3 for Iodine-125:')  
    disp('Plot the decay function for Iodine-125')
    disp('over the time interval it takes to decay to')
    disp('below 1 muCi.')
    disp(' ')
    disp('-------------------------------------------')
    disp('How does this decay time compare with the Duke')
    disp('EPD guideline of 10 half-lives? ')
    disp('Answer as MATLAB comments in your diary file.')
    disp(' ')
    disp('After you are finished, to continue type')
    disp('the word return and hit enter!')
    disp(' ')

    keyboard
    disp(' ')
  
    disp('-------------------------------------------') 
    disp('Step 5: ')
    disp('Show your calculations in your diary file.')
    disp(' ')
    disp('Copy each of the MATLAB comment lines below,')
    disp('fill in the information, and enter for')
    disp('your diary file.')
    disp(' ')
    disp('%Iodine-131 (500 mCi) ')
    disp('%  Half-Life:')
    disp('%  Lambda value:')
    disp('%  Time to reduce to 1 MuCi:')
    disp(' ')
    disp('---------------------------------------------')  
    disp('Plot the decay function for Iodine-131')
    disp('over the time interval it takes to decay to')
    disp('below 1 muCi.')
    disp(' ')
    disp('----------------------------------------------')
    disp('How does this decay time compare with the Duke')
    disp('EPD guideline of 10 half-lives? ')
    disp('Answer as MATLAB comments in your diary file.')
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('To go on to Part 4 of this module,')
    disp('type: radwas4')
    disp(' ')


