%  sinugr2.m
% Matlab file for Part 2 of the Sinusoidal Graphs
% module

disp('********************************************')
disp('Part 2:  Amplitude')
disp('********************************************')
disp('  ')    

    format short

    disp('----------------------------------------------')
    disp('Step 1:')
    disp('Answer the questions as MATLAB comments in')
    disp('your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('--------------------------------------------')
    disp('Steps 2 and 3:')
    disp('Enter the following commands to plot the ')
    disp('function B*sin(t), where B=3.')
    disp(' ')
    disp('     B=3;            ')
    disp('     t=-8:0.1:8;     ')
    disp('     y=B*sin(t);     ')
    disp('     plot(t,y,''b'') ')
    disp('     grid on         ')
    disp(' ')
    disp('--------------------------------------------')  
    disp('Experiment with changing B and replotting. ')
    disp(' ')
    disp('State the relation between B and the amplitude.')
    disp('Does changing the value of B have any effect')
    disp('on the period of the function?')
    disp('Answer using MATLAB comments in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 4:')
    disp('Enter appropriate values of B and C into MATLAB:')
    disp(' ')
    disp('  B= ?')
    disp('  C= ?')
    disp(' ')
    disp('Then enter the following commands to plot the ')
    disp('function B*sin(C*t).')
    disp(' ')
    disp('     t=-8:0.1:8;     ')
    disp('     y=B*sin(C*t);   ')
    disp('     plot(t,y,''b'') ')
    disp('     grid on         ')
    disp(' ')
    disp('--------------------------------------------')  
    disp('Experiment with changing B and C and replotting.')
    disp(' ')
    disp('Find B and C so that the function has amplitude')
    disp('equal to 3 and period equal to pi/2.')
    disp('Answer using MATLAB comments in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Step 4 (cont.):')
    disp('Find B and C so that the function has amplitude')
    disp('equal to 0.5 and period equal to 3*pi.')
    disp('  (Check by plotting to make sure.) ')
    disp(' ')
    disp('Answer using MATLAB comments in your diary file.')
    disp(' ')
    disp(' ')
    disp('----------------------------------------------')
    disp('To go on to part 3 of this module,') 
    disp('type: sinugr3.')
    disp(' ')
