%  sprints3.m
% Matlab file for Part 3 of the World Class Sprints
% module
global Time1 Dist1 Time2 Dist2

disp('********************************************')
disp('Part 3:  Parameter Values ')
disp('********************************************')
disp('  ')    

    format short

    disp('-----------------------------------------------')
    disp('Steps 1 ')
    disp('Calculate the average split times for the four')
    disp('men at each distance ')
    disp(' ')
    disp('For example, for the 30 meter distance, the ')
    disp('average split time for the four men is ')
    disp(' ')
    disp('  T1=mean( [3.85,3.83,3.82,3.95] ) ')
    disp(' ')
    disp('Calculate the other three averages. ')
    disp('Then fill in the blanks and enter the data')
    disp('below into MATLAB. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  T1=? ')
    disp('  T2=? ')
    disp('  T3=? ')
    disp('  T4=? ')
    disp('  D1=30; D2=60; D3=80; D4=100; ')
    disp('  distdata=[D1,D2,D3,D4]; ')
    disp(' ')
    disp('To continue, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('------------------------------------------------')
    disp('Step 2: ')
    disp('Derive the equation given in step 2. ')
    disp('Give your explanation using MATLAB comments ')
    disp('in your diary file. ')
    disp(' ')
    disp('When you are done, to continue, type the word')
    disp('return and hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')
    
    disp('---------------------------------------------')
    disp('Step 3: ')
    disp('A MATLAB function z=fun(b) is provided with this')
    disp('module in m-file fun.m ')
    disp(' ')
    disp('Enter ''''type fun'''' to see that the function is')
    disp('exactly the one whose root gives us the value of')
    disp('the parameter b that we are looking for. ')
    disp(' ')
    disp('To continue, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('-------------------------------------------- ')
    disp('Step 3 (cont.): ')
    disp('Let''s first fit our model function through the')
    disp('data points (T2,D2), (T4,D4).  You can change ')
    disp('this choice to any two data points you want.')
    disp(' ')
    disp('We need to first store the data points into the ')
    disp('global variables Time1,Dist1, Time2,Dist2 so the')
    disp('function fun(b) can use them.')
    disp(' ')
    disp('Then we use the MATLAB root finder fzero to solve')
    disp('for b, using b=1.0 as an initial guess. ')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  Time1=T2, Dist1=D2, ')
    disp('  Time2=T4, Dist2=D4, ')
    disp('  b=fzero(''fun'', 1.0) ')
    disp(' ')
    disp('To continue, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('------------------------------------------------')
    disp('Step 5: ')
    disp('Use the formula in step 4 to solve for the  ')
    disp('parameter A.   ')
    disp(' ')
    disp('You should use several choices of the two ')
    disp('(time,distance) data points to find b and the ')
    disp(' ')
    disp('resulting A.  Do this to get your best estimate. ')
    disp('When you are done, to continue, type the word')
    disp('return and hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')

    disp('-------------------------------------------- ')
    disp('Step 6: ')
    disp('Enter your best values of b and A.')
    disp('Then the following statements plot the data ')
    disp('pairs for Linford Christie (the fastest) as circles')
    disp('and for Carl Lewis (the slowest) as diamonds.')
    disp('Superimposed is the model function you have fit.')
    disp(' ')
    disp('Enter: ')
    disp(' ')
    disp('  b=? ')
    disp('  A=? ')
    disp('  timesLC=[3.85,6.45,8.15,9.87]; ')
    disp('  timesCL=[3.95,6.59,8.30,10.02]; ')
    disp('  plot(timesLC,distdata,''bo''); hold on ')
    disp('  plot(timesCL,distdata,''gd'') ')
    disp('  t=0:0.1:10.5; ')
    disp('  y=A*b*(t-b+b*exp(-t/b)); ')
    disp('  plot(t,y,''r'') ')
    disp(' ')
    disp('To continue, type the word return and')
    disp('hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('------------------------------------------------')
    disp('Step 7 and 8: ')
    disp('Repeat steps 3, 5, and 6 to estimate the parameters')
    disp('b and A for the women''s data and make the plot')
    disp('showing the model''s fit.')
    disp(' ')
    disp(' ')
    disp('-------------------------------------------- ')
    disp('When you are ready to go on to Part 4 ')
    disp('of this module, type: sprints4.')
    disp(' ')
