%  taylor2.m
% Matlab file for Part 2 of the Taylor Polynomial I module

disp('********************************************')
disp('Part 2:   Polynomial Approximations to e^x ')
disp('********************************************')
disp('  ')    

    format short

    disp('Step 1 and 2:')
    disp('Give the answers to the questions as MATLAB')
    disp('comments in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')
    disp('Step 3:')
    disp('In your calculations, you can use the MATLAB')
    disp('function: ')
    disp('     factorial(n)  ')
    disp('to calculate n factorial, if you wish. ')
    disp(' ')
    disp('Enter the first five Tayor coefficients')
    disp('for the function exp(x) into MATLAB.')
    disp(' ')
    disp('  a0=? ')
    disp('  a1=? ')
    disp('  a2=? ')
    disp('  a3=? ')
    disp('  a4=? ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')
    disp('Step 4: First p0(x). ')
    disp('The following commands plot p0(x)=a0 along ')
    disp('with exp(x) in one figure window and the error')
    disp('function exp(x)-p0(x) in another.')
    disp(' ')
    disp('Enter these commands: ')
    disp(' ')
    disp(' c=[a0]; ')
    disp(' x=-2:0.1:2; ')
    disp(' y=polyval(c,x); ')
    disp(' figure(1) ')
    disp(' plot(x,y,x,exp(x)) ')
    disp(' xlabel(''x'') ')
    disp(' ylabel(''y=p0(x)'') ')
    disp(' legend(''p0(x)'',''exp(x)'') ')
    disp(' figure(2) ')
    disp(' plot(x,exp(x)-y) ')
    disp(' xlabel(''x'') ')
    disp(' ylabel(''y = exp(x)-p0(x)'') ')
    disp(' ')
    disp('------------------------------------------- ')
    disp('Describe how well p0(x) approximates exp(x). ')
    disp('Write your description as MATLAB comments in')
    disp('your diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')
    disp('Step 4: Now p1(x). ')
    disp('The following commands plot p1(x)=a1*x + a0 ')
    disp('along with exp(x) in one figure window and the')
    disp('error function exp(x)-p1(x) in another.')
    disp(' ')
    disp('Enter these commands: ')
    disp('')
    disp(' c=[a1 a0]; ')
    disp(' x=-2:0.1:2; ')
    disp(' y=polyval(c,x); ')
    disp(' figure(1) ')
    disp(' plot(x,y,x,exp(x)) ')
    disp(' xlabel(''x'') ')
    disp(' ylabel(''y=p1(x)'') ')
    disp(' legend(''p1(x)'',''exp(x)'') ')
    disp(' figure(2) ')
    disp(' plot(x,exp(x)-y)')
    disp(' xlabel(''x'') ')
    disp(' ylabel(''y = exp(x)-p1(x)'') ')
    disp(' ')
    disp('------------------------------------------- ')
    disp('Describe how well p1(x) approximates exp(x). ')
    disp('Write your description as MATLAB comments in')
    disp('your diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')
    disp('Step 4: Continue ')
    disp('To graph p2(x)= a2*x^2 + a1*x +a0, you have')
    disp('to set c=[a2 a1 a0] in the commands above.')
    disp(' ')
    disp('To graph p3(x)= a3*x^3 + a2*x^2 + a1*x +a0,')
    disp('you have to to set c=[a3 a2 a1 a0]. ')
    disp(' ')
    disp('The pattern should now be clear. ')
    disp(' ')
    disp('------------------------------------------- ')
    disp(' For each polynomial p2(x), p3(x), p4(x),  ')
    disp(' plot pn(x) and exp(x) together and also ')
    disp(' plot the error function exp(x)-pn(x).')
    disp(' ')
    disp('Describe how well pn(x) approximates exp(x). ')
    disp('Write your description as MATLAB comments in')
    disp('your diary file. ')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')
    
    disp('--------------------------------------------')
    disp('Step 5:')
    disp('Show the MATLAB calculations needed to find ')
    disp('e^(5/4) to within 0.01, or use a calculator.')
    disp('Explain your reasoning as MATLAB comments')
    disp('in your diary file.')
    disp(' ')
    disp('----------------------------------------------')
    disp('When you are finished with part 2, to go on to')
    disp('part 3 of this module, type: taylor3.')
    disp(' ')