%  worpop1.m
% Matlab file for Part 1 of the World Population module

disp('********************************************')
disp('Part 1:  Background')
disp('********************************************')
disp('  ')    

    format short
    disp(' ')
    disp('Respond to the questions in Step 1 here.')
    disp('Write as MATLAB comments in your diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')
    
    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('World Population Data:')
    disp(' ')
    disp('Below find two lists.  The first is a list')
    disp('of years.  The second list gives the world')
    disp('population in millions for each of the years.')
    disp(' ')
    disp(' ')
    disp('Copy the following commands and paste them as')
    disp('a group at a MATLAB prompt, then execute them.')
    disp(' ')
    disp(' years=[1000,1650,1750,1800,1850,1900,1910, ...')
    disp('  1920,1930,1940,1950,1955,1960,1965,1970, ...')
    disp('  1975,1980,1985]; ')
    disp(' pops=[200,545,728,906,1171,1608,1750, ...')
    disp('  1834,2070,2295,2517,2780,3005,3345,3707, ...')
    disp('  4086,4454,4850]; ')  
    disp(' ')
    disp('After you have entered the lists, check that')
    disp('they match up by entering the command')
    disp('  [years;pops]''  ')
    disp('to see the data in table form.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;
    disp(' ')

    disp('----------------------------------------------')
    disp('Enter the following commands to plot the data,')
    disp('label the axes, and give the plot a title.')
    disp(' ')
    disp(' ')
    disp('  plot(years,pops,''o'') ')
    disp('  xlabel(''year '')  ')
    disp('  ylabel(''world population (in millions)'') ')
    disp('  title(''World Population Data'') ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Respond to Step 1 questions about the data')
    disp('here.  Write as MATLAB comments in your')
    disp('diary file.')
    disp(' ')
    disp('To continue afterwards, type the word return')
    disp('and hit enter!')
    disp(' ')

    keyboard;  
    disp(' ')

    disp('----------------------------------------------')
    disp('To make a semilog plot of our data, we will')
    disp('plot the pairs (years, log(pops)).')
    disp(' ')
    disp('Copy the following commands and paste them at')
    disp('a MATLAB prompt, then execute them.')
    disp(' ')
    disp('  plot(years,log(pops),''ro'') ')
    disp('  xlabel(''year '')  ')
    disp('  ylabel(''log( world population )'')  ')
    disp('  title(''SemiLog Plot of World Population Data'') ')
    disp(' ')
    disp('----------------------------------------------')
    disp('Give your answer to Step 3 here.')
    disp('Write as MATLAB comments in your diary file.')
    disp(' ')
    disp(' ')   
    disp('----------------------------------------------')
    disp('To go on to Part 2 of this module,')
    disp('type: worpop2')
    disp(' ')


