        
; -------------------------------------------------------------------
; This file is automatically generated by exceptions.xsl Do not edit
;
; See the bootcode_aware module of the mpc555 for details.
; -------------------------------------------------------------------

;-----------------------------------------------------------
; The __start location is the entry point to the application
;-----------------------------------------------------------
	.import __start

;-----------------------------------------------------------
; To handle the decrementer exception
;-----------------------------------------------------------
	.import decrementer_isr

; The default handler just loops
;-----------------------------------------------
	.text
default:
	ba default

	;--------------------------------------------
	; An entry in the application linker command
	; file is required to support this module
	;--------------------------------------------
	.section .application_bios
	
	.export reserved0x0
	.export application_reset
	.export machine_check_exception
	.export data_access_exception
	.export instruct_access_exception
	.export external_interrupt_exception
	.export alignment_exception
	.export program_exception
	.export fp_unavailable_exception
	.export decrementer_exception
	.export reserved0x50
	.export reserved0x58
	.export system_call_exception
	.export trace_exception
	.export fp_assist_exception
	.export software_emulation_exception
	.export reserved0x80
	.export reserved0x88
	.export reserved0x90
	.export instruction_protection_exception
	.export data_protection_exception
	.export reserved0xA8
	.export reserved0xB0
	.export reserved0xC8
	.export reserved0xD0
	.export reserved0xD8
	.export data_breakpoint
	.export instruct_breakpoint
	.export maskable_external_breakpoint
	.export nonmaskable_external_breakpoint
	.extern external_interrupt_isr
;------------------------------------------------
reserved0x0:
		
	ba reserved0x0
;------------------------------------------------
application_reset:
		
	ba __start
;------------------------------------------------
machine_check_exception:
		
	ba machine_check_exception
;------------------------------------------------
data_access_exception:
		
	ba data_access_exception
;------------------------------------------------
instruct_access_exception:
		
	ba instruct_access_exception
;------------------------------------------------
external_interrupt_exception:
		
	ba external_interrupt_isr
;------------------------------------------------
alignment_exception:
		
	ba alignment_exception
;------------------------------------------------
program_exception:
		
	ba program_exception
;------------------------------------------------
fp_unavailable_exception:
		
	ba fp_unavailable_exception
;------------------------------------------------
decrementer_exception:
		
	ba decrementer_isr
;------------------------------------------------
reserved0x50:
		
	ba reserved0x50
;------------------------------------------------
reserved0x58:
		
	ba reserved0x58
;------------------------------------------------
system_call_exception:
		
	ba system_call_exception
;------------------------------------------------
trace_exception:
		
	ba trace_exception
;------------------------------------------------
fp_assist_exception:
		
	ba fp_assist_exception
;------------------------------------------------
software_emulation_exception:
		
	ba software_emulation_exception
;------------------------------------------------
reserved0x80:
		
	ba reserved0x80
;------------------------------------------------
reserved0x88:
		
	ba reserved0x88
;------------------------------------------------
reserved0x90:
		
	ba reserved0x90
;------------------------------------------------
instruction_protection_exception:
		
	ba instruction_protection_exception
;------------------------------------------------
data_protection_exception:
		
	ba data_protection_exception
;------------------------------------------------
reserved0xA8:
		
	ba reserved0xA8
;------------------------------------------------
reserved0xB0:
		
	ba reserved0xB0
;------------------------------------------------
reserved0xC8:
		
	ba reserved0xC8
;------------------------------------------------
reserved0xD0:
		
	ba reserved0xD0
;------------------------------------------------
reserved0xD8:
		
	ba reserved0xD8
;------------------------------------------------
data_breakpoint:
		
	ba data_breakpoint
;------------------------------------------------
instruct_breakpoint:
		
	ba instruct_breakpoint
;------------------------------------------------
maskable_external_breakpoint:
		
	ba maskable_external_breakpoint
;------------------------------------------------
nonmaskable_external_breakpoint:
		
	ba nonmaskable_external_breakpoint