function te = cgtradeoff(varargin)
%CGTRADEOFF Constructor for cgtradeoff objects
%
%  WARNING: This class has been removed and replaced with the
%  cgtradeoffnode class.  The cgtradeoff class has been retained in a
%  reduced form solely for the purpose of loading CAGE projects from
%  previous versions.  This class should not be used for any other purpose.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.2.2.3 $  $Date: 2004/02/09 07:16:06 $

if nargin & isstruct(varargin{1})
    % use struct as base for object from loadobj
    te = varargin{1};
    varargin(1) = [];
    e =te.cgexpr;
    te = mv_rmfield(te,'cgexpr');
else
    te = struct('tablePtrs' , [] , ...
        'fillPtrs' , [] , ...
        'fillMask' , [] , ...
        'opPoint' , [] , ...
        'currentRow' , 1 , ...
        'currentCol' , 1 , ...
        'showError' , 1 , ...
        'viewStore' , [],...
        'sameYlimits' , 0 , ...
        'fillReg', [], ...
        'currentRows', [], ...
        'currentCols', [],...
        'version',4, ...
        'hiddenFactors', [], ...
        'hiddenModels', []);
    e = cgexpr;
end

te = class(te , 'cgtradeoff' , e);
