function errStruct = mkerrstruct(errID, errMsg)
%MKERRSTRUCT Make error structure for OPC Toolbox OPCROOT object errors
%   ErrStruct = MKERRSTRUCT(ErrID) constructs an error structure from the
%   error ID specified by ErrID, using an internal lookup table. If the
%   error ID is not found, a generic error message is used.
%
%   ErrStruct = MKERRSTRUCT(errID, errMsg) does not use internal lookup
%   tables, and utilises the passed ErrMsg instead.
%
%   ErrStruct = MKERRSTRUCT(ErrStruct) can be used to parse and clean up an
%   existing error structure, such as that passed by NARGCHK.
%
%   ErrStruct is a structure suitable for passing to RETHROW or ERROR.
%
%   This function is intended for internal use only and should not be
%   called by the user.

% Copyright 2003-2004 OPTI-NUM solutions (Pty) Ltd.
% $Revision: 1.1.6.4 $ $Date: 2004/03/24 20:43:31 $

% We should watch out for a structure being passed, ala nargchk
switch nargin
    case 1
        if isstruct(errID),
            errMsg = errID.message;
            errID = errID.identifier;
        else
            errMsg = '';
        end
    case 2
        % Do nothing
    otherwise
        error('opc:mkerrstruct:numargs', 'Invalid number of arguments.');
end
% Check for empty error IDs
if isempty(errID),
    errID = sprintf('opc:%s:general', evalin('caller','mfilename'));
else
    % Now parse the ID specification
    errIDSpec = fliplr(strtok(fliplr(errID),':'));
    errID = sprintf('opc:%s:%s', evalin('caller','mfilename'), errIDSpec);
    % Check for empty error messages
    if isempty(errMsg),
        errMsg = lookupgeneric(errID);
    end
end
errStruct = struct('message', deblank(errMsg), 'identifier', errID);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function errMsg = lookupgeneric(errID)
%LOOKUPGENERIC Lookup generic error messages
%   These error messages are the same, irrespective of their source
errIDSpec = fliplr(strtok(fliplr(errID),':'));
errIDMsg = {...
	'actioninvalid', 'Invalid action passed to OPCREGISTER.'; ...
	'activearg', 'Active must be a string (one item) or cell array of strings (many items).'; ...
	'activeinvalid', 'Active must be either ''on'' or ''off''.'; ...
	'activemismatch', 'The number of active status identifiers must match the number of items'; ...
	'addfailed', 'One or more items/groups could not be added.'; ...
	'additemfailed', 'One or more items could not be added.'; ...
	'alreadylogging', 'Group is already logging.'; ...
	'arginvalid', 'Cannot create objects directly. Use helper functions to create this object.'; ...
	'arraydatareturned', 'One or more records returned arrays of data. Using first element only.'; ...
	'badarg', 'Bad argument.'; ...
	'badsource', 'Invalid source string. Specify ''device'' or ''cache''.'; ...
	'cancelled', 'Operation has been cancelled by the user.'; ...
	'cellref', 'Cell contents reference from a non-cell array object.'; ...
	'cellsubs', 'Cell references are disallowed.'; ...
	'classmismatch', 'Elements of OPC Toolbox object vectors must be the same class'; ...
	'closefile', 'LogFile could not be closed.'; ...
	'clsiderror', 'ServerID not found on host.'; ...
	'complex', 'Complex numbers not supported.'; ...
	'connected', 'Cannot change Host property while connected.'; ...
	'creationerror', 'Error creating opcda object.'; ...
	'ctrlc', 'The specified operation was aborted because ctrl-c was pressed.'; ...
	'datatypearg', 'Datatype must be a string (one item) or cell array of strings (many items).'; ...
	'datatypeinvalid', 'Invalid datatype.'; ...
	'datatypelength', 'The number of data type identifiers must match the number of items'; ...
	'datatypemismatch', 'Data type mismatch.'; ...
	'datesarg', 'Dates must be two MATLAB date numbers.'; ...
	'dimagree', 'Matrix dimensions must agree.'; ...
	'disconnected', 'OPC Toolbox object is disconnected.'; ...
	'dll', 'Failure calling OPCMEX DLL.'; ...
	'dotsubs', 'Invalid dot position.'; ...
	'emptyarrays', 'Empty vectors are not supported. Use delete and clear to perform this operation.'; ...
	'emptygroup', 'No items defined for the group.'; ...
	'emptyitemid', 'ItemID is empty.'; ...
	'errunknown', 'Unknown error ID.'; ...
	'eventarg', 'First argument must be an opcda object or event structure.'; ...
	'eventlogmaxexceeded', 'Number of events in EventLog exceeds EventLogMax. EventLog has been cleared.'; ...
	'eventstructarg', 'First argument must be an opcda object or event structure.'; ...
	'eventtype', 'Unknown event type encountered.'; ...
	'exceedsdims', 'Index exceeds array dimensions.'; ...
	'exceptionerror', 'Unknown exception error.'; ...
	'failed', 'The specified operation failed.'; ...
	'failedstatus', 'Failed to get server status.'; ...
	'fileerror', 'Could not read line while searching for first record.'; ...
	'filenamearg', 'Filename must be a non-empty string.'; ...
	'filenotfound', 'File not found.'; ...
	'fileopen', 'Could not open file for writing.'; ...
	'firstarg', 'The first input argument must be a string or an OPC object.'; ...
	'firstignored', 'File appears to contain a header. Ignoring some lines.'; ...
	'groupcreation', 'Error creating group object.'; ...
	'groupinactive', 'Group is inactive.'; ...
	'groupnamearg', 'Group name must be a non-empty string.'; ...
	'groupnamedup', 'New group name must be unique.'; ...
	'grpvalueslength', 'Values must be the same length as the number of items in the group.'; ...
	'handleunknown', 'Unknown handle type.'; ...
	'hostarg', 'Host must be a string.'; ...
	'inargs', 'Incorrect number of input arguments.'; ...
	'indexarg', 'Second argument must be an index or event type.'; ...
	'indexrange', 'Subscript indices must either be real positive integers or logicals.'; ...
	'inputsnotenough', 'Not enough input arguments.'; ...
	'inputstoomany', 'Too many input arguments.'; ...
	'install', 'Install generated warnings.'; ...
	'installernotfound', 'Microsoft Installer not found.'; ...
	'installfailed', 'OPC Foundation Core Components failed to install.'; ...
	'insufficientrecords', 'Insufficient records in memory to perform this operation.'; ...
	'internalerror', 'Internal error creating local object.'; ...
	'interrupted', 'Interrupt (Ctrl-C) waiting for operation to complete.'; ...
	'invalidarg', 'Invalid argument.'; ...
	'invalidclient', 'Invalid opcda object argument.'; ...
	'invaliddatatype', 'Datatype not supported.'; ...
	'invalidgroup', 'Invalid group.'; ...
	'invalidhost', 'Invalid host.'; ...
	'invalidinputtype', 'Invalid input type.'; ...
	'invalidserver', 'Invalid server.'; ...
	'invalidstruct', 'First argument is not an OPC data structure.'; ...
	'invalidtype', 'Unknown object type.'; ...
	'itemcreation', 'Error creating item object.'; ...
	'itemidarg', 'ItemID must be a non-empty string.'; ...
	'itemidbad', 'ItemID must be a string (single item) or cell array of strings (multiple items).'; ...
	'itemiddup', 'Attempt to add one or more duplicate ItemIDs.'; ...
	'itemidrepeat', 'The itemIDs of items to be added must be unique'; ...
	'iteminactive', 'One or more items is inactive.'; ...
	'itemsremoved', 'Items have not been validated on the server and have been removed.'; ...
	'itmvaluescell', 'Values must be a cell array when writing to multiple items.'; ...
	'itmvalueslength', 'Values must be the same length as the number of items specified.'; ...
	'lineinvalid', 'Invalid line found in log file. Ignoring.'; ...
	'matrixdisallowed', 'Only a row or column vector of OPC Toolbox objects can be created.'; ...
	'mismatch', 'In an assignment A(I) = B, the number of elements in B and\nI must be the same.'; ...
	'modearg', 'Unknown mode in OBJ2MFILE.'; ...
	'namespacearg', 'First argument must be a namespace structure.'; ...
	'ndindexing', 'Indexing into N-D arrays is not supported.'; ...
	'negativeind', 'Subscript indices must either be real positive integers or logicals.'; ...
	'noconnect', 'Could not connect to server.'; ...
	'nomemory', 'Insufficient memory to perform this operation.'; ...
	'norecordsavailable', 'Group is not logging and no records are available.'; ...
	'nosuchfunction', 'Function not found.'; ...
	'notregistered', 'OPC Foundation Core Components not installed. Run OPCREGISTER to install the OPC Foundation Core Components.'; ...
	'nrecnumeric', 'Number of records must be a numeric scalar.'; ...
	'nrecposint', 'Number of records must be a positive integer.'; ...
	'nrectoolarge', 'Number of records can not exceed RecordsMax property value.'; ...
	'numargs', 'Invalid number of arguments.'; ...
	'obj2marg', 'Additional arguments must be strings.'; ...
	'objcreation', 'OPCROOT is not a user-creatable object. Use OPCDA, ADDGROUP, or ADDITEM to create OPC Toolbox objects.'; ...
	'objectsexist', 'OPC Toolbox objects exist in the workspace. Clear them with OPCRESET.'; ...
	'objinvalid', 'OPC Toolbox object is invalid.'; ...
	'objnotcopied', 'Parent object did not copy argument.'; ...
	'objvector', 'Object must be a scalar when using SET to retrieve information.'; ...
	'openfilefailed', 'Logfile could not be opened.'; ...
	'outputstoomany', 'Too many output arguments.'; ...
	'parensubs', 'Invalid parentheses.'; ...
	'parentdifferent', 'Vectors of OPC Toolbox objects must have the same parent.'; ...
	'parentdisconnected', 'Parent OPCDA object is disconnected.'; ...
	'parentinactive', 'Parent group is inactive.'; ...
	'parenttype', 'Parent type is invalid.'; ...
	'parentvector', 'Parent object must be a scalar.'; ...
	'properror', 'Unknown property.'; ...
	'propidarg', 'PropID must be a double array.'; ...
	'propinvalid', 'Invalid property.'; ...
	'pvmismatch', 'Property/Value pair mismatch.'; ...
	'recnotfound', 'Could not find record in file.'; ...
	'recordsarg', 'Records property must be a vector of two increasing integers.'; ...
	'secondarg', 'Second argument must be a string.'; ...
	'server', 'Host not found on network.'; ...
	'servererror', 'Failed to retrieve namespace.'; ...
	'serverexception', 'Failed to retrieve namespace.'; ...
	'serveridarg', 'ServerID must be a string.'; ...
	'serveritf', 'Could not initialise server interface.'; ...
	'serverstatus', 'Server status error.'; ...
	'shutdown', 'Shutdown callback will not work for this server.'; ...
	'startfailed', 'START failed for all groups.'; ...
	'stopfailed', 'STOP failed for all groups.'; ...
	'subsenabled', 'Subscription must be ''''on'''' for group to start logging.'; ...
	'substype', 'Unknown subscript type.'; ...
	'syntaxerror', 'Syntax error.'; ...
	'timeout', 'The specified operation timed out.'; ...
	'transidinvalid', 'Transaction ID must be a positive integer.'; ...
	'undefined', 'Function ''''subsindex'''' is not defined for values of class OPCROOT.'; ...
	'undefinedpropids', 'None of the requested PropIDs are defined for this item.'; ...
	'unhandlederror', 'Unknown error occurred while destroying objects.'; ...
	'valuescell', 'Values must be a cell array when writing to groups containing multiple items.'; ...
	'valueslength', 'Values must be the same length as the number of items in the group.'; ...
	'valuesmixed', 'Cannot write a cell array containing non-string elements to an item.'; ...
	'vecnotsupported', 'Cannot perform this operation on vectors of OPC Toolbox objects.'; ...
    };
errInd = strcmp(errIDSpec, errIDMsg(:,1));
if ~any(errInd),
    error('opc:mkerrstruct:errunknown', 'Unknown error ''%s''.', errIDSpec);
else
    errMsg = errIDMsg{errInd,2};
end
