function gr=graph1d(varargin)
%GRAPH1D/GRAPH1D  Constructor function for a Graph1d object. 
%   Constructor for a graph1d object - allows 1d viewing of a
%   design matrix with a factor selection facility.
%   GR=GRAPH1D creates a valid object. See also GRAPH1D/SET
%   for more details on the available properties.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.2.2.2 $  $Date: 2004/02/09 07:18:52 $

%  Date: 16/9/1999


% Data is stored as follows:
% gr.patch - copy of object
% gr.axes - position vector
% gr.line - data matrix
% gr.hist.axes - histogram on/off indicator
% gr.hist.patch - bar colour(s)
% gr.factorsel - list of labels
% gr.hist.patch - number of bars
% gr.factortext - limits
% gr.badim - visible setting

% Use given figure handle or current figure by default (creates one if necessary)
if nargin>0 & ishandle(varargin{1})
   gr.parent=varargin{1};
else
   gr.parent=gcf;
end

% default position - reset later if its given
pos=[50 50 400 250];
gr.patch=xregGui.oblong('parent',gr.parent,...
   'position',pos,...
   'facecolor',[1 1 1],...
   'visible','off',...
   'hittest','off',...
   'layer','back');

cp=floor(pos(1:2)+pos(3:4).*0.5)-15;
gr.badim=xregGui.axesimage('parent',gr.parent,...
   'image',pr_badim,...
   'position',[cp 32 32],...
   'visible','off',...
   'userdata','on',...
   'hittest','off');
   
gr.axes=xregGui.axes('units','pixels',...
   'parent',gr.parent,...
   'position',[pos(1)+30 pos(2)+100 pos(3)-60 5],...
   'ytick',[],...
   'ylim',[0 0.5],...
   'xlim',[0 1],...
   'yticklabel',{},...
   'color','none',...
   'visible','off',...
   'userdata',[50 50 400 250]);

gr.line=handle(line('xdata',[],...
   'ydata',[],...
   'parent',gr.axes,...
   'marker','o',...
   'linestyle','none',...
   'markeredgecolor','none',...
   'markerfacecolor','b',...
   'visible','off',...
   'markersize',4));

% Histogram axes

gr.hist.axes=xregGui.axes('units','pixels',...
   'parent',gr.parent,...
   'position',[pos(1)+28 pos(2)+130 pos(3)-56 pos(4)-160],...
   'ytick',[],...
   'xtick',[],...
   'ylim',[0 1],...
   'xlim',[0 1],...
   'xticklabel',{},...
   'color','none',...
   'visible','off',...
   'userdata',1,...
   'ygrid','on',...
   'layer','bottom',...
   'hittest','off');

ud.colours=[1 0 0;0 0 0];
ud.numbars=[];
ud.frameon=1;
gr.hist.patch=handle(patch('parent',gr.hist.axes,...
   'visible','off',...
   'userdata',[],...
   'facecolor','interp',...
   'facelighting', 'gouraud',...
   'edgelighting', 'flat',...
   'vertices',[],...
   'userdata',ud,...
   'clipping','off',...
   'hittest','off'));
set(get(gr.hist.axes,'title'),'string','Frequency');


% create extra controls for swapping factors
gr.factortext=xregGui.uicontrol('style','text',...
   'parent',gr.parent,...
   'position',[pos(1)+pos(3)/2-70 pos(2)+30 70 16],...
   'backgroundcolor','w',...
   'string','Select factor:',...
   'visible','off',...
   'userdata',{},...
   'enable','inactive',...
   'hittest','off');
gr.factorsel=xregGui.uicontrol('style','popupmenu',...
   'parent',gr.parent,...
   'position',[pos(1)+pos(3)/2 pos(2)+30 70 20],...
   'backgroundcolor','w',...
   'string',{''},...
   'visible','off');

gr=class(gr,'mvgraph1d');

% save an object handle in the patch for later use.
set(gr.factorsel,'callback',{@i_factorchange,gr});

% set extra props if specified
if nargin>1 & ishandle(varargin{1}); 
   % Set properties that are passed in
   gr=set(gr,'visible','on',varargin{2:end});
elseif nargin>0 & ~ishandle(varargin{1})
   gr=set(gr,'visible','on',varargin{:});
else
   set([gr.axes;gr.line;gr.patch;gr.factorsel;gr.factortext;gr.hist.axes;gr.hist.patch],'visible','on');
end

return



function i_factorchange(src,evt,obj)
factor_change(obj);
return