%CLOCK	Wall clock.
%	CLOCK returns a six element row vector containing the
% 	current time and date in decimal form:
% 
% 	   CLOCK = [year month day hour minute seconds]
% 
% 	The first five elements are integers. The seconds element
% 	is accurate to several digits beyond the decimal point.
% 	FIX(CLOCK) rounds to integer display format.
%
%	See also ETIME, TIC, TOC, CPUTIME.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
