%I   	Imaginary unit.
% 	The variables i and j both initially have the value sqrt(-1)
%	for use in forming complex quantities.  For example, the
%	expressions 3+2i, 3+2*i, 3+2i, 3+2*j and 3+2*sqrt(-1).
% 	all have the same value.  However, both i and j may be 
%	assigned other values, often in FOR loops and as subscripts.
%
% 	See also J.

%	Copyright (c) 1984-94 by The MathWorks, Inc.
%	Built-in function.
