function why
%WHY 	Provides succinct answers to any questions.

%	Copyright (c) 1984-94 by The MathWorks, Inc.

Y = ['How the hell should I know?'
     'Why not?                   '
     'It feels good.             '
     'R.T.F.M.                   '
     'Why? Because we like you!  '
     'Stupid question.           '
     'Pete made me do it.        '
     'Because it''s there.        '
     'For people like you.       '
     'Time to get back to work.  '];
disp(' ')
disp(Y(fix(10*rand)+1,:))
disp(' ')
