function menu_item = generic_menu(title_bar, label, menu_selections)

% Generates a menu of menu_selections and returns the number corresponding
% to the menu item selected

global Scale

num_items = size(menu_selections, 2) ;
size_fig = min((num_items * .1), .9) ;
menu_item = 0 ;

% Display main figure
genericfig = figure('Name', title_bar, ...
             'NumberTitle', 'off', ...
             'Color',[0.76 0.76 0.76], ...
             'Units','normalized', ...
             'Position', [.33 .5-(size_fig/2) .33 size_fig], ...
             'Menubar','none',...
             'Tag','GenericFigure');

% Display label
uicontrol('Parent', genericfig, ...
          'Units', 'normalized', ...
          'BackgroundColor', [0.76 0.76 0.76], ...
          'Position', [.1 .75 .8 .2], ...
          'Fontname', 'time roman', ...
          'Fontsize', Scale*18, ...
          'Style', 'text', ...
          'String', label)

% Display each menu item button
for k = 1:num_items
  item(k) = uicontrol('Parent', genericfig, ...
                      'Units', 'normalized', ...
                      'BackgroundColor',[0.752941 0.752941 0.752941], ...
                      'Fontname', 'time roman', ...
                      'Fontsize', Scale*14, ...
                      'String', menu_selections{k}, ...
                      'Position', [.1 .7-(k*.6/num_items) .8 .6/num_items], ...
                      'Callback', [sprintf('set(gcbo, ''UserData'', [%d]);', k), ...
                                   'uiresume(gcbf)'], ...
                      'Tag', sprintf('MenuItem%d', k), ...
                      'UserData', []) ;
end

uiwait(genericfig)

for k = 1:num_items
  tmp = get(findobj('Tag', sprintf('MenuItem%d', k)), 'UserData') ;
  if not(isempty(tmp))
    menu_item = tmp ;
    break ;
  end
end

close(gcf)
