function exit = return_to_main(fig)

% displays Return to Main Menu

exit = uimenu(fig, ...
              'Label', sprintf('Return to Main Menu %s',''),...
              'Tag','exit', ...
              'Callback','close all, start_maxim;') ;
