function lyt=candgui(des,action,figh,p)
% DESIGN/CANDGUI   Candidate space GUI creation
%   LYT=CANDGUI(D,'layout',FIGH,P) creates a gui for creating
%   a candidate set in the figure FIGH, using the design 
%   pointed to by P.  LYT is a returned layout object.  
%
%   Alternatively, FIGH may be a copy of LYT, in whch case the
%   current layout will be updated with the new pointer.
%

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.2.2.2 $  $Date: 2004/02/09 07:06:11 $


switch lower(action)
case 'layout'
   lyt=i_createlyt(figh,p);
case 'preview'
   i_preview(figh,p);
case 'designchange'
   i_updatepreview(figh);
case 'finalise'
   % no finalise action for this view => never any error
   lyt='';
end
return



function lyt=i_createlyt(figh,p)

if ~isa(figh,'xregcontainer')
   ud.pointer=p;
   ud.figure=figh;
   mnm=mfilename;
   [pth,mnm,ext,ver]=fileparts(mnm);
   % candidate space information fields
   txt1=xreguicontrol('parent',figh,...
      'style','text',...
      'string','Number of candidate points:',...
      'visible','off',...
      'horizontalalignment','left',...
      'userdata',xregdesign);
   txt2=xreguicontrol('parent',figh,...
      'style','text',...
      'string','Number of accepted points:',...
      'visible','off',...
      'horizontalalignment','left');
   txt3=xreguicontrol('parent',figh,...
      'style','text',...
      'string','Percentage rejected:',...
      'visible','off',...
      'horizontalalignment','left');
   ud.ncand=xreguicontrol('parent',figh,...
      'style','text',...
      'visible','off',...
      'horizontalalignment','left');
   ud.ncandconst=xreguicontrol('parent',figh,...
      'style','text',...
      'visible','off',...
      'horizontalalignment','left');
   ud.pcrej=xreguicontrol('parent',figh,...
      'style','text',...
      'visible','off',...
      'horizontalalignment','left');
   div=xregGui.dividerline(figh,'visible','off');
   
   txt4=xreguicontrol('style','text',...
      'parent',figh,...
      'position',[0 0 140 45],...
      'visible','off',...
      'string','Maximum number of candidate points to use for preview plots:',...
      'horizontalalignment','left');
   ud.nprevpnts=xregGui.clickedit(figh,'visible','off',...
      'position',[0 0 80 20],...
      'min',1,...
      'max',inf,...
      'rule','int',...
      'clickincrement',1,...
      'dragincrement',1,...
      'value',2500);
   
   load('xregdesign/candicons.mat');
   ud.prev1d=xreguicontrol('parent',figh,...
      'visible','off',...
      'style','pushbutton',...
      'cdata',bmp1d);
   ud.prev2d=xreguicontrol('parent',figh,...
      'visible','off',...
      'style','pushbutton',...
      'cdata',bmp2d);
   ud.prev3d=xreguicontrol('parent',figh,...
      'visible','off',...
      'style','pushbutton',...
      'cdata',bmp3d);
   ud.prev4d=xreguicontrol('parent',figh,...
      'visible','off',...
      'style','pushbutton',...
      'cdata',bmp4d);
   
   udh=sprintf('%20.15f',ud.ncand);
   objh=sprintf('%20.15f',txt1);
   cbstr=[mnm '(get(' objh ',''userdata''),''preview'',' udh ','];
   
   set(ud.prev1d,'callback',[cbstr '1);']);
   set(ud.prev2d,'callback',[cbstr '2);']);
   set(ud.prev3d,'callback',[cbstr '3);']);
   set(ud.prev4d,'callback',[cbstr '4);']);  
   des=xregdesign;
   % layouts
   cbstr=[mnm '(get(' objh ',''userdata''),''designchange'',' udh ');'];
   ud.opts=gui_candspace(des,'layout',figh,p,'callback',cbstr);
   ud.constr=constrainteditor(des,'layout',figh,p,'callback',cbstr);
   
   optsfrm=xregframetitlelayout(figh,'title','Candidate Set',...
      'innerborder',[10 10 10 10],'center',ud.opts);
   infogrd=xreggridlayout(figh,'correctalg','on','dimension',[3 2],...
      'colratios',[2 1],'elements',{txt1,txt2,txt3,ud.ncand,ud.ncandconst,ud.pcrej},...
      'border',[0 5 0 0]);
   flw1=xregflowlayout(figh,'orientation','left/bottom',...
      'elements',{txt4,ud.nprevpnts},'gap',5,'border',[-5 0 0 5]);
   prevgrd=xreggridlayout(figh,'correctalg','on','dimension',[1 4],...
      'elements',{ud.prev1d,ud.prev2d,ud.prev3d,ud.prev4d},'gap',5,...
      'border',[10 10 10 15]);
   brd1=xregborderlayout(figh,'north',infogrd,'south',flw1,'center',div,...
      'innerborder',[0 50 0 60]);
   brd2=xregborderlayout(figh,'north',brd1,...
      'center',prevgrd,'innerborder',[0 0 0 112]);
   infolyt=xregframetitlelayout(figh,'title','Preview','center',brd2,...
      'innerborder',[10 10 10 10],'border',[0 0 0 5]);
   set(ud.constr,'border',[0 5 0 0]);
   set(optsfrm,'border',[0 0 10 0]);
   brd3=xregborderlayout(figh,'north',ud.constr,...
      'center',infolyt,'innerborder',[0 0 0 140]);
   lyt=xregsplitlayout(figh,'left',optsfrm,'right',brd3,'resizable','off',...
      'split',[.55 .45]);
else
   % pick out the userdata object
   lyt=figh;
   el=get(get(get(get(get(get(lyt,'right'),'center'),'center'),'north'),'north'),'elements');
   el=el{4};
   ud=get(el,'userdata');
   figh=ud.figure;
   ud.pointer=p;
end
ud=i_setvalues(ud);
set(ud.ncand,'userdata',ud);
return




function ud=i_setvalues(ud)
p=ud.pointer;
set(ud.ncand,'string',ncand(p.info,'unconstrained'));
set(ud.ncandconst,'string',ncand(p.info));
set(ud.pcrej,'string',[num2str(pcreject(p.info)) '%']);
% update other layouts
lyt=constrainteditor(p.info,'layout',ud.constr,p);
lyt=gui_candspace(p.info,'layout',ud.opts,p);
return


function i_preview(udh,dim)
ud=get(udh,'userdata');
maxpoints=get(ud.nprevpnts,'value');
previewcand(ud.pointer.info,dim,maxpoints,'windowstyle','modal');
return


function i_updatepreview(udh)
ud=get(udh,'userdata');
p=ud.pointer;
set(ud.ncand,'string',ncand(p.info,'unconstrained'));
set(ud.ncandconst,'string',ncand(p.info));
set(ud.pcrej,'string',[num2str(pcreject(p.info)) '%']);
% pipe new design into candspace gui
l=gui_candspace(p.info,'layout',ud.opts,p);
return







