function [des, ok] = gui_round(des)
%GUI_ROUND Display a dialog for rounding a design factor
%
%  [DES, OK] = GUI_ROUND(DES) displays a dialog that allows the user to
%  round a factor in the design.
%
%  See also: XREGDESIGN/ROUDNFACTOR.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%  $Revision: 1.1.6.3 $    $Date: 2004/04/04 03:27:13 $ 

SC = xregGui.SystemColorsDbl;
hFig = xregdialog('Name', 'Round Design');
xregcenterfigure(hFig, [300 163]);

f = factors(des);
pUD = xregGui.RunTimePointer;
pUD.LinkToObject(hFig);

hFactPopup = uicontrol('parent', hFig, ...
    'style', 'popupmenu', ...
    'string', f, ...
    'value', 1, ...
    'backgroundcolor', SC.WINDOW_BG);
hFactLabel = xregGui.labelcontrol('parent', hFig, ...
    'String', 'Round factor:', ...
    'LabelSize', 90, ...
    'LabelSizeMode', 'absolute', ...
    'ControlSize', 1, ...
    'ControlSizeMode', 'relative', ...
    'Control', hFactPopup);

hRoundPopup = uicontrol('parent', hFig, ...
    'style', 'popupmenu', ...
    'string', {'Fixed interval'; 'Significant figures'}, ...
    'value', 1, ...
    'backgroundcolor', SC.WINDOW_BG, ...
    'callback', {@i_enablesetting, pUD});
hRoundLabel = xregGui.labelcontrol('parent', hFig, ...
    'String', 'Rounding mode:', ...
    'LabelSize', 90, ...
    'LabelSizeMode', 'absolute', ...
    'ControlSize', 1, ...
    'ControlSizeMode', 'relative', ...
    'Control', hRoundPopup);

hIntervalEdit = xregGui.clickedit('parent', hFig, ...
    'min', eps, ...
    'value', 1);
hIntervalLabel = xregGui.labelcontrol('parent', hFig, ...
    'String', 'Interval:', ...
    'LabelSize', 90, ...
    'LabelSizeMode', 'absolute', ...
    'ControlSize', 70, ...
    'ControlSizeMode', 'absolute', ...
    'Control', hIntervalEdit);

hSigFigEdit = xregGui.clickedit('parent', hFig, ...
    'min', 1, ...
    'rule', 'int', ...
    'value', 3);
hSigFigLabel = xregGui.labelcontrol('parent', hFig, ...
    'String', 'Significant figures:', ...
    'LabelSize', 90, ...
    'LabelSizeMode', 'absolute', ...
    'ControlSize', 70, ...
    'ControlSizeMode', 'absolute', ...
    'enable', 'off', ...
    'Control', hSigFigEdit);

hOK = uicontrol('parent', hFig, ...
    'style', 'pushbutton', ...
    'string', 'OK', ...
    'callback', 'set(gcbf, ''tag'', ''ok'', ''visible'', ''off'');');
hCancel = uicontrol('parent', hFig, ...
    'style', 'pushbutton', ...
    'string', 'Cancel', ...
    'callback', 'set(gcbf, ''visible'', ''off'');');

lyt = xreggridbaglayout(hFig, ...
    'packstatus', 'off', ...
    'dimension', [5 3], ...
    'rowsizes', [22 22 20 20 25], ...
    'colsizes', [-1 65 65], ...
    'gapx', 7, ...
    'gapy', 10, ...
    'border', [7 7 7 7], ...
    'mergeblock', {[1 1], [1 3]}, ...
    'mergeblock', {[2 2], [1 3]}, ...
    'mergeblock', {[3 3], [1 3]}, ...
    'mergeblock', {[4 4], [1 3]}, ...
    'elements', {hFactLabel, hRoundLabel, hIntervalLabel, hSigFigLabel, [], ...
    [], [], [], [], hOK, [], [], [], [], hCancel});

ud.sigfig = hSigFigLabel;
ud.interval = hIntervalLabel;
pUD.info = ud;

hFig.Layout = lyt;
set(lyt, 'packstatus', 'on');

hFig.showDialog(hOK);

tg = get(hFig, 'tag');
ok = false;
if strcmp(tg, 'ok')
    factind = get(hFactPopup, 'value');
    method = get(hRoundPopup, 'value');
    if method==1
        opt = hIntervalEdit.Value;
        des = roundfactor(des, factind, 'nearest', opt);
        
    elseif method==2
        opt = hSigFigEdit.Value;
        des = roundfactor(des, factind, 'sigfig', opt);
        
    end 
    ok = true;
end
delete(hFig);



function i_enablesetting(src, evt, pUD)
ud = pUD.info;

val = get(src, 'value');
if val==1
    ud.interval.enable = 'on';
    ud.sigfig.enable = 'off';
elseif val==2
    ud.interval.enable = 'off';
    ud.sigfig.enable = 'on';
end
