function varargout= dispstats(m,Action,varargin)
% DISPSTATS
% 
% GUI Tool for displaying ANOVA Table and other Statistics
% This is based on the statistics calculated by
% s = stats(m,'stepwise').
% This tool makes extensive use of UITABLES
%
% See also xreglinear/STATS, UITABLE

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.
%   $Revision: 1.4.4.2 $  $Date: 2004/02/09 07:49:35 $



switch lower(Action)
case 'create'
   % create tool
   varargout{1}=i_Create(varargin{:});
case 'display'
   % Update Table Values
   i_Display(m,varargin{:});
case 'nofit'
   i_NoFit(m,varargin{:});
case 'id'
   varargout{1}='xreglinear';
end

function Tool= i_Create(hFig);


% Anova Table
Headings = {'SS','df','MS'};
Stbl=xregtable(hFig,...
   'visible','off',...
   'defaultcelltype','uitext',...
   'defaultcellformat','%.4g',...
   'rows.number',4,...
   'cols.number',4,...
   'rows.size',15,...
   'cols.size',60,...
   'rows.fixed',1,...
   'zeroindex',[2 2],...
   'rows.spacing',0,...
   'cols.spacing',0,...
   'frame.hborder',[2 2],...
   'frame.vborder',[2 2],...
   'frame.box','on',...
   'frame.visible','off',...
   'hslider.width',13,...
   'vslider.width',13,...
   'redrawmode','basic',...
   'position',[-200 -200 100 60]);
%Tbl.cells.defaultbackgroundcolor=[1 1 1];
Tool.Anova=Stbl;
set(Tool.Anova,...
   'cells.rowselection',[1 1],...
   'cells.colselection',[2 4],...
   'cells.type','uitext',...
   'cells.horizontalalignment','right',...
   'cells.string',Headings,...
   'cells.rowselection',[2 4],...
   'cells.colselection',[2 4],...
   'cells.horizontalalignment','right',...
   'cells.rowselection',[4 4],...
   'cells.colselection',[4 4],...
   'cells.visible','off',...
   'cells.rowselection',[1 4],...
   'cells.colselection',[1 1],...
   'cells.type','uitext',...
   'cells.horizontalalignment','left',...
   'cells.string',{'Source','Regression','Error','Total'}');

% C) Wrap these two inside FrameTitleLayouts
Tool.layout= xregframetitlelayout(hFig,...
   'title','Anova table',...
   'Center',Stbl,...
   'innerborder',[10 0 0 5],...
   'visible','off');


set(Tool.Anova,'redrawmode','normal');


function i_Display(Model,Tool)

StatsRes= stats(Model,'stepwise');
% Display Anova Table
Tool.Anova(:,:)= StatsRes(:,1:3);


function i_NoFit(m,Tool)

dfTot  = size(m.Store.X,1)-IncludeConst(m);
dfe= dferror(m);

Tool.Anova(:,[1 3:end])= NaN;
Tool.Anova(:,2)= [dfTot-dfe dfe dfTot]';
