function note = parseNoteString(noteExp, noteString, noteColor)
%PARSENOTESTRING

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.

%   $Revision: 1.3.6.2 $ 

% Make sure inputs are strings
noteExp = char(noteExp);
noteString = char(noteString);

note = struct(...
    'OK', false,...
    'inlineExp', vectorize(mbcinline(noteExp)),...
    'isMultiNote', false,...
    'lAppliesTo', [],...
    'noteColor', noteColor,...
    'noteExp', noteExp,...
    'noteString', noteString,...
    'result','');