function dispprops(hnd)
%TABLE/PRIVATE/DISPPROPS   Private function
%   Private function to display the available properties and
%   their current settings of the table data that is currently
%   in the global memory.

%  Copyright 2000-2004 The MathWorks, Inc. and Ford Global Technologies, Inc.


%   $Revision: 1.2.2.2 $  $Date: 2004/02/09 07:32:56 $


%   Called by 'get'


% Mammoth display problem.   Need to construct nasty string

% Property list hard-coded here

props={'parent';...
      'position';...
      'units';...
      'visible';...
      'defaultcelltype';...
      'defaultcellformat';...
      'zeroindex';...
      'showzeros';...
      'redrawmode';...
      'colormap';...
      'colorintervals';...
      'usecolors';...
      'userdata';...
      'diagscroll';...
      'sliders';...
      'frame.visible';...
      'frame.hborder';...
      'frame.vborder';...
      'frame.backgroundcolor';...
      'frame.box';...
      'frame.boxcolor';...
      'vslider.width';...
      'vslider.value';...
      'vslider.offset';...
      'hslider.width';...
      'hslider.value';...
      'hslider.offset';...
      'rows.number';...
      'rows.fixed';...
      'rows.size';...
      'rows.spacing';...
      'rows.onscreen';...
      'cols.number';...
      'cols.fixed';...
      'cols.size';...
      'cols.spacing';...
      'cols.onscreen';...
      'cells.type';...
      'cells.value';...
      'cells.string';...
      'cells.visible';...
      'cells.format';...
      'cells.rowselection';...
      'cells.colselection';...
      'filters.type';...
      'filters.value';...
      'filters.tolerance'};

dispstr=[];
spacer='      ';
assignin('base','TEMP_TABLE_HANDLE',hnd);

for n=1:length(props)

   out=evalin('base',['get(TEMP_TABLE_HANDLE,''' props{n} ''')']);

   if ischar(out)
      % Try displaying string if its short enough
      if size(out,1)==1 & size(out,2)<35
         descrip=out;
      else
         descrip=['[ (' num2str(size(out,1),3) ' by ' num2str(size(out,2),3) ') char array]'];
      end
   elseif isnumeric(out)
      % try printing out 1D arrays
      descrip=[];
      if size(out,1)==1
         nstr=['[' num2str(out) ']'];
         if length(nstr)<35
            descrip=nstr;
         end
      end
      if isempty(descrip)
         tp=class(out);
         descrip=['[ (' num2str(size(out,1),3) ' by ' num2str(size(out,2),3) ') ' tp ' array]'];
      end
      
   elseif iscell(out)
      % Don't bother trying to display cell arrays!
         descrip=['[ (' num2str(size(out,1),3) ' by ' num2str(size(out,2),3) ') cell array]'];
   end
   dispstr=[dispstr spacer props{n} ' = ' descrip char(10)];
end

disp(dispstr);
evalin('base',['clear TEMP_TABLE_HANDLE']);
return





